import { useEffect, useState } from "react";
import { Plus, Search, Eye, CheckCircle, XCircle, Clock, FileText } from "lucide-react";
import api from "../../api";
import Toast from "../../components/Toast";
import useToast from "../../utils/useToast";
import { hasPermission, isAdmin } from "../../utils/permissions";

export default function TrainingRequests() {
  const [requests, setRequests] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [programs, setPrograms] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [showModal, setShowModal] = useState(false);
  const [showApprovalModal, setShowApprovalModal] = useState(false);
  const [showViewModal, setShowViewModal] = useState(false);
  const [selectedRequest, setSelectedRequest] = useState(null);
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    employee_id: "",
    training_program_id: "",
    requested_training: "",
    justification: "",
    priority: "Medium"
  });

  // Auto-populate current user when employees are loaded (only for non-admin users)
  useEffect(() => {
    if (employees.length > 0 && !isAdmin()) {
      const currentUserId = localStorage.getItem('user_id');
      if (currentUserId && !formData.employee_id) {
        const currentUserEmployee = employees.find(emp => {
          if (emp.id == currentUserId) return true;
          if (emp.original_user_id == currentUserId) return true;
          return false;
        });
        if (currentUserEmployee) {
          setFormData(prev => ({ ...prev, employee_id: currentUserEmployee.id }));
        }
      }
    }
  }, [employees]);
  const [approvalData, setApprovalData] = useState({
    action: "",
    comment: ""
  });
  const { toast, showToast, hideToast } = useToast();

  // Check permissions
  if (!hasPermission('view_training_requests') && !hasPermission('view_self') && !isAdmin()) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <div className="text-6xl mb-4">🔒</div>
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Access Denied</h2>
          <p className="text-gray-600">You don't have permission to view training requests.</p>
        </div>
      </div>
    );
  }

  useEffect(() => {
    fetchRequests();
    fetchEmployees();
    fetchPrograms();
    
    const fetchColors = async () => {
      try {
        const tenantCode = localStorage.getItem('tenant_code');
        if (tenantCode) {
          const response = await api.get(`/auth/branding/${tenantCode}`);
          document.documentElement.style.setProperty('--primary-color', response.data.primary_color || '#2862e9');
          document.documentElement.style.setProperty('--secondary-color', response.data.secondary_color || '#474e71');
        }
      } catch (error) {
        console.error('Failed to fetch branding colors:', error);
      }
    };
    fetchColors();
  }, []);

  const fetchRequests = async () => {
    try {
      setLoading(true);
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 5000);
      
      const res = await api.get("/api/training/requests", {
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      setRequests(res.data || []);
    } catch (error) {
      if (error.name === 'AbortError') {
        console.log('Request timed out');
      } else {
        console.error("Error fetching training requests:", error);
      }
      setRequests([]);
    } finally {
      setLoading(false);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      // Fetch from both onboarding and user management like EIS module
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        api.get(`/hospitals/users/${tenant}/list`).then(res => res.data).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id
      }));
      
      // Process user management employees
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          employee_code: user.employee_code
        }));
      
      // Combine and remove duplicates
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
      setEmployees([]);
    }
  };

  const fetchPrograms = async () => {
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 5000);
      
      const res = await api.get("/api/training/programs", {
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      setPrograms(res.data?.data?.filter(p => p.status === 'Published') || []);
    } catch (error) {
      if (error.name === 'AbortError') {
        console.log('Request timed out');
      } else {
        console.error("Error fetching training programs:", error);
      }
      setPrograms([]);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      setLoading(true);
      await api.post("/api/training/requests", formData);
      await fetchRequests();
      handleCloseModal();
    } catch (error) {
      console.error("Error creating training request:", error);
      showToast('Failed to create training request. Please try again.', 'error');
    } finally {
      setLoading(false);
    }
  };

  const handleApproval = async (e) => {
    e.preventDefault();
    try {
      setLoading(true);
      await api.put(`/api/training/requests/${selectedRequest.id}/approve`, {
        action: approvalData.action,
        comment: approvalData.comment
      });
      await fetchRequests();
      setShowApprovalModal(false);
      setSelectedRequest(null);
      setApprovalData({ action: "", comment: "" });
    } catch (error) {
      console.error("Error processing approval:", error);
      showToast('Failed to process approval. Please try again.', 'error');
    } finally {
      setLoading(false);
    }
  };

  const handleOpenModal = () => {
    setFormData({
      employee_id: "",
      training_program_id: "",
      requested_training: "",
      justification: "",
      priority: "Medium"
    });
    setShowModal(true);
  };

  const handleCloseModal = () => {
    setShowModal(false);
  };

  const handleOpenViewModal = (request) => {
    setSelectedRequest(request);
    setShowViewModal(true);
  };

  const handleCloseViewModal = () => {
    setShowViewModal(false);
    setSelectedRequest(null);
  };

  const handleOpenApprovalModal = (request) => {
    setSelectedRequest(request);
    setApprovalData({ action: "", comment: "" });
    setShowApprovalModal(true);
  };

  const getEmployeeName = (employeeId) => {
    console.log('Looking for employee with ID:', employeeId, 'in employees:', employees);
    const employee = employees.find(emp => {
      // Handle both string and number IDs, and user_ prefixed IDs
      const empId = emp.id;
      const searchId = employeeId;
      
      // Direct match
      if (empId === searchId) return true;
      
      // Handle user_ prefix
      if (typeof empId === 'string' && empId.startsWith('user_')) {
        const numericId = parseInt(empId.replace('user_', ''));
        if (numericId === parseInt(searchId)) return true;
      }
      
      // Handle reverse case
      if (typeof searchId === 'string' && searchId.startsWith('user_')) {
        const numericSearchId = parseInt(searchId.replace('user_', ''));
        if (parseInt(empId) === numericSearchId) return true;
      }
      
      return false;
    });
    
    console.log('Found employee:', employee);
    return employee ? `${employee.name} (${employee.employee_code || employee.id})` : `Employee #${employeeId}`;
  };

  const getProgramName = (programId) => {
    const program = programs.find(p => p.id === programId);
    return program ? program.title : "Custom Training";
  };

  const filteredRequests = requests.filter(request => {
    const employeeName = getEmployeeName(request.employee_id);
    const matchesSearch = request.requested_training?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         employeeName.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = !statusFilter || request.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const priorities = ["Low", "Medium", "High", "Urgent"];
  const statuses = ["Pending", "HR Approved", "Rejected"];

  return (
    <div className="space-y-6">

      <div className="rounded-xl shadow-sm overflow-hidden relative border" style={{
        background: `linear-gradient(135deg, white 0%, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}05 100%)`,
        borderColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
      }}>
        <div className="absolute top-0 right-0 w-32 h-32 rounded-full blur-3xl opacity-10" style={{
          backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5',
          transform: 'translate(40%, -40%)'
        }}></div>
        {/* Header */}
        <div className="p-6 border-0 relative z-10">
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-lg font-medium text-gray-900">Training Requests</h3>
            {(hasPermission('add_training_request') || isAdmin()) && (
              <button 
                onClick={handleOpenModal}
                className="flex items-center gap-2 px-4 py-2 text-white rounded-lg transition-colors"
                style={{
                  backgroundColor: 'var(--primary-color)'
                }}
                onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--secondary-color)'}
                onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--primary-color)'}
              >
                <Plus className="w-4 h-4" />
                New Request
              </button>
            )}
          </div>
          <div className="flex gap-4">
            <div className="relative flex-1 max-w-md">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={16} />
              <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
                type="text"
                placeholder="Search requests..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10 pr-4 py-2 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent w-full"
              />
            </div>
            <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className=" rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">All Status</option>
              {statuses.map(status => (
                <option key={status} value={status}>{status}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Table */}
        <div className="overflow-x-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
          {loading ? (
            <div className="flex justify-center items-center py-8">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
            </div>
          ) : (
            <>
              {/* Desktop Table View */}
              <div className="hidden md:block">
                <table className="w-full">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-0">Employee</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-0">Training Requested</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-0">Priority</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-0">Status</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-0">Requested Date</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-0">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-100">
                    {filteredRequests.length === 0 ? (
                      <tr>
                        <td colSpan="6" className="px-6 py-12 text-center">
                          <FileText className="mx-auto h-12 w-12 text-muted" />
                          <h3 className="mt-2 text-sm font-medium text-primary">No training requests</h3>
                          <p className="mt-1 text-sm text-muted">
                            {searchTerm || statusFilter ? "No requests match your search criteria." : "No training requests have been submitted yet."}
                          </p>
                          {!searchTerm && !statusFilter && (hasPermission('add_training_request') || isAdmin()) && (
                            <div className="mt-6">
                              <button 
                                onClick={handleOpenModal}
                                className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 mx-auto transition-colors"
                              >
                                <Plus size={16} />
                                Create First Request
                              </button>
                            </div>
                          )}
                        </td>
                      </tr>
                    ) : (
                      filteredRequests.map((request) => (
                        <tr key={request.id} className="hover:bg-gray-50 border-0">
                          <td className="px-6 py-4 whitespace-nowrap border-0">
                            <div className="text-sm font-medium text-gray-900">{getEmployeeName(request.employee_id)}</div>
                          </td>
                          <td className="px-6 py-4 border-0">
                            <div className="text-sm text-gray-900">{request.requested_training}</div>
                            {request.justification && (
                              <div className="text-sm text-gray-500 truncate max-w-xs">{request.justification}</div>
                            )}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap border-0">
                            <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                              request.priority === "Urgent" ? "bg-red-100 text-red-800" :
                              request.priority === "High" ? "bg-orange-100 text-orange-800" :
                              request.priority === "Medium" ? "bg-yellow-100 text-yellow-800" :
                              "bg-green-100 text-green-800"
                            }`}>
                              {request.priority}
                            </span>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap border-0">
                            <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                              request.status === "HR Approved" || request.status === "Approved" ? "bg-green-100 text-green-800" :
                              request.status === "Manager Approved" ? "bg-blue-100 text-blue-800" :
                              request.status === "Rejected" ? "bg-red-100 text-red-800" :
                              "bg-yellow-100 text-yellow-800"
                            }`}>
                              {request.status}
                            </span>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap border-0">
                            <div className="text-sm text-gray-900">
                              {new Date(request.created_at).toLocaleDateString()}
                            </div>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                            <div className="flex items-center gap-2">
                              <button 
                                onClick={() => handleOpenViewModal(request)}
                                className="text-blue-600 hover:text-blue-900 p-1 rounded"
                                title="View Details"
                              >
                                <Eye size={16} />
                              </button>
                              {(request.status === "Pending" || request.status === "Manager Approved") && (hasPermission('approve_training_request') || hasPermission('reject_training_request') || isAdmin()) && (
                                <>
                                  <button 
                                    onClick={() => handleOpenApprovalModal(request)}
                                    className="text-green-600 hover:text-green-900 p-1 rounded"
                                    title="Approve/Reject"
                                  >
                                    <CheckCircle size={16} />
                                  </button>
                                </>
                              )}
                            </div>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>

              {/* Mobile Card View */}
              <div className="md:hidden">
                {filteredRequests.length === 0 ? (
                  <div className="px-6 py-12 text-center">
                    <FileText className="mx-auto h-12 w-12 text-muted" />
                    <h3 className="mt-2 text-sm font-medium text-primary">No training requests</h3>
                    <p className="mt-1 text-sm text-muted">
                      {searchTerm || statusFilter ? "No requests match your search criteria." : "No training requests have been submitted yet."}
                    </p>
                    {!searchTerm && !statusFilter && (hasPermission('add_training_request') || isAdmin()) && (
                      <div className="mt-6">
                        <button 
                          onClick={handleOpenModal}
                          className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 mx-auto transition-colors"
                        >
                          <Plus size={16} />
                          Create First Request
                        </button>
                      </div>
                    )}
                  </div>
                ) : (
                  filteredRequests.map((request) => (
                    <div key={request.id} className="p-4 border-b-0 last:border-b-0">
                      <div className="flex justify-between items-start mb-3">
                        <div className="flex-1">
                          <h4 className="font-medium text-gray-900">{getEmployeeName(request.employee_id)}</h4>
                          <p className="text-sm text-gray-600 mt-1">{request.requested_training}</p>
                          {request.justification && (
                            <p className="text-sm text-gray-500 mt-1">{request.justification}</p>
                          )}
                        </div>
                        <div className="flex flex-col gap-1">
                          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                            request.priority === "Urgent" ? "bg-red-100 text-red-800" :
                            request.priority === "High" ? "bg-orange-100 text-orange-800" :
                            request.priority === "Medium" ? "bg-yellow-100 text-yellow-800" :
                            "bg-green-100 text-green-800"
                          }`}>
                            {request.priority}
                          </span>
                          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                            request.status === "HR Approved" || request.status === "Approved" ? "bg-green-100 text-green-800" :
                            request.status === "Manager Approved" ? "bg-blue-100 text-blue-800" :
                            request.status === "Rejected" ? "bg-red-100 text-red-800" :
                            "bg-yellow-100 text-yellow-800"
                          }`}>
                            {request.status}
                          </span>
                        </div>
                      </div>
                      
                      <div className="flex justify-between items-center">
                        <span className="text-sm text-gray-600">
                          {new Date(request.created_at).toLocaleDateString()}
                        </span>
                        <div className="flex gap-2">
                          <button 
                            onClick={() => handleOpenViewModal(request)}
                            className="flex items-center gap-1 px-3 py-1 text-xs bg-gray-50 text-gray-700 rounded-md border border-gray-300 hover:bg-gray-100"
                          >
                            <Eye className="w-3 h-3" />
                            View
                          </button>
                          {(request.status === "Pending" || request.status === "Manager Approved") && (hasPermission('approve_training_request') || hasPermission('reject_training_request') || isAdmin()) && (
                            <button 
                              onClick={() => handleOpenApprovalModal(request)}
                              className="flex items-center gap-1 px-3 py-1 text-xs bg-green-50 text-green-700 rounded-md border border-green-300 hover:bg-green-100"
                            >
                              <CheckCircle className="w-3 h-3" />
                              Review
                            </button>
                          )}
                        </div>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </>
          )}
        </div>

        {/* Stats Footer */}
        <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">
          <div className="flex justify-between items-center text-sm text-gray-600">
            <span>Total Requests: {requests.length}</span>
            <span>Pending Approval: {requests.filter(r => r.status === 'Pending' || r.status === 'Manager Approved').length}</span>
            <span>Approved: {requests.filter(r => r.status === 'HR Approved' || r.status === 'Approved').length}</span>
          </div>
        </div>
      </div>

      {/* Create Request Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col">
            <div className="px-6 py-4 border-b-0 flex-shrink-0">
              <h3 className="text-lg font-semibold text-gray-900">New Training Request</h3>
              <p className="text-sm text-gray-500 mt-1">Submit a request for training approval</p>
            </div>
            <div className="px-6 py-4 overflow-y-auto flex-1" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Employee</label>
                  {isAdmin() ? (
                    <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
                      value={formData.employee_id}
                      onChange={(e) => setFormData({...formData, employee_id: e.target.value})}
                      className="w-full px-3 py-2 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 bg-white"
                      required
                    >
                      <option value="">Select Employee</option>
                      {employees.map(employee => (
                        <option key={employee.id} value={employee.id}>
                          {employee.name} ({employee.employee_code || employee.id})
                        </option>
                      ))}
                    </select>
                  ) : (
                    <div className="w-full px-3 py-2 border-0 rounded-lg bg-gray-50 text-gray-700">
                      {(() => {
                        const currentUserId = localStorage.getItem('user_id');
                        const currentUserEmployee = employees.find(emp => {
                          if (emp.id == currentUserId) return true;
                          if (emp.original_user_id == currentUserId) return true;
                          return false;
                        });
                        return currentUserEmployee ? `${currentUserEmployee.employee_code || currentUserEmployee.id} - ${currentUserEmployee.name}` : 'Loading...';
                      })()} 
                    </div>
                  )}
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Training Program (Optional)</label>
                  <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
                    value={formData.training_program_id}
                    onChange={(e) => {
                      const programId = e.target.value;
                      const program = programs.find(p => p.id === parseInt(programId));
                      setFormData({
                        ...formData, 
                        training_program_id: programId,
                        requested_training: program ? program.title : formData.requested_training
                      });
                    }}
                    className="w-full px-3 py-2 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 bg-white"
                  >
                    <option value="">Select from Available Programs</option>
                    {programs.map(program => (
                      <option key={program.id} value={program.id}>
                        {program.title} - {program.category}
                      </option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Training Requested</label>
                  <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
                    type="text"
                    value={formData.requested_training}
                    onChange={(e) => setFormData({...formData, requested_training: e.target.value})}
                    className="w-full px-3 py-2 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 bg-white"
                    placeholder="Enter training name or description"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Justification</label>
                  <textarea style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
                    value={formData.justification}
                    onChange={(e) => setFormData({...formData, justification: e.target.value})}
                    className="w-full px-3 py-2 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 bg-white resize-none"
                    rows="2"
                    placeholder="Explain why this training is needed"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Priority</label>
                  <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
                    value={formData.priority}
                    onChange={(e) => setFormData({...formData, priority: e.target.value})}
                    className="w-full px-3 py-2 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 bg-white"
                    required
                  >
                    {priorities.map(priority => (
                      <option key={priority} value={priority}>{priority}</option>
                    ))}
                  </select>
                </div>
              </form>
            </div>
            <div className="px-6 py-4 bg-gray-50 border-t border-gray-100 flex gap-3 flex-shrink-0">
              <button
                type="button"
                onClick={handleCloseModal}
                className="flex-1 px-4 py-2 border-0 rounded-lg text-gray-700 font-medium hover:bg-gray-100 transition-all duration-200"
              >
                Cancel
              </button>
              <button
                type="submit"
                onClick={handleSubmit}
                disabled={loading}
                className="flex-1 px-4 py-2 text-white rounded-lg font-medium disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 shadow-lg hover:shadow-xl"
                style={{
                  backgroundColor: 'var(--primary-color)'
                }}
                onMouseEnter={(e) => !loading && (e.target.style.backgroundColor = 'var(--secondary-color)')}
                onMouseLeave={(e) => !loading && (e.target.style.backgroundColor = 'var(--primary-color)')}
              >
                {loading ? "Submitting..." : "Submit Request"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* View Request Modal */}
      {showViewModal && selectedRequest && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-2xl">
            <h3 className="text-lg font-semibold mb-4">Training Request Details</h3>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-secondary">Employee</label>
                  <p className="text-sm text-primary">{getEmployeeName(selectedRequest.employee_id)}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary">Priority</label>
                  <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                    selectedRequest.priority === "Urgent" ? "bg-red-100 text-red-800" :
                    selectedRequest.priority === "High" ? "bg-orange-100 text-orange-800" :
                    selectedRequest.priority === "Medium" ? "bg-yellow-100 text-yellow-800" :
                    "bg-green-100 text-green-800"
                  }`}>
                    {selectedRequest.priority}
                  </span>
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-secondary">Training Requested</label>
                <p className="text-sm text-primary">{selectedRequest.requested_training}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-secondary">Justification</label>
                <p className="text-sm text-primary">{selectedRequest.justification || 'No justification provided'}</p>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-secondary">Status</label>
                  <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                    selectedRequest.status === "HR Approved" || selectedRequest.status === "Approved" ? "bg-green-100 text-green-800" :
                    selectedRequest.status === "Manager Approved" ? "bg-blue-100 text-blue-800" :
                    selectedRequest.status === "Rejected" ? "bg-red-100 text-red-800" :
                    "bg-yellow-100 text-yellow-800"
                  }`}>
                    {selectedRequest.status}
                  </span>
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary">Requested Date</label>
                  <p className="text-sm text-primary">{new Date(selectedRequest.created_at).toLocaleDateString()}</p>
                </div>
              </div>
            </div>
            <div className="flex justify-end pt-4">
              <button
                onClick={handleCloseViewModal}
                className="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
      {/* Approval Modal */}
      {showApprovalModal && selectedRequest && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <h3 className="text-lg font-semibold mb-4">Approve/Reject Request</h3>
            <div className="mb-4 p-4 bg-content rounded-lg">
              <p><strong>Employee:</strong> {getEmployeeName(selectedRequest.employee_id)}</p>
              <p><strong>Training:</strong> {selectedRequest.requested_training}</p>
              <p><strong>Priority:</strong> {selectedRequest.priority}</p>
            </div>
            <form onSubmit={handleApproval} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-secondary mb-1">Action</label>
                <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
                  value={approvalData.action}
                  onChange={(e) => setApprovalData({...approvalData, action: e.target.value})}
                  className="w-full rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                >
                  <option value="">Select Action</option>
                  <option value="approve">Approve</option>
                  <option value="reject">Reject</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-secondary mb-1">Comment</label>
                <textarea style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
                  value={approvalData.comment}
                  onChange={(e) => setApprovalData({...approvalData, comment: e.target.value})}
                  className="w-full rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  rows="3"
                  placeholder="Add your comments (optional)"
                />
              </div>
              <div className="flex gap-4 pt-4">
                <button
                  type="button"
                  onClick={() => setShowApprovalModal(false)}
                  className="flex-1 px-4 py-2 border-0 rounded-lg text-secondary hover:bg-content"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="flex-1 px-4 py-2 bg-black text-white rounded-lg hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {loading ? "Processing..." : "Submit"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}


