import { useEffect, useState } from "react";
import { Award, Download, Eye, Search, Plus } from "lucide-react";
import api from "../../api";

export default function TrainingCertificates({ showModal, setShowModal }) {
  const [certificates, setCertificates] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [loading, setLoading] = useState(false);
  const [programs, setPrograms] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [formData, setFormData] = useState({
    training_id: "",
    employee_id: "",
    score: "",
    compliance_type: "",
    has_expiry: false
  });

  useEffect(() => {
    fetchCertificates();
    fetchPrograms();
    fetchEmployees();
  }, []);

  const fetchCertificates = async () => {
    try {
      setLoading(true);
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 5000);
      
      const res = await api.get("/api/training/certificates", {
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      setCertificates(res.data || []);
    } catch (error) {
      if (error.name === 'AbortError') {
        console.log('Request timed out');
      } else {
        console.error("Error fetching training certificates:", error);
      }
      setCertificates([]);
    } finally {
      setLoading(false);
    }
  };

  const fetchPrograms = async () => {
    try {
      const res = await api.get("/api/training/programs");
      setPrograms(res.data?.data?.filter(p => p.status === 'Published') || []);
    } catch (error) {
      console.error("Error fetching programs:", error);
      setPrograms([]);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          employee_code: user.employee_code
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
      setEmployees([]);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      setLoading(true);
      await api.post("/api/training/certificates", formData);
      await fetchCertificates();
      setShowModal(false);
      setFormData({
        training_id: "",
        employee_id: "",
        score: "",
        compliance_type: "",
        has_expiry: false
      });
    } catch (error) {
      console.error("Error generating certificate:", error);
      alert('Failed to generate certificate. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async (certificate) => {
    try {
      const response = await fetch(`http://localhost:8000/api/training/certificates/${certificate.id}/download`, {
        headers: {
          'tenant-id': localStorage.getItem('tenant_db'),
          'Authorization': `Bearer ${localStorage.getItem('access_token')}`
        }
      });
      
      if (response.ok) {
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${certificate.employee_name}_${certificate.program_title}_Certificate.html`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
      } else {
        alert('Failed to download certificate');
      }
    } catch (error) {
      console.error('Download error:', error);
      alert('Failed to download certificate');
    }
  };

  const handleView = (certificate) => {
    alert(`Certificate Details:\n\nEmployee: ${certificate.employee_name}\nProgram: ${certificate.program_title}\nIssued: ${new Date(certificate.issued_date).toLocaleDateString()}\nValid Until: ${certificate.expiry_date ? new Date(certificate.expiry_date).toLocaleDateString() : 'No expiry'}`);
  };

  const filteredCertificates = certificates.filter(cert => 
    cert.employee_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    cert.program_title?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="space-y-6">

      <div className="rounded-lg shadow-sm border border-black" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
        {/* Search */}
        <div className="p-6 border-b border-black">
          <div className="relative max-w-md">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={16} />
            <input
              type="text"
              placeholder="Search certificates..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10 pr-4 py-2 border border-black rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent w-full"
            />
          </div>
        </div>

        {/* Content */}
        <div className="overflow-x-auto">
          {loading ? (
            <div className="flex justify-center items-center py-8">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
            </div>
          ) : filteredCertificates.length === 0 ? (
            <div className="text-center py-12">
              <Award className="mx-auto h-12 w-12 text-muted" />
              <h3 className="mt-2 text-sm font-medium text-primary">No certificates found</h3>
              <p className="mt-1 text-sm text-muted">
                {searchTerm ? "No certificates match your search criteria." : "Certificates will appear here when training programs are completed."}
              </p>
            </div>
          ) : (
            <table className="w-full">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Employee</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Training Program</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Certificate ID</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Issued Date</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Expiry Date</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Status</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Actions</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-black">
                {filteredCertificates.map((certificate) => {
                  const isExpired = certificate.expiry_date && new Date(certificate.expiry_date) < new Date();
                  const isExpiringSoon = certificate.expiry_date && !isExpired && new Date(certificate.expiry_date) <= new Date(Date.now() + 30 * 24 * 60 * 60 * 1000);
                  
                  return (
                    <tr key={certificate.id} className="hover:bg-gray-50 border-b border-black">
                      <td className="px-6 py-4 whitespace-nowrap border-r border-black">
                        <div className="text-sm font-medium text-gray-900">{certificate.employee_name}</div>
                      </td>
                      <td className="px-6 py-4 border-r border-black">
                        <div className="text-sm text-gray-900">{certificate.program_title}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap border-r border-black">
                        <div className="text-sm text-gray-900 font-mono">{certificate.certificate_number}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap border-r border-black">
                        <div className="text-sm text-gray-900">{new Date(certificate.issued_date).toLocaleDateString()}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap border-r border-black">
                        <div className="text-sm text-gray-900">
                          {certificate.expiry_date ? new Date(certificate.expiry_date).toLocaleDateString() : 'No expiry'}
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap border-r border-black">
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                          isExpired ? 'bg-red-100 text-red-800' :
                          isExpiringSoon ? 'bg-yellow-100 text-yellow-800' :
                          'bg-green-100 text-green-800'
                        }`}>
                          {isExpired ? 'Expired' : isExpiringSoon ? 'Expiring Soon' : 'Active'}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                        <div className="flex items-center gap-2">
                          <button 
                            onClick={() => handleView(certificate)}
                            className="text-blue-600 hover:text-blue-900 p-1 rounded"
                            title="View Details"
                          >
                            <Eye size={16} />
                          </button>
                          <button 
                            onClick={() => handleDownload(certificate)}
                            className="text-green-600 hover:text-green-900 p-1 rounded"
                            title="Download Certificate"
                          >
                            <Download size={16} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          )}
        </div>

        {/* Stats Footer */}
        <div className="px-6 py-4 bg-gray-50 border-t border-black">
          <div className="flex justify-between items-center text-sm text-gray-600">
            <span>Total Certificates: {certificates.length}</span>
            <span>Active: {certificates.filter(c => !c.expiry_date || new Date(c.expiry_date) > new Date()).length}</span>
            <span>Expired: {certificates.filter(c => c.expiry_date && new Date(c.expiry_date) < new Date()).length}</span>
          </div>
        </div>
      </div>

      {/* Generate Certificate Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col">
            <div className="px-6 py-4 border-b border-gray-100 flex-shrink-0">
              <h3 className="text-lg font-semibold text-gray-900">Generate Training Certificate</h3>
              <p className="text-sm text-gray-500 mt-1">Create a certificate for completed training</p>
            </div>
            <div className="px-6 py-4 overflow-y-auto flex-1">
              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Training Program</label>
                  <select
                    value={formData.training_id}
                    onChange={(e) => setFormData({...formData, training_id: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 bg-gray-50 focus:bg-white"
                    required
                  >
                    <option value="">Select Training Program</option>
                    {programs.map(program => (
                      <option key={program.id} value={program.id}>
                        {program.title} - {program.category}
                      </option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Employee</label>
                  <select
                    value={formData.employee_id}
                    onChange={(e) => setFormData({...formData, employee_id: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 bg-gray-50 focus:bg-white"
                    required
                  >
                    <option value="">Select Employee</option>
                    {employees.map(employee => (
                      <option key={employee.id} value={employee.id}>
                        {employee.name} ({employee.employee_code || employee.id})
                      </option>
                    ))}
                  </select>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Score (%)</label>
                    <input
                      type="number"
                      min="0"
                      max="100"
                      value={formData.score}
                      onChange={(e) => setFormData({...formData, score: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 bg-gray-50 focus:bg-white"
                      placeholder="Final score"
                      required
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Compliance Type</label>
                    <select
                      value={formData.compliance_type}
                      onChange={(e) => setFormData({...formData, compliance_type: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 bg-gray-50 focus:bg-white"
                    >
                      <option value="">Select Type</option>
                      <option value="Safety">Safety</option>
                      <option value="Quality">Quality</option>
                      <option value="Technical">Technical</option>
                      <option value="Compliance">Compliance</option>
                      <option value="General">General</option>
                    </select>
                  </div>
                </div>
                <div className="bg-gray-50 rounded-lg p-3">
                  <label className="flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      checked={formData.has_expiry}
                      onChange={(e) => setFormData({...formData, has_expiry: e.target.checked})}
                      className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                    />
                    <span className="ml-2 text-sm font-medium text-gray-700">
                      Certificate has expiry date (1 year from issue)
                    </span>
                  </label>
                </div>
              </form>
            </div>
            <div className="px-6 py-4 bg-gray-50 border-t border-gray-100 flex gap-3 flex-shrink-0">
              <button
                type="button"
                onClick={() => setShowModal(false)}
                className="flex-1 px-4 py-2 border border-gray-200 rounded-lg text-gray-700 font-medium hover:bg-gray-100 transition-all duration-200"
              >
                Cancel
              </button>
              <button
                type="submit"
                onClick={handleSubmit}
                disabled={loading}
                className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 shadow-lg hover:shadow-xl"
              >
                {loading ? "Generating..." : "Generate Certificate"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
