import { useState, useEffect } from "react";
import api from "../../api";
import Toast from "../../components/Toast";
import useToast from "../../utils/useToast";
import { hasPermission, isAdmin } from "../../utils/permissions";

export default function Assets() {
  // Permission checks
  const canView = hasPermission('view_assets') || hasPermission('view_self');
  const canAdd = hasPermission('add_asset');
  const canApprove = hasPermission('approve_asset');
  const canReject = hasPermission('reject_asset');
  const [colors, setColors] = useState({ primary: '#2862e9', secondary: '#474e71' });
  
  if (!canView) {
    return (
      <div className="p-6 text-center">
        <div className="bg-white rounded-2xl border-0 p-8 max-w-md mx-auto">
          <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <span className="text-2xl">🔒</span>
          </div>
          <h3 className="text-lg font-medium text-gray-900 mb-2">Access Denied</h3>
          <p className="text-gray-600">You don't have permission to view assets.</p>
        </div>
      </div>
    );
  }
  
  const [formData, setFormData] = useState({
    employeeId: "",
    assetType: "",
    assetName: "",
    assetId: "",
    brand: "",
    model: "",
    serialNumber: "",
    assignedDate: "",
    condition: "",
    location: "",
    cost: "",
    remarks: ""
  });

  const [assets, setAssets] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [pendingAssets, setPendingAssets] = useState([]);
  const { toast, showToast, hideToast } = useToast();

  useEffect(() => {
    fetchColors();
    fetchEmployees();
    fetchPendingAssets();
    fetchApprovedAssets();
  }, []);

  const fetchColors = async () => {
    try {
      const tenantCode = localStorage.getItem('tenant_code');
      if (tenantCode) {
        const response = await api.get(`/auth/branding/${tenantCode}`);
        if (response.data.primary_color && response.data.secondary_color) {
          setColors({
            primary: response.data.primary_color,
            secondary: response.data.secondary_color
          });
        }
      }
    } catch (error) {
      console.error('Error fetching colors:', error);
    }
  };
  
  // Auto-populate employee ID for non-admin users
  useEffect(() => {
    if (!isAdmin() && employees.length > 0 && !formData.employeeId) {
      const currentUserId = localStorage.getItem('user_id');
      const currentUserEmployee = employees.find(emp => {
        if (emp.source === 'user_management') {
          return emp.original_user_id == currentUserId;
        }
        return emp.id == currentUserId;
      });
      
      if (currentUserEmployee) {
        setFormData(prev => ({ ...prev, employeeId: currentUserEmployee.employee_code }));
      }
    }
  }, [employees]);

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      // Fetch from both onboarding and user management like EIS does
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`${api.defaults.baseURL}/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        email: emp.email || `${emp.employee_id}@company.com`,
        source: 'onboarding'
      }));
      
      // Process user management employees
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          employee_code: user.employee_code,
          email: user.email || `${user.employee_code}@company.com`,
          source: 'user_management'
        }));
      
      // Combine and remove duplicates
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const fetchPendingAssets = async () => {
    try {
      const response = await api.get('/hr/assets/pending');
      console.log('Pending assets response:', response.data);
      const data = Array.isArray(response.data) ? response.data : [];
      setPendingAssets(data);
    } catch (error) {
      console.error('Error fetching pending assets:', error);
      setPendingAssets([]);
    }
  };

  const fetchApprovedAssets = async () => {
    try {
      const response = await api.get('/hr/assets/');
      const data = Array.isArray(response.data?.data) ? response.data.data : [];
      setAssets(data);
    } catch (error) {
      console.error('Error fetching approved assets:', error);
      setAssets([]);
    }
  };

  const getEmployeeEmail = (employeeCode) => {
    const employee = employees.find(emp => emp.employee_code === employeeCode);
    return employee?.email || `${employeeCode}@company.com`;
  };

  const handleApproval = async (assetId, approved) => {
    try {
      const asset = pendingAssets.find(a => a.id === assetId);
      if (!asset) return;

      const employeeEmail = getEmployeeEmail(asset.employeeId);
      
      await api.post('/hr/assets/approve', {
        assetId,
        approved,
        employeeEmail,
        assetDetails: asset
      });

      if (approved) {
        // Move to approved assets
        const approvedAsset = {
          ...asset,
          status: 'Assigned',
          approvedDate: new Date().toISOString().split('T')[0]
        };
        setAssets(prev => Array.isArray(prev) ? [approvedAsset, ...prev] : [approvedAsset]);
      }

      // Remove from pending
      setPendingAssets(prev => Array.isArray(prev) ? prev.filter(a => a.id !== assetId) : []);
      
      showToast(approved ? 'Asset approved successfully!' : 'Asset rejected successfully!');
    } catch (error) {
      console.error('Error processing approval:', error);
      showToast('Failed to process approval. Please try again.', 'error');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log("Asset data:", formData);
    
    try {
      // Save as pending asset
      const response = await api.post('/hr/assets/pending', formData);
      console.log('Asset created:', response.data);
      
      // Refresh pending assets to get real database data
      await fetchPendingAssets();
      
      // Show success message
      showToast('Asset assignment request submitted for approval!');
      
      // Reset form
      setFormData({
        employeeId: "",
        assetType: "",
        assetName: "",
        assetId: "",
        brand: "",
        model: "",
        serialNumber: "",
        assignedDate: "",
        condition: "",
        location: "",
        cost: "",
        remarks: ""
      });
    } catch (error) {
      console.error('Error saving asset:', error);
      showToast('Failed to save asset. Please try again.', 'error');
    }
  };

  return (
    <div className="space-y-6">
      {/* Asset Assignment Form */}
      <div className="rounded-lg shadow-sm bg-white relative overflow-hidden" style={{
        background: `linear-gradient(135deg, white 0%, ${colors.primary}05 100%)`,
        border: `1px solid ${colors.primary}20`
      }}>
        <div className="absolute top-0 right-0 w-64 h-64 rounded-full blur-3xl opacity-30 pointer-events-none" style={{
          background: `radial-gradient(circle, ${colors.primary}40 0%, transparent 70%)`,
          transform: 'translate(40%, -40%)'
        }}></div>
        <div className="px-6 py-4 border-b border-gray-200 relative z-10">
          <h3 className="text-lg font-semibold text-gray-900">Asset Assignment</h3>
        </div>
        <form onSubmit={handleSubmit} className="p-4 sm:p-6 relative z-10">
          {!canAdd ? (
            <div className="text-center py-8">
              <p className="text-gray-500">You don't have permission to create asset assignments.</p>
            </div>
          ) : (
            <>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Employee ID</label>
                  {isAdmin() ? (
                    <select 
                      value={formData.employeeId}
                      onChange={(e) => setFormData({...formData, employeeId: e.target.value})}
                      className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                      style={{
                        backgroundColor: `${colors.primary}10`,
                        border: `1px solid ${colors.primary}`
                      }}
                    >
                      <option value="">Select Employee</option>
                      {employees.map((emp) => (
                        <option key={emp.id} value={emp.employee_code}>
                          {emp.employee_code} - {emp.name}
                        </option>
                      ))}
                    </select>
                  ) : (
                    <div className="w-full px-3 py-2  rounded-md bg-gray-50 text-gray-700">
                      {(() => {
                        const currentUserId = localStorage.getItem('user_id');
                        const currentUserEmployee = employees.find(emp => {
                          if (emp.source === 'user_management') {
                            return emp.original_user_id == currentUserId;
                          }
                          return emp.id == currentUserId;
                        });
                        return currentUserEmployee ? `${currentUserEmployee.employee_code} - ${currentUserEmployee.name}` : 'Loading...';
                      })()} 
                    </div>
                  )}
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Asset Type</label>
                  <select 
                    value={formData.assetType}
                    onChange={(e) => setFormData({...formData, assetType: e.target.value})}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  >
                    <option value="">Select Type</option>
                    <option value="laptop">Laptop</option>
                    <option value="desktop">Desktop</option>
                    <option value="mobile">Mobile Phone</option>
                    <option value="tablet">Tablet</option>
                    <option value="monitor">Monitor</option>
                    <option value="keyboard">Keyboard</option>
                    <option value="mouse">Mouse</option>
                    <option value="headset">Headset</option>
                    <option value="printer">Printer</option>
                    <option value="furniture">Furniture</option>
                    <option value="vehicle">Vehicle</option>
                    <option value="other">Other</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Asset Name</label>
                  <input 
                    type="text"
                    value={formData.assetName}
                    onChange={(e) => setFormData({...formData, assetName: e.target.value})}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    placeholder="Asset name"
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Asset ID</label>
                  <input 
                    type="text"
                    value={formData.assetId}
                    onChange={(e) => setFormData({...formData, assetId: e.target.value})}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    placeholder="Unique asset ID"
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Brand</label>
                  <input 
                    type="text"
                    value={formData.brand}
                    onChange={(e) => setFormData({...formData, brand: e.target.value})}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    placeholder="Brand name"
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Model</label>
                  <input 
                    type="text"
                    value={formData.model}
                    onChange={(e) => setFormData({...formData, model: e.target.value})}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    placeholder="Model number"
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Serial Number</label>
                  <input 
                    type="text"
                    value={formData.serialNumber}
                    onChange={(e) => setFormData({...formData, serialNumber: e.target.value})}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    placeholder="Serial number"
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Assigned Date</label>
                  <input 
                    type="date"
                    value={formData.assignedDate}
                    onChange={(e) => setFormData({...formData, assignedDate: e.target.value})}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Condition</label>
                  <select 
                    value={formData.condition}
                    onChange={(e) => setFormData({...formData, condition: e.target.value})}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  >
                    <option value="">Select Condition</option>
                    <option value="new">New</option>
                    <option value="excellent">Excellent</option>
                    <option value="good">Good</option>
                    <option value="fair">Fair</option>
                    <option value="poor">Poor</option>
                    <option value="damaged">Damaged</option>
                  </select>
                </div>
                <div className="sm:col-span-2 lg:col-span-3">
                  <label className="block text-sm font-medium text-gray-700 mb-2">Remarks</label>
                  <textarea 
                    value={formData.remarks}
                    onChange={(e) => setFormData({...formData, remarks: e.target.value})}
                    rows={3}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                    placeholder="Additional remarks or special instructions..."
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  />
                </div>
              </div>
              <div className="mt-4 sm:mt-6 flex justify-end">
                <button 
                  type="submit"
                  className="w-full sm:w-auto px-6 py-2 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 text-sm sm:text-base transition-colors"
                  style={{
                    backgroundColor: colors.primary,
                    borderColor: colors.primary
                  }}
                  onMouseEnter={(e) => e.currentTarget.style.backgroundColor = colors.secondary}
                  onMouseLeave={(e) => e.currentTarget.style.backgroundColor = colors.primary}
                >
                  Submit for Approval
                </button>
              </div>
            </>
          )}
        </form>
      </div>

      {/* Pending Assets */}
      {pendingAssets.length > 0 && (
        <div className="rounded-lg shadow-sm bg-white relative overflow-hidden" style={{
          background: `linear-gradient(135deg, white 0%, ${colors.primary}05 100%)`,
          border: `1px solid ${colors.primary}20`
        }}>
          <div className="absolute top-0 right-0 w-64 h-64 rounded-full blur-3xl opacity-30 pointer-events-none" style={{
            background: `radial-gradient(circle, ${colors.primary}40 0%, transparent 70%)`,
            transform: 'translate(40%, -40%)'
          }}></div>
          <div className="px-6 py-4 border-b border-gray-200 relative z-10">
            <h3 className="text-lg font-semibold text-gray-900">Pending Asset Approvals</h3>
          </div>
          
          {/* Desktop Table View */}
          <div className="hidden md:block overflow-x-auto relative z-10" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
            <table className="min-w-full divide-y divide-gray-200 ">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Employee</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Asset</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Brand/Model</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Serial Number</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Assigned Date</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {pendingAssets.map((asset) => (
                  <tr key={asset.id}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-primary">{asset.name}</div>
                        <div className="text-sm text-muted">{asset.employee}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-primary">{asset.assetName}</div>
                        <div className="text-sm text-muted">{asset.assetType}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-primary">{asset.brand}</div>
                      <div className="text-sm text-muted">{asset.model}</div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{asset.serialNumber}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{asset.assignedDate || asset.requestDate}</td>
                    <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm font-medium">
                      <div className="flex flex-col sm:flex-row space-y-1 sm:space-y-0 sm:space-x-2">
                        {canApprove && (
                          <button
                            onClick={() => handleApproval(asset.id, true)}
                            className="inline-flex items-center justify-center px-2 sm:px-3 py-1 border text-xs sm:text-sm leading-4 font-medium rounded-md text-white transition-colors"
                            style={{
                              backgroundColor: colors.primary,
                              borderColor: colors.primary
                            }}
                            onMouseEnter={(e) => e.currentTarget.style.backgroundColor = colors.secondary}
                            onMouseLeave={(e) => e.currentTarget.style.backgroundColor = colors.primary}
                          >
                            <svg className="w-3 h-3 sm:w-4 sm:h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                            </svg>
                            <span className="hidden sm:inline">Approve</span>
                            <span className="sm:hidden">✓</span>
                          </button>
                        )}
                        {canReject && (
                          <button
                            onClick={() => handleApproval(asset.id, false)}
                            className="inline-flex items-center justify-center px-2 sm:px-3 py-1 border text-xs sm:text-sm leading-4 font-medium rounded-md text-white transition-colors"
                            style={{
                              backgroundColor: colors.secondary,
                              borderColor: colors.secondary
                            }}
                            onMouseEnter={(e) => e.currentTarget.style.backgroundColor = colors.primary}
                            onMouseLeave={(e) => e.currentTarget.style.backgroundColor = colors.secondary}
                          >
                            <svg className="w-3 h-3 sm:w-4 sm:h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                            </svg>
                            <span className="hidden sm:inline">Reject</span>
                            <span className="sm:hidden">✗</span>
                          </button>
                        )}
                        {!canApprove && !canReject && (
                          <div></div>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Mobile Card View */}
          <div className="md:hidden relative z-10">
            {pendingAssets.map((asset) => (
              <div key={asset.id} className="p-4 border-b-0 hover:bg-gray-50">
                <div className="flex items-center justify-between mb-3">
                  <div>
                    <div className="text-sm font-medium text-gray-900">{asset.name}</div>
                    <div className="text-sm text-gray-600">{asset.employee}</div>
                  </div>
                  <span className="inline-flex px-2 py-1 text-xs font-semibold rounded-full bg-yellow-100 text-yellow-800">
                    Pending
                  </span>
                </div>
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Asset:</span>
                    <div className="text-right">
                      <div className="text-sm text-gray-600">{asset.assetName}</div>
                      <div className="text-xs text-gray-500">{asset.assetType}</div>
                    </div>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Brand/Model:</span>
                    <div className="text-right">
                      <div className="text-sm text-gray-600">{asset.brand}</div>
                      <div className="text-xs text-gray-500">{asset.model}</div>
                    </div>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Serial:</span>
                    <span className="text-sm text-gray-600">{asset.serialNumber}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Date:</span>
                    <span className="text-sm text-gray-600">{asset.assignedDate || asset.requestDate}</span>
                  </div>
                </div>
                {(canApprove || canReject) && (
                  <div className="flex items-center justify-end gap-2 mt-3 pt-3 border-t border-gray-100">
                    {canApprove && (
                      <button
                        onClick={() => handleApproval(asset.id, true)}
                        className="flex items-center gap-1 px-3 py-1 text-sm text-white rounded-md transition-colors"
                        style={{
                          backgroundColor: colors.primary,
                          borderColor: colors.primary
                        }}
                        onMouseEnter={(e) => e.currentTarget.style.backgroundColor = colors.secondary}
                        onMouseLeave={(e) => e.currentTarget.style.backgroundColor = colors.primary}
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                        Approve
                      </button>
                    )}
                    {canReject && (
                      <button
                        onClick={() => handleApproval(asset.id, false)}
                        className="flex items-center gap-1 px-3 py-1 text-sm text-white rounded-md transition-colors"
                        style={{
                          backgroundColor: colors.secondary,
                          borderColor: colors.secondary
                        }}
                        onMouseEnter={(e) => e.currentTarget.style.backgroundColor = colors.primary}
                        onMouseLeave={(e) => e.currentTarget.style.backgroundColor = colors.secondary}
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                        Reject
                      </button>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Assets List */}
      <div className="rounded-lg shadow-sm bg-white relative overflow-hidden" style={{
        background: `linear-gradient(135deg, white 0%, ${colors.primary}05 100%)`,
        border: `1px solid ${colors.primary}20`
      }}>
        <div className="absolute top-0 right-0 w-64 h-64 rounded-full blur-3xl opacity-30 pointer-events-none" style={{
          background: `radial-gradient(circle, ${colors.primary}40 0%, transparent 70%)`,
          transform: 'translate(40%, -40%)'
        }}></div>
        <div className="px-6 py-4 border-b border-gray-200 relative z-10">
          <h3 className="text-lg font-semibold text-gray-900">All Assets</h3>
        </div>
        
        {/* Desktop Table View */}
        <div className="hidden md:block overflow-x-auto relative z-10" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
          <table className="min-w-full divide-y divide-gray-200 ">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Employee</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Asset</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Brand/Model</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Serial Number</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Assigned Date</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {assets.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-4 text-center text-gray-500">No assets found</td>
                </tr>
              ) : (
                assets.map((asset) => (
                  <tr key={asset.id}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-gray-900">{asset.name}</div>
                        <div className="text-sm text-gray-500">{asset.employee}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{asset.asset || asset.assetName}</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-gray-900">{asset.brand}</div>
                      <div className="text-sm text-gray-500">{asset.model}</div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{asset.serial || asset.serialNumber}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{asset.assignedDate}</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${
                        asset.status === 'Assigned' ? 'bg-green-100 text-green-800 border-green-300' : 
                        asset.status === 'Rejected' ? 'bg-red-100 text-red-800 border-red-300' : 
                        asset.status === 'Pending' ? 'bg-yellow-100 text-yellow-800 border-yellow-300' :
                        'bg-blue-100 text-blue-800 border-blue-300'
                      }`}>
                        {asset.status}
                      </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Mobile Card View */}
        <div className="md:hidden relative z-10">
          {assets.length === 0 ? (
            <div className="p-6 text-center text-gray-500">
              <p>No assets found</p>
            </div>
          ) : (
            assets.map((asset) => (
              <div key={asset.id} className="p-4 border-b-0 hover:bg-gray-50">
                <div className="flex items-center justify-between mb-3">
                  <div>
                    <div className="text-sm font-medium text-gray-900">{asset.name}</div>
                    <div className="text-sm text-gray-600">{asset.employee}</div>
                  </div>
                  <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${
                    asset.status === 'Assigned' ? 'bg-green-100 text-green-800 border-green-300' : 
                    asset.status === 'Rejected' ? 'bg-red-100 text-red-800 border-red-300' : 
                    asset.status === 'Pending' ? 'bg-yellow-100 text-yellow-800 border-yellow-300' :
                    'bg-blue-100 text-blue-800 border-blue-300'
                  }`}>
                    {asset.status}
                  </span>
                </div>
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Asset:</span>
                    <span className="text-sm text-gray-600">{asset.asset || asset.assetName}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Brand/Model:</span>
                    <div className="text-right">
                      <div className="text-sm text-gray-600">{asset.brand}</div>
                      <div className="text-xs text-gray-500">{asset.model}</div>
                    </div>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Serial:</span>
                    <span className="text-sm text-gray-600">{asset.serial || asset.serialNumber}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Assigned:</span>
                    <span className="text-sm text-gray-600">{asset.assignedDate}</span>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}

