import { useState, useEffect } from "react";
import api from "../../api";

export default function Assets() {
  const [formData, setFormData] = useState({
    employeeId: "",
    assetType: "",
    assetName: "",
    assetId: "",
    brand: "",
    model: "",
    serialNumber: "",
    assignedDate: "",
    condition: "",
    location: "",
    cost: "",
    remarks: ""
  });

  const [assets, setAssets] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [pendingAssets, setPendingAssets] = useState([]);

  useEffect(() => {
    fetchEmployees();
    fetchPendingAssets();
    fetchApprovedAssets();
  }, []);

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      // Fetch from both onboarding and user management like EIS does
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        email: emp.email || `${emp.employee_id}@company.com`,
        source: 'onboarding'
      }));
      
      // Process user management employees
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          name: user.name,
          employee_code: user.employee_code,
          email: user.email || `${user.employee_code}@company.com`,
          source: 'user_management'
        }));
      
      // Combine and remove duplicates
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const fetchPendingAssets = async () => {
    try {
      const response = await api.get('/hr/assets/pending');
      console.log('Pending assets response:', response.data);
      const data = Array.isArray(response.data) ? response.data : [];
      setPendingAssets(data);
    } catch (error) {
      console.error('Error fetching pending assets:', error);
      setPendingAssets([]);
    }
  };

  const fetchApprovedAssets = async () => {
    try {
      const response = await api.get('/hr/assets/');
      const data = Array.isArray(response.data?.data) ? response.data.data : [];
      setAssets(data);
    } catch (error) {
      console.error('Error fetching approved assets:', error);
      setAssets([]);
    }
  };

  const getEmployeeEmail = (employeeCode) => {
    const employee = employees.find(emp => emp.employee_code === employeeCode);
    return employee?.email || `${employeeCode}@company.com`;
  };

  const handleApproval = async (assetId, approved) => {
    try {
      const asset = pendingAssets.find(a => a.id === assetId);
      if (!asset) return;

      const employeeEmail = getEmployeeEmail(asset.employeeId);
      
      await api.post('/hr/assets/approve', {
        assetId,
        approved,
        employeeEmail,
        assetDetails: asset
      });

      if (approved) {
        // Move to approved assets
        const approvedAsset = {
          ...asset,
          status: 'Assigned',
          approvedDate: new Date().toISOString().split('T')[0]
        };
        setAssets(prev => Array.isArray(prev) ? [approvedAsset, ...prev] : [approvedAsset]);
      }

      // Remove from pending
      setPendingAssets(prev => Array.isArray(prev) ? prev.filter(a => a.id !== assetId) : []);
      
      alert(approved ? 'Asset approved successfully!' : 'Asset rejected successfully!');
    } catch (error) {
      console.error('Error processing approval:', error);
      alert('Failed to process approval. Please try again.');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log("Asset data:", formData);
    
    try {
      // Save as pending asset
      const response = await api.post('/hr/assets/pending', formData);
      console.log('Asset created:', response.data);
      
      // Refresh pending assets to get real database data
      await fetchPendingAssets();
      
      // Show success message
      alert('Asset assignment request submitted for approval!');
      
      // Reset form
      setFormData({
        employeeId: "",
        assetType: "",
        assetName: "",
        assetId: "",
        brand: "",
        model: "",
        serialNumber: "",
        assignedDate: "",
        condition: "",
        location: "",
        cost: "",
        remarks: ""
      });
    } catch (error) {
      console.error('Error saving asset:', error);
      alert('Failed to save asset. Please try again.');
    }
  };

  return (
    <div className="space-y-6">
      {/* Enhanced Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-white rounded-xl p-6 border shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className=" text-sm font-medium" style={{color: 'var(--text-secondary, #374151)'}}>Total Assets</p>
              <p className="text-3xl font-bold text-primary">{assets.length + pendingAssets.length}</p>
            </div>
            <div className="p-3 bg-blue-50 rounded-xl">
              <svg className="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z" />
              </svg>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl p-6 border shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className=" text-sm font-medium" style={{color: 'var(--text-secondary, #374151)'}}>Pending</p>
              <p className="text-3xl font-bold text-primary">{pendingAssets.length}</p>
            </div>
            <div className="p-3 bg-orange-50 rounded-xl">
              <svg className="w-8 h-8 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl p-6 border shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className=" text-sm font-medium" style={{color: 'var(--text-secondary, #374151)'}}>Assigned</p>
              <p className="text-3xl font-bold text-primary">{assets.length}</p>
            </div>
            <div className="p-3 bg-green-50 rounded-xl">
              <svg className="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
          </div>
        </div>
      </div>

      {/* Asset Assignment Form */}
      <div className="rounded-lg shadow-sm border" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
        <div className="px-6 py-4 border-b">
          <h3 className="text-lg font-semibold text-primary">Asset Assignment</h3>
        </div>
        <form onSubmit={handleSubmit} className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Employee ID</label>
              <select 
                value={formData.employeeId}
                onChange={(e) => setFormData({...formData, employeeId: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Select Employee</option>
                {employees.map((emp) => (
                  <option key={emp.id} value={emp.employee_code}>
                    {emp.employee_code} - {emp.name}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Asset Type</label>
              <select 
                value={formData.assetType}
                onChange={(e) => setFormData({...formData, assetType: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Select Type</option>
                <option value="laptop">Laptop</option>
                <option value="desktop">Desktop</option>
                <option value="mobile">Mobile Phone</option>
                <option value="tablet">Tablet</option>
                <option value="monitor">Monitor</option>
                <option value="keyboard">Keyboard</option>
                <option value="mouse">Mouse</option>
                <option value="headset">Headset</option>
                <option value="printer">Printer</option>
                <option value="furniture">Furniture</option>
                <option value="vehicle">Vehicle</option>
                <option value="other">Other</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Asset Name</label>
              <input 
                type="text"
                value={formData.assetName}
                onChange={(e) => setFormData({...formData, assetName: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Asset name"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Asset ID</label>
              <input 
                type="text"
                value={formData.assetId}
                onChange={(e) => setFormData({...formData, assetId: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Unique asset ID"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Brand</label>
              <input 
                type="text"
                value={formData.brand}
                onChange={(e) => setFormData({...formData, brand: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Brand name"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Model</label>
              <input 
                type="text"
                value={formData.model}
                onChange={(e) => setFormData({...formData, model: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Model number"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Serial Number</label>
              <input 
                type="text"
                value={formData.serialNumber}
                onChange={(e) => setFormData({...formData, serialNumber: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Serial number"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Assigned Date</label>
              <input 
                type="date"
                value={formData.assignedDate}
                onChange={(e) => setFormData({...formData, assignedDate: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Condition</label>
              <select 
                value={formData.condition}
                onChange={(e) => setFormData({...formData, condition: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Select Condition</option>
                <option value="new">New</option>
                <option value="excellent">Excellent</option>
                <option value="good">Good</option>
                <option value="fair">Fair</option>
                <option value="poor">Poor</option>
                <option value="damaged">Damaged</option>
              </select>
            </div>
            <div className="md:col-span-3">
              <label className="block text-sm font-medium text-secondary mb-2">Remarks</label>
              <textarea 
                value={formData.remarks}
                onChange={(e) => setFormData({...formData, remarks: e.target.value})}
                rows={3}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Additional remarks or special instructions..."
              />
            </div>
          </div>
          <div className="mt-6 flex justify-end">
            <button 
              type="submit"
              className="px-6 py-2 bg-orange-600 text-white rounded-md hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
            >
              Submit for Approval
            </button>
          </div>
        </form>
      </div>

      {/* Pending Assets */}
      {pendingAssets.length > 0 && (
        <div className="rounded-lg shadow-sm border" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
          <div className="px-6 py-4 border-b">
            <h3 className="text-lg font-semibold text-primary">Pending Asset Approvals</h3>
          </div>
          <div className="overflow-x-auto">
            <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="min-w-full divide-y">
              <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-content">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Employee</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Asset</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Brand/Model</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Serial Number</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Assigned Date</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-white divide-y">
                {pendingAssets.map((asset) => (
                  <tr key={asset.id}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-primary">{asset.name}</div>
                        <div className="text-sm text-muted">{asset.employee}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-primary">{asset.assetName}</div>
                        <div className="text-sm text-muted">{asset.assetType}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-primary">{asset.brand}</div>
                      <div className="text-sm text-muted">{asset.model}</div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{asset.serialNumber}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{asset.assignedDate || asset.requestDate}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                      <div className="flex space-x-2">
                        <button
                          onClick={() => handleApproval(asset.id, true)}
                          className="inline-flex items-center px-3 py-1 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"
                        >
                          <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                          </svg>
                          Approve
                        </button>
                        <button
                          onClick={() => handleApproval(asset.id, false)}
                          className="inline-flex items-center px-3 py-1 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
                        >
                          <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                          </svg>
                          Reject
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Assets List */}
      <div className="rounded-lg shadow-sm border" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
        <div className="px-6 py-4 border-b">
          <h3 className="text-lg font-semibold text-primary">All Assets</h3>
        </div>
        <div className="overflow-x-auto">
          <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="min-w-full divide-y">
            <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-content">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Employee</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Asset</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Brand/Model</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Serial Number</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Assigned Date</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Status</th>
              </tr>
            </thead>
            <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-white divide-y">
              {assets.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-4 text-center text-muted">No assets found</td>
                </tr>
              ) : (
                assets.map((asset) => (
                  <tr key={asset.id}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-primary">{asset.name}</div>
                        <div className="text-sm text-muted">{asset.employee}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{asset.asset || asset.assetName}</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-primary">{asset.brand}</div>
                      <div className="text-sm text-muted">{asset.model}</div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{asset.serial || asset.serialNumber}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{asset.assignedDate}</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                        asset.status === 'Rejected' ? 'bg-red-100 text-red-800' : 'bg-green-100 text-green-800'
                      }`}>
                        {asset.status}
                      </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
