import { useState, useEffect } from "react";
import api from "../../api";

export default function Communication() {
  const [formData, setFormData] = useState({
    employeeId: "",
    letterType: "",
    subject: "",
    content: "",
    priority: "",
    deliveryMethod: "",
    scheduledDate: "",
    approvalRequired: false
  });

  const [letters, setLetters] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [showModal, setShowModal] = useState(false);
  const [modalMode, setModalMode] = useState('view'); // 'view' or 'edit'
  const [selectedLetter, setSelectedLetter] = useState(null);

  useEffect(() => {
    const loadData = async () => {
      await fetchEmployees();
      await fetchLetters();
    };
    loadData();
  }, []);

  useEffect(() => {
    if (employees.length > 0) {
      fetchLetters();
    }
  }, [employees]);

  const fetchLetters = async () => {
    try {
      const response = await api.get('/hr/communication/');
      const fetchedLetters = response.data.map(comm => {
        const employeeCode = comm.sent_to_ids?.[0];
        const employee = employees.find(emp => emp.employee_code === employeeCode);
        
        return {
          id: comm.id,
          employee: employeeCode || 'All',
          name: employee ? employee.name : (employeeCode ? 'Employee Name' : 'All Employees'),
          type: comm.letter_type,
          subject: comm.subject,
          date: comm.created_at ? new Date(comm.created_at).toISOString().split('T')[0] : new Date().toISOString().split('T')[0],
          status: comm.status === 'Sent' ? 'Ready' : comm.status  // Convert Sent to Ready for display
        };
      });
      setLetters(fetchedLetters);
    } catch (error) {
      console.error('Error fetching letters:', error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      // Fetch from both onboarding and user management like EIS does
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        source: 'onboarding'
      }));
      
      // Process user management employees
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          name: user.name,
          employee_code: user.employee_code,
          source: 'user_management'
        }));
      
      // Combine and remove duplicates
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const handleOK = async () => {
    try {
      // Save to database via API
      await api.post('/hr/communication/', formData);
      
      // Add to letters list for immediate UI update
      const newLetter = {
        id: Date.now(),
        employee: formData.employeeId,
        name: employees.find(emp => emp.employee_code === formData.employeeId)?.name || 'Unknown',
        type: formData.letterType,
        subject: formData.subject,
        date: new Date().toISOString().split('T')[0],
        status: 'Ready'
      };
      
      setLetters(prev => [newLetter, ...prev]);
      
      // Show success message
      alert('Letter saved successfully!');
      
      // Reset form
      resetForm();
    } catch (error) {
      console.error('Error saving letter:', error);
      alert('Failed to save letter. Please try again.');
    }
  };

  const handlePrint = () => {
    if (!formData.content || !formData.subject) {
      alert('Please fill in the subject and content before printing.');
      return;
    }

    const employeeName = employees.find(emp => emp.employee_code === formData.employeeId)?.name || 'Employee';
    
    const printContent = `
      <html>
        <head>
          <title>HR Letter - ${formData.subject}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
            .company-name { font-size: 24px; font-weight: bold; color: #2c5aa0; }
            .letter-type { font-size: 16px; color: #666; margin-top: 5px; }
            .content { margin: 30px 0; }
            .subject { font-weight: bold; margin-bottom: 20px; }
            .footer { margin-top: 50px; }
            .signature { margin-top: 60px; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="company-name">Nutryah HRM</div>
            <div class="letter-type">${formData.letterType.toUpperCase()} LETTER</div>
          </div>
          
          <div class="content">
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
            <p><strong>To:</strong> ${employeeName} (${formData.employeeId})</p>
            
            <div class="subject">
              <strong>Subject:</strong> ${formData.subject}
            </div>
            
            <div style="white-space: pre-line; margin-top: 20px;">
              ${formData.content}
            </div>
          </div>
          
          <div class="footer">
            <div class="signature">
              <p>Best regards,</p>
              <br><br>
              <p>_________________________</p>
              <p><strong>Human Resources Department</strong></p>
              <p>Nutryah HRM</p>
            </div>
          </div>
        </body>
      </html>
    `;
    
    const printWindow = window.open('', '_blank');
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.print();
  };

  const handleViewLetter = async (letterId) => {
    try {
      const response = await api.get(`/hr/communication/${letterId}`);
      setSelectedLetter(response.data);
      setModalMode('view');
      setShowModal(true);
    } catch (error) {
      console.error('Error fetching letter:', error);
      alert('Failed to load letter details.');
    }
  };

  const handleEditLetter = async (letterId) => {
    try {
      const response = await api.get(`/hr/communication/${letterId}`);
      setSelectedLetter(response.data);
      setModalMode('edit');
      setShowModal(true);
    } catch (error) {
      console.error('Error fetching letter:', error);
      alert('Failed to load letter details.');
    }
  };

  const handleUpdateLetter = async () => {
    try {
      const updateData = {
        letterType: selectedLetter.letter_type,
        subject: selectedLetter.subject,
        content: selectedLetter.content,
        employeeId: selectedLetter.sent_to_ids?.[0] || '',
        status: 'Ready'
      };
      
      await api.put(`/hr/communication/${selectedLetter.id}`, updateData);
      
      // Update the letter in the list
      setLetters(prev => prev.map(letter => 
        letter.id === selectedLetter.id 
          ? { ...letter, status: 'Ready', subject: selectedLetter.subject, type: selectedLetter.letter_type }
          : letter
      ));
      
      setShowModal(false);
      alert('Letter updated and marked as ready!');
    } catch (error) {
      console.error('Error updating letter:', error);
      alert('Failed to update letter. Please try again.');
    }
  };

  const handleDeleteLetter = async (letterId) => {
    if (window.confirm('Are you sure you want to delete this letter?')) {
      try {
        await api.delete(`/hr/communication/${letterId}`);
        
        // Remove the letter from the list
        setLetters(prev => prev.filter(letter => letter.id !== letterId));
        
        alert('Letter deleted successfully!');
      } catch (error) {
        console.error('Error deleting letter:', error);
        alert('Failed to delete letter. Please try again.');
      }
    }
  };

  const handleSendDraft = async (letterId) => {
    try {
      await api.put(`/hr/communication/${letterId}/send`);
      
      // Update the letter status in the list
      setLetters(prev => prev.map(letter => 
        letter.id === letterId ? { ...letter, status: 'Sent' } : letter
      ));
      
      alert('Draft sent successfully!');
    } catch (error) {
      console.error('Error sending draft:', error);
      alert('Failed to send draft. Please try again.');
    }
  };

  const handlePrintLetter = (letter) => {
    const printContent = `
      <html>
        <head>
          <title>HR Letter - ${letter.subject}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
            .company-name { font-size: 24px; font-weight: bold; color: #2c5aa0; }
            .letter-type { font-size: 16px; color: #666; margin-top: 5px; }
            .content { margin: 30px 0; }
            .subject { font-weight: bold; margin-bottom: 20px; }
            .footer { margin-top: 50px; }
            .signature { margin-top: 60px; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="company-name">Nutryah HRM</div>
            <div class="letter-type">${letter.type.toUpperCase()} LETTER</div>
          </div>
          
          <div class="content">
            <p><strong>Date:</strong> ${letter.date}</p>
            <p><strong>To:</strong> ${letter.name} (${letter.employee})</p>
            
            <div class="subject">
              <strong>Subject:</strong> ${letter.subject}
            </div>
            
            <div style="white-space: pre-line; margin-top: 20px;">
              [Letter content would be displayed here]
            </div>
          </div>
          
          <div class="footer">
            <div class="signature">
              <p>Best regards,</p>
              <br><br>
              <p>_________________________</p>
              <p><strong>Human Resources Department</strong></p>
              <p>Nutryah HRM</p>
            </div>
          </div>
        </body>
      </html>
    `;
    
    const printWindow = window.open('', '_blank');
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.print();
  };

  const handleSaveDraft = async () => {
    try {
      // Save as draft via API
      await api.post('/hr/communication/draft', formData);
      
      // Add to letters list for immediate UI update
      const newLetter = {
        id: Date.now(),
        employee: formData.employeeId,
        name: employees.find(emp => emp.employee_code === formData.employeeId)?.name || 'Unknown',
        type: formData.letterType,
        subject: formData.subject,
        date: new Date().toISOString().split('T')[0],
        status: 'Draft'
      };
      
      setLetters(prev => [newLetter, ...prev]);
      
      // Show success message
      alert('Draft saved successfully!');
      
      // Reset form
      resetForm();
    } catch (error) {
      console.error('Error saving draft:', error);
      alert('Failed to save draft. Please try again.');
    }
  };

  const resetForm = () => {
    setFormData({
      employeeId: "",
      letterType: "",
      subject: "",
      content: "",
      priority: "",
      deliveryMethod: "",
      scheduledDate: "",
      approvalRequired: false
    });
  };

  return (
    <div className="space-y-6">
      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-white p-6 rounded-lg shadow-sm border">
          <div className="flex items-center">
            <div className="p-2 bg-blue-100 rounded-lg">
              <svg className="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 4.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-600">Total Letters</p>
              <p className="text-2xl font-semibold text-gray-900">{letters.length}</p>
            </div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-lg shadow-sm border">
          <div className="flex items-center">
            <div className="p-2 bg-green-100 rounded-lg">
              <svg className="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-600">Ready</p>
              <p className="text-2xl font-semibold text-gray-900">{letters.filter(l => l.status === 'Ready').length}</p>
            </div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-lg shadow-sm border">
          <div className="flex items-center">
            <div className="p-2 bg-yellow-100 rounded-lg">
              <svg className="w-6 h-6 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-600">Drafts</p>
              <p className="text-2xl font-semibold text-gray-900">{letters.filter(l => l.status === 'Draft').length}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Letter Creation Form */}
      <div className="bg-white rounded-lg shadow-sm border">
        <div className="px-6 py-4 border-b">
          <h3 className="text-lg font-semibold text-gray-900">Create HR Letter</h3>
        </div>
        <form className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Employee ID</label>
              <select 
                value={formData.employeeId}
                onChange={(e) => setFormData({...formData, employeeId: e.target.value})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Select Employee</option>
                {employees.map((emp) => (
                  <option key={emp.id} value={emp.employee_code}>
                    {emp.employee_code} - {emp.name}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Letter Type</label>
              <select 
                value={formData.letterType}
                onChange={(e) => setFormData({...formData, letterType: e.target.value})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Select Type</option>
                <option value="offer">Offer Letter</option>
                <option value="appointment">Appointment Letter</option>
                <option value="increment">Increment Letter</option>
                <option value="promotion">Promotion Letter</option>
                <option value="transfer">Transfer Letter</option>
                <option value="warning">Warning Letter</option>
                <option value="termination">Termination Letter</option>
                <option value="experience">Experience Certificate</option>
                <option value="relieving">Relieving Letter</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Priority</label>
              <select 
                value={formData.priority}
                onChange={(e) => setFormData({...formData, priority: e.target.value})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Select Priority</option>
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
                <option value="urgent">Urgent</option>
              </select>
            </div>
            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-gray-700 mb-2">Subject</label>
              <input 
                type="text"
                value={formData.subject}
                onChange={(e) => setFormData({...formData, subject: e.target.value})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Letter subject"
              />
            </div>
            <div className="md:col-span-3">
              <label className="block text-sm font-medium text-gray-700 mb-2">Content</label>
              <textarea 
                value={formData.content}
                onChange={(e) => setFormData({...formData, content: e.target.value})}
                rows={6}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Letter content..."
              />
            </div>
          </div>
          <div className="mt-6 flex justify-end space-x-3">
            <button 
              type="button"
              onClick={handleSaveDraft}
              className="px-6 py-2 border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              Save as Draft
            </button>
            <button 
              type="button"
              onClick={handleOK}
              className="px-6 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500"
            >
              OK
            </button>
          </div>
        </form>
      </div>

      {/* Letters History */}
      <div className="bg-white rounded-lg shadow-sm border">
        <div className="px-6 py-4 border-b">
          <h3 className="text-lg font-semibold text-gray-900">Recent Letters</h3>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Employee</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Subject</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {letters.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-4 text-center text-gray-500">No letters found</td>
                </tr>
              ) : (
                letters.map((letter) => (
                  <tr key={letter.id}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-gray-900">{letter.name}</div>
                        <div className="text-sm text-gray-500">{letter.employee}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{letter.type}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{letter.subject}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{letter.date}</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                        letter.status === 'Ready' ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'
                      }`}>
                        {letter.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                      <div className="flex space-x-2">
                        <button
                          onClick={() => handleViewLetter(letter.id)}
                          className="text-gray-600 hover:text-gray-900"
                          title="View Letter"
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                          </svg>
                        </button>
                        {letter.status === 'Draft' && (
                          <button
                            onClick={() => handleEditLetter(letter.id)}
                            className="text-blue-600 hover:text-blue-900"
                            title="Edit & Send"
                          >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                            </svg>
                          </button>
                        )}
                        <button
                          onClick={() => handlePrintLetter(letter)}
                          className="text-green-600 hover:text-green-900"
                          title="Print Letter"
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                          </svg>
                        </button>
                        <button
                          onClick={() => handleDeleteLetter(letter.id)}
                          className="text-red-600 hover:text-red-900"
                          title="Delete Letter"
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                          </svg>
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* View/Edit Modal */}
      {showModal && selectedLetter && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">
                {modalMode === 'view' ? 'View Letter' : 'Edit Letter'}
              </h3>
              <button
                onClick={() => setShowModal(false)}
                className="text-gray-500 hover:text-gray-700"
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Letter Type</label>
                {modalMode === 'view' ? (
                  <p className="text-sm text-gray-900">{selectedLetter.letter_type}</p>
                ) : (
                  <select
                    value={selectedLetter.letter_type}
                    onChange={(e) => setSelectedLetter({...selectedLetter, letter_type: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="offer">Offer Letter</option>
                    <option value="appointment">Appointment Letter</option>
                    <option value="increment">Increment Letter</option>
                    <option value="promotion">Promotion Letter</option>
                    <option value="transfer">Transfer Letter</option>
                    <option value="warning">Warning Letter</option>
                    <option value="termination">Termination Letter</option>
                    <option value="experience">Experience Certificate</option>
                    <option value="relieving">Relieving Letter</option>
                  </select>
                )}
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Subject</label>
                {modalMode === 'view' ? (
                  <p className="text-sm text-gray-900">{selectedLetter.subject}</p>
                ) : (
                  <input
                    type="text"
                    value={selectedLetter.subject}
                    onChange={(e) => setSelectedLetter({...selectedLetter, subject: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                )}
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Content</label>
                {modalMode === 'view' ? (
                  <div className="text-sm text-gray-900 whitespace-pre-line border border-gray-300 rounded-md p-3 min-h-[200px]">
                    {selectedLetter.content}
                  </div>
                ) : (
                  <textarea
                    value={selectedLetter.content}
                    onChange={(e) => setSelectedLetter({...selectedLetter, content: e.target.value})}
                    rows={8}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                )}
              </div>
            </div>
            
            <div className="flex justify-end space-x-3 mt-6">
              <button
                onClick={() => setShowModal(false)}
                className="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400"
              >
                {modalMode === 'view' ? 'Close' : 'Cancel'}
              </button>
              {modalMode === 'edit' && (
                <button
                  onClick={handleUpdateLetter}
                  className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700"
                >
                  Update & Mark Ready
                </button>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}