import { useState, useEffect } from "react";
import api from "../../api";

export default function Grievances() {
  const [formData, setFormData] = useState({
    employeeId: "",
    grievanceType: "",
    priority: "",
    subject: "",
    description: "",
    dateOccurred: "",
    anonymousComplaint: false
  });

  const [grievances, setGrievances] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [viewModal, setViewModal] = useState({ show: false, grievance: null });

  useEffect(() => {
    fetchEmployees();
    fetchGrievances();
  }, []);

  const fetchGrievances = async () => {
    try {
      console.log('Fetching grievances...');
      const response = await api.get('/hr/grievances');
      console.log('Grievances response:', response.data);
      setGrievances(response.data || []);
    } catch (error) {
      console.error('Error fetching grievances:', error);
      setGrievances([]);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      // Fetch from both onboarding and user management like EIS does
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        source: 'onboarding'
      }));
      
      // Process user management employees
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          name: user.name,
          employee_code: user.employee_code,
          source: 'user_management'
        }));
      
      // Combine and remove duplicates
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const handleView = async (id) => {
    try {
      const response = await api.get(`/hr/grievances/${id}`);
      setViewModal({ show: true, grievance: response.data });
    } catch (error) {
      console.error('Error fetching grievance details:', error);
      alert('Failed to load grievance details');
    }
  };

  const handleDelete = async (id) => {
    if (!confirm('Are you sure you want to delete this grievance?')) return;
    
    try {
      await api.delete(`/hr/grievances/${id}`);
      setGrievances(prev => prev.filter(g => g.id !== id));
      alert('Grievance deleted successfully');
    } catch (error) {
      console.error('Error deleting grievance:', error);
      alert('Failed to delete grievance');
    }
  };

  const handleCompleteInvestigation = async (id) => {
    try {
      await api.post(`/hr/grievances/${id}/complete`);
      setGrievances(prev => prev.map(g => 
        g.id === id ? { ...g, status: 'Resolved' } : g
      ));
      alert('Investigation marked as completed');
    } catch (error) {
      console.error('Error completing investigation:', error);
      alert('Failed to complete investigation');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log("Grievance data:", formData);
    
    try {
      // Save to database via API
      console.log('Submitting grievance:', formData);
      const response = await api.post('/hr/grievances', formData);
      console.log('Grievance created:', response.data);
      
      // Clear any existing data and refresh
      setGrievances([]);
      setTimeout(async () => {
        await fetchGrievances();
      }, 500);
      
      // Show success message
      alert('Grievance submitted successfully!');
      
      // Reset form
      setFormData({
        employeeId: "",
        grievanceType: "",
        priority: "",
        subject: "",
        description: "",
        dateOccurred: "",
        anonymousComplaint: false
      });
    } catch (error) {
      console.error('Error saving grievance:', error);
      alert('Failed to submit grievance. Please try again.');
    }
  };

  return (
    <div className="space-y-6">
      {/* Grievance Form */}
      <div className="rounded-lg shadow-sm border border-black bg-white">
        <div className="px-6 py-4 border-b border-black">
          <h3 className="text-lg font-semibold text-gray-900">Submit Grievance</h3>
        </div>
        <form onSubmit={handleSubmit} className="p-4 sm:p-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Employee ID</label>
              <select 
                value={formData.employeeId}
                onChange={(e) => setFormData({...formData, employeeId: e.target.value})}
                className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
              >
                <option value="">Select Employee</option>
                {employees.map((emp) => (
                  <option key={emp.id} value={emp.employee_code}>
                    {emp.employee_code} - {emp.name}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Grievance Type</label>
              <select 
                value={formData.grievanceType}
                onChange={(e) => setFormData({...formData, grievanceType: e.target.value})}
                className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
              >
                <option value="">Select Type</option>
                <option value="harassment">Harassment</option>
                <option value="discrimination">Discrimination</option>
                <option value="policy_violation">Policy Violation</option>
                <option value="workplace_safety">Workplace Safety</option>
                <option value="compensation">Compensation Issues</option>
                <option value="work_environment">Work Environment</option>
                <option value="management_issues">Management Issues</option>
                <option value="other">Other</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Priority</label>
              <select 
                value={formData.priority}
                onChange={(e) => setFormData({...formData, priority: e.target.value})}
                className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
              >
                <option value="">Select Priority</option>
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
                <option value="critical">Critical</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Date of Occurrence</label>
              <input 
                type="date"
                value={formData.dateOccurred}
                onChange={(e) => setFormData({...formData, dateOccurred: e.target.value})}
                className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
              />
            </div>
            <div className="sm:col-span-2 lg:col-span-2">
              <label className="block text-sm font-medium text-gray-700 mb-2">Subject</label>
              <input 
                type="text"
                value={formData.subject}
                onChange={(e) => setFormData({...formData, subject: e.target.value})}
                className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                placeholder="Brief subject of the grievance"
              />
            </div>
            <div className="sm:col-span-2 lg:col-span-3">
              <label className="block text-sm font-medium text-gray-700 mb-2">Description</label>
              <textarea 
                value={formData.description}
                onChange={(e) => setFormData({...formData, description: e.target.value})}
                rows={4}
                className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                placeholder="Detailed description of the grievance..."
              />
            </div>
          </div>
          <div className="mt-4 sm:mt-6 flex justify-end">
            <button 
              type="submit"
              className="w-full sm:w-auto px-6 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-500 border border-black text-sm sm:text-base"
            >
              Submit Grievance
            </button>
          </div>
        </form>
      </div>

      {/* Grievances List */}
      <div className="rounded-lg shadow-sm border border-black bg-white">
        <div className="px-6 py-4 border-b border-black">
          <h3 className="text-lg font-semibold text-gray-900">Grievances Management</h3>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200 border border-black">
            <thead className="bg-gray-50 border-b border-black">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Employee</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Category</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Priority</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Date</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {grievances.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-4 text-center text-gray-500">No grievances found</td>
                </tr>
              ) : (
                grievances.map((grievance) => (
                  <tr key={grievance.id}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-gray-900">{grievance.employee_name || 'Unknown'}</div>
                        <div className="text-sm text-gray-500">{grievance.employee_code || 'N/A'}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{grievance.category || 'N/A'}</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${
                        grievance.priority === 'high' ? 'bg-gray-100 text-gray-800 border-gray-300' : 
                        grievance.priority === 'medium' ? 'bg-gray-50 text-gray-700 border-gray-200' : 'bg-gray-100 text-gray-600 border-gray-300'
                      }`}>
                        {grievance.priority || 'Medium'}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {grievance.created_at ? new Date(grievance.created_at).toLocaleDateString() : 'N/A'}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${
                        grievance.status === 'Resolved' ? 'bg-gray-100 text-gray-800 border-gray-300' : 
                        grievance.status === 'Under Investigation' ? 'bg-gray-50 text-gray-700 border-gray-200' : 'bg-gray-100 text-gray-600 border-gray-300'
                      }`}>
                        {grievance.status || 'Under Investigation'}
                      </span>
                    </td>
                    <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm font-medium">
                      <div className="flex flex-wrap gap-1 sm:gap-2">
                        <button
                          onClick={() => handleView(grievance.id)}
                          className="text-gray-600 hover:text-gray-900 border border-gray-300 px-2 py-1 rounded text-xs sm:text-sm"
                        >
                          View
                        </button>
                        <button
                          onClick={() => handleDelete(grievance.id)}
                          className="text-gray-600 hover:text-gray-900 border border-gray-300 px-2 py-1 rounded text-xs sm:text-sm"
                        >
                          Delete
                        </button>
                        {grievance.status !== 'Resolved' && (
                          <button
                            onClick={() => handleCompleteInvestigation(grievance.id)}
                            className="text-gray-600 hover:text-gray-900 border border-gray-300 px-2 py-1 rounded text-xs sm:text-sm"
                          >
                            Complete
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* View Modal */}
      {viewModal.show && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50 p-4">
          <div className="relative top-20 mx-auto p-4 sm:p-5 border w-full max-w-2xl shadow-lg rounded-md bg-white">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">Grievance Details</h3>
              <button
                onClick={() => setViewModal({ show: false, grievance: null })}
                className=" hover:text-secondary" style={{color: 'var(--text-muted, #6b7280)'}}
              >
                ✕
              </button>
            </div>
            {viewModal.grievance && (
              <div className="space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-secondary">Ticket Code</label>
                    <p className="text-sm text-primary">{viewModal.grievance.ticket_code}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Employee</label>
                    <p className="text-sm text-primary">{viewModal.grievance.employee_name} ({viewModal.grievance.employee_code})</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Category</label>
                    <p className="text-sm text-primary">{viewModal.grievance.category}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Priority</label>
                    <p className="text-sm text-primary">{viewModal.grievance.priority}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Status</label>
                    <p className="text-sm text-primary">{viewModal.grievance.status}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Created Date</label>
                    <p className="text-sm text-primary">{new Date(viewModal.grievance.created_at).toLocaleDateString()}</p>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary">Description</label>
                  <p className="text-sm text-primary mt-1">{viewModal.grievance.description}</p>
                </div>
                {viewModal.grievance.resolution_notes && (
                  <div>
                    <label className="block text-sm font-medium text-secondary">Resolution Notes</label>
                    <p className="text-sm text-primary mt-1">{viewModal.grievance.resolution_notes}</p>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
