import { useState, useEffect } from "react";
import api from "../../api";
import useToast from "../../utils/useToast";
import Toast from "../../components/Toast";
import { hasPermission, isAdmin } from "../../utils/permissions";

export default function Grievances() {
  const { toast, showToast, hideToast } = useToast();
  const [colors, setColors] = useState({ primary: '#2862e9', secondary: '#474e71' });
  
  // Permission checks
  const canView = hasPermission('view_grievances') || hasPermission('view_self');
  const canAdd = hasPermission('add_grievance');
  const canDelete = hasPermission('delete_grievance');
  const canResolve = hasPermission('resolve_grievance');
  
  if (!canView) {
    return (
      <div className="p-6 text-center">
        <div className="bg-white rounded-2xl border-0 p-8 max-w-md mx-auto">
          <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <span className="text-2xl">🔒</span>
          </div>
          <h3 className="text-lg font-medium text-gray-900 mb-2">Access Denied</h3>
          <p className="text-gray-600">You don't have permission to view grievances.</p>
        </div>
      </div>
    );
  }
  
  const [formData, setFormData] = useState({
    employeeId: "",
    grievanceType: "",
    priority: "",
    subject: "",
    description: "",
    dateOccurred: "",
    anonymousComplaint: false
  });

  const [grievances, setGrievances] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [viewModal, setViewModal] = useState({ show: false, grievance: null });

  // Auto-populate current user when employees are loaded (only for non-admin users)
  useEffect(() => {
    if (employees.length > 0 && !isAdmin()) {
      const currentUserId = localStorage.getItem('user_id');
      if (currentUserId && !formData.employeeId) {
        const currentUserEmployee = employees.find(emp => {
          if (emp.source === 'user_management') {
            return emp.original_user_id == currentUserId;
          }
          return emp.id == currentUserId;
        });
        if (currentUserEmployee) {
          setFormData(prev => ({ ...prev, employeeId: currentUserEmployee.employee_code }));
        }
      }
    }
  }, [employees]);

  useEffect(() => {
    fetchColors();
    fetchEmployees();
    fetchGrievances();
  }, []);

  const fetchColors = async () => {
    try {
      const tenantCode = localStorage.getItem('tenant_code');
      if (tenantCode) {
        const response = await api.get(`/auth/branding/${tenantCode}`);
        if (response.data.primary_color && response.data.secondary_color) {
          setColors({
            primary: response.data.primary_color,
            secondary: response.data.secondary_color
          });
        }
      }
    } catch (error) {
      console.error('Error fetching colors:', error);
    }
  };

  const fetchGrievances = async () => {
    try {
      console.log('Fetching grievances...');
      const response = await api.get('/hr/grievances');
      console.log('Grievances response:', response.data);
      setGrievances(response.data || []);
    } catch (error) {
      console.error('Error fetching grievances:', error);
      showToast('Failed to load grievances', 'error');
      setGrievances([]);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      // Fetch from both onboarding and user management like EIS does
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`${api.defaults.baseURL}/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        source: 'onboarding'
      }));
      
      // Process user management employees
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          employee_code: user.employee_code,
          source: 'user_management'
        }));
      
      // Combine and remove duplicates
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
      showToast('Failed to load employees', 'error');
    }
  };

  const handleView = async (id) => {
    try {
      const response = await api.get(`/hr/grievances/${id}`);
      setViewModal({ show: true, grievance: response.data });
    } catch (error) {
      console.error('Error fetching grievance details:', error);
      showToast('Failed to load grievance details', 'error');
    }
  };

  const handleDelete = async (id) => {
    if (!confirm('Are you sure you want to delete this grievance?')) return;
    
    try {
      await api.delete(`/hr/grievances/${id}`);
      setGrievances(prev => prev.filter(g => g.id !== id));
      showToast('Grievance deleted successfully', 'success');
    } catch (error) {
      console.error('Error deleting grievance:', error);
      showToast('Failed to delete grievance', 'error');
    }
  };

  const handleCompleteInvestigation = async (id) => {
    try {
      await api.post(`/hr/grievances/${id}/complete`);
      setGrievances(prev => prev.map(g => 
        g.id === id ? { ...g, status: 'Resolved' } : g
      ));
      showToast('Investigation marked as completed', 'success');
    } catch (error) {
      console.error('Error completing investigation:', error);
      showToast('Failed to complete investigation', 'error');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log("Grievance data:", formData);
    
    try {
      // Save to database via API
      console.log('Submitting grievance:', formData);
      const response = await api.post('/hr/grievances', formData);
      console.log('Grievance created:', response.data);
      
      // Clear any existing data and refresh
      setGrievances([]);
      setTimeout(async () => {
        await fetchGrievances();
      }, 500);
      
      // Show success message
      showToast('Grievance submitted successfully!', 'success');
      
      // Reset form
      setFormData({
        employeeId: "",
        grievanceType: "",
        priority: "",
        subject: "",
        description: "",
        dateOccurred: "",
        anonymousComplaint: false
      });
    } catch (error) {
      console.error('Error saving grievance:', error);
      showToast('Failed to submit grievance. Please try again.', 'error');
    }
  };

  return (
    <div className="space-y-6">
      {/* Grievance Form */}
      <div className="rounded-lg shadow-sm bg-white relative overflow-hidden" style={{
        background: `linear-gradient(135deg, white 0%, ${colors.primary}05 100%)`,
        border: `1px solid ${colors.primary}20`
      }}>
        <div className="absolute top-0 right-0 w-64 h-64 rounded-full blur-3xl opacity-30 pointer-events-none" style={{
          background: `radial-gradient(circle, ${colors.primary}40 0%, transparent 70%)`,
          transform: 'translate(40%, -40%)'
        }}></div>
        <div className="px-6 py-4 border-b border-gray-200 relative z-10">
          <h3 className="text-lg font-semibold text-gray-900">Submit Grievance</h3>
        </div>
        <form onSubmit={handleSubmit} className="p-4 sm:p-6 relative z-10">
          {!canAdd ? (
            <div className="text-center py-8">
              <p className="text-gray-500">You don't have permission to create grievances.</p>
            </div>
          ) : (
            <>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Employee ID</label>
                  {isAdmin() ? (
                    <select 
                      value={formData.employeeId}
                      onChange={(e) => setFormData({...formData, employeeId: e.target.value})}
                      className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                      style={{
                        backgroundColor: `${colors.primary}10`,
                        border: `1px solid ${colors.primary}`
                      }}
                    >
                      <option value="">Select Employee</option>
                      {employees.map((emp) => (
                        <option key={emp.id} value={emp.employee_code}>
                          {emp.employee_code} - {emp.name}
                        </option>
                      ))}
                    </select>
                  ) : (
                    <div className="w-full px-3 py-2  rounded-md bg-gray-50 text-gray-700">
                      {(() => {
                        const currentUserId = localStorage.getItem('user_id');
                        const currentUserEmployee = employees.find(emp => {
                          if (emp.source === 'user_management') {
                            return emp.original_user_id == currentUserId;
                          }
                          return emp.id == currentUserId;
                        });
                        return currentUserEmployee ? `${currentUserEmployee.employee_code} - ${currentUserEmployee.name}` : 'Loading...';
                      })()} 
                    </div>
                  )}
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Grievance Type</label>
                  <select 
                    value={formData.grievanceType}
                    onChange={(e) => setFormData({...formData, grievanceType: e.target.value})}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  >
                    <option value="">Select Type</option>
                    <option value="harassment">Harassment</option>
                    <option value="discrimination">Discrimination</option>
                    <option value="policy_violation">Policy Violation</option>
                    <option value="workplace_safety">Workplace Safety</option>
                    <option value="compensation">Compensation Issues</option>
                    <option value="work_environment">Work Environment</option>
                    <option value="management_issues">Management Issues</option>
                    <option value="other">Other</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Priority</label>
                  <select 
                    value={formData.priority}
                    onChange={(e) => setFormData({...formData, priority: e.target.value})}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  >
                    <option value="">Select Priority</option>
                    <option value="low">Low</option>
                    <option value="medium">Medium</option>
                    <option value="high">High</option>
                    <option value="critical">Critical</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Date of Occurrence</label>
                  <input 
                    type="date"
                    value={formData.dateOccurred}
                    onChange={(e) => setFormData({...formData, dateOccurred: e.target.value})}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  />
                </div>
                <div className="sm:col-span-2 lg:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 mb-2">Subject</label>
                  <input 
                    type="text"
                    value={formData.subject}
                    onChange={(e) => setFormData({...formData, subject: e.target.value})}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                    placeholder="Brief subject of the grievance"
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  />
                </div>
                <div className="sm:col-span-2 lg:col-span-3">
                  <label className="block text-sm font-medium text-gray-700 mb-2">Description</label>
                  <textarea 
                    value={formData.description}
                    onChange={(e) => setFormData({...formData, description: e.target.value})}
                    rows={4}
                    className="w-full px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                    placeholder="Detailed description of the grievance..."
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  />
                </div>
              </div>
              <div className="mt-4 sm:mt-6 flex justify-end">
                <button 
                  type="submit"
                  className="w-full sm:w-auto px-6 py-2 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 text-sm sm:text-base transition-colors"
                  style={{
                    backgroundColor: colors.primary,
                    borderColor: colors.primary
                  }}
                  onMouseEnter={(e) => e.currentTarget.style.backgroundColor = colors.secondary}
                  onMouseLeave={(e) => e.currentTarget.style.backgroundColor = colors.primary}
                >
                  Submit Grievance
                </button>
              </div>
            </>
          )}
        </form>
      </div>

      {/* Grievances List */}
      <div className="rounded-lg shadow-sm bg-white relative overflow-hidden" style={{
        background: `linear-gradient(135deg, white 0%, ${colors.primary}05 100%)`,
        border: `1px solid ${colors.primary}20`
      }}>
        <div className="absolute top-0 right-0 w-64 h-64 rounded-full blur-3xl opacity-30 pointer-events-none" style={{
          background: `radial-gradient(circle, ${colors.primary}40 0%, transparent 70%)`,
          transform: 'translate(40%, -40%)'
        }}></div>
        <div className="px-6 py-4 border-b border-gray-200 relative z-10">
          <h3 className="text-lg font-semibold text-gray-900">Grievances Management</h3>
        </div>
        
        {/* Desktop Table View */}
        <div className="hidden md:block overflow-x-auto relative z-10" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
          <table className="min-w-full divide-y divide-gray-200 ">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Employee</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Category</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Priority</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Date</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {grievances.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-4 text-center text-gray-500">No grievances found</td>
                </tr>
              ) : (
                grievances.map((grievance) => (
                  <tr key={grievance.id}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-gray-900">{grievance.employee_name || 'Unknown'}</div>
                        <div className="text-sm text-gray-500">{grievance.employee_code || 'N/A'}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{grievance.category || 'N/A'}</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${
                        grievance.priority === 'critical' ? 'bg-red-100 text-red-800 border-red-300' : 
                        grievance.priority === 'high' ? 'bg-orange-100 text-orange-800 border-orange-300' : 
                        grievance.priority === 'medium' ? 'bg-yellow-100 text-yellow-800 border-yellow-300' : 
                        'bg-green-100 text-green-800 border-green-300'
                      }`}>
                        {grievance.priority || 'Medium'}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {grievance.created_at ? new Date(grievance.created_at).toLocaleDateString() : 'N/A'}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${
                        grievance.status === 'Resolved' ? 'bg-green-100 text-green-800 border-green-300' : 
                        grievance.status === 'Under Investigation' ? 'bg-yellow-100 text-yellow-800 border-yellow-300' : 
                        grievance.status === 'Pending' ? 'bg-orange-100 text-orange-800 border-orange-300' :
                        'bg-blue-100 text-blue-800 border-blue-300'
                      }`}>
                        {grievance.status || 'Under Investigation'}
                      </span>
                    </td>
                    <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm font-medium">
                      <div className="flex flex-wrap gap-1 sm:gap-2">
                        <button
                          onClick={() => handleView(grievance.id)}
                          className="p-1 text-gray-600 hover:text-gray-900  rounded"
                          title="View Details"
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                          </svg>
                        </button>
                        {canDelete && (
                          <button
                            onClick={() => handleDelete(grievance.id)}
                            className="p-1 text-red-600 hover:text-red-900 border border-red-300 rounded"
                            title="Delete"
                          >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                            </svg>
                          </button>
                        )}
                        {canResolve && grievance.status !== 'Resolved' && (
                          <button
                            onClick={() => handleCompleteInvestigation(grievance.id)}
                            className="p-1 text-green-600 hover:text-green-900  rounded"
                            title="Complete Investigation"
                          >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                            </svg>
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Mobile Card View */}
        <div className="md:hidden relative z-10">
          {grievances.length === 0 ? (
            <div className="p-6 text-center text-gray-500">
              <p>No grievances found</p>
            </div>
          ) : (
            grievances.map((grievance) => (
              <div key={grievance.id} className="p-4 border-b-0 hover:bg-gray-50">
                <div className="flex items-center justify-between mb-3">
                  <div>
                    <div className="text-sm font-medium text-gray-900">{grievance.employee_name || 'Unknown'}</div>
                    <div className="text-sm text-gray-500">{grievance.employee_code || 'N/A'}</div>
                  </div>
                  <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${
                    grievance.status === 'Resolved' ? 'bg-green-100 text-green-800 border-green-300' : 
                    grievance.status === 'Under Investigation' ? 'bg-yellow-100 text-yellow-800 border-yellow-300' : 
                    grievance.status === 'Pending' ? 'bg-orange-100 text-orange-800 border-orange-300' :
                    'bg-blue-100 text-blue-800 border-blue-300'
                  }`}>
                    {grievance.status || 'Under Investigation'}
                  </span>
                </div>
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Category:</span>
                    <span className="text-sm text-gray-600">{grievance.category || 'N/A'}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Priority:</span>
                    <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${
                      grievance.priority === 'critical' ? 'bg-red-100 text-red-800 border-red-300' : 
                      grievance.priority === 'high' ? 'bg-orange-100 text-orange-800 border-orange-300' : 
                      grievance.priority === 'medium' ? 'bg-yellow-100 text-yellow-800 border-yellow-300' : 
                      'bg-green-100 text-green-800 border-green-300'
                    }`}>
                      {grievance.priority || 'Medium'}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Date:</span>
                    <span className="text-sm text-gray-600">
                      {grievance.created_at ? new Date(grievance.created_at).toLocaleDateString() : 'N/A'}
                    </span>
                  </div>
                </div>
                <div className="flex items-center justify-end gap-2 mt-3 pt-3 border-t border-gray-100">
                  <button
                    onClick={() => handleView(grievance.id)}
                    className="flex items-center gap-1 text-gray-600 hover:text-gray-900 px-3 py-1 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                    View
                  </button>
                  {canDelete && (
                    <button
                      onClick={() => handleDelete(grievance.id)}
                      className="flex items-center gap-1 text-red-600 hover:text-red-900 px-3 py-1 rounded-lg hover:bg-red-50 transition-colors text-sm"
                    >
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                      </svg>
                      Delete
                    </button>
                  )}
                  {canResolve && grievance.status !== 'Resolved' && (
                    <button
                      onClick={() => handleCompleteInvestigation(grievance.id)}
                      className="flex items-center gap-1 text-green-600 hover:text-green-900 px-3 py-1 rounded-lg hover:bg-green-50 transition-colors text-sm"
                    >
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                      Resolve
                    </button>
                  )}
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {/* View Modal */}
      {viewModal.show && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50 p-4" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
          <div className="relative top-20 mx-auto p-4 sm:p-5 border w-full max-w-2xl shadow-lg rounded-md bg-white">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">Grievance Details</h3>
              <button
                onClick={() => setViewModal({ show: false, grievance: null })}
                className=" hover:text-secondary" style={{color: 'var(--text-muted, #6b7280)'}}
              >
                ✕
              </button>
            </div>
            {viewModal.grievance && (
              <div className="space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-secondary">Ticket Code</label>
                    <p className="text-sm text-primary">{viewModal.grievance.ticket_code}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Employee</label>
                    <p className="text-sm text-primary">{viewModal.grievance.employee_name} ({viewModal.grievance.employee_code})</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Category</label>
                    <p className="text-sm text-primary">{viewModal.grievance.category}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Priority</label>
                    <p className="text-sm text-primary">{viewModal.grievance.priority}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Status</label>
                    <p className="text-sm text-primary">{viewModal.grievance.status}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-secondary">Created Date</label>
                    <p className="text-sm text-primary">{new Date(viewModal.grievance.created_at).toLocaleDateString()}</p>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary">Description</label>
                  <p className="text-sm text-primary mt-1">{viewModal.grievance.description}</p>
                </div>
                {viewModal.grievance.resolution_notes && (
                  <div>
                    <label className="block text-sm font-medium text-secondary">Resolution Notes</label>
                    <p className="text-sm text-primary mt-1">{viewModal.grievance.resolution_notes}</p>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      )}
      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}

