import { useState, useEffect } from "react";
import api from "../../api";
import useToast from "../../utils/useToast";
import Toast from "../../components/Toast";
import { hasPermission } from "../../utils/permissions";

export default function Insurance() {
  const { toast, showToast, hideToast } = useToast();
  
  // Permission checks
  const canView = hasPermission('view_insurance_benefits');
  const canAdd = hasPermission('add_insurance_benefit');
  const canDelete = hasPermission('delete_insurance_policy');
  
  if (!canView) {
    return (
      <div className="p-6 text-center">
        <div className="bg-white rounded-2xl border border-gray-200 p-8 max-w-md mx-auto">
          <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <span className="text-2xl">🔒</span>
          </div>
          <h3 className="text-lg font-medium text-gray-900 mb-2">Access Denied</h3>
          <p className="text-gray-600">You don't have permission to view insurance benefits.</p>
        </div>
      </div>
    );
  }
  
  const [formData, setFormData] = useState({
    employeeId: "",
    policyType: "",
    policyNumber: "",
    provider: "",
    coverageAmount: "",
    startDate: "",
    expiryDate: ""
  });

  const [employees, setEmployees] = useState([]);
  const [policies, setPolicies] = useState([]);
  const [stats, setStats] = useState({ total: 0, active: 0, expiring_soon: 0, expired: 0 });

  useEffect(() => {
    fetchEmployees();
    fetchPolicies();
    fetchStats();
  }, []);

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        email: emp.email || `${emp.employee_id}@company.com`,
        source: 'onboarding'
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          name: user.name,
          employee_code: user.employee_code,
          email: user.email || `${user.employee_code}@company.com`,
          source: 'user_management'
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
      showToast('Failed to load employees', 'error');
    }
  };

  const fetchStats = async () => {
    try {
      const response = await api.get('/hr/insurance/stats');
      setStats(response.data || { total: 0, active: 0, expiring_soon: 0, expired: 0 });
    } catch (error) {
      console.error('Error fetching stats:', error);
      showToast('Failed to load insurance statistics', 'error');
    }
  };

  const fetchPolicies = async () => {
    try {
      const response = await api.get('/hr/insurance/');
      setPolicies(response.data?.data || []);
    } catch (error) {
      console.error('Error fetching policies:', error);
      showToast('Failed to load insurance policies', 'error');
      setPolicies([]);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    try {
      await api.post('/hr/insurance/', formData);
      
      await fetchPolicies();
      await fetchStats();
      
      showToast('Insurance policy created successfully!', 'success');
      
      setFormData({
        employeeId: "",
        policyType: "",
        policyNumber: "",
        provider: "",
        coverageAmount: "",
        startDate: "",
        expiryDate: ""
      });
    } catch (error) {
      console.error('Error creating policy:', error);
      showToast('Failed to create policy. Please try again.', 'error');
    }
  };

  const handleDelete = async (policyId) => {
    if (!confirm('Are you sure you want to delete this policy?')) return;
    
    try {
      await api.delete(`/hr/insurance/${policyId}`);
      await fetchPolicies();
      await fetchStats();
      showToast('Policy deleted successfully!', 'success');
    } catch (error) {
      console.error('Error deleting policy:', error);
      showToast('Failed to delete policy. Please try again.', 'error');
    }
  };

  return (
    <div className="space-y-6">
      {/* Insurance Policy Form */}
      <div className="rounded-lg shadow-sm border border-black bg-white">
        <div className="px-6 py-4 border-b border-black">
          <h3 className="text-lg font-semibold text-gray-900">Add Insurance Policy(Optional)</h3>
        </div>
        <form onSubmit={handleSubmit} className="p-4 sm:p-6">
          {!canAdd ? (
            <div className="text-center py-8">
              <p className="text-gray-500">You don't have permission to create insurance policies.</p>
            </div>
          ) : (
            <>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Employee</label>
                  <select 
                    value={formData.employeeId}
                    onChange={(e) => setFormData({...formData, employeeId: e.target.value})}
                    className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    required
                  >
                    <option value="">Select Employee</option>
                    {employees.map((emp) => (
                      <option key={emp.id} value={emp.employee_code}>
                        {emp.employee_code} - {emp.name}
                      </option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Policy Type</label>
                  <input 
                    type="text"
                    value={formData.policyType}
                    onChange={(e) => setFormData({...formData, policyType: e.target.value})}
                    className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    placeholder="e.g., Medical, Life, Accident"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Policy Number</label>
                  <input 
                    type="text"
                    value={formData.policyNumber}
                    onChange={(e) => setFormData({...formData, policyNumber: e.target.value})}
                    className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    placeholder="Policy number"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Provider</label>
                  <input 
                    type="text"
                    value={formData.provider}
                    onChange={(e) => setFormData({...formData, provider: e.target.value})}
                    className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    placeholder="Insurance provider"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Coverage Amount</label>
                  <input 
                    type="number"
                    value={formData.coverageAmount}
                    onChange={(e) => setFormData({...formData, coverageAmount: e.target.value})}
                    className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    placeholder="Coverage amount"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Start Date</label>
                  <input 
                    type="date"
                    value={formData.startDate}
                    onChange={(e) => setFormData({...formData, startDate: e.target.value})}
                    className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Expiry Date</label>
                  <input 
                    type="date"
                    value={formData.expiryDate}
                    onChange={(e) => setFormData({...formData, expiryDate: e.target.value})}
                    className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500"
                    required
                  />
                </div>
              </div>
              <div className="mt-4 sm:mt-6 flex justify-end">
                <button 
                  type="submit"
                  className="w-full sm:w-auto px-6 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-500 border border-black text-sm sm:text-base"
                >
                  Add Policy
                </button>
              </div>
            </>
          )}
        </form>
      </div>

      {/* Policies List */}
      <div className="rounded-lg shadow-sm border border-black bg-white">
        <div className="px-6 py-4 border-b border-black">
          <h3 className="text-lg font-semibold text-gray-900">Insurance Policies</h3>
        </div>
        
        {/* Desktop Table View */}
        <div className="hidden md:block overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200 border border-black">
            <thead className="bg-gray-50 border-b border-black">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Employee</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Policy Type</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Policy Number</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Provider</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Coverage</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Expiry Date</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {policies.length === 0 ? (
                <tr>
                  <td colSpan={8} className="px-6 py-4 text-center text-gray-500">No policies found</td>
                </tr>
              ) : (
                policies.map((policy) => (
                  <tr key={policy.id}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-gray-900">{policy.name}</div>
                        <div className="text-sm text-gray-500">{policy.employee}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{policy.policyType}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{policy.policyNumber}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{policy.provider}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">₹{policy.coverageAmount?.toLocaleString()}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{policy.expiryDate}</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${
                        policy.status === 'Active' ? 'bg-gray-100 text-gray-800 border-gray-300' : 'bg-gray-50 text-gray-600 border-gray-200'
                      }`}>
                        {policy.status}
                      </span>
                    </td>
                    <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm font-medium">
                      {canDelete && (
                        <button
                          onClick={() => handleDelete(policy.id)}
                          className="text-gray-600 hover:text-gray-900 border border-gray-300 px-2 py-1 rounded text-xs sm:text-sm"
                        >
                          Delete
                        </button>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Mobile Card View */}
        <div className="md:hidden">
          {policies.length === 0 ? (
            <div className="p-6 text-center text-gray-500">
              <p>No policies found</p>
            </div>
          ) : (
            policies.map((policy) => (
              <div key={policy.id} className="p-4 border-b border-gray-200 hover:bg-gray-50">
                <div className="flex items-center justify-between mb-3">
                  <div>
                    <div className="text-sm font-medium text-gray-900">{policy.name}</div>
                    <div className="text-sm text-gray-500">{policy.employee}</div>
                  </div>
                  <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${
                    policy.status === 'Active' ? 'bg-gray-100 text-gray-800 border-gray-300' : 'bg-gray-50 text-gray-600 border-gray-200'
                  }`}>
                    {policy.status}
                  </span>
                </div>
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Policy Type:</span>
                    <span className="text-sm text-gray-600">{policy.policyType}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Policy Number:</span>
                    <span className="text-sm text-gray-600">{policy.policyNumber}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Provider:</span>
                    <span className="text-sm text-gray-600">{policy.provider}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Coverage:</span>
                    <span className="text-sm text-gray-600">₹{policy.coverageAmount?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Expiry Date:</span>
                    <span className="text-sm text-gray-600">{policy.expiryDate}</span>
                  </div>
                </div>
                {canDelete && (
                  <div className="flex items-center justify-end mt-3 pt-3 border-t border-gray-100">
                    <button
                      onClick={() => handleDelete(policy.id)}
                      className="flex items-center gap-1 text-red-600 hover:text-red-900 px-3 py-1 rounded-lg hover:bg-red-50 transition-colors text-sm"
                    >
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                      </svg>
                      Delete
                    </button>
                  </div>
                )}
              </div>
            ))
          )}
        </div>
      </div>
      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}
