import { useState, useEffect } from "react";
import api from "../../api";

export default function Lifecycle() {
  const [formData, setFormData] = useState({
    employeeId: "",
    actionType: "",
    effectiveDate: "",
    currentRole: "",
    newRole: "",
    currentDepartment: "",
    newDepartment: "",
    currentGrade: "",
    newGrade: "",
    currentSalary: "",
    newSalary: "",
    reason: "",
    remarks: ""
  });

  const [employees, setEmployees] = useState([]);
  const [actions, setActions] = useState([]);
  const [pendingActions, setPendingActions] = useState([]);
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [emailData, setEmailData] = useState({ email: '', actionId: null, approved: false, action: null });

  useEffect(() => {
    fetchEmployees();
    fetchPendingActions();
    fetchApprovedActions();
  }, []);

  const handleApproval = async (actionId, approved) => {
    try {
      const action = pendingActions.find(a => a.id === actionId);
      if (!action) return;

      const employeeEmail = getEmployeeEmail(action.employee);
      
      // Show email modal for confirmation
      setEmailData({ email: employeeEmail, actionId, approved, action });
      setShowEmailModal(true);
    } catch (error) {
      console.error('Error preparing approval:', error);
      alert('Failed to prepare approval. Please try again.');
    }
  };

  const submitApproval = async () => {
    try {
      const { actionId, approved, action, email } = emailData;
      
      // Validate email
      if (!email || !email.trim()) {
        alert('Please enter a valid email address');
        return;
      }
      
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) {
        alert('Please enter a valid email format');
        return;
      }
      
      await api.post('/hr/lifecycle/approve', {
        actionId,
        approved,
        employeeEmail: email,
        actionDetails: action
      });

      if (approved) {
        // Move to approved actions with all details
        const approvedAction = {
          ...action,
          status: approved ? 'Approved' : 'Rejected',
          approvedDate: new Date().toISOString().split('T')[0]
        };
        setActions(prev => [approvedAction, ...(prev || [])]);
      } else {
        // Move rejected action to actions list too
        const rejectedAction = {
          ...action,
          status: 'Rejected',
          approvedDate: new Date().toISOString().split('T')[0]
        };
        setActions(prev => [rejectedAction, ...(prev || [])]);
      }

      // Remove from pending
      setPendingActions(prev => (prev || []).filter(a => a.id !== actionId));
      
      // Refresh approved actions to get latest data from database
      await fetchApprovedActions();
      
      setShowEmailModal(false);
      alert(approved ? 'Action approved and email sent!' : 'Action rejected and email sent!');
    } catch (error) {
      console.error('Error processing approval:', error);
      if (error.response?.status === 404) {
        // Action not found, refresh data
        fetchPendingActions();
        fetchApprovedActions();
        setShowEmailModal(false);
        alert('Action not found. Data has been refreshed.');
      } else {
        alert('Failed to process approval. Please try again.');
      }
    }
  };

  const getEmployeeEmail = (employeeCode) => {
    if (!employeeCode) return 'employee@company.com';
    const employee = employees.find(emp => emp.employee_code === employeeCode);
    return employee?.email || `${employeeCode.toLowerCase()}@company.com`;
  };



  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      // Fetch from both onboarding and user management like EIS does
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        email: emp.email || `${emp.employee_id}@company.com`,
        source: 'onboarding'
      }));
      
      // Process user management employees
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          name: user.name,
          employee_code: user.employee_code,
          email: user.email || `${user.employee_code}@company.com`,
          source: 'user_management'
        }));
      
      // Combine and remove duplicates
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const fetchPendingActions = async () => {
    try {
      const response = await api.get('/hr/lifecycle/pending');
      setPendingActions(response.data?.data || []);
    } catch (error) {
      console.error('Error fetching pending actions:', error);
      setPendingActions([]);
    }
  };

  const fetchApprovedActions = async () => {
    try {
      const response = await api.get('/hr/lifecycle/');
      setActions(response.data?.data || []);
    } catch (error) {
      console.error('Error fetching approved actions:', error);
      setActions([]);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log("Lifecycle action:", formData);
    
    try {
      // Save as pending lifecycle action
      const pendingAction = {
        ...formData,
        employee_name: employees.find(emp => emp.employee_code === formData.employeeId)?.name || 'Unknown',
        action_type: formData.actionType,
        effective_date: formData.effectiveDate
      };
      
      await api.post('/hr/lifecycle/pending', pendingAction);
      
      // Refresh pending actions from database to get correct IDs
      await fetchPendingActions();
      
      // Show success message
      alert('Lifecycle action submitted for approval!');
      
      // Reset form
      setFormData({
        employeeId: "",
        actionType: "",
        effectiveDate: "",
        currentRole: "",
        newRole: "",
        currentDepartment: "",
        newDepartment: "",
        currentGrade: "",
        newGrade: "",
        currentSalary: "",
        newSalary: "",
        reason: "",
        remarks: ""
      });
    } catch (error) {
      console.error('Error saving lifecycle action:', error);
      alert('Failed to save action. Please try again.');
    }
  };

  return (
    <div className="space-y-6">
      {/* Enhanced Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-6 gap-4">
        <div className="bg-content rounded-xl p-4 border shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className=" text-xs font-medium" style={{color: 'var(--text-secondary, #374151)'}}>Promotions</p>
              <p className="text-xl font-bold text-primary">{actions.filter(a => a.action === 'promotion' || a.actionType === 'promotion').length}</p>
            </div>
            <div className="p-2 bg-green-50 rounded-lg">
              <svg className="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
              </svg>
            </div>
          </div>
        </div>
        <div className="bg-content rounded-xl p-4 border shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className=" text-xs font-medium" style={{color: 'var(--text-secondary, #374151)'}}>Transfers</p>
              <p className="text-xl font-bold text-primary">{actions.filter(a => a.action === 'transfer' || a.actionType === 'transfer').length}</p>
            </div>
            <div className="p-2 bg-blue-50 rounded-lg">
              <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4" />
              </svg>
            </div>
          </div>
        </div>
        <div className="bg-content rounded-xl p-4 border shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className=" text-xs font-medium" style={{color: 'var(--text-secondary, #374151)'}}>Pending</p>
              <p className="text-xl font-bold text-primary">{pendingActions.length}</p>
            </div>
            <div className="p-2 bg-yellow-50 rounded-lg">
              <svg className="w-5 h-5 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
          </div>
        </div>
        <div className="bg-content rounded-xl p-4 border shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className=" text-xs font-medium" style={{color: 'var(--text-secondary, #374151)'}}>Demotions</p>
              <p className="text-xl font-bold text-primary">{actions.filter(a => a.action === 'demotion' || a.actionType === 'demotion').length}</p>
            </div>
            <div className="p-2 bg-orange-50 rounded-lg">
              <svg className="w-5 h-5 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 17h8m0 0V9m0 8l-8-8-4 4-6-6" />
              </svg>
            </div>
          </div>
        </div>
        <div className="bg-content rounded-xl p-4 border shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className=" text-xs font-medium" style={{color: 'var(--text-secondary, #374151)'}}>Resignations</p>
              <p className="text-xl font-bold text-primary">{actions.filter(a => a.action === 'resignation' || a.actionType === 'resignation').length}</p>
            </div>
            <div className="p-2 bg-red-50 rounded-lg">
              <svg className="w-5 h-5 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
              </svg>
            </div>
          </div>
        </div>
        <div className="bg-content rounded-xl p-4 border shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className=" text-xs font-medium" style={{color: 'var(--text-secondary, #374151)'}}>Terminations</p>
              <p className="text-xl font-bold text-primary">{actions.filter(a => a.action === 'termination' || a.actionType === 'termination').length}</p>
            </div>
            <div className="p-2 bg-gray-100 rounded-lg">
              <svg className="w-5 h-5 text-secondary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </div>
          </div>
        </div>
      </div>

      {/* Enhanced Action Form */}
      <div className="rounded-2xl shadow-lg border border-gray-100" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
        <div className="bg-gradient-to-r from-orange-50 to-red-50 px-6 py-4 border-b  rounded-t-2xl">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-orange-100 rounded-xl">
              <svg className="w-5 h-5 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
              </svg>
            </div>
            <h3 className="text-lg font-semibold text-primary">Employee Lifecycle Action</h3>
          </div>
        </div>
        <form onSubmit={handleSubmit} className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Employee ID</label>
              <select 
                value={formData.employeeId}
                onChange={(e) => setFormData({...formData, employeeId: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Select Employee</option>
                {employees.map((emp) => (
                  <option key={emp.id} value={emp.employee_code}>
                    {emp.employee_code} - {emp.name}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Action Type</label>
              <select 
                value={formData.actionType}
                onChange={(e) => setFormData({...formData, actionType: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Select Action</option>
                <option value="promotion">Promotion</option>
                <option value="transfer">Transfer</option>
                <option value="demotion">Demotion</option>
                <option value="resignation">Resignation</option>
                <option value="termination">Termination</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Effective Date</label>
              <input 
                type="date"
                value={formData.effectiveDate}
                onChange={(e) => setFormData({...formData, effectiveDate: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Current Role</label>
              <input 
                type="text"
                value={formData.currentRole}
                onChange={(e) => setFormData({...formData, currentRole: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Current designation"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">New Role</label>
              <input 
                type="text"
                value={formData.newRole}
                onChange={(e) => setFormData({...formData, newRole: e.target.value})}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="New designation"
              />
            </div>
            <div className="md:col-span-3">
              <label className="block text-sm font-medium text-secondary mb-2">Reason</label>
              <textarea 
                value={formData.reason}
                onChange={(e) => setFormData({...formData, reason: e.target.value})}
                rows={3}
                className="w-full px-3 py-2 border-dark rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Reason for this action"
              />
            </div>
          </div>
          <div className="mt-6 flex justify-end">
            <button 
              type="submit"
              className="px-6 py-2 bg-orange-600 text-white rounded-md hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
            >
              Submit for Approval
            </button>
          </div>
        </form>
      </div>

      {/* Pending Actions */}
      {pendingActions.length > 0 && (
        <div className="rounded-lg shadow-sm border" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
          <div className="px-6 py-4 border-b">
            <h3 className="text-lg font-semibold text-primary">Pending Action Approvals</h3>
          </div>
          <div className="overflow-x-auto">
            <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="min-w-full divide-y">
              <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-content">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Employee</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Action</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">From</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">To</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Date</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-white divide-y">
                {pendingActions.map((action) => (
                  <tr key={action.id}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-primary">{action.name}</div>
                        <div className="text-sm text-muted">{action.employee}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{action.action}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{action.from}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{action.to}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{action.date}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                      <div className="flex space-x-2">
                        <button
                          onClick={() => handleApproval(action.id, true)}
                          className="inline-flex items-center px-3 py-1 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"
                        >
                          <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                          </svg>
                          Approve
                        </button>
                        <button
                          onClick={() => handleApproval(action.id, false)}
                          className="inline-flex items-center px-3 py-1 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
                        >
                          <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                          </svg>
                          Reject
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Actions History */}
      <div className="rounded-lg shadow-sm border" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
        <div className="px-6 py-4 border-b">
          <h3 className="text-lg font-semibold text-primary">Approved Actions</h3>
        </div>
        <div className="overflow-x-auto">
          <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="min-w-full divide-y">
            <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-content">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Employee</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Action</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">From</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">To</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Date</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Status</th>
              </tr>
            </thead>
            <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-white divide-y">
              {actions.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-4 text-center text-muted">No actions found</td>
                </tr>
              ) : (
                actions.map((action) => (
                  <tr key={action.id}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-primary">{action.name || action.employee_name}</div>
                        <div className="text-sm text-muted">{action.employee || action.employeeId}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{action.action || action.actionType}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{action.from || action.currentRole}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{action.to || action.newRole}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">{action.date || action.effectiveDate}</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center space-x-2">
                        <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                          action.status === 'Approved' ? 'bg-green-100 text-green-800' : 
                          action.status === 'Rejected' ? 'bg-red-100 text-red-800' : 'bg-yellow-100 text-yellow-800'
                        }`}>
                          {action.status}
                        </span>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Email Confirmation Modal */}
      {showEmailModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <h3 className="text-lg font-semibold mb-4">
              {emailData.approved ? 'Approve' : 'Reject'} Lifecycle Action
            </h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-secondary mb-1">Employee Email</label>
                <input
                  type="email"
                  value={emailData.email}
                  onChange={(e) => setEmailData({...emailData, email: e.target.value})}
                  className="w-full px-3 py-2 border-dark rounded-lg focus:ring-2 focus:ring-blue-500"
                  placeholder="employee@company.com"
                />
              </div>
              
              <div className="bg-content p-3 rounded-lg">
                <p className="text-sm text-secondary"><strong>Employee:</strong> {emailData.action?.name}</p>
                <p className="text-sm text-secondary"><strong>Action:</strong> {emailData.action?.action}</p>
                <p className="text-sm text-secondary"><strong>From:</strong> {emailData.action?.from} → <strong>To:</strong> {emailData.action?.to}</p>
              </div>
            </div>
            
            <div className="flex gap-2 mt-6">
              <button
                onClick={submitApproval}
                className={`flex-1 px-4 py-2 text-white rounded-lg ${
                  emailData.approved ? 'bg-green-600 hover:bg-green-700' : 'bg-red-600 hover:bg-red-700'
                }`}
              >
                {emailData.approved ? 'Approve' : 'Reject'} & Send Email
              </button>
              <button
                onClick={() => setShowEmailModal(false)}
                className="px-4 py-2 bg-gray-300 text-secondary rounded-lg hover:bg-gray-400"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
