import { useEffect, useState } from "react";
import api from "../../api";
import Sidebar from "../../components/Sidebar";
import Header from "../../components/Header";
import * as XLSX from 'xlsx';

export default function AttendanceLogs() {
  const [logs, setLogs] = useState([]);
  const [activeTab, setActiveTab] = useState('logs');
  const [currentStatus, setCurrentStatus] = useState(null);
  const [checkInSource, setCheckInSource] = useState(null);
  const [location, setLocation] = useState(null);
  const [loading, setLoading] = useState(false);
  const [employees, setEmployees] = useState([]);
  const [selectedEmployee, setSelectedEmployee] = useState("");
  const [attendanceMode, setAttendanceMode] = useState(""); // 'WEB' or 'MOBILE'
  const [gpsPermissionGranted, setGpsPermissionGranted] = useState(false);
  const [officeLocations, setOfficeLocations] = useState([]);
  const [selectedLocation, setSelectedLocation] = useState("");
  const [showAddLocation, setShowAddLocation] = useState(false);
  const [newLocationName, setNewLocationName] = useState("");
  const [regularizationForm, setRegularizationForm] = useState({
    employee_id: "",
    date: "",
    issue_type: "Missed IN",
    reason: ""
  });
  const [regularizationRequests, setRegularizationRequests] = useState([]);
  const [reportFilters, setReportFilters] = useState({
    reportType: 'daily',
    fromDate: new Date().toISOString().split('T')[0],
    toDate: new Date().toISOString().split('T')[0],
    employeeId: ''
  });
  const [reportData, setReportData] = useState([]);
  const [odApplications, setOdApplications] = useState([]);
  const [odForm, setOdForm] = useState({
    employee_id: "",
    od_date: "",
    purpose: "",
    from_time: "",
    to_time: "",
    location: ""
  });

  useEffect(() => {
    fetchEmployees();
    fetchLogs();
    fetchOfficeLocations();
    fetchRegularizationRequests();
    fetchOdApplications();
    checkTodayStatus();
  }, []);

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      // Fetch from both onboarding and user management (same as shifts)
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        source: 'onboarding'
      }));
      
      // Process user management employees
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          employee_code: user.employee_code,
          source: 'user_management'
        }));
      
      // Combine and remove duplicates
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
    }
  };

  const fetchLogs = async () => {
    try {
      const res = await api.get("/api/attendance/punches/");
      setLogs(res.data);
    } catch (err) {
      console.error("Failed to fetch logs:", err);
    }
  };

  const fetchOfficeLocations = async () => {
    try {
      const res = await api.get("/api/attendance/locations/");
      setOfficeLocations(res.data || []);
      if (res.data && res.data.length > 0) {
        setSelectedLocation(res.data[0].id); // Set first location as default
      }
    } catch (err) {
      console.error("Failed to fetch locations:", err);
      setOfficeLocations([{ id: 1, name: "Office - Main Building" }]); // Fallback
      setSelectedLocation(1);
    }
  };

  const checkTodayStatus = () => {
    if (!selectedEmployee) {
      setCurrentStatus('not_checked_in');
      setCheckInSource(null);
      return;
    }
    
    const today = new Date().toISOString().split('T')[0];
    const actualEmployeeId = selectedEmployee.startsWith('user_') ? selectedEmployee.replace('user_', '') : selectedEmployee;
    const todayLog = logs.find(log => 
      log.employee_id == actualEmployeeId && log.date === today
    );
    
    if (todayLog) {
      if (todayLog.out_time) {
        setCurrentStatus('checked_out');
        setCheckInSource(null);
      } else {
        setCurrentStatus('checked_in');
        setCheckInSource(todayLog.source);
      }
    } else {
      setCurrentStatus('not_checked_in');
      setCheckInSource(null);
    }
  };

  const getCurrentLocation = () => {
    return new Promise((resolve, reject) => {
      if (!navigator.geolocation) {
        reject(new Error('Geolocation not supported'));
        return;
      }
      
      navigator.geolocation.getCurrentPosition(
        (position) => {
          const { latitude, longitude } = position.coords;
          resolve(`${latitude.toFixed(6)}, ${longitude.toFixed(6)}`);
        },
        (error) => {
          console.warn('GPS error:', error);
          resolve('Location unavailable');
        },
        { timeout: 10000, enableHighAccuracy: true }
      );
    });
  };

  const handlePunchIn = async (source) => {
    if (currentStatus === 'checked_in') {
      alert('You are already checked in today!');
      return;
    }
    
    // Check if there's already a record for today
    const today = new Date().toISOString().split('T')[0];
    const actualEmployeeId = selectedEmployee.startsWith('user_') ? selectedEmployee.replace('user_', '') : selectedEmployee;
    const existingRecord = logs.find(log => 
      log.employee_id == actualEmployeeId && log.date === today
    );
    
    if (existingRecord) {
      // Don't show alert, just update status to show checkout option
      setCurrentStatus(existingRecord.out_time ? 'checked_out' : 'checked_in');
      setCheckInSource(existingRecord.source);
      return;
    }
    
    setLoading(true);
    try {
      const currentDate = new Date().toISOString().split('T')[0];
      const currentTime = new Date().toTimeString().split(' ')[0];
      
      const selectedLocationObj = officeLocations.find(loc => loc.id == selectedLocation);
      let locationStr = selectedLocationObj ? (selectedLocationObj.location_name || selectedLocationObj.name) : 'Office Location';
      
      if (source === 'MOBILE') {
        try {
          locationStr = await getCurrentLocation();
          locationStr = `GPS: ${locationStr}`;
        } catch (err) {
          alert('Failed to get GPS location. Please try again.');
          setLoading(false);
          return;
        }
      }
      
      const actualEmployeeId = selectedEmployee.startsWith('user_') ? parseInt(selectedEmployee.replace('user_', '')) : parseInt(selectedEmployee);
      
      console.log('Debug punch data:', {
        employee_id: actualEmployeeId,
        date: currentDate,
        in_time: currentTime,
        location: locationStr,
        source: source
      });
      
      const punchData = {
        employee_id: actualEmployeeId,
        date: currentDate,
        in_time: currentTime,
        location: locationStr,
        source: source,
        status: 'Present'
      };
      
      const response = await api.post("/api/attendance/punches/", punchData);
      console.log('Success response:', response.data);
      
      setCurrentStatus('checked_in');
      setCheckInSource(source);
      fetchLogs();
      
      // Success notification
      const notification = document.createElement('div');
      notification.className = 'fixed top-4 right-4 bg-green-500 text-white px-6 py-3 rounded-lg shadow-lg z-50';
      notification.innerHTML = `
        <div class="flex items-center gap-2">
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
          </svg>
          <div>
            <div class="font-semibold">Check-In Successful!</div>
            <div class="text-sm opacity-90">Time: ${new Date().toLocaleTimeString()}</div>
          </div>
        </div>
      `;
      document.body.appendChild(notification);
      setTimeout(() => notification.remove(), 4000);
      
    } catch (err) {
      console.error("Punch-in failed:", err);
      console.error("Error response:", err.response?.data);
      console.error("Error details:", JSON.stringify(err.response?.data, null, 2));
      const errorDetail = err.response?.data?.detail?.[0]?.msg || err.response?.data?.detail || err.message;
      alert(`Check-in failed: ${errorDetail}`);
    } finally {
      setLoading(false);
    }
  };

  const handlePunchOut = async (source) => {
    if (currentStatus !== 'checked_in') {
      alert('You need to check in first!');
      return;
    }
    
    if (checkInSource !== source) {
      alert(`You checked in via ${checkInSource}. Please use ${checkInSource} check-out.`);
      return;
    }
    
    setLoading(true);
    try {
      const currentDate = new Date().toISOString().split('T')[0];
      const currentTime = new Date().toTimeString().split(' ')[0];
      
      const actualEmployeeId = selectedEmployee.startsWith('user_') ? selectedEmployee.replace('user_', '') : selectedEmployee;
      const todayLog = logs.find(log => 
        log.employee_id == actualEmployeeId && log.date === currentDate && !log.out_time
      );
      
      if (todayLog) {
        let locationStr = todayLog.location;
        
        if (source === 'MOBILE') {
          try {
            const gpsLocation = await getCurrentLocation();
            locationStr = `${todayLog.location} | Out: GPS ${gpsLocation}`;
          } catch (err) {
            locationStr = `${todayLog.location} | Out: Mobile`;
          }
        }
        
        const updateData = {
          employee_id: parseInt(todayLog.employee_id),
          date: todayLog.date,
          in_time: todayLog.in_time,
          out_time: currentTime,
          location: locationStr,
          source: todayLog.source,
          status: todayLog.status || 'Present'
        };
        
        await api.put(`/api/attendance/punches/${todayLog.id}/`, updateData);
        
        setCurrentStatus('checked_out');
        setCheckInSource(null);
        fetchLogs();
        
        // Calculate work hours
        const inTime = new Date(`2000-01-01 ${todayLog.in_time}`);
        const outTime = new Date(`2000-01-01 ${currentTime}`);
        const workHours = ((outTime - inTime) / (1000 * 60 * 60)).toFixed(1);
        
        // Success notification
        const notification = document.createElement('div');
        notification.className = 'fixed top-4 right-4 bg-blue-500 text-white px-6 py-3 rounded-lg shadow-lg z-50';
        notification.innerHTML = `
          <div class="flex items-center gap-2">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd"></path>
            </svg>
            <div>
              <div class="font-semibold">Check-Out Successful!</div>
              <div class="text-sm opacity-90">Work Hours: ${workHours}h | Time: ${new Date().toLocaleTimeString()}</div>
            </div>
          </div>
        `;
        document.body.appendChild(notification);
        setTimeout(() => notification.remove(), 5000);
        
      } else {
        alert("No active check-in found for today.");
      }
    } catch (err) {
      console.error("Check-out failed:", err);
      alert("Check-out failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const fetchRegularizationRequests = async () => {
    try {
      const res = await api.get('/api/attendance/regularizations/');
      const requests = res.data.map(req => {
        const employee = employees.find(e => e.id == req.employee_id || `user_${e.original_user_id}` == `user_${req.employee_id}`);
        return {
          ...req,
          employee: employee ? `${employee.employee_code} - ${employee.name}` : `Employee ${req.employee_id}`,
          date: req.punch_date,
          type: req.issue_type
        };
      });
      setRegularizationRequests(requests);
    } catch (err) {
      console.error('Failed to fetch regularization requests:', err);
    }
  };

  const handleRegularizationSubmit = async () => {
    if (!regularizationForm.employee_id || !regularizationForm.date || !regularizationForm.reason.trim()) {
      alert('Please fill all fields');
      return;
    }
    
    try {
      const actualEmployeeId = regularizationForm.employee_id.startsWith('user_') 
        ? parseInt(regularizationForm.employee_id.replace('user_', '')) 
        : parseInt(regularizationForm.employee_id);
      
      await api.post('/api/attendance/regularizations/', {
        employee_id: actualEmployeeId,
        punch_date: regularizationForm.date,
        issue_type: regularizationForm.issue_type,
        reason: regularizationForm.reason
      });
      
      setRegularizationForm({ employee_id: "", date: "", issue_type: "Missed IN", reason: "" });
      fetchRegularizationRequests();
      alert('Regularization request submitted successfully!');
    } catch (err) {
      console.error('Failed to submit regularization:', err);
      alert('Failed to submit request. Please try again.');
    }
  };

  const handleApprove = async (id) => {
    try {
      await api.patch(`/api/attendance/regularizations/${id}/approve`);
      fetchRegularizationRequests();
      alert('Request approved successfully!');
    } catch (err) {
      console.error('Failed to approve:', err);
      alert('Failed to approve request.');
    }
  };

  const handleReject = async (id) => {
    try {
      await api.patch(`/api/attendance/regularizations/${id}/reject`);
      fetchRegularizationRequests();
      alert('Request rejected!');
    } catch (err) {
      console.error('Failed to reject:', err);
      alert('Failed to reject request.');
    }
  };

  const fetchOdApplications = async () => {
    try {
      const res = await api.get('/api/attendance/od-applications/');
      const applications = res.data.map(app => {
        const employee = employees.find(e => e.id == app.employee_id || `user_${e.original_user_id}` == `user_${app.employee_id}`);
        return {
          ...app,
          employee: employee ? `${employee.employee_code} - ${employee.name}` : `Employee ${app.employee_id}`
        };
      });
      setOdApplications(applications);
    } catch (err) {
      console.error('Failed to fetch OD applications:', err);
    }
  };

  const handleOdSubmit = async () => {
    if (!odForm.employee_id || !odForm.od_date || !odForm.purpose.trim()) {
      alert('Please fill all required fields');
      return;
    }
    
    try {
      const actualEmployeeId = odForm.employee_id.startsWith('user_') 
        ? parseInt(odForm.employee_id.replace('user_', '')) 
        : parseInt(odForm.employee_id);
      
      await api.post('/api/attendance/od-applications/', {
        employee_id: actualEmployeeId,
        od_date: odForm.od_date,
        purpose: odForm.purpose,
        from_time: odForm.from_time,
        to_time: odForm.to_time,
        location: odForm.location
      });
      
      setOdForm({ employee_id: "", od_date: "", purpose: "", from_time: "", to_time: "", location: "" });
      fetchOdApplications();
      alert('OD application submitted successfully!');
    } catch (err) {
      console.error('Failed to submit OD application:', err);
      alert('Failed to submit application. Please try again.');
    }
  };

  const handleOdApprove = async (id) => {
    try {
      await api.patch(`/api/attendance/od-applications/${id}/approve`);
      fetchOdApplications();
      alert('OD application approved successfully!');
    } catch (err) {
      console.error('Failed to approve OD application:', err);
      alert('Failed to approve application.');
    }
  };

  const handleOdReject = async (id) => {
    try {
      await api.patch(`/api/attendance/od-applications/${id}/reject`);
      fetchOdApplications();
      alert('OD application rejected!');
    } catch (err) {
      console.error('Failed to reject OD application:', err);
      alert('Failed to reject application.');
    }
  };

  useEffect(() => {
    checkTodayStatus();
  }, [logs, selectedEmployee]);

  useEffect(() => {
    if (employees.length > 0) {
      fetchRegularizationRequests();
      fetchOdApplications();
    }
  }, [employees]);

  const exportToExcel = () => {
    if (reportData.length === 0) {
      alert('Please generate a report first');
      return;
    }

    const excelData = reportData.map(log => {
      const employee = employees.find(emp => emp.id == log.employee_id);
      return {
        'Employee Code': employee?.employee_code || log.employee_id,
        'Employee Name': employee?.name || '',
        'Date': log.date,
        'In Time': log.in_time || '-',
        'Out Time': log.out_time || '-',
        'Location': log.location || '-',
        'Status': log.status,
        'Source': log.source
      };
    });

    const ws = XLSX.utils.json_to_sheet(excelData);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Attendance Report');
    XLSX.writeFile(wb, `attendance-report-${new Date().toISOString().split('T')[0]}.xlsx`);
  };

  const tabs = [
    { id: 'logs', label: 'Punch Logs' },
    { id: 'regularization', label: 'Regularization' },
    { id: 'od', label: 'OD Applications' },
    { id: 'reports', label: 'Reports' },
  ];

  return (
    <div className="flex bg-gradient-to-br from-slate-50 to-blue-50 min-h-screen">
      <Sidebar />
      
      <div className="flex-1 flex flex-col">
        <Header />
        
        <div className="p-6 pt-24">
          <div className="text-sm text-muted mb-3">Attendance · Logs & Regularization</div>
          
          <div className="mb-6">
            <div className="bg-white rounded-2xl border shadow-sm p-6">
              <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-blue-100 rounded-xl">
                    <svg className="w-6 h-6 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd"></path>
                    </svg>
                  </div>
                  <div>
                    <h1 className="text-2xl font-bold text-primary">Attendance Logs & Regularization</h1>
                    <p className=" mt-1" style={{color: 'var(--text-secondary, #374151)'}}>Advanced attendance tracking with Web & Mobile GPS, smart regularization, and comprehensive reporting</p>
                  </div>
                </div>
                
                <div className="flex items-center gap-4">
                  <div className="text-center">
                    <div className="text-2xl font-bold text-blue-600">{logs.length}</div>
                    <div className="text-sm text-muted">Total Records</div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* TAB NAVIGATION */}
          <div className="bg-white rounded-2xl shadow-xl border border-gray-100 mb-8 overflow-hidden">
            <div className="flex border-b bg-gradient-to-r from-gray-50 to-blue-50">
              {tabs.map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`px-8 py-5 text-sm font-semibold border-b-3 transition-all duration-300 ${
                    activeTab === tab.id
                      ? 'border-blue-500 text-blue-600 bg-white shadow-lg transform -translate-y-1'
                      : 'border-transparent text-muted hover:text-secondary hover:bg-white/50'
                  }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>
            
            {activeTab === 'logs' && (
              <div className="p-4">
                {/* Step 1: Employee Selection */}
                <div className="mb-6 p-6 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl border border-blue-200 shadow-lg">
                  <h3 className="text-lg font-bold mb-6 text-blue-800 flex items-center gap-2">
                    <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    </svg>
                    Step 1: Select Employee
                  </h3>
                  <div className="grid grid-cols-1 gap-4">
                    <div>
                      <label className="block text-sm font-semibold text-secondary mb-2">Employee</label>
                      <select
                        value={selectedEmployee}
                        onChange={(e) => {
                          setSelectedEmployee(e.target.value);
                          setAttendanceMode(""); // Reset mode when employee changes
                          setSelectedLocation(officeLocations.length > 0 ? officeLocations[0].id : ""); // Reset location
                          setShowAddLocation(false);
                          setNewLocationName('');
                        }}
                        className="w-full px-4 py-3 border-2  rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white shadow-sm"
                      >
                        <option value="">Choose Employee</option>
                        {employees.map((employee) => (
                          <option key={employee.id} value={employee.id}>
                            {employee.employee_code} - {employee.name}
                          </option>
                        ))}
                      </select>
                    </div>
                    
                    {attendanceMode === 'WEB' && (
                      <div className="mt-4">
                        <label className="block text-sm font-semibold text-secondary mb-2">Office Location</label>
                        {!showAddLocation ? (
                          <select
                            value={selectedLocation}
                            onChange={(e) => {
                              if (e.target.value === 'add_new') {
                                setShowAddLocation(true);
                              } else {
                                setSelectedLocation(e.target.value);
                              }
                            }}
                            className="w-full px-4 py-3 border-2  rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white shadow-sm"
                          >
                            {officeLocations.map((location) => (
                              <option key={location.id} value={location.id}>
                                {location.location_name || location.name}
                              </option>
                            ))}
                            <option value="add_new">+ Add New Location</option>
                          </select>
                        ) : (
                          <div className="flex gap-3">
                            <input
                              type="text"
                              value={newLocationName}
                              onChange={(e) => setNewLocationName(e.target.value)}
                              placeholder="Enter location name"
                              className="flex-1 px-4 py-3 border-2  rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white shadow-sm"
                            />
                            <button
                              onClick={async () => {
                                if (newLocationName.trim()) {
                                  try {
                                    const res = await api.post('/api/attendance/locations/', {
                                      location_name: newLocationName.trim()
                                    });
                                    const newLocation = res.data;
                                    setOfficeLocations([...officeLocations, newLocation]);
                                    setSelectedLocation(newLocation.id);
                                    setNewLocationName('');
                                    setShowAddLocation(false);
                                  } catch (err) {
                                    alert('Failed to add location. Please try again.');
                                  }
                                }
                              }}
                              className="px-4 py-3 bg-gradient-to-r from-green-500 to-green-600 text-white rounded-xl hover:from-green-600 hover:to-green-700 font-semibold shadow-lg transition-all duration-300"
                            >
                              Add
                            </button>
                            <button
                              onClick={() => {
                                setShowAddLocation(false);
                                setNewLocationName('');
                              }}
                              className="px-4 py-3 bg-gradient-to-r from-gray-400 to-gray-500 text-white rounded-xl hover:from-gray-500 hover:to-gray-600 font-semibold shadow-lg transition-all duration-300"
                            >
                              Cancel
                            </button>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                </div>

                {/* Step 2: Attendance Mode Selection - Only show if not checked in */}
                {selectedEmployee && !attendanceMode && currentStatus === 'not_checked_in' && (
                  <div className="mb-4 p-4 rounded-lg border bg-blue-50">
                    <h3 className="text-md font-semibold mb-4">Step 2: Choose Attendance Mode</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <button
                        onClick={() => setAttendanceMode('WEB')}
                        className="p-4 border-2 border-blue-200 rounded-lg hover:border-blue-400 hover:bg-blue-100 transition text-left"
                      >
                        <div className="flex items-center gap-3 mb-2">
                          <svg className="w-6 h-6 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M3 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clipRule="evenodd"></path>
                          </svg>
                          <h4 className="font-semibold text-blue-800">Web Check-In</h4>
                        </div>
                        <p className="text-sm text-secondary">Check in from office computer</p>
                        <p className="text-xs text-muted mt-1">• Select office location</p>
                        <p className="text-xs text-muted">• No GPS required</p>
                      </button>
                      
                      <button
                        onClick={async () => {
                          if (!navigator.geolocation) {
                            alert('Geolocation is not supported by this browser.');
                            return;
                          }
                          
                          setAttendanceMode('MOBILE');
                          setLoading(true);
                          
                          // Request GPS permission immediately on user click
                          navigator.geolocation.getCurrentPosition(
                            (position) => {
                              setGpsPermissionGranted(true);
                              setLoading(false);
                              alert('GPS permission granted! You can now check in.');
                            },
                            (error) => {
                              console.error('GPS error:', error);
                              setGpsPermissionGranted(false);
                              setAttendanceMode("");
                              setLoading(false);
                              
                              let errorMsg = 'GPS permission denied. ';
                              if (error.code === 1) {
                                errorMsg += 'Please allow location access in your browser settings and try again.';
                              } else if (error.code === 2) {
                                errorMsg += 'Location unavailable. Please check your GPS settings.';
                              } else {
                                errorMsg += 'Location request timed out. Please try again.';
                              }
                              alert(errorMsg);
                            },
                            { 
                              timeout: 15000, 
                              enableHighAccuracy: true,
                              maximumAge: 0
                            }
                          );
                        }}
                        className="p-4 border-2 border-green-200 rounded-lg hover:border-green-400 hover:bg-green-100 transition text-left"
                      >
                        <div className="flex items-center gap-3 mb-2">
                          <svg className="w-6 h-6 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd"></path>
                          </svg>
                          <h4 className="font-semibold text-green-800">Mobile GPS Check-In</h4>
                        </div>
                        <p className="text-sm text-secondary">Check in from mobile device</p>
                        <p className="text-xs text-muted mt-1">• GPS location tracking</p>
                        <p className="text-xs text-muted">• Location permission required</p>
                      </button>
                    </div>
                  </div>
                )}

                {/* Status Display */}
                {selectedEmployee && attendanceMode && (
                  <div className="mb-4 p-4 rounded-lg border-2 border-dashed ">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className={`w-3 h-3 rounded-full ${
                          currentStatus === 'checked_in' ? 'bg-green-500 animate-pulse' :
                          currentStatus === 'checked_out' ? 'bg-blue-500' :
                          'bg-gray-400'
                        }`}></div>
                        <div>
                          <div className="font-semibold text-primary">
                            {currentStatus === 'checked_in' ? 'Currently Checked In' :
                             currentStatus === 'checked_out' ? 'Checked Out for Today' :
                             'Ready to Check In'}
                          </div>
                          <div className="text-sm text-muted">
                            {new Date().toLocaleDateString()} • {new Date().toLocaleTimeString()}
                          </div>
                        </div>
                      </div>
                      <div className="text-right">
                        <div className="text-sm text-muted">Employee</div>
                        <div className="font-semibold">
                          {employees.find(e => e.id == selectedEmployee)?.name}
                          {(() => {
                            const employee = employees.find(e => e.id == selectedEmployee);
                            return employee?.employee_code ? (
                              <span className="ml-2 px-2 py-1 bg-blue-100 text-blue-800 text-xs rounded-full">
                                {employee.employee_code}
                              </span>
                            ) : null;
                          })()}
                        </div>
                      </div>
                    </div>
                  </div>
                )}
                
                {/* Action Buttons */}
                {selectedEmployee && (
                  <div>
                    {currentStatus === 'not_checked_in' && attendanceMode && (
                      <div className="text-center mb-4">
                        <div className="inline-block p-4 bg-content rounded-lg border">
                          <p className="text-sm text-secondary mb-3">
                            Ready to check in using <span className="font-semibold">{attendanceMode}</span> mode
                            {attendanceMode === 'MOBILE' && gpsPermissionGranted && (
                              <span className="ml-2 text-green-600">✓ GPS Permission Granted</span>
                            )}
                          </p>
                          <button 
                            onClick={() => handlePunchIn(attendanceMode)}
                            disabled={loading}
                            className={`py-3 px-6 rounded-lg font-medium transition flex items-center justify-center gap-2 mx-auto ${
                              attendanceMode === 'WEB' 
                                ? 'bg-[#0A2540] text-white hover:bg-[#061829]'
                                : 'bg-green-600 text-white hover:bg-green-700'
                            }`}
                          >
                            <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                              {attendanceMode === 'WEB' ? (
                                <path fillRule="evenodd" d="M3 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clipRule="evenodd"></path>
                              ) : (
                                <path fillRule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd"></path>
                              )}
                            </svg>
                            {attendanceMode} Check-In
                          </button>
                          <button 
                            onClick={() => {
                              setAttendanceMode("");
                              setGpsPermissionGranted(false);
                            }}
                            className="mt-2 text-sm text-blue-600 hover:text-blue-800"
                          >
                            Change Mode
                          </button>
                        </div>
                      </div>
                    )}
                    
                    {/* Show check-out option directly when already checked in */}
                    {currentStatus === 'checked_in' && (
                      <div className="mb-4 p-4 rounded-lg border bg-orange-50">
                        <h3 className="text-md font-semibold mb-4">Step 2: Check Out</h3>
                        <div className="text-center">
                          <div className="inline-block p-4 bg-white rounded-lg border">
                            <p className="text-sm text-secondary mb-3">
                              You checked in via <span className="font-semibold">{checkInSource}</span>. 
                              Please use the same method to check out.
                            </p>
                            <button 
                              onClick={() => handlePunchOut(checkInSource)}
                              disabled={loading}
                              className={`py-3 px-6 rounded-lg font-medium transition flex items-center justify-center gap-2 mx-auto ${
                                checkInSource === 'WEB' 
                                  ? 'bg-red-600 text-white hover:bg-red-700'
                                  : 'bg-orange-600 text-white hover:bg-orange-700'
                              }`}
                            >
                              <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clipRule="evenodd"></path>
                              </svg>
                              {checkInSource} Check-Out
                            </button>
                          </div>
                        </div>
                      </div>
                    )}
                  </div>
                )}
                
                {loading && (
                  <div className="text-center py-2">
                    <div className="inline-flex items-center gap-2 text-blue-600">
                      <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="m4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      Processing...
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* CONTENT BASED ON ACTIVE TAB */}
          <div className="bg-white rounded-3xl shadow-2xl border border-gray-100 overflow-hidden">
            {activeTab === 'logs' && (
              <div className="overflow-x-auto">
                <div className="p-6 border-b bg-gradient-to-r from-gray-50 to-blue-50">
                  <h3 className="text-xl font-bold text-primary flex items-center gap-2">
                    <svg className="w-6 h-6 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd"></path>
                    </svg>
                    Punch Logs - {new Date().toLocaleDateString('en-US', { 
                      weekday: 'long', 
                      year: 'numeric', 
                      month: 'long', 
                      day: 'numeric' 
                    })}
                  </h3>
                </div>
                <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="w-full bg-white">
                  <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-gradient-to-r from-blue-50 to-indigo-50 border-b-2 border-blue-200">
                    <tr>
                      <th className="p-4 text-left text-sm font-bold text-secondary">Emp Code</th>
                      <th className="p-4 text-left text-sm font-bold text-secondary">Date</th>
                      <th className="p-4 text-left text-sm font-bold text-secondary">In</th>
                      <th className="p-4 text-left text-sm font-bold text-secondary">Out</th>
                      <th className="p-4 text-left text-sm font-bold text-secondary">Location</th>
                      <th className="p-4 text-left text-sm font-bold text-secondary">Status</th>
                      <th className="p-4 text-left text-sm font-bold text-secondary">Source</th>
                    </tr>
                  </thead>
                  <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                    {(() => {
                      const today = new Date().toISOString().split('T')[0];
                      const todayLogs = logs.filter(log => log.date === today);
                      
                      if (todayLogs.length === 0) {
                        return (
                          <tr>
                            <td colSpan="7" className="p-8 text-center text-muted">
                              No attendance records for today
                            </td>
                          </tr>
                        );
                      }
                      
                      return todayLogs.map((log) => (
                        <tr key={log.id} className="border-b hover:bg-content" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                          <td className="p-4 text-sm text-primary">
                            {(() => {
                              const employee = employees.find(emp => {
                                if (emp.source === 'user_management') {
                                  return emp.original_user_id == log.employee_id;
                                }
                                return emp.id == log.employee_id;
                              });
                              return employee?.employee_code || log.employee_id;
                            })()}
                          </td>
                          <td className="p-4 text-sm text-primary">{log.date}</td>
                          <td className="p-4 text-sm text-primary">{log.in_time || "-"}</td>
                          <td className="p-4 text-sm text-primary">{log.out_time || "-"}</td>
                          <td className="p-4 text-sm text-primary">{log.location || "-"}</td>
                          <td className="p-4 text-sm">
                            <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                              log.status === 'Present' ? 'bg-green-100 text-green-800' :
                              log.status === 'Late' ? 'bg-yellow-100 text-yellow-800' :
                              'bg-red-100 text-red-800'
                            }`}>
                              {log.status}
                            </span>
                          </td>
                          <td className="p-4 text-sm text-primary">{log.source}</td>
                        </tr>
                      ));
                    })()}
                  </tbody>
                </table>
              </div>
            )}
            
            {activeTab === 'regularization' && (
              <div className="p-6">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  {/* Request Form */}
                  <div>
                    <h3 className="text-lg font-semibold mb-4">Submit Regularization Request</h3>
                    <div className="space-y-4">
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-1">Employee</label>
                        <select 
                          value={regularizationForm.employee_id}
                          onChange={(e) => setRegularizationForm({...regularizationForm, employee_id: e.target.value})}
                          className="w-full border-dark rounded-lg px-3 py-2"
                        >
                          <option value="">Choose Employee</option>
                          {employees.map((employee) => (
                            <option key={employee.id} value={employee.id}>
                              {employee.employee_code} - {employee.name}
                            </option>
                          ))}
                        </select>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-1">Date</label>
                        <input 
                          type="date" 
                          value={regularizationForm.date}
                          onChange={(e) => setRegularizationForm({...regularizationForm, date: e.target.value})}
                          className="w-full border-dark rounded-lg px-3 py-2" 
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-1">Issue Type</label>
                        <select 
                          value={regularizationForm.issue_type}
                          onChange={(e) => setRegularizationForm({...regularizationForm, issue_type: e.target.value})}
                          className="w-full border-dark rounded-lg px-3 py-2"
                        >
                          <option>Missed IN</option>
                          <option>Missed OUT</option>
                          <option>Wrong Punch</option>
                        </select>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-1">Reason</label>
                        <textarea 
                          value={regularizationForm.reason}
                          onChange={(e) => setRegularizationForm({...regularizationForm, reason: e.target.value})}
                          className="w-full border-dark rounded-lg px-3 py-2" 
                          rows="3" 
                          placeholder="Explain the reason"
                        ></textarea>
                      </div>
                      <button 
                        onClick={handleRegularizationSubmit}
                        className="bg-[#0A2540] text-white py-2 px-4 rounded-lg hover:bg-[#061829] transition"
                      >
                        Submit Request
                      </button>
                    </div>
                  </div>
                  
                  {/* Requests Table */}
                  <div>
                    <h3 className="text-lg font-semibold mb-4">Regularization Requests</h3>
                    <div className="overflow-x-auto">
                      <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="w-full text-sm border rounded-lg">
                        <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-content">
                          <tr>
                            <th className="p-3 text-left">Employee</th>
                            <th className="p-3 text-left">Date</th>
                            <th className="p-3 text-left">Type</th>
                            <th className="p-3 text-left">Status</th>
                            <th className="p-3 text-left">Actions</th>
                          </tr>
                        </thead>
                        <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                          {regularizationRequests.length === 0 ? (
                            <tr className="border-t" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                              <td colSpan="5" className="p-4 text-center text-muted">
                                No regularization requests yet
                              </td>
                            </tr>
                          ) : (
                            regularizationRequests.map((request) => (
                              <tr key={request.id} className="border-t" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                                <td className="p-3">{request.employee}</td>
                                <td className="p-3">{request.date}</td>
                                <td className="p-3">{request.type}</td>
                                <td className="p-3">
                                  <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                                    request.status === 'Pending' ? 'bg-yellow-100 text-yellow-800' :
                                    request.status === 'Approved' ? 'bg-green-100 text-green-800' :
                                    'bg-red-100 text-red-800'
                                  }`}>
                                    {request.status}
                                  </span>
                                </td>
                                <td className="p-3">
                                  {request.status === 'Pending' && (
                                    <div className="flex gap-2">
                                      <button 
                                        onClick={() => handleApprove(request.id)}
                                        className="px-3 py-1 bg-green-600 text-white text-xs rounded hover:bg-green-700"
                                      >
                                        Approve
                                      </button>
                                      <button 
                                        onClick={() => handleReject(request.id)}
                                        className="px-3 py-1 bg-red-600 text-white text-xs rounded hover:bg-red-700"
                                      >
                                        Reject
                                      </button>
                                    </div>
                                  )}
                                </td>
                              </tr>
                            ))
                          )}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            )}
            
            {activeTab === 'od' && (
              <div className="p-6">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  <div>
                    <h3 className="text-lg font-semibold mb-4">Submit OD Application</h3>
                    <div className="space-y-4">
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-1">Employee *</label>
                        <select 
                          value={odForm.employee_id}
                          onChange={(e) => setOdForm({...odForm, employee_id: e.target.value})}
                          className="w-full border-dark rounded-lg px-3 py-2"
                        >
                          <option value="">Choose Employee</option>
                          {employees.map((employee) => (
                            <option key={employee.id} value={employee.id}>
                              {employee.employee_code} - {employee.name}
                            </option>
                          ))}
                        </select>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-1">OD Date *</label>
                        <input 
                          type="date" 
                          value={odForm.od_date}
                          onChange={(e) => setOdForm({...odForm, od_date: e.target.value})}
                          className="w-full border-dark rounded-lg px-3 py-2" 
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-1">Purpose *</label>
                        <textarea 
                          value={odForm.purpose}
                          onChange={(e) => setOdForm({...odForm, purpose: e.target.value})}
                          className="w-full border-dark rounded-lg px-3 py-2" 
                          rows="3" 
                          placeholder="Purpose of OD"
                        ></textarea>
                      </div>
                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <label className="block text-sm font-medium text-secondary mb-1">From Time</label>
                          <input 
                            type="time" 
                            value={odForm.from_time}
                            onChange={(e) => setOdForm({...odForm, from_time: e.target.value})}
                            className="w-full border-dark rounded-lg px-3 py-2" 
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-secondary mb-1">To Time</label>
                          <input 
                            type="time" 
                            value={odForm.to_time}
                            onChange={(e) => setOdForm({...odForm, to_time: e.target.value})}
                            className="w-full border-dark rounded-lg px-3 py-2" 
                          />
                        </div>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-1">Location</label>
                        <input 
                          type="text" 
                          value={odForm.location}
                          onChange={(e) => setOdForm({...odForm, location: e.target.value})}
                          className="w-full border-dark rounded-lg px-3 py-2" 
                          placeholder="OD Location"
                        />
                      </div>
                      <button 
                        onClick={handleOdSubmit}
                        className="bg-[#0A2540] text-white py-2 px-4 rounded-lg hover:bg-[#061829] transition"
                      >
                        Submit Application
                      </button>
                    </div>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-semibold mb-4">OD Applications</h3>
                    <div className="overflow-x-auto">
                      <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="w-full text-sm border rounded-lg">
                        <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-content">
                          <tr>
                            <th className="p-3 text-left">Employee</th>
                            <th className="p-3 text-left">Date</th>
                            <th className="p-3 text-left">Purpose</th>
                            <th className="p-3 text-left">Status</th>
                            <th className="p-3 text-left">Actions</th>
                          </tr>
                        </thead>
                        <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                          {odApplications.length === 0 ? (
                            <tr className="border-t" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                              <td colSpan="5" className="p-4 text-center text-muted">
                                No OD applications yet
                              </td>
                            </tr>
                          ) : (
                            odApplications.map((application) => (
                              <tr key={application.id} className="border-t" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                                <td className="p-3">{application.employee}</td>
                                <td className="p-3">{application.od_date}</td>
                                <td className="p-3" title={application.purpose}>
                                  {application.purpose.length > 30 ? 
                                    `${application.purpose.substring(0, 30)}...` : 
                                    application.purpose
                                  }
                                </td>
                                <td className="p-3">
                                  <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                                    application.status === 'pending' ? 'bg-yellow-100 text-yellow-800' :
                                    application.status === 'approved' ? 'bg-green-100 text-green-800' :
                                    'bg-red-100 text-red-800'
                                  }`}>
                                    {application.status}
                                  </span>
                                </td>
                                <td className="p-3">
                                  {application.status === 'pending' && (
                                    <div className="flex gap-2">
                                      <button 
                                        onClick={() => handleOdApprove(application.id)}
                                        className="px-3 py-1 bg-green-600 text-white text-xs rounded hover:bg-green-700"
                                      >
                                        ✓
                                      </button>
                                      <button 
                                        onClick={() => handleOdReject(application.id)}
                                        className="px-3 py-1 bg-red-600 text-white text-xs rounded hover:bg-red-700"
                                      >
                                        ✖
                                      </button>
                                    </div>
                                  )}
                                </td>
                              </tr>
                            ))
                          )}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            )}
            
            {activeTab === 'reports' && (
              <div className="p-6">
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                  {/* Report Filters */}
                  <div className="lg:col-span-1">
                    <h3 className="text-lg font-semibold mb-4">Generate Reports</h3>
                    <div className="space-y-4">
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-1">Report Type</label>
                        <select 
                          value={reportFilters.reportType}
                          onChange={(e) => setReportFilters({...reportFilters, reportType: e.target.value})}
                          className="w-full border-dark rounded-lg px-3 py-2"
                        >
                          <option value="daily">Daily Report</option>
                          <option value="monthly">Monthly Summary</option>
                          <option value="employee">Employee Wise</option>
                        </select>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-1">From Date</label>
                        <input 
                          type="date" 
                          value={reportFilters.fromDate}
                          onChange={(e) => setReportFilters({...reportFilters, fromDate: e.target.value})}
                          className="w-full border-dark rounded-lg px-3 py-2" 
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-1">To Date</label>
                        <input 
                          type="date" 
                          value={reportFilters.toDate}
                          onChange={(e) => setReportFilters({...reportFilters, toDate: e.target.value})}
                          className="w-full border-dark rounded-lg px-3 py-2" 
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-secondary mb-1">Employee</label>
                        <select 
                          value={reportFilters.employeeId}
                          onChange={(e) => setReportFilters({...reportFilters, employeeId: e.target.value})}
                          className="w-full border-dark rounded-lg px-3 py-2"
                        >
                          <option value="">All Employees</option>
                          {employees.map((employee) => (
                            <option key={employee.id} value={employee.id}>
                              {employee.employee_code} - {employee.name}
                            </option>
                          ))}
                        </select>
                      </div>
                      <button 
                        onClick={() => {
                          const filtered = logs.filter(log => {
                            const logDate = log.date;
                            const matchesDate = logDate >= reportFilters.fromDate && logDate <= reportFilters.toDate;
                            const matchesEmployee = !reportFilters.employeeId || log.employee_id == reportFilters.employeeId;
                            return matchesDate && matchesEmployee;
                          });
                          setReportData(filtered);
                        }}
                        className="w-full bg-[#0A2540] text-white py-2 px-4 rounded-lg hover:bg-[#061829] transition"
                      >
                        Generate Report
                      </button>
                    </div>
                  </div>
                  
                  {/* Report Results */}
                  <div className="lg:col-span-2">
                    <h3 className="text-lg font-semibold mb-4">Report Results</h3>
                    <div className="bg-content rounded-lg p-6">
                      {reportData.length > 0 && (
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                          <div className="text-center">
                            <div className="text-2xl font-bold text-blue-600">{reportData.length}</div>
                            <div className="text-sm text-secondary">Total Records</div>
                          </div>
                          <div className="text-center">
                            <div className="text-2xl font-bold text-green-600">
                              {reportData.filter(r => r.status === 'Present').length}
                            </div>
                            <div className="text-sm text-secondary">Present</div>
                          </div>
                          <div className="text-center">
                            <div className="text-2xl font-bold text-yellow-600">
                              {reportData.filter(r => r.status === 'Late').length}
                            </div>
                            <div className="text-sm text-secondary">Late</div>
                          </div>
                          <div className="text-center">
                            <div className="text-2xl font-bold text-red-600">
                              {reportData.filter(r => r.status === 'Absent').length}
                            </div>
                            <div className="text-sm text-secondary">Absent</div>
                          </div>
                        </div>
                      )}
                      
                      <div className="overflow-x-auto">
                        <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="w-full text-sm border rounded-lg bg-white">
                          <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-gray-100">
                            <tr>
                              <th className="p-3 text-left">Emp Code</th>
                              <th className="p-3 text-left">Date</th>
                              <th className="p-3 text-left">In Time</th>
                              <th className="p-3 text-left">Out Time</th>
                              <th className="p-3 text-left">Location</th>
                              <th className="p-3 text-left">Status</th>
                            </tr>
                          </thead>
                          <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                            {reportData.length === 0 ? (
                              <tr>
                                <td colSpan="6" className="p-8 text-center text-muted">
                                  Click "Generate Report" to view attendance data
                                </td>
                              </tr>
                            ) : (
                              reportData.map((log) => (
                                <tr key={log.id} className="border-t" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                                  <td className="p-3">
                                    {(() => {
                                      const employee = employees.find(emp => {
                                        if (emp.source === 'user_management') {
                                          return emp.original_user_id == log.employee_id;
                                        }
                                        return emp.id == log.employee_id;
                                      });
                                      return employee?.employee_code || log.employee_id;
                                    })()}
                                  </td>
                                  <td className="p-3">{log.date}</td>
                                  <td className="p-3">{log.in_time || '-'}</td>
                                  <td className="p-3">{log.out_time || '-'}</td>
                                  <td className="p-3">{log.location || '-'}</td>
                                  <td className="p-3">
                                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                                      log.status === 'Present' ? 'bg-green-100 text-green-800' :
                                      log.status === 'Late' ? 'bg-yellow-100 text-yellow-800' :
                                      'bg-red-100 text-red-800'
                                    }`}>
                                      {log.status}
                                    </span>
                                  </td>
                                </tr>
                              ))
                            )}
                          </tbody>
                        </table>
                      </div>
                      
                      <div className="mt-4">
                        <button 
                          onClick={exportToExcel}
                          disabled={reportData.length === 0}
                          className="bg-green-600 text-white py-2 px-4 rounded-lg hover:bg-green-700 transition text-sm disabled:bg-gray-400 disabled:cursor-not-allowed"
                        >
                          Export Excel
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
