import { useEffect, useState } from "react";
import { FiShield, FiClock, FiUser, FiCalendar, FiFileText, FiCheckCircle, FiXCircle } from 'react-icons/fi';
import api from "../../api";
import { isAdmin, hasPermission } from "../../utils/permissions";
import useToast from "../../utils/useToast";
import Toast from "../../components/Toast";

export default function AttendancePermission() {
  const [list, setList] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [employeesLoading, setEmployeesLoading] = useState(true);
  const { toast, showToast, hideToast } = useToast();
  const [colors, setColors] = useState({ primary: '#2862e9', secondary: '#474e71' });

  const [form, setForm] = useState({
    employee_id: localStorage.getItem("user_id"),
    date: "",
    request_type: "HALF_DAY_FIRST",
    from_time: "",
    to_time: "",
    reason: ""
  });

  const canView = isAdmin() || hasPermission("view_attendance_permission") || hasPermission("view_self");
  const canApply = isAdmin() || hasPermission("apply_attendance_permission");
  const canApprove = isAdmin() || hasPermission("approve_attendance_permission");
  const canSelectEmployee = isAdmin() || hasPermission("view_attendance_permission");

  const fetchEmployees = async () => {
    if (!canSelectEmployee) return;
    try {
      setEmployeesLoading(true);
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) {
        setEmployeesLoading(false);
        return;
      }
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        api.get(`/hospitals/users/${tenant}/list`).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.data?.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        source: 'onboarding'
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          employee_code: user.employee_code,
          source: 'user_management'
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Failed to fetch employees:', error);
      showToast('Failed to load employees', 'error');
    } finally {
      setEmployeesLoading(false);
    }
  };

  const fetchList = async () => {
    if (!canView) return;
    try {
      const res = await api.get("/api/attendance/permissions/");
      setList(res.data);
    } catch (error) {
      console.error('Failed to fetch attendance permissions:', error);
      showToast('Failed to load attendance permissions', 'error');
    }
  };

  useEffect(() => {
    fetchColors();
    fetchList();
    fetchEmployees();
  }, []);

  const fetchColors = async () => {
    try {
      const tenantCode = localStorage.getItem('tenantCode');
      if (tenantCode) {
        const response = await api.get(`/auth/branding/${tenantCode}`);
        if (response.data.primary_color && response.data.secondary_color) {
          const newColors = {
            primary: response.data.primary_color,
            secondary: response.data.secondary_color
          };
          setColors(newColors);
        }
      }
    } catch (error) {
      console.error('Error fetching colors:', error);
    }
  };

  const submit = async () => {
    if (!canApply) {
      showToast("You don't have permission to apply", "error");
      return;
    }
    
    if (!form.employee_id || !form.date || !form.reason.trim()) {
      showToast("Fill all fields", "error");
      return;
    }

    try {
      const actualEmployeeId = form.employee_id.toString().startsWith('user_') 
        ? parseInt(form.employee_id.replace('user_', '')) 
        : parseInt(form.employee_id);
      
      await api.post("/api/attendance/permissions/", {
        ...form,
        employee_id: actualEmployeeId
      });
      setForm({ ...form, date: "", reason: "", from_time: "", to_time: "" });
      fetchList();
      showToast("Request submitted");
    } catch (error) {
      console.error('Failed to submit request:', error);
      showToast('Failed to submit request', 'error');
    }
  };

  const updateStatus = async (id, action) => {
    try {
      await api.patch(`/api/attendance/permissions/${id}/${action}`);
      fetchList();
      showToast(`Request ${action}d`);
    } catch (error) {
      console.error(`Failed to ${action} request:`, error);
      showToast(`Failed to ${action} request`, 'error');
    }
  };

  return (
    <div className="p-4 sm:p-6 space-y-6 sm:space-y-8">

        {/* Key Performance Indicators matching Dashboard */}
        <div className="bg-white rounded-xl border-0 shadow-sm overflow-hidden">
          {/* Header */}
          <div className="p-5 border-b-0">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg" style={{
                backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
              }}>
                <FiShield className="h-5 w-5" style={{
                  color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                }} />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-gray-900">Permission Overview</h2>
                <p className="text-sm text-gray-600">Manage attendance permission requests and approvals</p>
              </div>
            </div>
          </div>
          
          <div className="p-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white rounded-xl p-5 border-0 shadow-sm hover:shadow-md transition-all duration-200">
          <div className="flex items-center justify-between">
            <div className="min-w-0 flex-1">
              <p className="text-gray-500 text-xs font-medium uppercase tracking-wider mb-2">Total Requests</p>
              <p className="text-2xl font-bold text-gray-900">{list.length}</p>
              <p className="text-gray-400 text-xs mt-1">All submissions</p>
            </div>
            <div className="p-3 rounded-lg" style={{
              backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
            }}>
              <FiFileText className="h-6 w-6" style={{
                color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
              }} />
            </div>
          </div>
        </div>

        <div className="bg-white rounded-xl p-5 border-0 shadow-sm hover:shadow-md transition-all duration-200">
          <div className="flex items-center justify-between">
            <div className="min-w-0 flex-1">
              <p className="text-gray-500 text-xs font-medium uppercase tracking-wider mb-2">Pending</p>
              <p className="text-2xl font-bold text-gray-900">{list.filter(r => r.status === 'Pending').length}</p>
              <p className="text-gray-400 text-xs mt-1">Awaiting approval</p>
            </div>
            <div className="p-3 rounded-lg" style={{
              backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
            }}>
              <FiClock className="h-6 w-6" style={{
                color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
              }} />
            </div>
          </div>
        </div>

        <div className="bg-white rounded-xl p-5 border-0 shadow-sm hover:shadow-md transition-all duration-200">
          <div className="flex items-center justify-between">
            <div className="min-w-0 flex-1">
              <p className="text-gray-500 text-xs font-medium uppercase tracking-wider mb-2">Approved</p>
              <p className="text-2xl font-bold text-gray-900">{list.filter(r => r.status === 'Approved').length}</p>
              <p className="text-gray-400 text-xs mt-1">Accepted requests</p>
            </div>
            <div className="p-3 rounded-lg" style={{
              backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
            }}>
              <FiCheckCircle className="h-6 w-6" style={{
                color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
              }} />
            </div>
          </div>
        </div>

        <div className="bg-white rounded-xl p-5 border-0 shadow-sm hover:shadow-md transition-all duration-200">
          <div className="flex items-center justify-between">
            <div className="min-w-0 flex-1">
              <p className="text-gray-500 text-xs font-medium uppercase tracking-wider mb-2">Rejected</p>
              <p className="text-2xl font-bold text-gray-900">{list.filter(r => r.status === 'Rejected').length}</p>
              <p className="text-gray-400 text-xs mt-1">Declined requests</p>
            </div>
            <div className="p-3 rounded-lg" style={{
              backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
            }}>
              <FiXCircle className="h-6 w-6" style={{
                color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
              }} />
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>

      {/* Apply Permission */}
      <div className="bg-white rounded-xl border-0 shadow-sm">
        <div className="p-5 border-b-0">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg" style={{
                backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
              }}>
                <FiShield className="h-5 w-5" style={{
                  color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                }} />
              </div>
              <h3 className="text-lg font-semibold text-gray-900">Apply for Permission</h3>
            </div>
          </div>
        </div>
        
        <div className="p-5 space-y-4">
          {/* Employee Selection */}
          {canSelectEmployee ? (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Employee</label>
              <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
                value={form.employee_id}
                onChange={e => setForm({ ...form, employee_id: e.target.value })}
                className="w-full px-4 py-2 border-0 rounded-lg focus:outline-none focus:ring-2 focus:border-transparent text-sm"
                style={{
                  focusRingColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                }}
                disabled={employeesLoading}
              >
                <option value="">{employeesLoading ? 'Loading employees...' : 'Select Employee'}</option>
                {employees.map(emp => (
                  <option key={emp.id} value={emp.id}>
                    {emp.employee_code || `EMP${emp.id}`} - {emp.name}
                  </option>
                ))}
              </select>
            </div>
          ) : (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Employee</label>
              <div className="w-full px-4 py-2 border-0 rounded-lg bg-gray-50 text-gray-700 text-sm">
                Employee: {employees.find(emp => emp.id == form.employee_id)?.name || 'Current User'}
              </div>
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Date</label>
            <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
              type="date"
              value={form.date}
              onChange={e => setForm({ ...form, date: e.target.value })}
              className="w-full px-4 py-2 border-0 rounded-lg focus:outline-none focus:ring-2 focus:border-transparent text-sm"
              style={{
                focusRingColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
              }}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Request Type</label>
            <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
              value={form.request_type}
              onChange={e => setForm({ ...form, request_type: e.target.value })}
              className="w-full px-4 py-2 border-0 rounded-lg focus:outline-none focus:ring-2 focus:border-transparent text-sm"
              style={{
                focusRingColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
              }}
            >
              <option value="HALF_DAY_FIRST">Half Day – First Half</option>
              <option value="HALF_DAY_SECOND">Half Day – Second Half</option>
              <option value="SHORT_LEAVE">Short Leave</option>
              <option value="LATE_COMING">Late Coming</option>
              <option value="EARLY_GOING">Early Going</option>
            </select>
          </div>

          {["SHORT_LEAVE", "LATE_COMING", "EARLY_GOING"].includes(form.request_type) && (
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">From Time</label>
                <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
                  type="time"
                  value={form.from_time}
                  onChange={e => setForm({ ...form, from_time: e.target.value })}
                  className="w-full px-4 py-2 border-0 rounded-lg focus:outline-none focus:ring-2 focus:border-transparent text-sm"
                  style={{
                    focusRingColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                  }}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">To Time</label>
                <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
                  type="time"
                  value={form.to_time}
                  onChange={e => setForm({ ...form, to_time: e.target.value })}
                  className="w-full px-4 py-2 border-0 rounded-lg focus:outline-none focus:ring-2 focus:border-transparent text-sm"
                  style={{
                    focusRingColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                  }}
                />
              </div>
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Reason</label>
            <textarea style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
              placeholder="Reason for permission request..."
              value={form.reason}
              onChange={e => setForm({ ...form, reason: e.target.value })}
              className="w-full px-4 py-2 border-0 rounded-lg focus:outline-none focus:ring-2 focus:border-transparent text-sm"
              style={{
                focusRingColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
              }}
              rows="3"
            />
          </div>

          <button 
            onClick={submit} 
            className="text-white px-6 py-3 rounded-lg transition-colors font-medium flex items-center gap-2"
            style={{
              backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
            }}
            onMouseEnter={(e) => {
              const hoverColor = getComputedStyle(document.documentElement).getPropertyValue('--secondary-color') || '#474e71';
              e.target.style.backgroundColor = hoverColor;
            }}
            onMouseLeave={(e) => {
              e.target.style.backgroundColor = getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5';
            }}
          >
            <FiShield className="w-4 h-4" />
            Submit Request
          </button>
        </div>
      </div>

      {/* Requests List */}
      <div className="bg-white rounded-2xl border-0 shadow-sm overflow-hidden">
        <div className="p-6 border-b-0" style={{
          background: `linear-gradient(135deg, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}05, ${getComputedStyle(document.documentElement).getPropertyValue('--secondary-color') || '#474e71'}05)`
        }}>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-xl" style={{
                backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
              }}>
                <FiFileText className="h-6 w-6" style={{
                  color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                }} />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-2">Permission Requests</h2>
                <p className="text-gray-600">Manage attendance permission requests and approvals</p>
              </div>
            </div>
          </div>
        </div>

        <div className="p-6">
          {list.length === 0 ? (
            <div className="text-center py-16">
              <div className="w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4" style={{
                backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}10`
              }}>
                <FiFileText className="h-8 w-8" style={{
                  color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                }} />
              </div>
              <h4 className="text-lg font-semibold text-gray-900 mb-2">No Permission Requests</h4>
              <p className="text-gray-600">Permission requests will appear here once submitted</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
              {list.map(r => {
                const employee = employees.find(emp => emp.id == r.employee_id);
                return (
                  <div key={r.id} className="bg-white rounded-lg p-4 shadow-sm hover:shadow-md transition-all duration-300">
                    <div className="flex items-start justify-between mb-3">
                      <div className="flex items-center gap-3">
                        <div className="p-2 rounded-lg" style={{
                          backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}15`
                        }}>
                          <FiUser className="h-4 w-4" style={{
                            color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                          }} />
                        </div>
                        <div>
                          <h3 className="text-sm font-bold text-gray-900">
                            {employee ? `${employee.employee_code || `EMP${employee.id}`} - ${employee.name}` : `Employee ID: ${r.employee_id}`}
                          </h3>
                          <p className="text-xs text-gray-600 mt-1">{r.date} • {r.request_type.replace("_", " ")}</p>
                        </div>
                      </div>
                      <div className={`w-2 h-2 rounded-full ${
                        r.status === 'Approved' ? 'bg-green-400' : 
                        r.status === 'Rejected' ? 'bg-red-400' : 'bg-yellow-400'
                      }`}></div>
                    </div>
                    
                    <div className="space-y-2">
                      <div className="bg-gray-50 rounded-lg p-2 border-0">
                        <div className="flex justify-between items-start mb-1">
                          <span className="text-xs text-gray-600">Reason</span>
                          <span className="text-xs font-medium text-gray-900 text-right break-words">
                            {r.reason}
                          </span>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-xs text-gray-600">Status</span>
                          <span className="text-xs font-medium text-gray-700">{r.status}</span>
                        </div>
                      </div>
                      
                      {canApprove && r.status === "Pending" && (
                        <div className="flex gap-2 pt-1">
                          <button
                            onClick={() => updateStatus(r.id, "approve")}
                            className="flex-1 text-white px-3 py-1.5 rounded-lg transition-colors font-medium flex items-center justify-center gap-1 text-xs"
                            style={{
                              backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                            }}
                            onMouseEnter={(e) => {
                              const hoverColor = getComputedStyle(document.documentElement).getPropertyValue('--secondary-color') || '#474e71';
                              e.target.style.backgroundColor = hoverColor;
                            }}
                            onMouseLeave={(e) => {
                              e.target.style.backgroundColor = getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5';
                            }}
                          >
                            <FiCheckCircle className="w-3 h-3" />
                            Approve
                          </button>
                          <button
                            onClick={() => updateStatus(r.id, "reject")}
                            className="flex-1 bg-white hover:bg-gray-100 text-gray-700 border-0 px-3 py-1.5 rounded-lg font-medium flex items-center justify-center gap-1 text-xs"
                          >
                            <FiXCircle className="w-3 h-3" />
                            Reject
                          </button>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}
