import { useEffect, useState } from "react";
import api from "../../api";
import { isAdmin, hasPermission } from "../../utils/permissions";
import useToast from "../../utils/useToast";
import Toast from "../../components/Toast";

export default function AttendancePermission() {
  const [list, setList] = useState([]);
  const [employees, setEmployees] = useState([]);
  const { toast, showToast, hideToast } = useToast();
  const [colors, setColors] = useState({ primary: '#2862e9', secondary: '#474e71' });

  const [form, setForm] = useState({
    employee_id: localStorage.getItem("user_id"),
    date: "",
    request_type: "HALF_DAY_FIRST",
    from_time: "",
    to_time: "",
    reason: ""
  });

  const canView = isAdmin() || hasPermission("view_attendance_permission") || hasPermission("view_self");
  const canApply = isAdmin() || hasPermission("apply_attendance_permission");
  const canApprove = isAdmin() || hasPermission("approve_attendance_permission");
  const canSelectEmployee = isAdmin() || hasPermission("view_attendance_permission");

  const fetchEmployees = async () => {
    if (!canSelectEmployee) return;
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        source: 'onboarding'
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          employee_code: user.employee_code,
          source: 'user_management'
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Failed to fetch employees:', error);
      showToast('Failed to load employees', 'error');
    }
  };

  const fetchList = async () => {
    if (!canView) return;
    try {
      const res = await api.get("/api/attendance/permissions/");
      setList(res.data);
    } catch (error) {
      console.error('Failed to fetch attendance permissions:', error);
      showToast('Failed to load attendance permissions', 'error');
    }
  };

  useEffect(() => {
    fetchColors();
    fetchList();
    fetchEmployees();
  }, []);

  const fetchColors = async () => {
    try {
      const tenantCode = localStorage.getItem('tenantCode');
      if (tenantCode) {
        const response = await api.get(`/auth/branding/${tenantCode}`);
        if (response.data.primary_color && response.data.secondary_color) {
          const newColors = {
            primary: response.data.primary_color,
            secondary: response.data.secondary_color
          };
          setColors(newColors);
        }
      }
    } catch (error) {
      console.error('Error fetching colors:', error);
    }
  };

  const submit = async () => {
    if (!canApply) {
      showToast("You don't have permission to apply", "error");
      return;
    }
    
    if (!form.employee_id || !form.date || !form.reason.trim()) {
      showToast("Fill all fields", "error");
      return;
    }

    try {
      const actualEmployeeId = form.employee_id.toString().startsWith('user_') 
        ? parseInt(form.employee_id.replace('user_', '')) 
        : parseInt(form.employee_id);
      
      await api.post("/api/attendance/permissions/", {
        ...form,
        employee_id: actualEmployeeId
      });
      setForm({ ...form, date: "", reason: "", from_time: "", to_time: "" });
      fetchList();
      showToast("Request submitted");
    } catch (error) {
      console.error('Failed to submit request:', error);
      showToast('Failed to submit request', 'error');
    }
  };

  const updateStatus = async (id, action) => {
    try {
      await api.patch(`/api/attendance/permissions/${id}/${action}`);
      fetchList();
      showToast(`Request ${action}d`);
    } catch (error) {
      console.error(`Failed to ${action} request:`, error);
      showToast(`Failed to ${action} request`, 'error');
    }
  };

  return (
    <div className="p-6 space-y-6">

      <h2 className="text-xl font-bold">Attendance Permission</h2>

      {/* APPLY */}
      <div className="border p-4 rounded-lg space-y-3">
        {/* Employee Selection */}
        {canSelectEmployee ? (
          <select
            value={form.employee_id}
            onChange={e => setForm({ ...form, employee_id: e.target.value })}
            className="border p-2 w-full rounded"
          >
            <option value="">Select Employee</option>
            {employees.map(emp => (
              <option key={emp.id} value={emp.id}>
                {emp.employee_code || `EMP${emp.id}`} - {emp.name}
              </option>
            ))}
          </select>
        ) : (
          <div className="border p-2 w-full rounded bg-gray-100">
            <span className="text-gray-600">
              Employee: {employees.find(emp => emp.id == form.employee_id)?.name || 'Current User'}
            </span>
          </div>
        )}

        <input
          type="date"
          value={form.date}
          onChange={e => setForm({ ...form, date: e.target.value })}
          className="border p-2 w-full rounded"
        />

        <select
          value={form.request_type}
          onChange={e => setForm({ ...form, request_type: e.target.value })}
          className="border p-2 w-full rounded"
        >
          <option value="HALF_DAY_FIRST">Half Day – First Half</option>
          <option value="HALF_DAY_SECOND">Half Day – Second Half</option>
          <option value="SHORT_LEAVE">Short Leave</option>
          <option value="LATE_COMING">Late Coming</option>
          <option value="EARLY_GOING">Early Going</option>
        </select>

        {["SHORT_LEAVE", "LATE_COMING", "EARLY_GOING"].includes(form.request_type) && (
          <div className="grid grid-cols-2 gap-3">
            <input
              type="time"
              value={form.from_time}
              onChange={e => setForm({ ...form, from_time: e.target.value })}
              className="border p-2 rounded"
            />
            <input
              type="time"
              value={form.to_time}
              onChange={e => setForm({ ...form, to_time: e.target.value })}
              className="border p-2 rounded"
            />
          </div>
        )}

        <textarea
          placeholder="Reason"
          value={form.reason}
          onChange={e => setForm({ ...form, reason: e.target.value })}
          className="border p-2 w-full rounded"
        />

        <button 
          onClick={submit} 
          className="text-white px-4 py-2 rounded transition-colors"
          style={{ backgroundColor: colors.primary }}
          onMouseEnter={(e) => e.target.style.backgroundColor = colors.secondary}
          onMouseLeave={(e) => e.target.style.backgroundColor = colors.primary}
        >
          Submit
        </button>
      </div>

      {/* LIST */}
      <div className="border rounded-lg p-4 space-y-3">
        {list.map(r => {
          const employee = employees.find(emp => emp.id == r.employee_id);
          return (
            <div key={r.id} className="border p-3 rounded">
              <div className="font-semibold">
                {employee ? `${employee.employee_code || `EMP${employee.id}`} - ${employee.name}` : `Employee ID: ${r.employee_id}`}
              </div>
              <div className="text-sm">
                {r.date} • {r.request_type.replace("_", " ")}
              </div>
              <div className="text-sm">{r.reason}</div>
              <div className="text-sm font-bold">{r.status}</div>

              {canApprove && r.status === "Pending" && (
                <div className="flex gap-2 mt-2">
                  <button
                    onClick={() => updateStatus(r.id, "approve")}
                    className="text-white px-3 py-1 rounded transition-colors"
                    style={{ backgroundColor: colors.primary }}
                    onMouseEnter={(e) => e.target.style.backgroundColor = colors.secondary}
                    onMouseLeave={(e) => e.target.style.backgroundColor = colors.primary}
                  >
                    Approve
                  </button>
                  <button
                    onClick={() => updateStatus(r.id, "reject")}
                    className="bg-white hover:bg-gray-100 text-black border border-black px-3 py-1 rounded"
                  >
                    Reject
                  </button>
                </div>
              )}
            </div>
          );
        })}
      </div>

      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}