import React, { useState, useEffect } from 'react';
import { FiPlus, FiEdit, FiCalendar, FiClock, FiFileText, FiCheckCircle } from 'react-icons/fi';
import api from '../../api';
import useToast from '../../utils/useToast';
import Toast from '../../components/Toast';
import { hasPermission, isAdmin } from '../../utils/permissions';

const DailyUpdates = () => {
  const { toast, showToast, hideToast } = useToast();
  const [updates, setUpdates] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [selectedEmployee, setSelectedEmployee] = useState('');
  const [loading, setLoading] = useState(true);
  const [employeesLoading, setEmployeesLoading] = useState(true);
  const [currentUserInfo, setCurrentUserInfo] = useState(null);
  const [showForm, setShowForm] = useState(false);
  const [editingUpdate, setEditingUpdate] = useState(null);
  const [formData, setFormData] = useState({
    employee_id: localStorage.getItem('user_id') || 1,
    date: new Date().toISOString().split('T')[0],
    work_done: '',
    blockers: '',
    plan_for_tomorrow: '',
    hours_spent: '',
    status: 'Draft'
  });

  // Permission checks
  const canView = isAdmin() || hasPermission('view_daily_updates');
  const canAdd = isAdmin() || hasPermission('add_daily_update');
  const canEdit = isAdmin() || hasPermission('edit_daily_update');
  const canDelete = isAdmin() || hasPermission('delete_daily_update');

  // Access denied screen
  if (!canView) {
    return (
      <div className="p-6">
        <div className="bg-white rounded-2xl border-0 p-8 max-w-md mx-auto text-center">
          <h3 className="text-lg font-medium text-gray-900 mb-2">Access Denied</h3>
          <p className="text-gray-600">You do not have permission to view daily updates.</p>
        </div>
      </div>
    );
  }

  useEffect(() => {
    fetchCurrentUserInfo();
    fetchEmployees();
    fetchMyUpdates();
  }, []);

  const fetchCurrentUserInfo = async () => {
    try {
      const response = await api.get('/api/daily-updates/current-user');
      setCurrentUserInfo(response.data);
    } catch (error) {
      console.error('Error fetching current user info:', error);
    }
  };

  const fetchEmployees = async () => {
    try {
      setEmployeesLoading(true);
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) {
        setEmployeesLoading(false);
        return;
      }
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        api.get(`/hospitals/users/${tenant}/list`).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.data?.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        source: 'onboarding'
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          employee_code: user.employee_code,
          source: 'user_management'
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
      showToast('Failed to load employees', 'error');
    } finally {
      setEmployeesLoading(false);
    }
  };

  const fetchMyUpdates = async () => {
    try {
      setLoading(true);
      let userId;
      
      if (isAdmin() && selectedEmployee) {
        const actualEmployeeId = selectedEmployee.startsWith('user_') 
          ? selectedEmployee.replace('user_', '') 
          : selectedEmployee;
        userId = actualEmployeeId;
      } else {
        userId = localStorage.getItem('user_id') || 1;
      }
      
      const response = await api.get(`/api/daily-updates/my-updates?employee_id=${userId}`);
      setUpdates(response.data);
    } catch (error) {
      console.error('Error fetching updates:', error);
      showToast('Failed to load daily updates', 'error');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!formData.work_done.trim()) {
      showToast('Work done is required', 'error');
      return;
    }

    try {
      if (editingUpdate) {
        await api.put(`/api/daily-updates/${editingUpdate.id}`, formData);
        showToast('Update saved successfully', 'success');
      } else {
        await api.post('/api/daily-updates/', formData);
        showToast('Update created successfully', 'success');
      }
      
      setShowForm(false);
      setEditingUpdate(null);
      resetForm();
      fetchMyUpdates();
    } catch (error) {
      console.error('Error saving update:', error);
      showToast(error.response?.data?.detail || 'Failed to save update', 'error');
    }
  };

  const resetForm = () => {
    setFormData({
      employee_id: localStorage.getItem('user_id') || 1,
      date: new Date().toISOString().split('T')[0],
      work_done: '',
      blockers: '',
      plan_for_tomorrow: '',
      hours_spent: '',
      status: 'Draft'
    });
  };

  const handleEdit = (update) => {
    setEditingUpdate(update);
    setFormData({
      employee_id: update.employee_id,
      date: update.date,
      work_done: update.work_done,
      blockers: update.blockers || '',
      plan_for_tomorrow: update.plan_for_tomorrow || '',
      hours_spent: update.hours_spent || '',
      status: update.status
    });
    setShowForm(true);
  };

  const handleNewUpdate = () => {
    setEditingUpdate(null);
    resetForm();
    setShowForm(true);
  };

  const canEditUpdate = (update) => {
    const today = new Date().toISOString().split('T')[0];
    return update.date === today;
  };

  if (loading) {
    return (
      <div className="p-6">
        <div className="animate-pulse space-y-4">
          {[...Array(3)].map((_, i) => (
            <div key={i} className="bg-white rounded-xl p-6 border border-black">
              <div className="h-4 bg-gray-200 rounded w-1/4 mb-4"></div>
              <div className="h-20 bg-gray-200 rounded mb-4"></div>
              <div className="h-4 bg-gray-200 rounded w-1/2"></div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  return (
    <>
      <div className="p-4 sm:p-6 space-y-6 sm:space-y-8">

        {/* Key Performance Indicators matching Dashboard */}
        <div className="rounded-xl shadow-sm overflow-hidden relative border" style={{
          background: `linear-gradient(135deg, white 0%, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}05 100%)`,
          borderColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
        }}>
          <div className="absolute top-0 right-0 w-32 h-32 rounded-full blur-3xl opacity-20" style={{
            backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5',
            transform: 'translate(30%, -30%)'
          }}></div>
          {/* Header */}
          <div className="p-5 border-b-0">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg" style={{
                backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
              }}>
                <FiEdit className="h-5 w-5" style={{
                  color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                }} />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-gray-900">Daily Updates Overview</h2>
                <p className="text-sm text-gray-600">Track your daily work progress and productivity</p>
              </div>
            </div>
          </div>
          
          <div className="p-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="rounded-xl p-5 shadow-sm hover:shadow-md transition-all duration-200 relative overflow-hidden border" style={{
            background: `linear-gradient(135deg, white 0%, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}03 100%)`,
            borderColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
          }}>
            <div className="absolute top-0 right-0 w-16 h-16 rounded-full blur-2xl opacity-10" style={{
              backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5',
              transform: 'translate(25%, -25%)'
            }}></div>
            <div className="flex items-center justify-between relative z-10">
              <div className="min-w-0 flex-1">
                <p className="text-gray-500 text-xs font-medium uppercase tracking-wider mb-2">Total Updates</p>
                <p className="text-2xl font-bold text-gray-900">{updates.length}</p>
                <p className="text-gray-400 text-xs mt-1">All entries</p>
              </div>
              <div className="p-3 rounded-lg" style={{
                backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
              }}>
                <FiEdit className="h-6 w-6" style={{
                  color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                }} />
              </div>
            </div>
          </div>

          <div className="rounded-xl p-5 shadow-sm hover:shadow-md transition-all duration-200 relative overflow-hidden border" style={{
            background: `linear-gradient(135deg, white 0%, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}03 100%)`,
            borderColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
          }}>
            <div className="absolute top-0 right-0 w-16 h-16 rounded-full blur-2xl opacity-10" style={{
              backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5',
              transform: 'translate(25%, -25%)'
            }}></div>
            <div className="flex items-center justify-between relative z-10">
              <div className="min-w-0 flex-1">
                <p className="text-gray-500 text-xs font-medium uppercase tracking-wider mb-2">Draft Updates</p>
                <p className="text-2xl font-bold text-gray-900">{updates.filter(u => u.status === 'Draft').length}</p>
                <p className="text-gray-400 text-xs mt-1">Pending submission</p>
              </div>
              <div className="p-3 rounded-lg" style={{
                backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
              }}>
                <FiFileText className="h-6 w-6" style={{
                  color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                }} />
              </div>
            </div>
          </div>

          <div className="rounded-xl p-5 shadow-sm hover:shadow-md transition-all duration-200 relative overflow-hidden border" style={{
            background: `linear-gradient(135deg, white 0%, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}03 100%)`,
            borderColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
          }}>
            <div className="absolute top-0 right-0 w-16 h-16 rounded-full blur-2xl opacity-10" style={{
              backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5',
              transform: 'translate(25%, -25%)'
            }}></div>
            <div className="flex items-center justify-between relative z-10">
              <div className="min-w-0 flex-1">
                <p className="text-gray-500 text-xs font-medium uppercase tracking-wider mb-2">Submitted</p>
                <p className="text-2xl font-bold text-gray-900">{updates.filter(u => u.status === 'Submitted').length}</p>
                <p className="text-gray-400 text-xs mt-1">Completed entries</p>
              </div>
              <div className="p-3 rounded-lg" style={{
                backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
              }}>
                <FiCheckCircle className="h-6 w-6" style={{
                  color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                }} />
              </div>
            </div>
          </div>

          <div className="rounded-xl p-5 shadow-sm hover:shadow-md transition-all duration-200 relative overflow-hidden border" style={{
            background: `linear-gradient(135deg, white 0%, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}03 100%)`,
            borderColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
          }}>
            <div className="absolute top-0 right-0 w-16 h-16 rounded-full blur-2xl opacity-10" style={{
              backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5',
              transform: 'translate(25%, -25%)'
            }}></div>
            <div className="flex items-center justify-between relative z-10">
              <div className="min-w-0 flex-1">
                <p className="text-gray-500 text-xs font-medium uppercase tracking-wider mb-2">This Week</p>
                <p className="text-2xl font-bold text-gray-900">{updates.filter(u => {
                  const updateDate = new Date(u.date);
                  const now = new Date();
                  const weekStart = new Date(now.setDate(now.getDate() - now.getDay()));
                  return updateDate >= weekStart;
                }).length}</p>
                <p className="text-gray-400 text-xs mt-1">Recent activity</p>
              </div>
              <div className="p-3 rounded-lg" style={{
                backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
              }}>
                <FiCalendar className="h-6 w-6" style={{
                  color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                }} />
              </div>
            </div>
          </div>
            </div>
          </div>
        </div>

        {/* Employee Selection */}
        <div className="rounded-xl shadow-sm relative overflow-hidden border" style={{
          background: `linear-gradient(135deg, white 0%, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}05 100%)`,
          borderColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
        }}>
          <div className="absolute top-0 right-0 w-32 h-32 rounded-full blur-3xl opacity-20" style={{
            backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5',
            transform: 'translate(30%, -30%)'
          }}></div>
          <div className="absolute bottom-0 left-0 w-24 h-24 rounded-full blur-2xl opacity-15" style={{
            backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--secondary-color') || '#474e71',
            transform: 'translate(-30%, 30%)'
          }}></div>
          <div className="p-5 border-b-0">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg" style={{
                  backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
                }}>
                  <FiEdit className="h-5 w-5" style={{
                    color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                  }} />
                </div>
                <h3 className="text-lg font-semibold text-gray-900">Employee Selection</h3>
              </div>
              {canAdd && (
                <button
                  onClick={handleNewUpdate}
                  className="text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2 text-sm font-medium"
                  style={{ backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5' }}
                  onMouseEnter={(e) => {
                    const hoverColor = getComputedStyle(document.documentElement).getPropertyValue('--secondary-color') || '#474e71';
                    e.target.style.backgroundColor = hoverColor;
                  }}
                  onMouseLeave={(e) => {
                    e.target.style.backgroundColor = getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5';
                  }}
                >
                  <FiPlus className="w-4 h-4" />
                  New Update
                </button>
              )}
            </div>
          </div>
          
          <div className="p-5">
          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 mb-2">Employee</label>
            {isAdmin() ? (
              <select
                value={selectedEmployee}
                onChange={(e) => {
                  setSelectedEmployee(e.target.value);
                  if (e.target.value) {
                    fetchMyUpdates();
                  }
                }}
                className="w-full px-3 py-2 bg-white rounded-lg focus:ring-1 focus:ring-gray-500 focus:border-gray-500 text-sm"
                style={{
                  backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                  border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                }}
                disabled={employeesLoading}
              >
                <option value="">{employeesLoading ? 'Loading employees...' : 'Select Employee'}</option>
                {employees.map(emp => (
                  <option key={emp.id} value={emp.id}>
                    {emp.employee_code || `EMP${emp.id}`} - {emp.name}
                  </option>
                ))}
              </select>
            ) : (
              <div className="w-full px-3 py-2 bg-gray-50 rounded-lg text-gray-700 text-sm border" style={{
                borderColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}20`
              }}>
                {employeesLoading ? (
                  <div className="flex items-center gap-2">
                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-gray-600"></div>
                    Loading...
                  </div>
                ) : (() => {
                  const currentUserId = localStorage.getItem('user_id');
                  const currentUserEmployee = employees.find(emp => {
                    if (emp.source === 'user_management') {
                      return emp.original_user_id == currentUserId;
                    }
                    return emp.id == currentUserId;
                  });
                  
                  if (currentUserEmployee) {
                    return `${currentUserEmployee.employee_code} - ${currentUserEmployee.name}`;
                  } else if (currentUserInfo) {
                    return `${currentUserInfo.employee_code} - ${currentUserInfo.name}`;
                  } else {
                    return `EMP${currentUserId} - Current User`;
                  }
                })()}
              </div>
            )}
          </div>
          </div>
        </div>

        {/* Form Modal */}
        {showForm && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto border" style={{
              scrollbarWidth: 'none',
              msOverflowStyle: 'none',
              scrollbarWidth: 'none',
              msOverflowStyle: 'none',
              scrollbarWidth: 'none',
              msOverflowStyle: 'none',
              borderColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}20`
            }}>
              <div className="p-6 border-b" style={{
                borderColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}20`
              }}>
                <h2 className="text-xl font-bold text-gray-900">
                  {editingUpdate ? 'Edit Daily Update' : 'New Daily Update'}
                </h2>
              </div>
              
              <form onSubmit={handleSubmit} className="p-6 space-y-4">
                {isAdmin() && (
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Employee</label>
                    <select
                      value={formData.employee_id}
                      onChange={(e) => setFormData({...formData, employee_id: e.target.value})}
                      className="w-full bg-white text-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      style={{
                        backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                        border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                      }}
                      required
                    >
                      <option value="">Select Employee</option>
                      {employees.map(emp => {
                        const actualId = emp.source === 'user_management' ? emp.original_user_id : emp.id;
                        return (
                          <option key={emp.id} value={actualId}>
                            {emp.employee_code || `EMP${emp.id}`} - {emp.name}
                          </option>
                        );
                      })}
                    </select>
                  </div>
                )}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Date</label>
                  <input
                    type="date"
                    value={formData.date}
                    onChange={(e) => setFormData({...formData, date: e.target.value})}
                    max={new Date().toISOString().split('T')[0]}
                    className="w-full bg-white text-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    style={{
                      backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                      border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                    }}
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Work Done Today *</label>
                  <textarea
                    value={formData.work_done}
                    onChange={(e) => setFormData({...formData, work_done: e.target.value})}
                    placeholder="Describe what you accomplished today..."
                    rows={4}
                    className="w-full bg-white text-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 resize-none"
                    style={{
                      backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                      border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                    }}
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Blockers (Optional)</label>
                  <textarea
                    value={formData.blockers}
                    onChange={(e) => setFormData({...formData, blockers: e.target.value})}
                    placeholder="Any challenges or blockers you faced..."
                    rows={3}
                    className="w-full bg-white text-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 resize-none"
                    style={{
                      backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                      border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                    }}
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Plan for Tomorrow (Optional)</label>
                  <textarea
                    value={formData.plan_for_tomorrow}
                    onChange={(e) => setFormData({...formData, plan_for_tomorrow: e.target.value})}
                    placeholder="What do you plan to work on tomorrow..."
                    rows={3}
                    className="w-full bg-white text-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 resize-none"
                    style={{
                      backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                      border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                    }}
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Hours Spent (Optional)</label>
                    <input
                      type="number"
                      step="0.5"
                      min="0"
                      max="24"
                      value={formData.hours_spent}
                      onChange={(e) => setFormData({...formData, hours_spent: e.target.value})}
                      placeholder="8.0"
                      className="w-full bg-white text-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      style={{
                        backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                        border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                      }}
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Status</label>
                    <select
                      value={formData.status}
                      onChange={(e) => setFormData({...formData, status: e.target.value})}
                      className="w-full bg-white text-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      style={{
                        backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                        border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                      }}
                    >
                      <option value="Draft">Draft</option>
                      <option value="Submitted">Submitted</option>
                    </select>
                  </div>
                </div>

                <div className="flex justify-end gap-3 pt-4">
                  <button
                    type="button"
                    onClick={() => setShowForm(false)}
                    className="px-6 py-2 bg-white text-black rounded-lg hover:bg-gray-100 transition-colors border"
                    style={{
                      borderColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                    }}
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="px-6 py-2 text-white rounded-lg hover:bg-gray-800 transition-colors"
                    style={{
                      backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5',
                      border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                    }}
                    onMouseEnter={(e) => {
                      e.target.style.backgroundColor = getComputedStyle(document.documentElement).getPropertyValue('--secondary-color') || '#474e71';
                    }}
                    onMouseLeave={(e) => {
                      e.target.style.backgroundColor = getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5';
                    }}
                  >
                    {editingUpdate ? 'Update' : 'Save'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {/* Updates List */}
        <div className="rounded-2xl shadow-sm overflow-hidden relative border" style={{
          background: `linear-gradient(135deg, white 0%, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}05 100%)`,
          borderColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
        }}>
          <div className="absolute top-0 right-0 w-32 h-32 rounded-full blur-3xl opacity-20" style={{
            backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5',
            transform: 'translate(30%, -30%)'
          }}></div>
          <div className="p-6 border-b-0" style={{
            background: `linear-gradient(135deg, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}05, ${getComputedStyle(document.documentElement).getPropertyValue('--secondary-color') || '#474e71'}05)`
          }}>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="p-3 rounded-xl" style={{
                  backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
                }}>
                  <FiEdit className="h-6 w-6" style={{
                    color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                  }} />
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-gray-900 mb-2">My Daily Updates</h2>
                  <p className="text-gray-600">Track and manage your daily work progress</p>
                </div>
              </div>
            </div>
          </div>
          
          <div className="p-6">
          
          {/* Desktop Table View */}
          <div className="hidden md:block overflow-x-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
            {updates.length === 0 ? (
              <div className="text-center py-12">
                <FiEdit className="mx-auto h-12 w-12 text-gray-400 mb-4" />
                <h3 className="text-lg font-medium text-gray-900 mb-2">No updates yet</h3>
                <p className="text-gray-600 mb-4">Start tracking your daily work progress</p>
                {canAdd && (
                  <button
                    onClick={handleNewUpdate}
                    className="bg-black text-white px-6 py-2 rounded-lg hover:bg-gray-800 transition-colors"
                  >
                    Create First Update
                  </button>
                )}
              </div>
            ) : (
              <table className="w-full border-collapse">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Employee</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Date</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Work Done</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Hours</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Status</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Actions</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {updates.map((update) => {
                    const employee = employees.find(emp => {
                      if (emp.source === 'user_management') {
                        return emp.original_user_id == update.employee_id;
                      }
                      return emp.id == update.employee_id;
                    });
                    
                    return (
                      <tr key={update.id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                          <div className="font-medium">{employee?.employee_code || `EMP${update.employee_id}`}</div>
                          <div className="text-gray-500">{employee?.name || `Employee ${update.employee_id}`}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                          <div className="flex items-center gap-2">
                            <FiCalendar size={16} className="text-gray-400" />
                            {new Date(update.date).toLocaleDateString()}
                          </div>
                        </td>
                        <td className="px-6 py-4 text-sm text-gray-900 max-w-xs">
                          <div className="truncate" title={update.work_done}>
                            {update.work_done}
                          </div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                          {update.hours_spent ? (
                            <div className="flex items-center gap-1">
                              <FiClock size={14} />
                              {update.hours_spent}h
                            </div>
                          ) : '-'}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                            update.status === 'Submitted' 
                              ? 'bg-green-100 text-green-800' 
                              : 'bg-yellow-100 text-yellow-800'
                          }`}>
                            {update.status}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                          {canEdit && canEditUpdate(update) && (
                            <button
                              onClick={() => handleEdit(update)}
                              className="text-gray-600 hover:text-blue-600 hover:text-white p-2 rounded-lg transition-colors"
                              style={{ backgroundColor: 'var(--primary-color, #4575b5)' }}
                              onMouseEnter={(e) => { e.target.style.backgroundColor = 'var(--secondary-color, #6b7280)'; }}
                              onMouseLeave={(e) => { e.target.style.backgroundColor = 'var(--primary-color, #4575b5)'; }}
                            >
                              <FiEdit size={16} />
                            </button>
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            )}
          </div>

          {/* Mobile Card View */}
          <div className="md:hidden">
            {updates.length === 0 ? (
              <div className="text-center py-12">
                <FiEdit className="mx-auto h-12 w-12 text-gray-400 mb-4" />
                <h3 className="text-lg font-medium text-gray-900 mb-2">No updates yet</h3>
                <p className="text-gray-600 mb-4">Start tracking your daily work progress</p>
                {canAdd && (
                  <button
                    onClick={handleNewUpdate}
                    className="bg-black text-white px-6 py-2 rounded-lg hover:bg-gray-800 transition-colors"
                  >
                    Create First Update
                  </button>
                )}
              </div>
            ) : (
              <div className="space-y-4">
                {updates.map((update) => {
                  const employee = employees.find(emp => {
                    if (emp.source === 'user_management') {
                      return emp.original_user_id == update.employee_id;
                    }
                    return emp.id == update.employee_id;
                  });
                  
                  return (
                    <div key={update.id} className=" rounded-xl p-4 hover:shadow-sm transition-shadow">
                      <div className="flex justify-between items-start mb-3">
                        <div className="flex items-center gap-3">
                          <div className="flex items-center gap-2 text-sm text-gray-600">
                            <FiCalendar size={16} />
                            {new Date(update.date).toLocaleDateString()}
                          </div>
                          <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                            update.status === 'Submitted' 
                              ? 'bg-green-100 text-green-800' 
                              : 'bg-yellow-100 text-yellow-800'
                          }`}>
                            {update.status}
                          </span>
                        </div>
                        <div className="flex gap-2">
                          {canEdit && canEditUpdate(update) && (
                            <button
                              onClick={() => handleEdit(update)}
                              className="p-2 text-gray-600 hover:text-blue-600 hover:text-white rounded-lg transition-colors"
                              style={{ backgroundColor: 'var(--primary-color, #4575b5)' }}
                              onMouseEnter={(e) => { e.target.style.backgroundColor = 'var(--secondary-color, #6b7280)'; }}
                              onMouseLeave={(e) => { e.target.style.backgroundColor = 'var(--primary-color, #4575b5)'; }}
                            >
                              <FiEdit size={16} />
                            </button>
                          )}
                        </div>
                      </div>
                      
                      <div className="space-y-3">
                        <div>
                          <h4 className="font-medium text-gray-900 mb-1">Employee</h4>
                          <p className="text-gray-700 text-sm">
                            {employee?.employee_code || `EMP${update.employee_id}`} - {employee?.name || `Employee ${update.employee_id}`}
                          </p>
                        </div>
                        
                        <div>
                          <h4 className="font-medium text-gray-900 mb-1">Work Done</h4>
                          <p className="text-gray-700 text-sm">{update.work_done}</p>
                        </div>
                        
                        {update.blockers && (
                          <div>
                            <h4 className="font-medium text-gray-900 mb-1">Blockers</h4>
                            <p className="text-gray-700 text-sm">{update.blockers}</p>
                          </div>
                        )}
                        
                        {update.plan_for_tomorrow && (
                          <div>
                            <h4 className="font-medium text-gray-900 mb-1">Plan for Tomorrow</h4>
                            <p className="text-gray-700 text-sm">{update.plan_for_tomorrow}</p>
                          </div>
                        )}
                        
                        {update.hours_spent && (
                          <div className="flex items-center gap-2 text-sm text-gray-600">
                            <FiClock size={16} />
                            {update.hours_spent} hours
                          </div>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
          </div>
        </div>
      </div>
      <Toast toast={toast} hideToast={hideToast} />
    </>
  );
};

export default DailyUpdates;
