import { useState, useEffect } from "react";
import { ChevronDown, ChevronUp, Calendar, Download, Copy, Save, Plus } from "lucide-react";
import Sidebar from "../../components/Sidebar";
import Header from "../../components/Header";
import api from "../../api";

export default function ShiftRoster() {
  const [shifts, setShifts] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [rosterData, setRosterData] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [showShifts, setShowShifts] = useState(false);
  const [selectedDepartment, setSelectedDepartment] = useState("");
  const [selectedRole, setSelectedRole] = useState("");
  const [selectedUser, setSelectedUser] = useState("");
  const [roles, setRoles] = useState([]);
  const [users, setUsers] = useState([]);
  const [allocatedUsers, setAllocatedUsers] = useState([]);
  const [editingCell, setEditingCell] = useState(null);
  const [bulkShift, setBulkShift] = useState("");
  const [viewMode, setViewMode] = useState("week"); // week or month
  const [currentDate, setCurrentDate] = useState(new Date());
  const [bulkDateRange, setBulkDateRange] = useState({
    start: new Date().toISOString().split('T')[0],
    end: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
  });
  const [nightShiftRules, setNightShiftRules] = useState({
    applicable_shifts: [],
    punch_out_rule: "Same day",
    minimum_hours: 6,
    night_ot_rate: "1.5x",
    grace_minutes: 15
  });
  const [showCreateShift, setShowCreateShift] = useState(false);
  const [newShift, setNewShift] = useState({ name: "", start_time: "", end_time: "" });
  const [selectedUsersForBulk, setSelectedUsersForBulk] = useState([]);

  useEffect(() => {
    fetchShifts();
    fetchEmployees();
    fetchNightShiftRules();
    fetchDepartments();
    fetchRoles();
    fetchUsers();
  }, []);

  useEffect(() => {
    fetchRosterData();
  }, [currentDate, viewMode, selectedDepartment]);

  useEffect(() => {
    // Load all users by default to show in calendar
    fetchUsers();
  }, []);

  const fetchShifts = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) {
        console.error("Missing authentication data:", { tenant, token: !!token });
        return;
      }
      
      console.log("Fetching shifts for tenant:", tenant);
      const response = await fetch(`http://localhost:8000/shifts/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      console.log("Response status:", response.status);
      console.log("Response headers:", response.headers.get('content-type'));
      
      const responseText = await response.text();
      console.log("Raw response:", responseText.substring(0, 200));
      
      if (!response.ok) {
        console.error("API Error - Full response:", responseText);
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      
      try {
        const data = JSON.parse(responseText);
        console.log("Shifts data received:", data);
        setShifts(data.shifts || []);
      } catch (parseError) {
        console.error("JSON parse error:", parseError);
        console.error("Response was not JSON:", responseText.substring(0, 500));
      }
    } catch (error) {
      console.error("Error fetching shifts:", error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      // Fetch from both onboarding and user management (same as Employee Directory)
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees (same logic as Employee Directory)
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        email: emp.candidate_email || 'N/A',
        designation: emp.job_title,
        department_name: emp.department,
        employee_code: emp.employee_id,
        joining_date: emp.joining_date,
        work_location: emp.work_location,
        reporting_manager: emp.reporting_manager,
        status: 'Active',
        source: 'onboarding'
      }));
      
      // Process user management employees (users with employee codes)
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          email: user.email,
          designation: user.designation || 'N/A',
          department_name: user.department_name,
          employee_code: user.employee_code,
          joining_date: user.joining_date,
          work_location: 'N/A',
          reporting_manager: 'N/A',
          status: user.status || 'Active',
          source: 'user_management'
        }));
      
      // Combine and remove duplicates (prefer user management data for same employee codes)
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      console.log('=== ROSTER EMPLOYEE FETCH DEBUG ===');
      console.log('Onboarding response:', onboardingRes);
      console.log('Users response:', usersRes);
      console.log('Valid onboarded employees:', validOnboardedEmployees.length, validOnboardedEmployees);
      console.log('User employees with codes:', userEmployeeData.length, userEmployeeData);
      console.log('Final combined employees:', allEmployees.length, allEmployees);
      console.log('=== END DEBUG ===');
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
    }
  };

  const fetchRosterData = async () => {
    try {
      const token = localStorage.getItem("access_token");
      if (!token) return;
      
      const dates = getDateRange();
      const startDate = dates[0];
      const endDate = dates[dates.length - 1];
      
      const url = `http://localhost:8000/api/roster/schedule?start_date=${startDate}&end_date=${endDate}${selectedDepartment ? `&department=${selectedDepartment}` : ''}`;
      
      const response = await fetch(url, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        console.log("Roster data received:", data);
        setRosterData(data.roster || []);
        
        // Auto-populate allocated users from roster data
        if (data.roster && data.roster.length > 0) {
          const uniqueUsers = data.roster.reduce((acc, entry) => {
            if (!acc.find(u => u.id === entry.employee_id)) {
              acc.push({
                id: entry.employee_id,
                name: entry.employee_name || `User ${entry.employee_id}`,
                department_name: entry.department || "Unknown",
                role_name: "Unknown",
                roster: {}
              });
            }
            return acc;
          }, []);
          
          // Populate roster data from schedule
          data.roster.forEach(empData => {
            const user = uniqueUsers.find(u => u.id === empData.employee_id);
            if (user && empData.schedule) {
              empData.schedule.forEach(dayData => {
                if (dayData.shift_id) {
                  user.roster[dayData.date] = dayData.shift_id;
                }
              });
            }
          });
          
          setAllocatedUsers(uniqueUsers);
        }
      } else {
        console.error("Failed to fetch roster data:", await response.text());
      }
    } catch (error) {
      console.error("Error fetching roster data:", error);
    }
  };

  const fetchDepartments = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) {
        console.log("Missing auth for departments:", { tenant, token: !!token });
        return;
      }
      
      console.log("Fetching departments for tenant:", tenant);
      const response = await fetch(`http://localhost:8000/hospitals/departments/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      console.log("Departments response status:", response.status);
      
      if (response.ok) {
        const data = await response.json();
        console.log("Departments data:", data);
        setDepartments(data.departments || []);
      } else {
        const errorText = await response.text();
        console.error("Departments API error:", errorText);
      }
    } catch (error) {
      console.error("Error fetching departments:", error);
    }
  };

  const fetchNightShiftRules = async () => {
    try {
      const token = localStorage.getItem("access_token");
      if (!token) return;
      
      const response = await fetch("http://localhost:8000/api/roster/night-shift-rules", {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        if (data.rules) {
          setNightShiftRules(data.rules);
        }
      }
    } catch (error) {
      console.error("Error fetching night shift rules:", error);
    }
  };

  const saveRosterEntry = async (employeeId, date, shiftId, status = "Scheduled") => {
    try {
      const token = localStorage.getItem("access_token");
      console.log("Attempting to save roster entry:", { employeeId, date, shiftId, status });
      console.log("Using token:", token ? "Token exists" : "No token");
      
      const response = await fetch("http://localhost:8000/api/roster/save", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          employee_id: employeeId,
          date: date,
          shift_id: shiftId,
          status: status
        })
      });
      
      console.log("Response status:", response.status);
      
      if (response.ok) {
        const result = await response.json();
        console.log("Roster entry saved successfully:", result);
      } else {
        const errorText = await response.text();
        console.error("Failed to save roster entry:", errorText);
      }
    } catch (error) {
      console.error("Error saving roster:", error);
    }
  };

  const fetchRoles = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      const response = await fetch(`http://localhost:8000/hospitals/roles/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        setRoles(data.roles || []);
      }
    } catch (error) {
      console.error("Error fetching roles:", error);
    }
  };

  const fetchUsers = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      const response = await fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        setUsers(data.users || []);
      }
    } catch (error) {
      console.error("Error fetching users:", error);
    }
  };

  const getFilteredEmployees = () => {
    console.log('Dropdown employees:', employees.length, employees);
    return employees; // Show all employees, don't filter out allocated ones
  };

  const addEmployeeToRoster = () => {
    if (!selectedUser) return;
    
    const employee = employees.find(e => e.id == selectedUser);
    if (employee && !allocatedUsers.find(allocated => allocated.id === employee.id)) {
      setAllocatedUsers([...allocatedUsers, { ...employee, roster: {} }]);
      setSelectedUser("");
    }
  };

  const bulkAllocateShifts = async () => {
    if (!bulkShift || selectedUsersForBulk.length === 0) {
      alert("Please select users and shift for bulk allocation");
      return;
    }
    
    const start = new Date(bulkDateRange.start);
    const end = new Date(bulkDateRange.end);
    const updatedUsers = [...allocatedUsers];
    
    // Save each entry to database
    for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
      const dateStr = new Date(d).toISOString().split('T')[0];
      
      for (const user of updatedUsers) {
        if (selectedUsersForBulk.includes(user.id)) {
          if (!user.roster) user.roster = {};
          user.roster[dateStr] = bulkShift;
          
          // Save to database
          const shiftId = bulkShift === "OFF" ? null : parseInt(bulkShift);
          const status = bulkShift === "OFF" ? "OFF" : "Scheduled";
          await saveRosterEntry(user.id, dateStr, shiftId, status);
        }
      }
    }
    
    setAllocatedUsers(updatedUsers);
    setBulkShift("");
    setSelectedUsersForBulk([]);
    
    // Refresh roster data to show updated entries
    fetchRosterData();
  };

  const removeUserFromRoster = (userId) => {
    setAllocatedUsers(allocatedUsers.filter(user => user.id !== userId));
  };

  const updateUserRoster = (userId, date, shiftId) => {
    setAllocatedUsers(allocatedUsers.map(user => {
      if (user.id === userId) {
        return {
          ...user,
          roster: {
            ...user.roster,
            [date]: shiftId
          }
        };
      }
      return user;
    }));
  };

  const createShift = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!newShift.name || !newShift.start_time || !newShift.end_time) {
        alert("Please fill all fields");
        return;
      }
      
      const response = await fetch(`http://localhost:8000/shifts/${tenant}/create`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify(newShift)
      });
      
      if (response.ok) {
        alert("Shift created successfully!");
        setNewShift({ name: "", start_time: "", end_time: "" });
        setShowCreateShift(false);
        fetchShifts();
      }
    } catch (error) {
      console.error("Error creating shift:", error);
    }
  };

  const deleteShift = async (shiftId) => {
    if (!confirm("Are you sure you want to delete this shift?")) {
      return;
    }
    
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      const response = await fetch(`http://localhost:8000/shifts/${tenant}/${shiftId}`, {
        method: "DELETE",
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      
      if (response.ok) {
        alert("Shift deleted successfully!");
        fetchShifts();
      } else {
        alert("Failed to delete shift");
      }
    } catch (error) {
      console.error("Error deleting shift:", error);
      alert("Error deleting shift");
    }
  };

  const saveNightShiftRules = async () => {
    try {
      const token = localStorage.getItem("access_token");
      const response = await fetch("http://localhost:8000/api/roster/night-shift-rules", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify(nightShiftRules)
      });
      
      if (response.ok) {
        alert("Night shift rules saved successfully!");
      } else {
        const errorText = await response.text();
        console.error("Failed to save night shift rules:", errorText);
        alert("Failed to save night shift rules");
      }
    } catch (error) {
      console.error("Error saving night shift rules:", error);
      alert("Error saving night shift rules");
    }
  };

  const getDayName = (dateStr) => {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', { weekday: 'short' });
  };

  const getDateRange = () => {
    const dates = [];
    let start, end;
    
    if (viewMode === "week") {
      // Get current week (Monday to Sunday)
      const curr = new Date(currentDate);
      const first = curr.getDate() - curr.getDay() + 1; // Monday
      start = new Date(curr.setDate(first));
      end = new Date(curr.setDate(first + 6)); // Sunday
    } else {
      // Get current month
      start = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1);
      end = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0);
    }
    
    for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
      dates.push(new Date(d).toISOString().split('T')[0]);
    }
    
    return dates;
  };

  const navigateDate = (direction) => {
    const newDate = new Date(currentDate);
    if (viewMode === "week") {
      newDate.setDate(newDate.getDate() + (direction * 7));
    } else {
      newDate.setMonth(newDate.getMonth() + direction);
    }
    setCurrentDate(newDate);
  };

  const getCalendarTitle = () => {
    if (viewMode === "week") {
      const dates = getDateRange();
      const start = new Date(dates[0]);
      const end = new Date(dates[dates.length - 1]);
      return `${start.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} - ${end.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;
    } else {
      return currentDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
    }
  };

  return (
    <div className="flex h-screen bg-gray-50">
      <Sidebar />
      <div className="flex-1 flex flex-col overflow-hidden">
        <Header />
        <div className="flex-1 overflow-y-auto p-6">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-800">Shift & Roster Management</h1>
        <p className="text-gray-600 mt-1">Manage employee shift assignments and roster planning</p>
      </div>

      {/* Section 1: Shift Planning Overview */}
      <div className="bg-white rounded-lg shadow-sm border p-6 mb-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold text-gray-800"> Shift Planning Overview</h2>
          <div className="flex gap-2">
            <button
              onClick={() => setShowCreateShift(!showCreateShift)}
              className="flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700"
            >
              <Plus size={16} /> Create Shift
            </button>
            <button
              onClick={() => setShowShifts(!showShifts)}
              className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
            >
              View All Shifts ({shifts.length}) {showShifts ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
            </button>
          </div>
        </div>

        {showCreateShift && (
          <div className="mb-6 p-4 bg-gray-50 rounded-lg border">
            <h3 className="text-md font-semibold mb-4">Create New Shift</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Shift Name</label>
                <input
                  type="text"
                  value={newShift.name}
                  onChange={(e) => setNewShift({...newShift, name: e.target.value})}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  placeholder="e.g., Morning Shift"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Start Time</label>
                <input
                  type="time"
                  value={newShift.start_time}
                  onChange={(e) => setNewShift({...newShift, start_time: e.target.value})}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">End Time</label>
                <input
                  type="time"
                  value={newShift.end_time}
                  onChange={(e) => setNewShift({...newShift, end_time: e.target.value})}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </div>
            <div className="flex gap-2 mt-4">
              <button
                onClick={createShift}
                className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
              >
                Create Shift
              </button>
              <button
                onClick={() => setShowCreateShift(false)}
                className="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700"
              >
                Cancel
              </button>
            </div>
          </div>
        )}

        {showShifts && (
          <div className="overflow-x-auto">
            <table className="w-full border-collapse border border-gray-300">
              <thead>
                <tr className="bg-gray-100">
                  <th className="border border-gray-300 px-4 py-2 text-left">Shift Name</th>
                  <th className="border border-gray-300 px-4 py-2 text-left">Start Time</th>
                  <th className="border border-gray-300 px-4 py-2 text-left">End Time</th>
                  <th className="border border-gray-300 px-4 py-2 text-left">Duration</th>
                  <th className="border border-gray-300 px-4 py-2 text-center">Actions</th>
                </tr>
              </thead>
              <tbody>
                {shifts.length === 0 ? (
                  <tr>
                    <td colSpan="5" className="border border-gray-300 px-4 py-8 text-center text-gray-500">
                      <div className="flex flex-col items-center gap-2">
                        <p>No shifts found</p>
                        <p className="text-sm">Please create shifts in Organization Setup → Shifts first</p>
                        <button
                          onClick={() => navigate('/organization/shifts')}
                          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm"
                        >
                          Go to Shifts Setup
                        </button>
                      </div>
                    </td>
                  </tr>
                ) : (
                  shifts.map((shift) => {
                    const calculateDuration = (start, end) => {
                      const startTime = new Date(`2000-01-01 ${start}`);
                      const endTime = new Date(`2000-01-01 ${end}`);
                      let diff = endTime - startTime;
                      if (diff < 0) diff += 24 * 60 * 60 * 1000; // Handle overnight shifts
                      const hours = Math.floor(diff / (1000 * 60 * 60));
                      return `${hours} hours`;
                    };
                    
                    return (
                      <tr key={shift.id}>
                        <td className="border border-gray-300 px-4 py-2 font-medium">{shift.name}</td>
                        <td className="border border-gray-300 px-4 py-2">{shift.start_time}</td>
                        <td className="border border-gray-300 px-4 py-2">{shift.end_time}</td>
                        <td className="border border-gray-300 px-4 py-2">
                          {calculateDuration(shift.start_time, shift.end_time)}
                        </td>
                        <td className="border border-gray-300 px-4 py-2">
                          <button 
                            onClick={() => deleteShift(shift.id)}
                            className="px-3 py-1 bg-red-600 text-white text-sm rounded hover:bg-red-700"
                          >
                            Delete
                          </button>
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Section 2: Roster Allocation */}
      <div className="bg-white rounded-lg shadow-sm border p-6 mb-6">
        <h2 className="text-lg font-semibold text-gray-800 mb-4"> Roster Allocation</h2>
        
        {/* Employee Allocation */}
        <div className="mb-6 p-4 bg-gray-50 rounded-lg border">
          <h3 className="text-md font-semibold mb-4">Add Employee to Roster</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Employee</label>
              <select
                value={selectedUser}
                onChange={(e) => setSelectedUser(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Select Employee</option>
                {getFilteredEmployees().map((employee) => (
                  <option key={employee.id} value={employee.id}>
                    {employee.employee_code} - {employee.name}
                  </option>
                ))}
              </select>
            </div>
            
            <div className="flex items-end">
              <button
                onClick={addEmployeeToRoster}
                disabled={!selectedUser}
                className="w-full px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:bg-gray-300"
              >
                Add to Roster
              </button>
            </div>
          </div>
        </div>

        {/* Bulk Shift Allocation */}
        {allocatedUsers.length > 0 && (
          <div className="mb-6 p-4 bg-blue-50 rounded-lg border border-blue-200">
            <h3 className="text-md font-semibold mb-4 text-blue-800">Bulk Shift Allocation</h3>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">From Date</label>
                <input
                  type="date"
                  value={bulkDateRange.start}
                  onChange={(e) => setBulkDateRange({...bulkDateRange, start: e.target.value})}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">To Date</label>
                <input
                  type="date"
                  value={bulkDateRange.end}
                  onChange={(e) => setBulkDateRange({...bulkDateRange, end: e.target.value})}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Shift</label>
                <select
                  value={bulkShift}
                  onChange={(e) => setBulkShift(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select Shift</option>
                  {shifts.map((shift) => (
                    <option key={shift.id} value={shift.id}>{shift.name}</option>
                  ))}
                  <option value="OFF">OFF</option>
                </select>
              </div>
              
              <div className="flex items-end">
                <button
                  onClick={bulkAllocateShifts}
                  disabled={!bulkShift}
                  className="w-full px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-300"
                >
                  Apply to Selected ({selectedUsersForBulk.length})
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Calendar Navigation */}
        <div className="flex items-center justify-between mb-6 p-4 bg-gray-50 rounded-lg border">
          <div className="flex items-center gap-4">
            <div className="flex bg-white rounded-lg border">
              <button
                onClick={() => setViewMode("week")}
                className={`px-4 py-2 text-sm font-medium rounded-l-lg ${
                  viewMode === "week" ? "bg-blue-600 text-white" : "text-gray-700 hover:bg-gray-100"
                }`}
              >
                Week
              </button>
              <button
                onClick={() => setViewMode("month")}
                className={`px-4 py-2 text-sm font-medium rounded-r-lg ${
                  viewMode === "month" ? "bg-blue-600 text-white" : "text-gray-700 hover:bg-gray-100"
                }`}
              >
                Month
              </button>
            </div>
            
            <div className="flex items-center gap-2">
              <button
                onClick={() => navigateDate(-1)}
                className="p-2 text-gray-600 hover:bg-white rounded-lg border"
              >
                <ChevronDown className="rotate-90" size={16} />
              </button>
              
              <h3 className="text-lg font-semibold text-gray-800 min-w-[200px] text-center">
                {getCalendarTitle()}
              </h3>
              
              <button
                onClick={() => navigateDate(1)}
                className="p-2 text-gray-600 hover:bg-white rounded-lg border"
              >
                <ChevronDown className="-rotate-90" size={16} />
              </button>
            </div>
          </div>
          
          <button
            onClick={() => setCurrentDate(new Date())}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm"
          >
            Today
          </button>
        </div>



        {/* Elegant Roster Calendar */}
        <div className="bg-white rounded-xl shadow-sm border overflow-hidden">
          <div className="px-4 py-3 bg-gradient-to-r from-blue-50 to-indigo-50 border-b">
            <h3 className="font-semibold text-gray-800">
              {viewMode === "week" ? "Weekly" : "Monthly"} Roster Calendar
              {allocatedUsers.length > 0 && (
                <span className="ml-2 text-sm text-gray-600">({allocatedUsers.length} employees)</span>
              )}
            </h3>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gradient-to-r from-blue-50 to-indigo-50">
                <tr>
                  <th className="px-2 py-4 text-center font-semibold text-gray-800 w-12 border-r border-gray-200">
                    <input
                      type="checkbox"
                      checked={selectedUsersForBulk.length === allocatedUsers.length && allocatedUsers.length > 0}
                      onChange={(e) => {
                        if (e.target.checked) {
                          setSelectedUsersForBulk(allocatedUsers.map(u => u.id));
                        } else {
                          setSelectedUsersForBulk([]);
                        }
                      }}
                      className="rounded"
                    />
                  </th>
                  <th className="px-6 py-4 text-left font-semibold text-gray-800 min-w-[200px] border-r border-gray-200">
                    Employee
                  </th>
                  {getDateRange().map((date) => {
                    const dayName = getDayName(date);
                    const dayNum = new Date(date).getDate();
                    const isWeekend = ['Sat', 'Sun'].includes(dayName);
                    
                    return (
                      <th key={date} className={`px-3 py-4 text-center min-w-[130px] border-r border-gray-200 ${
                        isWeekend ? 'bg-red-50' : ''
                      }`}>
                        <div className={`font-semibold ${
                          isWeekend ? 'text-red-600' : 'text-gray-800'
                        }`}>{dayName}</div>
                        <div className={`text-sm ${
                          isWeekend ? 'text-red-500' : 'text-gray-500'
                        }`}>{dayNum}</div>
                      </th>
                    );
                  })}
                  <th className="px-4 py-4 text-center font-semibold text-gray-800">Action</th>
                </tr>
              </thead>
              <tbody>
                {allocatedUsers.length === 0 ? (
                  <tr>
                    <td colSpan={getDateRange().length + 3} className="px-8 py-12 text-center text-gray-500">
                      <div className="flex flex-col items-center gap-3">
                        <Calendar size={48} className="text-gray-300" />
                        <p className="text-lg font-medium">No employees in roster</p>
                        <p className="text-sm">Add employees above to start scheduling shifts</p>
                      </div>
                    </td>
                  </tr>
                ) : (
                  allocatedUsers.map((user, index) => (
                    <tr key={user.id} className={`${index % 2 === 0 ? 'bg-gray-50' : 'bg-white'} hover:bg-blue-50 transition-colors`}>
                      <td className="px-2 py-4 text-center border-r border-gray-200">
                        <input
                          type="checkbox"
                          checked={selectedUsersForBulk.includes(user.id)}
                          onChange={(e) => {
                            if (e.target.checked) {
                              setSelectedUsersForBulk([...selectedUsersForBulk, user.id]);
                            } else {
                              setSelectedUsersForBulk(selectedUsersForBulk.filter(id => id !== user.id));
                            }
                          }}
                          className="rounded"
                        />
                      </td>
                      <td className="px-6 py-4 border-r border-gray-200">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-semibold">
                            {user.name.charAt(0).toUpperCase()}
                          </div>
                          <div>
                            <div className="font-semibold text-gray-800">{user.name}</div>
                            <div className="text-sm text-gray-500">{user.department_name} • {user.role_name}</div>
                          </div>
                        </div>
                      </td>
                      {getDateRange().map((date) => {
                        const dayName = getDayName(date);
                        const isWeekend = ['Sat', 'Sun'].includes(dayName);
                        const shiftValue = user.roster?.[date] || "";
                        const shift = shifts.find(s => s.id == shiftValue);
                        
                        return (
                          <td key={date} className={`px-3 py-4 border-r border-gray-200 ${
                            isWeekend ? 'bg-red-25' : ''
                          }`}>
                            {editingCell === `${user.id}-${date}` ? (
                              <select
                                value={shiftValue}
                                onChange={async (e) => {
                                  const shiftId = e.target.value ? parseInt(e.target.value) : null;
                                  const status = e.target.value === "OFF" ? "OFF" : "Scheduled";
                                  console.log('Saving roster:', { userId: user.id, date, shiftId, status });
                                  updateUserRoster(user.id, date, e.target.value);
                                  await saveRosterEntry(user.id, date, shiftId, status);
                                  setEditingCell(null);
                                }}
                                onBlur={() => setEditingCell(null)}
                                autoFocus
                                className="w-full px-2 py-1 text-sm border rounded focus:ring-2 focus:ring-blue-500"
                              >
                                <option value="">Select</option>
                                {shifts.map((shift) => (
                                  <option key={shift.id} value={shift.id}>{shift.name}</option>
                                ))}
                                <option value="OFF">OFF</option>
                              </select>
                            ) : shiftValue ? (
                              <div className="text-center">
                                <div 
                                  onClick={() => setEditingCell(`${user.id}-${date}`)}
                                  className={`px-3 py-2 text-sm rounded-lg font-medium cursor-pointer hover:opacity-80 ${
                                    shiftValue === "OFF" ? 'bg-red-100 text-red-700' :
                                    'bg-green-100 text-green-700'
                                  }`}
                                >
                                  {shiftValue === "OFF" ? "OFF" : shift?.name || "Unknown"}
                                </div>
                                {shift && (
                                  <div className="text-xs text-gray-500 mt-1">
                                    {shift.start_time} - {shift.end_time}
                                  </div>
                                )}
                                <button
                                  onClick={async () => {
                                    updateUserRoster(user.id, date, "");
                                    await saveRosterEntry(user.id, date, null, "Unscheduled");
                                  }}
                                  className="text-xs text-red-500 hover:text-red-700 mt-1"
                                >
                                  Clear
                                </button>
                              </div>
                            ) : (
                              <div 
                                onClick={() => setEditingCell(`${user.id}-${date}`)}
                                className="text-center text-gray-400 text-sm cursor-pointer hover:text-blue-500 hover:bg-blue-50 py-2 rounded"
                              >
                                + Add
                              </div>
                            )}
                          </td>
                        );
                      })}
                      <td className="px-4 py-4 text-center">
                        <button 
                          onClick={() => removeUserFromRoster(user.id)}
                          className="px-3 py-2 bg-red-500 text-white text-sm rounded-lg hover:bg-red-600 transition-colors"
                        >
                          Remove
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Section 3: Night Shift Rules */}
      <div className="bg-white rounded-lg shadow-sm border p-6">
        <h2 className="text-lg font-semibold text-gray-800 mb-4"> Night Shift Rules</h2>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Night shift applicable for Shifts:
            </label>
            <select
              value={(nightShiftRules.applicable_shifts && nightShiftRules.applicable_shifts[0]) || ""}
              onChange={(e) => {
                const value = e.target.value ? [parseInt(e.target.value)] : [];
                setNightShiftRules({...nightShiftRules, applicable_shifts: value});
              }}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
            >
              <option value="">Select Shift</option>
              {shifts.map((shift) => (
                <option key={shift.id} value={shift.id}>{shift.name}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Punch Out after midnight counts as:
            </label>
            <select
              value={nightShiftRules.punch_out_rule}
              onChange={(e) => setNightShiftRules({...nightShiftRules, punch_out_rule: e.target.value})}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
            >
              <option value="Same day">Same day</option>
              <option value="Next day">Next day</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Minimum hours for night shift credit:
            </label>
            <input
              type="number"
              value={nightShiftRules.minimum_hours}
              onChange={(e) => setNightShiftRules({...nightShiftRules, minimum_hours: parseInt(e.target.value)})}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Night OT bonus rate:
            </label>
            <select
              value={nightShiftRules.night_ot_rate}
              onChange={(e) => setNightShiftRules({...nightShiftRules, night_ot_rate: e.target.value})}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
            >
              <option value="1.25x">1.25x</option>
              <option value="1.5x">1.5x</option>
              <option value="2x">2x</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Grace time for night login (minutes):
            </label>
            <input
              type="number"
              value={nightShiftRules.grace_minutes}
              onChange={(e) => setNightShiftRules({...nightShiftRules, grace_minutes: parseInt(e.target.value)})}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
            />
          </div>
        </div>

        <div className="mt-6">
          <button
            onClick={saveNightShiftRules}
            className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            Save Night Shift Rules
          </button>
        </div>
      </div>
        </div>
      </div>
    </div>
  );
}