import { useState, useEffect } from "react";
import { ChevronDown, ChevronUp, Calendar, Download, Copy, Save, Plus } from "lucide-react";
import Sidebar from "../../components/Sidebar";
import Header from "../../components/Header";
import api from "../../api";

export default function ShiftRoster() {
  const [shifts, setShifts] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [rosterData, setRosterData] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [showShifts, setShowShifts] = useState(false);
  const [selectedDepartment, setSelectedDepartment] = useState("");
  const [selectedRole, setSelectedRole] = useState("");
  const [selectedUser, setSelectedUser] = useState("");
  const [roles, setRoles] = useState([]);
  const [users, setUsers] = useState([]);
  const [allocatedUsers, setAllocatedUsers] = useState([]);
  const [editingCell, setEditingCell] = useState(null);
  const [bulkShift, setBulkShift] = useState("");
  const [viewMode, setViewMode] = useState("week"); // week or month
  const [currentDate, setCurrentDate] = useState(new Date());
  const [bulkDateRange, setBulkDateRange] = useState({
    start: new Date().toISOString().split('T')[0],
    end: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
  });
  const [nightShiftRules, setNightShiftRules] = useState({
    applicable_shifts: [],
    punch_out_rule: "Same day",
    minimum_hours: 6,
    night_ot_rate: "1.5x",
    grace_minutes: 15
  });
  const [allNightShiftRules, setAllNightShiftRules] = useState([]);
  const [showNightShiftRulesList, setShowNightShiftRulesList] = useState(false);
  const [editingNightShiftRule, setEditingNightShiftRule] = useState(null);
  const [showCreateShift, setShowCreateShift] = useState(false);
  const [newShift, setNewShift] = useState({ name: "", start_time: "", end_time: "" });
  const [selectedUsersForBulk, setSelectedUsersForBulk] = useState([]);

  useEffect(() => {
    fetchShifts();
    fetchEmployees();
    fetchNightShiftRules();
    fetchDepartments();
    fetchRoles();
    fetchUsers();
  }, []);

  useEffect(() => {
    fetchRosterData();
  }, [currentDate, viewMode, selectedDepartment]);

  useEffect(() => {
    // Load all users by default to show in calendar
    fetchUsers();
  }, []);

  const fetchShifts = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) {
        console.error("Missing authentication data:", { tenant, token: !!token });
        return;
      }
      
      console.log("Fetching shifts for tenant:", tenant);
      const response = await fetch(`http://localhost:8000/shifts/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      console.log("Response status:", response.status);
      console.log("Response headers:", response.headers.get('content-type'));
      
      const responseText = await response.text();
      console.log("Raw response:", responseText.substring(0, 200));
      
      if (!response.ok) {
        console.error("API Error - Full response:", responseText);
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      
      try {
        const data = JSON.parse(responseText);
        console.log("Shifts data received:", data);
        setShifts(data.shifts || []);
      } catch (parseError) {
        console.error("JSON parse error:", parseError);
        console.error("Response was not JSON:", responseText.substring(0, 500));
      }
    } catch (error) {
      console.error("Error fetching shifts:", error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      // Fetch from both onboarding and user management (same as Employee Directory)
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees (same logic as Employee Directory)
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        email: emp.candidate_email || 'N/A',
        designation: emp.job_title,
        department_name: emp.department,
        employee_code: emp.employee_id,
        joining_date: emp.joining_date,
        work_location: emp.work_location,
        reporting_manager: emp.reporting_manager,
        status: 'Active',
        source: 'onboarding'
      }));
      
      // Process user management employees (users with employee codes)
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          email: user.email,
          designation: user.designation || 'N/A',
          department_name: user.department_name,
          employee_code: user.employee_code,
          joining_date: user.joining_date,
          work_location: 'N/A',
          reporting_manager: 'N/A',
          status: user.status || 'Active',
          source: 'user_management'
        }));
      
      // Combine and remove duplicates (prefer user management data for same employee codes)
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      console.log('=== ROSTER EMPLOYEE FETCH DEBUG ===');
      console.log('Onboarding response:', onboardingRes);
      console.log('Users response:', usersRes);
      console.log('Valid onboarded employees:', validOnboardedEmployees.length, validOnboardedEmployees);
      console.log('User employees with codes:', userEmployeeData.length, userEmployeeData);
      console.log('Final combined employees:', allEmployees.length, allEmployees);
      console.log('=== END DEBUG ===');
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
    }
  };

  const fetchRosterData = async () => {
    try {
      const token = localStorage.getItem("access_token");
      if (!token) return;
      
      const dates = getDateRange();
      const startDate = dates[0];
      const endDate = dates[dates.length - 1];
      
      const url = `http://localhost:8000/api/roster/schedule?start_date=${startDate}&end_date=${endDate}${selectedDepartment ? `&department=${selectedDepartment}` : ''}`;
      
      const response = await fetch(url, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        console.log("Roster data received:", data);
        setRosterData(data.roster || []);
        
        // Auto-populate allocated users from roster data
        if (data.roster && data.roster.length > 0) {
          const uniqueUsers = data.roster.reduce((acc, entry) => {
            if (!acc.find(u => u.id === entry.employee_id)) {
              acc.push({
                id: entry.employee_id,
                name: entry.employee_name || `User ${entry.employee_id}`,
                department_name: entry.department || "Unknown",
                role_name: "Unknown",
                roster: {}
              });
            }
            return acc;
          }, []);
          
          // Populate roster data from schedule
          data.roster.forEach(empData => {
            const user = uniqueUsers.find(u => u.id === empData.employee_id);
            if (user && empData.schedule) {
              empData.schedule.forEach(dayData => {
                if (dayData.shift_id) {
                  user.roster[dayData.date] = dayData.shift_id;
                }
              });
            }
          });
          
          setAllocatedUsers(uniqueUsers);
        }
      } else {
        console.error("Failed to fetch roster data:", await response.text());
      }
    } catch (error) {
      console.error("Error fetching roster data:", error);
    }
  };

  const fetchDepartments = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) {
        console.log("Missing auth for departments:", { tenant, token: !!token });
        return;
      }
      
      console.log("Fetching departments for tenant:", tenant);
      const response = await fetch(`http://localhost:8000/hospitals/departments/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      console.log("Departments response status:", response.status);
      
      if (response.ok) {
        const data = await response.json();
        console.log("Departments data:", data);
        setDepartments(data.departments || []);
      } else {
        const errorText = await response.text();
        console.error("Departments API error:", errorText);
      }
    } catch (error) {
      console.error("Error fetching departments:", error);
    }
  };

  const fetchNightShiftRules = async () => {
    try {
      const token = localStorage.getItem("access_token");
      if (!token) return;
      
      const response = await fetch("http://localhost:8000/api/roster/night-shift-rules", {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        if (data.rules) {
          setNightShiftRules(data.rules);
        }
      }
    } catch (error) {
      console.error("Error fetching night shift rules:", error);
    }
  };

  const fetchAllNightShiftRules = async () => {
    try {
      const token = localStorage.getItem("access_token");
      if (!token) return;
      
      const response = await fetch("http://localhost:8000/api/roster/night-shift-rules/list", {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        setAllNightShiftRules(data.rules || []);
      }
    } catch (error) {
      console.error("Error fetching all night shift rules:", error);
    }
  };

  const editNightShiftRule = async (ruleId) => {
    try {
      const token = localStorage.getItem("access_token");
      if (!token) return;
      
      const response = await fetch(`http://localhost:8000/api/roster/night-shift-rules/${ruleId}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        setEditingNightShiftRule(data.rule);
        setNightShiftRules(data.rule);
      }
    } catch (error) {
      console.error("Error fetching night shift rule:", error);
    }
  };

  const updateNightShiftRule = async (ruleId) => {
    try {
      const token = localStorage.getItem("access_token");
      const response = await fetch(`http://localhost:8000/api/roster/night-shift-rules/${ruleId}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify(nightShiftRules)
      });
      
      if (response.ok) {
        alert("Night shift rule updated successfully!");
        setEditingNightShiftRule(null);
        fetchAllNightShiftRules();
      }
    } catch (error) {
      console.error("Error updating night shift rule:", error);
    }
  };

  const deleteNightShiftRule = async (ruleId) => {
    if (!confirm("Are you sure you want to delete this night shift rule?")) {
      return;
    }
    
    try {
      const token = localStorage.getItem("access_token");
      const response = await fetch(`http://localhost:8000/api/roster/night-shift-rules/${ruleId}`, {
        method: "DELETE",
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        alert("Night shift rule deleted successfully!");
        fetchAllNightShiftRules();
      }
    } catch (error) {
      console.error("Error deleting night shift rule:", error);
    }
  };

  const saveRosterEntry = async (employeeId, date, shiftId, status = "Scheduled") => {
    try {
      const token = localStorage.getItem("access_token");
      console.log("Attempting to save roster entry:", { employeeId, date, shiftId, status });
      console.log("Using token:", token ? "Token exists" : "No token");
      
      const response = await fetch("http://localhost:8000/api/roster/save", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          employee_id: employeeId,
          date: date,
          shift_id: shiftId,
          status: status
        })
      });
      
      console.log("Response status:", response.status);
      
      if (response.ok) {
        const result = await response.json();
        console.log("Roster entry saved successfully:", result);
      } else {
        const errorText = await response.text();
        console.error("Failed to save roster entry:", errorText);
      }
    } catch (error) {
      console.error("Error saving roster:", error);
    }
  };

  const fetchRoles = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      const response = await fetch(`http://localhost:8000/hospitals/roles/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        setRoles(data.roles || []);
      }
    } catch (error) {
      console.error("Error fetching roles:", error);
    }
  };

  const fetchUsers = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      const response = await fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        setUsers(data.users || []);
      }
    } catch (error) {
      console.error("Error fetching users:", error);
    }
  };

  const getFilteredEmployees = () => {
    console.log('Dropdown employees:', employees.length, employees);
    return employees; // Show all employees, don't filter out allocated ones
  };

  const addEmployeeToRoster = () => {
    if (!selectedUser) return;
    
    const employee = employees.find(e => e.id == selectedUser);
    if (employee && !allocatedUsers.find(allocated => allocated.id === employee.id)) {
      setAllocatedUsers([...allocatedUsers, { ...employee, roster: {} }]);
      setSelectedUser("");
    }
  };

  const bulkAllocateShifts = async () => {
    if (!bulkShift || selectedUsersForBulk.length === 0) {
      alert("Please select users and shift for bulk allocation");
      return;
    }
    
    const start = new Date(bulkDateRange.start);
    const end = new Date(bulkDateRange.end);
    const updatedUsers = [...allocatedUsers];
    
    // Save each entry to database
    for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
      const dateStr = new Date(d).toISOString().split('T')[0];
      
      for (const user of updatedUsers) {
        if (selectedUsersForBulk.includes(user.id)) {
          if (!user.roster) user.roster = {};
          user.roster[dateStr] = bulkShift;
          
          // Save to database
          const shiftId = bulkShift === "OFF" ? null : parseInt(bulkShift);
          const status = bulkShift === "OFF" ? "OFF" : "Scheduled";
          await saveRosterEntry(user.id, dateStr, shiftId, status);
        }
      }
    }
    
    setAllocatedUsers(updatedUsers);
    setBulkShift("");
    setSelectedUsersForBulk([]);
    
    // Refresh roster data to show updated entries
    fetchRosterData();
  };

  const removeUserFromRoster = (userId) => {
    setAllocatedUsers(allocatedUsers.filter(user => user.id !== userId));
  };

  const updateUserRoster = (userId, date, shiftId) => {
    setAllocatedUsers(allocatedUsers.map(user => {
      if (user.id === userId) {
        return {
          ...user,
          roster: {
            ...user.roster,
            [date]: shiftId
          }
        };
      }
      return user;
    }));
  };

  const createShift = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!newShift.name || !newShift.start_time || !newShift.end_time) {
        alert("Please fill all fields");
        return;
      }
      
      const response = await fetch(`http://localhost:8000/shifts/${tenant}/create`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify(newShift)
      });
      
      if (response.ok) {
        alert("Shift created successfully!");
        setNewShift({ name: "", start_time: "", end_time: "" });
        setShowCreateShift(false);
        fetchShifts();
      }
    } catch (error) {
      console.error("Error creating shift:", error);
    }
  };

  const deleteShift = async (shiftId) => {
    if (!confirm("Are you sure you want to delete this shift?")) {
      return;
    }
    
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      const response = await fetch(`http://localhost:8000/shifts/${tenant}/${shiftId}`, {
        method: "DELETE",
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      
      if (response.ok) {
        alert("Shift deleted successfully!");
        fetchShifts();
      } else {
        alert("Failed to delete shift");
      }
    } catch (error) {
      console.error("Error deleting shift:", error);
      alert("Error deleting shift");
    }
  };

  const saveNightShiftRules = async () => {
    try {
      const token = localStorage.getItem("access_token");
      const response = await fetch("http://localhost:8000/api/roster/night-shift-rules", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify(nightShiftRules)
      });
      
      if (response.ok) {
        alert("Night shift rules saved successfully!");
      } else {
        const errorText = await response.text();
        console.error("Failed to save night shift rules:", errorText);
        alert("Failed to save night shift rules");
      }
    } catch (error) {
      console.error("Error saving night shift rules:", error);
      alert("Error saving night shift rules");
    }
  };

  const getDayName = (dateStr) => {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', { weekday: 'short' });
  };

  const getDateRange = () => {
    const dates = [];
    let start, end;
    
    if (viewMode === "week") {
      // Get current week (Monday to Sunday)
      const curr = new Date(currentDate);
      const first = curr.getDate() - curr.getDay() + 1; // Monday
      start = new Date(curr.setDate(first));
      end = new Date(curr.setDate(first + 6)); // Sunday
    } else {
      // Get current month
      start = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1);
      end = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0);
    }
    
    for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
      dates.push(new Date(d).toISOString().split('T')[0]);
    }
    
    return dates;
  };

  const navigateDate = (direction) => {
    const newDate = new Date(currentDate);
    if (viewMode === "week") {
      newDate.setDate(newDate.getDate() + (direction * 7));
    } else {
      newDate.setMonth(newDate.getMonth() + direction);
    }
    setCurrentDate(newDate);
  };

  const getCalendarTitle = () => {
    if (viewMode === "week") {
      const dates = getDateRange();
      const start = new Date(dates[0]);
      const end = new Date(dates[dates.length - 1]);
      return `${start.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} - ${end.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;
    } else {
      return currentDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
    }
  };

  return (
    <div className="flex h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <Sidebar />
      <div className="flex-1 flex flex-col overflow-hidden">
        <Header />
        <div className="flex-1 overflow-y-auto p-6 pt-24">
      <div className="mb-6">
        <div className="bg-white rounded-2xl border shadow-sm p-6">
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <div className="p-3 bg-blue-100 rounded-xl">
                <Calendar className="w-6 h-6 text-blue-600" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-primary">Shift & Roster Management</h1>
                <p className=" mt-1" style={{color: 'var(--text-secondary, #374151)'}}>Advanced shift planning and employee roster management system</p>
              </div>
            </div>
            
            <div className="flex items-center gap-4">
              <div className="text-center">
                <div className="text-2xl font-bold text-blue-600">{shifts.length}</div>
                <div className="text-sm text-muted">Active Shifts</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Section 1: Shift Planning Overview */}
      <div className="bg-white rounded-2xl shadow-xl border border-gray-100 p-8 mb-8 hover:shadow-2xl transition-shadow duration-300">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold text-primary"> Shift Planning Overview</h2>
          <div className="flex gap-2">
            <button
              onClick={() => setShowCreateShift(!showCreateShift)}
              className="flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700"
            >
              <Plus size={16} /> Create Shift
            </button>
            <button
              onClick={() => setShowShifts(!showShifts)}
              className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
            >
              View All Shifts ({shifts.length}) {showShifts ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
            </button>
          </div>
        </div>

        {showCreateShift && (
          <div className="mb-6 p-4 bg-content rounded-lg border">
            <h3 className="text-md font-semibold mb-4">Create New Shift</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-medium text-secondary mb-1">Shift Name</label>
                <input
                  type="text"
                  value={newShift.name}
                  onChange={(e) => setNewShift({...newShift, name: e.target.value})}
                  className="w-full px-3 py-2 border-dark rounded-lg focus:ring-2 focus:ring-blue-500"
                  placeholder="e.g., Morning Shift"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-secondary mb-1">Start Time</label>
                <input
                  type="time"
                  value={newShift.start_time}
                  onChange={(e) => setNewShift({...newShift, start_time: e.target.value})}
                  className="w-full px-3 py-2 border-dark rounded-lg focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-secondary mb-1">End Time</label>
                <input
                  type="time"
                  value={newShift.end_time}
                  onChange={(e) => setNewShift({...newShift, end_time: e.target.value})}
                  className="w-full px-3 py-2 border-dark rounded-lg focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </div>
            <div className="flex gap-2 mt-4">
              <button
                onClick={createShift}
                className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
              >
                Create Shift
              </button>
              <button
                onClick={() => setShowCreateShift(false)}
                className="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700"
              >
                Cancel
              </button>
            </div>
          </div>
        )}

        {showShifts && (
          <div className="overflow-x-auto">
            <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="w-full border-collapse border-dark">
              <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                <tr className="bg-gray-100">
                  <th className="border-dark px-4 py-2 text-left" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>Shift Name</th>
                  <th className="border-dark px-4 py-2 text-left" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>Start Time</th>
                  <th className="border-dark px-4 py-2 text-left" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>End Time</th>
                  <th className="border-dark px-4 py-2 text-left" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>Duration</th>
                  <th className="border-dark px-4 py-2 text-center" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>Actions</th>
                </tr>
              </thead>
              <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                {shifts.length === 0 ? (
                  <tr>
                    <td colSpan="5" className="border-dark px-4 py-8 text-center text-muted" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                      <div className="flex flex-col items-center gap-2">
                        <p>No shifts found</p>
                        <p className="text-sm">Please create shifts in Organization Setup → Shifts first</p>
                        <button
                          onClick={() => navigate('/organization/shifts')}
                          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm"
                        >
                          Go to Shifts Setup
                        </button>
                      </div>
                    </td>
                  </tr>
                ) : (
                  shifts.map((shift) => {
                    const calculateDuration = (start, end) => {
                      const startTime = new Date(`2000-01-01 ${start}`);
                      const endTime = new Date(`2000-01-01 ${end}`);
                      let diff = endTime - startTime;
                      if (diff < 0) diff += 24 * 60 * 60 * 1000; // Handle overnight shifts
                      const hours = Math.floor(diff / (1000 * 60 * 60));
                      return `${hours} hours`;
                    };
                    
                    return (
                      <tr key={shift.id}>
                        <td className="border-dark px-4 py-2 font-medium" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>{shift.name}</td>
                        <td className="border-dark px-4 py-2" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>{shift.start_time}</td>
                        <td className="border-dark px-4 py-2" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>{shift.end_time}</td>
                        <td className="border-dark px-4 py-2" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                          {calculateDuration(shift.start_time, shift.end_time)}
                        </td>
                        <td className="border-dark px-4 py-2" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                          <button 
                            onClick={() => deleteShift(shift.id)}
                            className="px-3 py-1 bg-red-600 text-white text-sm rounded hover:bg-red-700"
                          >
                            Delete
                          </button>
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Section 2: Roster Allocation */}
      <div className="bg-white rounded-2xl shadow-xl border border-gray-100 p-8 mb-8 hover:shadow-2xl transition-shadow duration-300">
        <h2 className="text-lg font-semibold text-primary mb-4"> Roster Allocation</h2>
        
        {/* Employee Allocation */}
        <div className="mb-8 p-6 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl border border-blue-200 shadow-lg">
          <h3 className="text-lg font-bold mb-6 text-blue-800 flex items-center gap-2">
            <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
              <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
            </svg>
            Add Employee to Roster
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-semibold text-secondary mb-2">Employee</label>
              <select
                value={selectedUser}
                onChange={(e) => setSelectedUser(e.target.value)}
                className="w-full px-4 py-3 border-2  rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white shadow-sm"
              >
                <option value="">Select Employee</option>
                {getFilteredEmployees().map((employee) => (
                  <option key={employee.id} value={employee.id}>
                    {employee.employee_code} - {employee.name}
                  </option>
                ))}
              </select>
            </div>
            
            <div className="flex items-end">
              <button
                onClick={addEmployeeToRoster}
                disabled={!selectedUser}
                className="w-full px-6 py-3 bg-gradient-to-r from-green-500 to-green-600 text-white rounded-xl hover:from-green-600 hover:to-green-700 disabled:from-gray-300 disabled:to-gray-400 font-semibold shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 disabled:transform-none"
              >
                Add to Roster
              </button>
            </div>
          </div>
        </div>

        {/* Bulk Shift Allocation */}
        {allocatedUsers.length > 0 && (
          <div className="mb-8 p-6 bg-gradient-to-r from-purple-50 to-pink-50 rounded-2xl border border-purple-200 shadow-lg">
            <h3 className="text-lg font-bold mb-6 text-purple-800 flex items-center gap-2">
              <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                <path d="M4 4a2 2 0 00-2 2v8a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2H4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z"></path>
              </svg>
              Bulk Shift Allocation
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
              <div>
                <label className="block text-sm font-semibold text-secondary mb-2">From Date</label>
                <input
                  type="date"
                  value={bulkDateRange.start}
                  onChange={(e) => setBulkDateRange({...bulkDateRange, start: e.target.value})}
                  className="w-full px-4 py-3 border-2  rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 bg-white shadow-sm"
                />
              </div>
              
              <div>
                <label className="block text-sm font-semibold text-secondary mb-2">To Date</label>
                <input
                  type="date"
                  value={bulkDateRange.end}
                  onChange={(e) => setBulkDateRange({...bulkDateRange, end: e.target.value})}
                  className="w-full px-4 py-3 border-2  rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 bg-white shadow-sm"
                />
              </div>
              
              <div>
                <label className="block text-sm font-semibold text-secondary mb-2">Shift</label>
                <select
                  value={bulkShift}
                  onChange={(e) => setBulkShift(e.target.value)}
                  className="w-full px-4 py-3 border-2  rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 bg-white shadow-sm"
                >
                  <option value="">Select Shift</option>
                  {shifts.map((shift) => (
                    <option key={shift.id} value={shift.id}>{shift.name}</option>
                  ))}
                  <option value="OFF">OFF</option>
                </select>
              </div>
              
              <div className="flex items-end">
                <button
                  onClick={bulkAllocateShifts}
                  disabled={!bulkShift}
                  className="w-full px-6 py-3 bg-gradient-to-r from-purple-500 to-purple-600 text-white rounded-xl hover:from-purple-600 hover:to-purple-700 disabled:from-gray-300 disabled:to-gray-400 font-semibold shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 disabled:transform-none"
                >
                  Apply to Selected ({selectedUsersForBulk.length})
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Calendar Navigation */}
        <div className="flex items-center justify-between mb-8 p-6 bg-gradient-to-r from-gray-50 to-blue-50 rounded-2xl border shadow-lg">
          <div className="flex items-center gap-6">
            <div className="flex bg-white rounded-xl border-2  shadow-sm">
              <button
                onClick={() => setViewMode("week")}
                className={`px-6 py-3 text-sm font-semibold rounded-l-xl transition-all duration-300 ${
                  viewMode === "week" ? "bg-gradient-to-r from-blue-500 to-blue-600 text-white shadow-lg" : "text-secondary hover:bg-gray-100"
                }`}
              >
                Week
              </button>
              <button
                onClick={() => setViewMode("month")}
                className={`px-6 py-3 text-sm font-semibold rounded-r-xl transition-all duration-300 ${
                  viewMode === "month" ? "bg-gradient-to-r from-blue-500 to-blue-600 text-white shadow-lg" : "text-secondary hover:bg-gray-100"
                }`}
              >
                Month
              </button>
            </div>
            
            <div className="flex items-center gap-3">
              <button
                onClick={() => navigateDate(-1)}
                className="p-3 text-secondary hover:bg-white rounded-xl border-2  shadow-sm hover:shadow-md transition-all duration-300 transform hover:-translate-y-1"
              >
                <ChevronDown className="rotate-90" size={20} />
              </button>
              
              <h3 className="text-xl font-bold text-primary min-w-[250px] text-center bg-white px-6 py-3 rounded-xl border-2  shadow-sm">
                {getCalendarTitle()}
              </h3>
              
              <button
                onClick={() => navigateDate(1)}
                className="p-3 text-secondary hover:bg-white rounded-xl border-2  shadow-sm hover:shadow-md transition-all duration-300 transform hover:-translate-y-1"
              >
                <ChevronDown className="-rotate-90" size={20} />
              </button>
            </div>
          </div>
          
          <button
            onClick={() => setCurrentDate(new Date())}
            className="px-6 py-3 bg-gradient-to-r from-blue-500 to-blue-600 text-white rounded-xl hover:from-blue-600 hover:to-blue-700 text-sm font-semibold shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1"
          >
            Today
          </button>
        </div>



        {/* Elegant Roster Calendar */}
        <div className="bg-white rounded-xl shadow-sm border overflow-hidden">
          <div className="px-4 py-3 bg-gradient-to-r from-blue-50 to-indigo-50 border-b">
            <h3 className="font-semibold text-primary">
              {viewMode === "week" ? "Weekly" : "Monthly"} Roster Calendar
              {allocatedUsers.length > 0 && (
                <span className="ml-2 text-sm text-secondary">({allocatedUsers.length} employees)</span>
              )}
            </h3>
          </div>
          <div className="overflow-x-auto">
            <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="w-full">
              <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-gradient-to-r from-blue-50 to-indigo-50">
                <tr>
                  <th className="px-2 py-4 text-center font-semibold text-primary w-12 border-r ">
                    <input
                      type="checkbox"
                      checked={selectedUsersForBulk.length === allocatedUsers.length && allocatedUsers.length > 0}
                      onChange={(e) => {
                        if (e.target.checked) {
                          setSelectedUsersForBulk(allocatedUsers.map(u => u.id));
                        } else {
                          setSelectedUsersForBulk([]);
                        }
                      }}
                      className="rounded"
                    />
                  </th>
                  <th className="px-6 py-4 text-left font-semibold text-primary min-w-[200px] border-r ">
                    Employee
                  </th>
                  {getDateRange().map((date) => {
                    const dayName = getDayName(date);
                    const dayNum = new Date(date).getDate();
                    const isWeekend = ['Sat', 'Sun'].includes(dayName);
                    
                    return (
                      <th key={date} className={`px-3 py-4 text-center min-w-[130px] border-r  ${
                        isWeekend ? 'bg-red-50' : ''
                      }`}>
                        <div className={`font-semibold ${
                          isWeekend ? 'text-red-600' : 'text-primary'
                        }`}>{dayName}</div>
                        <div className={`text-sm ${
                          isWeekend ? 'text-red-500' : 'text-muted'
                        }`}>{dayNum}</div>
                      </th>
                    );
                  })}
                  <th className="px-4 py-4 text-center font-semibold text-primary">Action</th>
                </tr>
              </thead>
              <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                {allocatedUsers.length === 0 ? (
                  <tr>
                    <td colSpan={getDateRange().length + 3} className="px-8 py-12 text-center text-muted">
                      <div className="flex flex-col items-center gap-3">
                        <Calendar size={48} className="text-gray-300" />
                        <p className="text-lg font-medium">No employees in roster</p>
                        <p className="text-sm">Add employees above to start scheduling shifts</p>
                      </div>
                    </td>
                  </tr>
                ) : (
                  allocatedUsers.map((user, index) => (
                    <tr key={user.id} className={`${index % 2 === 0 ? 'bg-content' : 'bg-white'} hover:bg-blue-50 transition-colors`}>
                      <td className="px-2 py-4 text-center border-r ">
                        <input
                          type="checkbox"
                          checked={selectedUsersForBulk.includes(user.id)}
                          onChange={(e) => {
                            if (e.target.checked) {
                              setSelectedUsersForBulk([...selectedUsersForBulk, user.id]);
                            } else {
                              setSelectedUsersForBulk(selectedUsersForBulk.filter(id => id !== user.id));
                            }
                          }}
                          className="rounded"
                        />
                      </td>
                      <td className="px-6 py-4 border-r ">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-semibold">
                            {user.name.charAt(0).toUpperCase()}
                          </div>
                          <div>
                            <div className="font-semibold text-primary">{user.name}</div>
                            <div className="text-sm text-muted">{user.department_name} • {user.role_name}</div>
                          </div>
                        </div>
                      </td>
                      {getDateRange().map((date) => {
                        const dayName = getDayName(date);
                        const isWeekend = ['Sat', 'Sun'].includes(dayName);
                        const shiftValue = user.roster?.[date] || "";
                        const shift = shifts.find(s => s.id == shiftValue);
                        
                        return (
                          <td key={date} className={`px-3 py-4 border-r  ${
                            isWeekend ? 'bg-red-25' : ''
                          }`}>
                            {editingCell === `${user.id}-${date}` ? (
                              <select
                                value={shiftValue}
                                onChange={async (e) => {
                                  const shiftId = e.target.value ? parseInt(e.target.value) : null;
                                  const status = e.target.value === "OFF" ? "OFF" : "Scheduled";
                                  console.log('Saving roster:', { userId: user.id, date, shiftId, status });
                                  updateUserRoster(user.id, date, e.target.value);
                                  await saveRosterEntry(user.id, date, shiftId, status);
                                  setEditingCell(null);
                                }}
                                onBlur={() => setEditingCell(null)}
                                autoFocus
                                className="w-full px-2 py-1 text-sm border rounded focus:ring-2 focus:ring-blue-500"
                              >
                                <option value="">Select</option>
                                {shifts.map((shift) => (
                                  <option key={shift.id} value={shift.id}>{shift.name}</option>
                                ))}
                                <option value="OFF">OFF</option>
                              </select>
                            ) : shiftValue ? (
                              <div className="text-center">
                                <div 
                                  onClick={() => setEditingCell(`${user.id}-${date}`)}
                                  className={`px-3 py-2 text-sm rounded-lg font-medium cursor-pointer hover:opacity-80 ${
                                    shiftValue === "OFF" ? 'bg-red-100 text-red-700' :
                                    'bg-green-100 text-green-700'
                                  }`}
                                >
                                  {shiftValue === "OFF" ? "OFF" : shift?.name || "Unknown"}
                                </div>
                                {shift && (
                                  <div className="text-xs text-muted mt-1">
                                    {shift.start_time} - {shift.end_time}
                                  </div>
                                )}
                                <button
                                  onClick={async () => {
                                    updateUserRoster(user.id, date, "");
                                    await saveRosterEntry(user.id, date, null, "Unscheduled");
                                  }}
                                  className="text-xs text-red-500 hover:text-red-700 mt-1"
                                >
                                  Clear
                                </button>
                              </div>
                            ) : (
                              <div 
                                onClick={() => setEditingCell(`${user.id}-${date}`)}
                                className="text-center text-muted text-sm cursor-pointer hover:text-blue-500 hover:bg-blue-50 py-2 rounded"
                              >
                                + Add
                              </div>
                            )}
                          </td>
                        );
                      })}
                      <td className="px-4 py-4 text-center">
                        <button 
                          onClick={() => removeUserFromRoster(user.id)}
                          className="px-3 py-2 bg-red-500 text-white text-sm rounded-lg hover:bg-red-600 transition-colors"
                        >
                          Remove
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Section 3: Night Shift Rules */}
      <div className="bg-white rounded-2xl shadow-xl border border-gray-100 p-8 hover:shadow-2xl transition-shadow duration-300">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold text-primary"> Night Shift Rules</h2>
          <div className="flex gap-2">
            <button
              onClick={() => {
                fetchAllNightShiftRules();
                setShowNightShiftRulesList(!showNightShiftRulesList);
              }}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
            >
              {showNightShiftRulesList ? 'Hide' : 'View All Rules'}
            </button>
          </div>
        </div>

        {showNightShiftRulesList && (
          <div className="mb-6 p-4 bg-content rounded-lg border">
            <h3 className="text-md font-semibold mb-4">All Night Shift Rules</h3>
            {allNightShiftRules.length === 0 ? (
              <p className="" style={{color: 'var(--text-muted, #6b7280)'}}>No night shift rules found</p>
            ) : (
              <div className="overflow-x-auto">
                <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="w-full border-collapse border-dark">
                  <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                    <tr className="bg-gray-100">
                      <th className="border-dark px-4 py-2 text-left" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>ID</th>
                      <th className="border-dark px-4 py-2 text-left" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>Applicable Shifts</th>
                      <th className="border-dark px-4 py-2 text-left" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>Punch Out Rule</th>
                      <th className="border-dark px-4 py-2 text-left" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>Min Hours</th>
                      <th className="border-dark px-4 py-2 text-left" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>OT Rate</th>
                      <th className="border-dark px-4 py-2 text-center" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>Actions</th>
                    </tr>
                  </thead>
                  <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                    {allNightShiftRules.map((rule) => (
                      <tr key={rule.id}>
                        <td className="border-dark px-4 py-2" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>{rule.id}</td>
                        <td className="border-dark px-4 py-2" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                          {rule.applicable_shifts?.map(shiftId => {
                            const shift = shifts.find(s => s.id === shiftId);
                            return shift ? shift.name : `Shift ${shiftId}`;
                          }).join(', ') || 'None'}
                        </td>
                        <td className="border-dark px-4 py-2" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>{rule.punch_out_rule}</td>
                        <td className="border-dark px-4 py-2" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>{rule.minimum_hours} hrs</td>
                        <td className="border-dark px-4 py-2" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>{rule.night_ot_rate}</td>
                        <td className="border-dark px-4 py-2" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                          <div className="flex gap-2 justify-center">
                            <button
                              onClick={() => editNightShiftRule(rule.id)}
                              className="px-3 py-1 bg-blue-600 text-white text-sm rounded hover:bg-blue-700"
                            >
                              Edit
                            </button>
                            <button
                              onClick={() => deleteNightShiftRule(rule.id)}
                              className="px-3 py-1 bg-red-600 text-white text-sm rounded hover:bg-red-700"
                            >
                              Delete
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}
        
        {/* Night Shift Rules Configuration */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
          <div className="space-y-6">
            <div className="p-4 bg-gradient-to-r from-indigo-50 to-purple-50 rounded-xl border border-indigo-200">
              <label className="block text-sm font-semibold text-secondary mb-3">
                Night shift applicable for Shifts:
              </label>
              <select
                value={(nightShiftRules.applicable_shifts && nightShiftRules.applicable_shifts[0]) || ""}
                onChange={(e) => {
                  const value = e.target.value ? [parseInt(e.target.value)] : [];
                  setNightShiftRules({...nightShiftRules, applicable_shifts: value});
                }}
                className="w-full px-4 py-3 border-2  rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 bg-white shadow-sm"
              >
                <option value="">Select Shift</option>
                {shifts.map((shift) => (
                  <option key={shift.id} value={shift.id}>{shift.name}</option>
                ))}
              </select>
            </div>

            <div className="p-4 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl border border-blue-200">
              <label className="block text-sm font-semibold text-secondary mb-3">
                Punch Out after midnight counts as:
              </label>
              <select
                value={nightShiftRules.punch_out_rule}
                onChange={(e) => setNightShiftRules({...nightShiftRules, punch_out_rule: e.target.value})}
                className="w-full px-4 py-3 border-2  rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white shadow-sm"
              >
                <option value="Same day">Same day</option>
                <option value="Next day">Next day</option>
              </select>
            </div>

            <div className="p-4 bg-gradient-to-r from-green-50 to-blue-50 rounded-xl border border-green-200">
              <label className="block text-sm font-semibold text-secondary mb-3">
                Minimum hours for night shift credit:
              </label>
              <input
                type="number"
                value={nightShiftRules.minimum_hours}
                onChange={(e) => setNightShiftRules({...nightShiftRules, minimum_hours: parseInt(e.target.value)})}
                className="w-full px-4 py-3 border-2  rounded-xl focus:ring-2 focus:ring-green-500 focus:border-green-500 bg-white shadow-sm"
              />
            </div>
          </div>

          <div className="space-y-6">
            <div className="p-4 bg-gradient-to-r from-orange-50 to-red-50 rounded-xl border border-orange-200">
              <label className="block text-sm font-semibold text-secondary mb-3">
                Night OT bonus rate:
              </label>
              <select
                value={nightShiftRules.night_ot_rate}
                onChange={(e) => setNightShiftRules({...nightShiftRules, night_ot_rate: e.target.value})}
                className="w-full px-4 py-3 border-2  rounded-xl focus:ring-2 focus:ring-orange-500 focus:border-orange-500 bg-white shadow-sm"
              >
                <option value="1.25x">1.25x</option>
                <option value="1.5x">1.5x</option>
                <option value="2x">2x</option>
              </select>
            </div>

            <div className="p-4 bg-gradient-to-r from-purple-50 to-pink-50 rounded-xl border border-purple-200">
              <label className="block text-sm font-semibold text-secondary mb-3">
                Grace time for night login (minutes):
              </label>
              <input
                type="number"
                value={nightShiftRules.grace_minutes}
                onChange={(e) => setNightShiftRules({...nightShiftRules, grace_minutes: parseInt(e.target.value)})}
                className="w-full px-4 py-3 border-2  rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 bg-white shadow-sm"
              />
            </div>

            <div className="p-4 bg-gradient-to-r from-gray-50 to-gray-100 rounded-xl border">
              <div className="text-center">
                <button
                  onClick={editingNightShiftRule ? () => updateNightShiftRule(editingNightShiftRule.id) : saveNightShiftRules}
                  className="w-full px-8 py-4 bg-gradient-to-r from-indigo-500 to-purple-600 text-white rounded-xl hover:from-indigo-600 hover:to-purple-700 font-semibold shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1"
                >
                  {editingNightShiftRule ? 'Update Rule' : 'Save Night Shift Rules'}
                </button>
                {editingNightShiftRule && (
                  <button
                    onClick={() => {
                      setEditingNightShiftRule(null);
                      setNightShiftRules({
                        applicable_shifts: [],
                        punch_out_rule: "Same day",
                        minimum_hours: 6,
                        night_ot_rate: "1.5x",
                        grace_minutes: 15
                      });
                    }}
                    className="w-full mt-3 px-8 py-4 bg-gradient-to-r from-gray-400 to-gray-500 text-white rounded-xl hover:from-gray-500 hover:to-gray-600 font-semibold shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1"
                  >
                    Cancel Edit
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
        </div>
      </div>
    </div>
  );
}
