import { useEffect, useState } from "react";
import { Play, Search, Eye, Download, Calendar, Users } from "lucide-react";
import Toast from "../../components/Toast";
import useToast from "../../utils/useToast";
import api from "../../api";
import { hasPermission, isAdmin } from "../../utils/permissions";

export default function PayrollRun() {
  const [runs, setRuns] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [structures, setStructures] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedMonth, setSelectedMonth] = useState("");
  const [showRunModal, setShowRunModal] = useState(false);
  const [showViewModal, setShowViewModal] = useState(false);
  const [selectedRun, setSelectedRun] = useState(null);
  const [loading, setLoading] = useState(false);
  const [colors, setColors] = useState({ primary: '#2862e9', secondary: '#474e71' });
  const [runData, setRunData] = useState({
    month: "",
    year: new Date().getFullYear()
  });
  const [validationResult, setValidationResult] = useState(null);
  const [showValidationModal, setShowValidationModal] = useState(false);
  const [validationChecked, setValidationChecked] = useState(false);
  const { toast, showToast, hideToast } = useToast();

  // Permission checks
  const canView = isAdmin() || hasPermission("view_payroll_run");
  const canCreate = isAdmin() || hasPermission("create_payroll_run");
  const canProcess = isAdmin() || hasPermission("process_payroll_run");
  const canViewDetails = isAdmin() || hasPermission("view_payroll_run");

  if (!canView) {
    return (
      <div className="p-6 text-center">
        <div className="bg-white rounded-2xl border-0 p-8 max-w-md mx-auto">
          <h3 className="text-lg font-medium text-gray-900 mb-2">Access Denied</h3>
          <p className="text-gray-600">You do not have permission to view payroll runs.</p>
        </div>
      </div>
    );
  }

  useEffect(() => {
    fetchColors();
    fetchRuns();
    fetchEmployees();
    fetchStructures();
  }, []);

  const fetchColors = async () => {
    try {
      const tenantCode = localStorage.getItem('tenantCode');
      if (tenantCode) {
        const response = await api.get(`/auth/branding/${tenantCode}`);
        if (response.data.primary_color && response.data.secondary_color) {
          const newColors = {
            primary: response.data.primary_color,
            secondary: response.data.secondary_color
          };
          setColors(newColors);
          document.documentElement.style.setProperty('--primary-color', newColors.primary);
          document.documentElement.style.setProperty('--secondary-color', newColors.secondary);
        }
      }
    } catch (error) {
      console.error('Error fetching colors:', error);
    }
  };

  const fetchStructures = async () => {
    try {
      const res = await api.get("/api/payroll/salary-structures");
      setStructures(res.data || []);
    } catch (error) {
      console.error("Error fetching salary structures:", error);
      setStructures([]);
    }
  };

  const fetchRuns = async () => {
    try {
      console.log('Fetching payroll runs...');
      const res = await api.get("/api/payroll/runs");
      console.log('Payroll runs response:', res.data);
      setRuns(res.data || []);
      console.log('Payroll runs set to state:', res.data?.length || 0, 'records');
    } catch (error) {
      console.error("Error fetching payroll runs:", error);
      setRuns([]);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      // Fetch employees from EIS system
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`${api.defaults.baseURL}/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process employees same as EIS
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        email: emp.candidate_email || 'N/A',
        designation: emp.job_title,
        department: emp.department,
        employee_code: emp.employee_id,
        status: 'Active'
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          email: user.email,
          designation: user.designation || 'N/A',
          department: user.department_name,
          employee_code: user.employee_code,
          status: user.status || 'Active'
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
      setEmployees([]);
    }
  };

  const checkPayrollValidation = async (month, year) => {
    try {
      const monthMap = {
        'January': 1, 'February': 2, 'March': 3, 'April': 4,
        'May': 5, 'June': 6, 'July': 7, 'August': 8,
        'September': 9, 'October': 10, 'November': 11, 'December': 12
      };
      const monthNum = monthMap[month];
      
      const response = await api.post(`/api/payroll/validation/check/${monthNum}/${year}`);
      return response.data;
    } catch (error) {
      console.error('Validation check failed:', error);
      throw error;
    }
  };

  const handleRunPayroll = async (e) => {
    e.preventDefault();
    
    if (!canCreate && !canProcess) {
      showToast("You do not have permission to run payroll", "error");
      return;
    }
    
    if (!runData.month || !runData.year) {
      showToast('Please select month and year', 'error');
      return;
    }
    
    try {
      setLoading(true);
      
      // Use bulk processing endpoint
      const payrollData = {
        month: runData.month,
        year: runData.year
      };
      
      console.log('Sending bulk payroll request:', payrollData);
      
      // Call the bulk processing endpoint
      const response = await api.post("/api/payroll/runs/bulk", payrollData);
      
      console.log('Payroll processing response:', response.data);
      
      // Wait a moment for database to be fully updated
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      // Fetch updated data from database multiple times to ensure we get the latest data
      await fetchRuns();
      await new Promise(resolve => setTimeout(resolve, 500));
      await fetchRuns(); // Fetch again to ensure we have the latest data
      
      setShowRunModal(false);
      setRunData({ month: "", year: new Date().getFullYear() });
      
      const successMessage = response.data.message || `Payroll processed successfully!`;
      if (response.data.database_records) {
        showToast(`${successMessage} (${response.data.database_records} records saved)`);
      } else {
        showToast(successMessage);
      }
      
    } catch (error) {
      console.error("Error running payroll:", error);
      
      // Check if it's a validation error
      if (error.response?.status === 400 && error.response?.data?.detail?.validation_required) {
        const validationError = error.response.data.detail;
        setValidationResult({
          can_run_payroll: false,
          total_issues: validationError.total_issues,
          critical_issues: validationError.critical_issues,
          warning_issues: validationError.warning_issues,
          issues: validationError.issues || []
        });
        setShowValidationModal(true);
      } else {
        const errorMessage = error.response?.data?.detail || error.message || 'Failed to process payroll. Please try again.';
        showToast(errorMessage, 'error');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleViewPayroll = (run) => {
    setSelectedRun(run);
    setShowViewModal(true);
  };

  const filteredRuns = runs.filter(run => {
    const matchesSearch = run.employee_name?.toLowerCase().includes(searchTerm.toLowerCase()) || 
                         run.employee_code?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         run.month?.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesMonth = !selectedMonth || run.month === selectedMonth;
    return matchesSearch && matchesMonth;
  });

  const months = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];

  // Get employees with salary structures from database
  const employeesWithSalary = employees.filter(employee => {
    // Check if employee is linked to any salary structure in database
    const linkedStructure = structures.find(structure => {
      if (!structure.employee_ids) return false;
      const storedIds = structure.employee_ids.split(',').filter(id => id.trim());
      // Convert stored IDs to match employee ID types
      const normalizedIds = storedIds.map(id => {
        const numId = parseInt(id);
        return isNaN(numId) ? id : numId;
      });
      return normalizedIds.includes(employee.id);
    });
    return linkedStructure;
  });
  
  const activeEmployeesCount = employeesWithSalary.length;
  const completedRunsCount = runs.filter(r => r.status === 'Completed').length;
  const thisMonthCount = runs.filter(r => r.month === months[new Date().getMonth()]).length;

  return (
    <div className="bg-white rounded-2xl border border-black overflow-hidden">
      {/* Header */}
      <div className="p-6 border-b border-black">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gray-100 rounded-xl flex items-center justify-center">
            <Play className="w-5 h-5 text-gray-600" />
          </div>
          <div>
            <h2 className="text-lg font-medium text-gray-900">Payroll Run</h2>
            <p className="text-sm text-gray-600">Process monthly payroll using attendance & leave data</p>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="p-6">
        {/* Add Payroll Button */}
        <div className="flex justify-center sm:justify-end mb-6">
          <button 
            onClick={() => setShowRunModal(true)}
            disabled={!canCreate}
            className={`px-6 py-3 rounded-xl flex items-center gap-2 transition-colors text-sm font-medium border w-full sm:w-auto justify-center ${
              canCreate 
                ? 'text-white' 
                : 'bg-gray-300 text-gray-500 cursor-not-allowed border-gray-300'
            }`}
            style={{
              backgroundColor: canCreate ? colors.primary : '#d1d5db',
              borderColor: canCreate ? colors.primary : '#d1d5db'
            }}
            onMouseEnter={(e) => {
              if (canCreate) {
                e.target.style.backgroundColor = colors.secondary;
              }
            }}
            onMouseLeave={(e) => {
              if (canCreate) {
                e.target.style.backgroundColor = colors.primary;
              }
            }}
          >
            <Play size={18} />
            Run Payroll
          </button>
        </div>
        {/* Filters */}
        <div className="mb-6">
          <div className="flex flex-col sm:flex-row gap-4">
            <div className="relative flex-1 max-w-md">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={16} />
              <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
                type="text"
                placeholder="Search by employee or month..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10 pr-4 py-2 border border-black rounded-xl focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent w-full text-sm"
              />
            </div>
            <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(e.target.value)}
              className=" border-black rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent text-sm w-full sm:w-auto"
            >
              <option value="">All Months</option>
              {months.map(month => (
                <option key={month} value={month}>{month}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="mb-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-gray-50 rounded-xl p-6 border border-black">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-600 text-sm font-medium">Active Employees</p>
                  <p className="text-3xl font-bold text-gray-900">{activeEmployeesCount}</p>
                </div>
                <div className="p-3 bg-gray-100 rounded-xl">
                  <Users className="h-10 w-10 text-gray-600" />
                </div>
              </div>
            </div>
            <div className="bg-gray-50 rounded-xl p-6 border border-black">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-600 text-sm font-medium">Completed Runs</p>
                  <p className="text-3xl font-bold text-gray-900">{completedRunsCount}</p>
                </div>
                <div className="p-3 bg-gray-100 rounded-xl">
                  <Play className="h-10 w-10 text-gray-600" />
                </div>
              </div>
            </div>
            <div className="bg-gray-50 rounded-xl p-6 border border-black">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-600 text-sm font-medium">This Month</p>
                  <p className="text-3xl font-bold text-gray-900">{thisMonthCount}</p>
                </div>
                <div className="p-3 bg-gray-100 rounded-xl">
                  <Calendar className="h-10 w-10 text-gray-600" />
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Table */}
        <div className="bg-white rounded-2xl border border-black overflow-hidden">
          {/* Desktop Table View */}
          <div className="hidden md:block overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-100 border-b border-black">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Employee</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Month</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Present Days</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">LOP Days</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Gross Salary</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Net Salary</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                  {filteredRuns.length === 0 ? (
                    <tr>
                      <td colSpan="8" className="px-6 py-12 text-center">
                        <Play className="mx-auto h-12 w-12 text-gray-400" />
                        <h3 className="mt-2 text-sm font-medium text-gray-900">No payroll runs yet</h3>
                        <p className="mt-1 text-sm text-gray-500">
                          Start by running payroll for your employees.
                        </p>
                        <div className="mt-6">
                          <button 
                            onClick={() => setShowRunModal(true)}
                            disabled={!canCreate}
                            className={`px-4 py-2 rounded-lg flex items-center gap-2 mx-auto transition-colors border border-black ${
                              canCreate 
                                ? 'bg-gray-900 hover:bg-gray-800 text-white' 
                                : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                            }`}
                          >
                            <Play size={16} />
                            Run First Payroll
                          </button>
                        </div>
                      </td>
                    </tr>
                  ) : (
                    filteredRuns.map((run, index) => (
                      <tr key={index} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm font-medium text-gray-900">{run.employee_name}</div>
                          <div className="text-sm text-gray-500">Code: {run.employee_code}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{run.month} {run.year}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{run.present_days}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{run.lop_days}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">₹{run.gross_salary?.toLocaleString()}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm font-medium text-gray-900">₹{run.net_salary?.toLocaleString()}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800 border border-gray-300">
                            {run.status}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                          <div className="flex items-center gap-2">
                            {canViewDetails && (
                              <button 
                                onClick={() => handleViewPayroll(run)}
                                className="text-gray-600 hover:text-gray-900 p-1 rounded border border-gray-300 hover:border-gray-400"
                                title="View Details"
                              >
                                <Eye size={16} />
                              </button>
                            )}
                          </div>
                        </td>
                      </tr>
                    ))
                  )}
              </tbody>
            </table>
          </div>

          {/* Mobile Card View */}
          <div className="md:hidden">
            {filteredRuns.length === 0 ? (
              <div className="p-6 text-center">
                <Play className="mx-auto h-12 w-12 text-gray-400" />
                <h3 className="mt-2 text-sm font-medium text-gray-900">No payroll runs yet</h3>
                <p className="mt-1 text-sm text-gray-500">
                  Start by running payroll for your employees.
                </p>
                <div className="mt-6">
                  <button 
                    onClick={() => setShowRunModal(true)}
                    disabled={!canCreate}
                    className={`px-4 py-2 rounded-lg flex items-center gap-2 mx-auto transition-colors border border-black ${
                      canCreate 
                        ? 'bg-gray-900 hover:bg-gray-800 text-white' 
                        : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                    }`}
                  >
                    <Play size={16} />
                    Run First Payroll
                  </button>
                </div>
              </div>
            ) : (
              filteredRuns.map((run, index) => (
                <div key={index} className="p-4 border-b-0 hover:bg-gray-50">
                  <div className="flex items-center justify-between mb-3">
                    <div>
                      <div className="text-sm font-medium text-gray-900">{run.employee_name}</div>
                      <div className="text-sm text-gray-500">Code: {run.employee_code}</div>
                    </div>
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800 border border-gray-300">
                      {run.status}
                    </span>
                  </div>
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <span className="text-sm font-medium text-gray-900">Month:</span>
                      <span className="text-sm text-gray-600">{run.month} {run.year}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-sm font-medium text-gray-900">Present Days:</span>
                      <span className="text-sm text-gray-600">{run.present_days}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-sm font-medium text-gray-900">LOP Days:</span>
                      <span className="text-sm text-gray-600">{run.lop_days}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-sm font-medium text-gray-900">Gross Salary:</span>
                      <span className="text-sm text-gray-600">₹{run.gross_salary?.toLocaleString()}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-sm font-medium text-gray-900">Net Salary:</span>
                      <span className="text-sm font-medium text-gray-900">₹{run.net_salary?.toLocaleString()}</span>
                    </div>
                  </div>
                  {canViewDetails && (
                    <div className="flex items-center justify-end mt-3 pt-3 border-t border-gray-100">
                      <button 
                        onClick={() => handleViewPayroll(run)}
                        className="flex items-center gap-1 text-gray-600 hover:text-gray-900 px-3 py-1 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                      >
                        <Eye size={14} />
                        View Details
                      </button>
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Run Payroll Modal */}
      {showRunModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg border border-black p-6 w-full max-w-md">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-lg font-semibold">Run Payroll</h3>
              <button 
                onClick={() => setShowRunModal(false)}
                className="text-gray-500 hover:text-gray-700"
              >
                ✕
              </button>
            </div>
            
            <form onSubmit={handleRunPayroll} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Month</label>
                <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
                  value={runData.month}
                  onChange={(e) => {
                    setRunData({...runData, month: e.target.value});
                    setValidationChecked(false);
                    setValidationResult(null);
                  }}
                  className="w-full border border-black rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-gray-500"
                  required
                >
                  <option value="">Select Month</option>
                  {months.map(month => (
                    <option key={month} value={month}>{month}</option>
                  ))}
                </select>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Year</label>
                <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
                  type="number"
                  value={runData.year}
                  onChange={(e) => {
                    setRunData({...runData, year: parseInt(e.target.value)});
                    setValidationChecked(false);
                    setValidationResult(null);
                  }}
                  className="w-full border border-black rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-gray-500"
                  min="2020"
                  max="2030"
                  required
                />
              </div>
              
              <div className="bg-gray-50 rounded-lg p-4 border-0">
                <p className="text-sm text-gray-600 mb-2">Employees with salary structures: <span className="font-medium">{activeEmployeesCount}</span></p>
                <p className="text-xs text-gray-500">Payroll will be processed for employees linked to salary structures.</p>
                {validationChecked && validationResult && (
                  <div className={`mt-3 p-2 rounded text-xs ${
                    validationResult.can_run_payroll 
                      ? 'bg-green-100 text-green-800 border border-green-200' 
                      : 'bg-red-100 text-red-800 border border-red-200'
                  }`}>
                    {validationResult.can_run_payroll 
                      ? `✓ Validation passed - Ready to run payroll` 
                      : `✗ Validation failed - ${validationResult.critical_issues} critical issues found`
                    }
                  </div>
                )}
              </div>
              
              <div className="flex gap-4 pt-4">
                <button
                  type="button"
                  onClick={() => {
                    setShowRunModal(false);
                    setValidationChecked(false);
                    setValidationResult(null);
                  }}
                  className="flex-1 px-4 py-2 border border-black rounded-xl text-gray-600 hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={async () => {
                    if (!runData.month || !runData.year) {
                      showToast('Please select month and year', 'error');
                      return;
                    }
                    try {
                      setLoading(true);
                      const validation = await checkPayrollValidation(runData.month, runData.year);
                      setValidationResult(validation);
                      setValidationChecked(true);
                      setShowValidationModal(true);
                    } catch (error) {
                      showToast('Validation check failed', 'error');
                    } finally {
                      setLoading(false);
                    }
                  }}
                  disabled={loading}
                  className="flex-1 px-4 py-2 border border-black rounded-xl text-gray-600 hover:bg-gray-50 disabled:opacity-50"
                >
                  {loading ? 'Checking...' : 'Validation Check'}
                </button>
                <button
                  type="submit"
                  disabled={loading || !validationChecked}
                  className="flex-1 text-white px-4 py-2 rounded-xl disabled:opacity-50 flex items-center justify-center gap-2 transition-colors"
                  style={{
                    backgroundColor: colors.primary,
                    borderColor: colors.primary
                  }}
                  onMouseEnter={(e) => {
                    if (!loading && validationChecked) {
                      e.target.style.backgroundColor = colors.secondary;
                    }
                  }}
                  onMouseLeave={(e) => {
                    if (!loading && validationChecked) {
                      e.target.style.backgroundColor = colors.primary;
                    }
                  }}
                >
                  {loading ? (
                    <>
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                      Processing...
                    </>
                  ) : (
                    <>
                      <Play size={16} />
                      Run Payroll
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* View Payroll Modal */}
      {showViewModal && selectedRun && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg border border-black p-4 sm:p-6 w-full max-w-2xl max-h-[80vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-lg font-semibold">Payroll Details</h3>
              <button 
                onClick={() => setShowViewModal(false)}
                className="text-gray-500 hover:text-gray-700"
              >
                ✕
              </button>
            </div>
            
            <div className="space-y-6">
              {/* Employee Info */}
              <div className="bg-gray-50 rounded-lg border border-black p-4">
                <h4 className="font-medium text-gray-900 mb-2">Employee Information</h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-600">Name:</span>
                    <span className="ml-2 font-medium">{selectedRun.employee_name}</span>
                  </div>
                  <div>
                    <span className="text-gray-600">Code:</span>
                    <span className="ml-2 font-medium">{selectedRun.employee_code}</span>
                  </div>
                  <div>
                    <span className="text-gray-600">Month:</span>
                    <span className="ml-2 font-medium">{selectedRun.month} {selectedRun.year}</span>
                  </div>
                  <div>
                    <span className="text-gray-600">Status:</span>
                    <span className="ml-2">
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800 border border-gray-300">
                        {selectedRun.status}
                      </span>
                    </span>
                  </div>
                </div>
              </div>

              {/* Attendance Details */}
              <div className="bg-gray-50 rounded-lg border border-black p-4">
                <h4 className="font-medium text-gray-900 mb-2">Attendance Summary</h4>
                <div className="grid grid-cols-1 sm:grid-cols-5 gap-4 text-sm">
                  <div className="text-center">
                    <div className="text-2xl font-bold text-gray-700">{selectedRun.present_days}</div>
                    <div className="text-gray-600">Present Days</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-gray-700">{selectedRun.leave_days || 0}</div>
                    <div className="text-gray-600">Leave Days</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-gray-700">{selectedRun.holiday_days || 0}</div>
                    <div className="text-gray-600">Holiday Days</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-gray-700">{selectedRun.total_working_days || 0}</div>
                    <div className="text-gray-600">Total Working Days</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-gray-700">{selectedRun.lop_days}</div>
                    <div className="text-gray-600">LOP Days</div>
                  </div>
                </div>
              </div>

              {/* Salary Breakdown */}
              <div className="bg-gray-50 rounded-lg border border-black p-4">
                <h4 className="font-medium text-gray-900 mb-4">Salary Breakdown</h4>
                <div className="space-y-3">
                  <div className="flex justify-between items-center py-2 border-b border-gray-300">
                    <span className="text-gray-700">Basic Salary</span>
                    <span className="font-medium">₹{selectedRun.basic_salary?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 border-b border-gray-300">
                    <span className="text-gray-700">HRA</span>
                    <span className="font-medium">₹{selectedRun.hra_salary?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 border-b border-gray-300">
                    <span className="text-gray-700">Allowances</span>
                    <span className="font-medium">₹{selectedRun.allowances?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 border-b-2 border-gray-400 font-semibold">
                    <span className="text-gray-900">Gross Salary</span>
                    <span className="text-gray-800">₹{selectedRun.gross_salary?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 text-gray-700">
                    <span>LOP Deduction</span>
                    <span className="font-medium">-₹{selectedRun.lop_deduction?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-3 bg-gray-100 px-4 rounded-lg font-bold text-lg border border-gray-300">
                    <span className="text-gray-900">Net Salary</span>
                    <span className="text-gray-800">₹{selectedRun.net_salary?.toLocaleString()}</span>
                  </div>
                </div>
              </div>
            </div>
            
            <div className="flex gap-4 mt-6">
              <button
                onClick={() => setShowViewModal(false)}
                className="flex-1 px-4 py-2 border border-black rounded-lg text-gray-600 hover:bg-gray-50"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
      {/* Validation Results Modal */}
      {showValidationModal && validationResult && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg border border-black p-6 w-full max-w-2xl max-h-[80vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-lg font-semibold">Payroll Validation Results</h3>
              <button 
                onClick={() => setShowValidationModal(false)}
                className="text-gray-500 hover:text-gray-700"
              >
                ✕
              </button>
            </div>
            
            <div className="space-y-4">
              {/* Summary */}
              <div className={`p-4 rounded-lg border ${
                validationResult.can_run_payroll 
                  ? 'bg-green-50 border-green-200' 
                  : 'bg-red-50 border-red-200'
              }`}>
                <div className="flex items-center gap-2 mb-2">
                  <div className={`w-3 h-3 rounded-full ${
                    validationResult.can_run_payroll ? 'bg-green-500' : 'bg-red-500'
                  }`}></div>
                  <h4 className="font-medium">
                    {validationResult.can_run_payroll 
                      ? 'Payroll can be processed' 
                      : 'Payroll cannot be processed'
                    }
                  </h4>
                </div>
                <div className="text-sm text-gray-600">
                  <p>Total Issues: {validationResult.total_issues}</p>
                  <p>Critical Issues: {validationResult.critical_issues}</p>
                  <p>Warning Issues: {validationResult.warning_issues || 0}</p>
                </div>
              </div>

              {/* Issues List */}
              {validationResult.issues && validationResult.issues.length > 0 && (
                <div>
                  <h4 className="font-medium mb-3">Issues Found:</h4>
                  <div className="space-y-2 max-h-60 overflow-y-auto">
                    {validationResult.issues.map((issue, index) => (
                      <div key={index} className={`p-3 rounded-lg border ${
                        issue.severity === 'critical' 
                          ? 'bg-red-50 border-red-200' 
                          : 'bg-yellow-50 border-yellow-200'
                      }`}>
                        <div className="flex items-start gap-2">
                          <div className={`w-2 h-2 rounded-full mt-2 ${
                            issue.severity === 'critical' ? 'bg-red-500' : 'bg-yellow-500'
                          }`}></div>
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-1">
                              <span className="font-medium text-sm">{issue.employee_name}</span>
                              <span className={`px-2 py-1 rounded text-xs ${
                                issue.severity === 'critical' 
                                  ? 'bg-red-100 text-red-800' 
                                  : 'bg-yellow-100 text-yellow-800'
                              }`}>
                                {issue.severity}
                              </span>
                            </div>
                            <p className="text-sm text-gray-700 mb-1">{issue.issue_description}</p>
                            <p className="text-xs text-gray-500">Date: {issue.date}</p>
                            <p className="text-xs text-gray-600 mt-1">Action: {issue.action_required}</p>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {validationResult.issues && validationResult.issues.length === 0 && (
                <div className="text-center py-8">
                  <div className="w-16 h-16 text-white rounded-full flex items-center justify-center mx-auto mb-4" style={{ backgroundColor: 'var(--primary-color, #4575b5)' }}>
                    <svg className="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                  </div>
                  <h3 className="text-lg font-medium text-gray-900 mb-2">All Clear!</h3>
                  <p className="text-gray-600">No validation issues found. Payroll is ready to be processed.</p>
                </div>
              )}
            </div>
            
            <div className="flex gap-4 mt-6">
              <button
                onClick={() => setShowValidationModal(false)}
                className="flex-1 px-4 py-2 border border-black rounded-lg text-gray-600 hover:bg-gray-50"
              >
                Close
              </button>
              {validationResult.can_run_payroll && (
                <button
                  onClick={() => {
                    setShowValidationModal(false);
                    // Trigger payroll run
                    handleRunPayroll({ preventDefault: () => {} });
                  }}
                  className="flex-1 text-white px-4 py-2 rounded-lg flex items-center justify-center gap-2 transition-colors"
                  style={{
                    backgroundColor: colors.primary,
                    borderColor: colors.primary
                  }}
                  onMouseEnter={(e) => e.target.style.backgroundColor = colors.secondary}
                  onMouseLeave={(e) => e.target.style.backgroundColor = colors.primary}
                >
                  <Play size={16} />
                  Proceed with Payroll
                </button>
              )}
            </div>
          </div>
        </div>
      )}

      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}
