import { useEffect, useState } from "react";
import { Play, Search, Eye, Download, Calendar, Users } from "lucide-react";
import api from "../../api";

export default function PayrollRun() {
  const [runs, setRuns] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [structures, setStructures] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedMonth, setSelectedMonth] = useState("");
  const [showRunModal, setShowRunModal] = useState(false);
  const [showViewModal, setShowViewModal] = useState(false);
  const [selectedRun, setSelectedRun] = useState(null);
  const [loading, setLoading] = useState(false);
  const [runData, setRunData] = useState({
    month: "",
    year: new Date().getFullYear()
  });
  const [validationResult, setValidationResult] = useState(null);
  const [showValidationModal, setShowValidationModal] = useState(false);
  const [validationChecked, setValidationChecked] = useState(false);

  useEffect(() => {
    fetchRuns();
    fetchEmployees();
    fetchStructures();
  }, []);

  const fetchStructures = async () => {
    try {
      const res = await api.get("/api/payroll/salary-structures");
      setStructures(res.data || []);
    } catch (error) {
      console.error("Error fetching salary structures:", error);
      setStructures([]);
    }
  };

  const fetchRuns = async () => {
    try {
      const res = await api.get("/api/payroll/runs");
      setRuns(res.data || []);
    } catch (error) {
      console.error("Error fetching payroll runs:", error);
      setRuns([]);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      // Fetch employees from EIS system
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process employees same as EIS
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        email: emp.candidate_email || 'N/A',
        designation: emp.job_title,
        department: emp.department,
        employee_code: emp.employee_id,
        status: 'Active'
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          email: user.email,
          designation: user.designation || 'N/A',
          department: user.department_name,
          employee_code: user.employee_code,
          status: user.status || 'Active'
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
      setEmployees([]);
    }
  };

  const checkPayrollValidation = async (month, year) => {
    try {
      const monthMap = {
        'January': 1, 'February': 2, 'March': 3, 'April': 4,
        'May': 5, 'June': 6, 'July': 7, 'August': 8,
        'September': 9, 'October': 10, 'November': 11, 'December': 12
      };
      const monthNum = monthMap[month];
      
      const response = await api.post(`/api/payroll/validation/check/${monthNum}/${year}`);
      return response.data;
    } catch (error) {
      console.error('Validation check failed:', error);
      throw error;
    }
  };

  const handleRunPayroll = async (e) => {
    e.preventDefault();
    
    if (!runData.month || !runData.year) {
      alert('Please select month and year');
      return;
    }
    
    try {
      setLoading(true);
      
      // First check validation
      const validation = await checkPayrollValidation(runData.month, runData.year);
      
      if (!validation.can_run_payroll && !runData.force_run) {
        setValidationResult(validation);
        setShowValidationModal(true);
        setLoading(false);
        return;
      }
      
      // If validation passes, proceed with payroll
      
      const employeesWithSalary = employees.filter(employee => {
        // Check if employee is linked to any salary structure in database
        const linkedStructure = structures.find(structure => {
          if (!structure.employee_ids) return false;
          const storedIds = structure.employee_ids.split(',').filter(id => id.trim());
          // Convert stored IDs to match employee ID types
          const normalizedIds = storedIds.map(id => {
            const numId = parseInt(id);
            return isNaN(numId) ? id : numId;
          });
          return normalizedIds.includes(employee.id);
        });
        return linkedStructure;
      });
      
      if (employeesWithSalary.length === 0) {
        alert('No employees with salary structures found to process payroll.');
        return;
      }
      
      console.log('Employees with salary structures:', employeesWithSalary.map(e => ({ id: e.id, name: e.name, employee_code: e.employee_code })));
      
      const payrollPromises = employeesWithSalary.map(async (employee) => {
        try {
          console.log(`\n=== Processing Employee: ${employee.name} ===`);
          console.log(`Employee data:`, {
            id: employee.id,
            original_user_id: employee.original_user_id,
            employee_code: employee.employee_code,
            name: employee.name
          });
          
          // Find employee's salary structure from database
          const linkedStructure = structures.find(structure => {
            if (!structure.employee_ids) return false;
            const storedIds = structure.employee_ids.split(',').filter(id => id.trim());
            // Convert stored IDs to match employee ID types
            const normalizedIds = storedIds.map(id => {
              const numId = parseInt(id);
              return isNaN(numId) ? id : numId;
            });
            return normalizedIds.includes(employee.id);
          });
          
          if (!linkedStructure) {
            console.warn(`❌ No salary structure linked for employee ${employee.name}`);
            return null;
          }
          
          console.log(`✅ Found salary structure ${linkedStructure.id} for ${employee.name}`);
          
          const salaryStructure = linkedStructure;
          
          // Calculate attendance data
          const attendanceRes = await api.get(`/api/attendance/punches/`, {
            params: {
              employee_id: employee.original_user_id || employee.id,
              month: runData.month,
              year: runData.year
            }
          });
          
          // Calculate leave data  
          const leaveRes = await api.get(`/api/leave/applications/`, {
            params: {
              employee_id: employee.original_user_id || employee.id,
              status: 'Approved',
              from_date: `${runData.year}-${String(months.indexOf(runData.month) + 1).padStart(2, '0')}-01`,
              to_date: `${runData.year}-${String(months.indexOf(runData.month) + 1).padStart(2, '0')}-31`
            }
          });
          
          // Process attendance data
          const monthlyAttendance = attendanceRes.data.filter(record => {
            const recordDate = new Date(record.date);
            return recordDate.getMonth() === months.indexOf(runData.month) && 
                   recordDate.getFullYear() === runData.year &&
                   record.employee_id == (employee.original_user_id || employee.id);
          });
          
          // Process leave data
          const monthlyLeaves = leaveRes.data.filter(leave => {
            const fromDate = new Date(leave.from_date);
            const toDate = new Date(leave.to_date);
            const monthStart = new Date(runData.year, months.indexOf(runData.month), 1);
            const monthEnd = new Date(runData.year, months.indexOf(runData.month) + 1, 0);
            
            return leave.employee_id == (employee.original_user_id || employee.id) &&
                   leave.status === 'Approved' &&
                   ((fromDate >= monthStart && fromDate <= monthEnd) ||
                    (toDate >= monthStart && toDate <= monthEnd) ||
                    (fromDate <= monthStart && toDate >= monthEnd));
          });
          
          const presentDays = monthlyAttendance.filter(record => 
            record.status === 'Present' || record.status === 'Late'
          ).length;
          
          const leaveDays = monthlyLeaves.reduce((total, leave) => {
            const fromDate = new Date(leave.from_date);
            const toDate = new Date(leave.to_date);
            const monthStart = new Date(runData.year, months.indexOf(runData.month), 1);
            const monthEnd = new Date(runData.year, months.indexOf(runData.month) + 1, 0);
            
            const actualFromDate = fromDate < monthStart ? monthStart : fromDate;
            const actualToDate = toDate > monthEnd ? monthEnd : toDate;
            
            const timeDiff = actualToDate.getTime() - actualFromDate.getTime();
            const daysDiff = Math.ceil(timeDiff / (1000 * 3600 * 24)) + 1;
            
            return total + Math.max(0, daysDiff);
          }, 0);
          
          const daysInMonth = new Date(runData.year, months.indexOf(runData.month) + 1, 0).getDate();
          const lopDays = Math.max(0, daysInMonth - presentDays - leaveDays);
          
          // Calculate salary
          const monthlyCTC = (salaryStructure.ctc || 0) / 12;
          const basicSalary = (monthlyCTC * (salaryStructure.basic_percent || 40)) / 100;
          const hraSalary = (monthlyCTC * (salaryStructure.hra_percent || 20)) / 100;
          const allowances = monthlyCTC - basicSalary - hraSalary;
          
          const grossSalary = monthlyCTC;
          const lopDeduction = (grossSalary / 30) * lopDays;
          const netSalary = grossSalary - lopDeduction;
          
          // Create payroll run record and save to database
          const payrollData = {
            employee_id: employee.original_user_id || employee.id,
            employee_name: employee.name,
            employee_code: employee.employee_code,
            month: runData.month,
            year: runData.year,
            present_days: presentDays,
            leave_days: leaveDays,
            lop_days: lopDays,
            basic_salary: basicSalary,
            hra_salary: hraSalary,
            allowances: allowances,
            gross_salary: grossSalary,
            lop_deduction: lopDeduction,
            net_salary: netSalary,
            status: 'Completed',
            processed_date: new Date().toISOString()
          };
          
          // Save to database
          await api.post("/api/payroll/runs", payrollData);
          return payrollData;
        } catch (error) {
          console.error(`Error processing payroll for ${employee.name}:`, error);
          return null;
        }
      });
      
      const payrollResults = await Promise.all(payrollPromises);
      const validResults = payrollResults.filter(result => result !== null);
      
      // Fetch updated data from database
      await fetchRuns();
      setShowRunModal(false);
      setRunData({ month: "", year: new Date().getFullYear() });
      
      alert(`Payroll processed successfully for ${validResults.length} employees!`);
    } catch (error) {
      console.error("Error running payroll:", error);
      
      // Check if it's a validation error
      if (error.response?.status === 400 && error.response?.data?.detail?.validation_required) {
        const validationError = error.response.data.detail;
        setValidationResult({
          can_run_payroll: false,
          total_issues: validationError.total_issues,
          critical_issues: validationError.critical_issues,
          issues: validationError.issues || []
        });
        setShowValidationModal(true);
      } else {
        alert('Failed to process payroll. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleViewPayroll = (run) => {
    setSelectedRun(run);
    setShowViewModal(true);
  };

  const filteredRuns = runs.filter(run => {
    const matchesSearch = run.employee_name?.toLowerCase().includes(searchTerm.toLowerCase()) || 
                         run.employee_code?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         run.month?.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesMonth = !selectedMonth || run.month === selectedMonth;
    return matchesSearch && matchesMonth;
  });

  const months = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];

  // Get employees with salary structures from database
  const employeesWithSalary = employees.filter(employee => {
    // Check if employee is linked to any salary structure in database
    const linkedStructure = structures.find(structure => {
      if (!structure.employee_ids) return false;
      const storedIds = structure.employee_ids.split(',').filter(id => id.trim());
      // Convert stored IDs to match employee ID types
      const normalizedIds = storedIds.map(id => {
        const numId = parseInt(id);
        return isNaN(numId) ? id : numId;
      });
      return normalizedIds.includes(employee.id);
    });
    return linkedStructure;
  });
  
  const activeEmployeesCount = employeesWithSalary.length;
  const completedRunsCount = runs.filter(r => r.status === 'Completed').length;
  const thisMonthCount = runs.filter(r => r.month === months[new Date().getMonth()]).length;

  return (
    <div className="bg-white rounded-2xl border border-black overflow-hidden">
      {/* Header */}
      <div className="p-6 border-b border-black">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gray-100 rounded-xl flex items-center justify-center">
            <Play className="w-5 h-5 text-gray-600" />
          </div>
          <div>
            <h2 className="text-lg font-medium text-gray-900">Payroll Run</h2>
            <p className="text-sm text-gray-600">Process monthly payroll using attendance & leave data</p>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="p-6">
        {/* Add Payroll Button */}
        <div className="flex justify-center sm:justify-end mb-6">
          <button 
            onClick={() => setShowRunModal(true)}
            className="bg-gray-900 hover:bg-gray-800 text-white px-6 py-3 rounded-xl flex items-center gap-2 transition-colors text-sm font-medium border border-black w-full sm:w-auto justify-center"
          >
            <Play size={18} />
            Run Payroll
          </button>
        </div>
        {/* Filters */}
        <div className="mb-6">
          <div className="flex flex-col sm:flex-row gap-4">
            <div className="relative flex-1 max-w-md">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={16} />
              <input
                type="text"
                placeholder="Search by employee or month..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10 pr-4 py-2 border border-black rounded-xl focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent w-full text-sm"
              />
            </div>
            <select
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(e.target.value)}
              className="border border-black rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent text-sm w-full sm:w-auto"
            >
              <option value="">All Months</option>
              {months.map(month => (
                <option key={month} value={month}>{month}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="mb-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-gray-50 rounded-xl p-6 border border-black">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-600 text-sm font-medium">Active Employees</p>
                  <p className="text-3xl font-bold text-gray-900">{activeEmployeesCount}</p>
                </div>
                <div className="p-3 bg-gray-100 rounded-xl">
                  <Users className="h-10 w-10 text-gray-600" />
                </div>
              </div>
            </div>
            <div className="bg-gray-50 rounded-xl p-6 border border-black">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-600 text-sm font-medium">Completed Runs</p>
                  <p className="text-3xl font-bold text-gray-900">{completedRunsCount}</p>
                </div>
                <div className="p-3 bg-gray-100 rounded-xl">
                  <Play className="h-10 w-10 text-gray-600" />
                </div>
              </div>
            </div>
            <div className="bg-gray-50 rounded-xl p-6 border border-black">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-600 text-sm font-medium">This Month</p>
                  <p className="text-3xl font-bold text-gray-900">{thisMonthCount}</p>
                </div>
                <div className="p-3 bg-gray-100 rounded-xl">
                  <Calendar className="h-10 w-10 text-gray-600" />
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Table */}
        <div className="overflow-x-auto border border-black rounded-xl">
          <table className="w-full">
            <thead className="bg-gray-100 border-b border-black">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Employee</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Month</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Present Days</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">LOP Days</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Gross Salary</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Net Salary</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
                {filteredRuns.length === 0 ? (
                  <tr>
                    <td colSpan="8" className="px-6 py-12 text-center">
                      <Play className="mx-auto h-12 w-12 text-gray-400" />
                      <h3 className="mt-2 text-sm font-medium text-gray-900">No payroll runs yet</h3>
                      <p className="mt-1 text-sm text-gray-500">
                        Start by running payroll for your employees.
                      </p>
                      <div className="mt-6">
                        <button 
                          onClick={() => setShowRunModal(true)}
                          className="bg-gray-900 hover:bg-gray-800 text-white px-4 py-2 rounded-lg flex items-center gap-2 mx-auto transition-colors border border-black"
                        >
                          <Play size={16} />
                          Run First Payroll
                        </button>
                      </div>
                    </td>
                  </tr>
                ) : (
                  filteredRuns.map((run, index) => (
                    <tr key={index} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-medium text-gray-900">{run.employee_name}</div>
                        <div className="text-sm text-gray-500">Code: {run.employee_code}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">{run.month} {run.year}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">{run.present_days}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">{run.lop_days}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">₹{run.gross_salary?.toLocaleString()}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-medium text-gray-900">₹{run.net_salary?.toLocaleString()}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800 border border-gray-300">
                          {run.status}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                        <div className="flex items-center gap-2">
                          <button 
                            onClick={() => handleViewPayroll(run)}
                            className="text-gray-600 hover:text-gray-900 p-1 rounded border border-gray-300 hover:border-gray-400"
                            title="View Details"
                          >
                            <Eye size={16} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                )}
            </tbody>
          </table>
        </div>
      </div>

      {/* View Payroll Modal */}
      {showViewModal && selectedRun && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg border border-black p-4 sm:p-6 w-full max-w-2xl max-h-[80vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-lg font-semibold">Payroll Details</h3>
              <button 
                onClick={() => setShowViewModal(false)}
                className="text-gray-500 hover:text-gray-700"
              >
                ✕
              </button>
            </div>
            
            <div className="space-y-6">
              {/* Employee Info */}
              <div className="bg-gray-50 rounded-lg border border-black p-4">
                <h4 className="font-medium text-gray-900 mb-2">Employee Information</h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-600">Name:</span>
                    <span className="ml-2 font-medium">{selectedRun.employee_name}</span>
                  </div>
                  <div>
                    <span className="text-gray-600">Code:</span>
                    <span className="ml-2 font-medium">{selectedRun.employee_code}</span>
                  </div>
                  <div>
                    <span className="text-gray-600">Month:</span>
                    <span className="ml-2 font-medium">{selectedRun.month} {selectedRun.year}</span>
                  </div>
                  <div>
                    <span className="text-gray-600">Status:</span>
                    <span className="ml-2">
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800 border border-gray-300">
                        {selectedRun.status}
                      </span>
                    </span>
                  </div>
                </div>
              </div>

              {/* Attendance Details */}
              <div className="bg-gray-50 rounded-lg border border-black p-4">
                <h4 className="font-medium text-gray-900 mb-2">Attendance Summary</h4>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-sm">
                  <div className="text-center">
                    <div className="text-2xl font-bold text-gray-700">{selectedRun.present_days}</div>
                    <div className="text-gray-600">Present Days</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-gray-700">{selectedRun.leave_days || 0}</div>
                    <div className="text-gray-600">Leave Days</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-gray-700">{selectedRun.lop_days}</div>
                    <div className="text-gray-600">LOP Days</div>
                  </div>
                </div>
              </div>

              {/* Salary Breakdown */}
              <div className="bg-gray-50 rounded-lg border border-black p-4">
                <h4 className="font-medium text-gray-900 mb-4">Salary Breakdown</h4>
                <div className="space-y-3">
                  <div className="flex justify-between items-center py-2 border-b border-gray-300">
                    <span className="text-gray-700">Basic Salary</span>
                    <span className="font-medium">₹{selectedRun.basic_salary?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 border-b border-gray-300">
                    <span className="text-gray-700">HRA</span>
                    <span className="font-medium">₹{selectedRun.hra_salary?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 border-b border-gray-300">
                    <span className="text-gray-700">Allowances</span>
                    <span className="font-medium">₹{selectedRun.allowances?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 border-b-2 border-gray-400 font-semibold">
                    <span className="text-gray-900">Gross Salary</span>
                    <span className="text-gray-800">₹{selectedRun.gross_salary?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 text-gray-700">
                    <span>LOP Deduction</span>
                    <span className="font-medium">-₹{selectedRun.lop_deduction?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-3 bg-gray-100 px-4 rounded-lg font-bold text-lg border border-gray-300">
                    <span className="text-gray-900">Net Salary</span>
                    <span className="text-gray-800">₹{selectedRun.net_salary?.toLocaleString()}</span>
                  </div>
                </div>
              </div>
            </div>
            
            <div className="flex gap-4 mt-6">
              <button
                onClick={() => setShowViewModal(false)}
                className="flex-1 px-4 py-2 border border-black rounded-lg text-gray-600 hover:bg-gray-50"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}