import { useEffect, useState } from "react";
import { Play, Search, Eye, Download, Calendar, Users } from "lucide-react";
import api from "../../api";

export default function PayrollRun() {
  const [runs, setRuns] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [structures, setStructures] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedMonth, setSelectedMonth] = useState("");
  const [showRunModal, setShowRunModal] = useState(false);
  const [showViewModal, setShowViewModal] = useState(false);
  const [selectedRun, setSelectedRun] = useState(null);
  const [loading, setLoading] = useState(false);
  const [runData, setRunData] = useState({
    month: "",
    year: new Date().getFullYear()
  });
  const [validationResult, setValidationResult] = useState(null);
  const [showValidationModal, setShowValidationModal] = useState(false);
  const [validationChecked, setValidationChecked] = useState(false);

  useEffect(() => {
    fetchRuns();
    fetchEmployees();
    fetchStructures();
  }, []);

  const fetchStructures = async () => {
    try {
      const res = await api.get("/api/payroll/salary-structures");
      setStructures(res.data || []);
    } catch (error) {
      console.error("Error fetching salary structures:", error);
      setStructures([]);
    }
  };

  const fetchRuns = async () => {
    try {
      const res = await api.get("/api/payroll/runs");
      setRuns(res.data || []);
    } catch (error) {
      console.error("Error fetching payroll runs:", error);
      setRuns([]);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      // Fetch employees from EIS system
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process employees same as EIS
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        email: emp.candidate_email || 'N/A',
        designation: emp.job_title,
        department: emp.department,
        employee_code: emp.employee_id,
        status: 'Active'
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          email: user.email,
          designation: user.designation || 'N/A',
          department: user.department_name,
          employee_code: user.employee_code,
          status: user.status || 'Active'
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
      setEmployees([]);
    }
  };

  const checkPayrollValidation = async (month, year) => {
    try {
      const monthMap = {
        'January': 1, 'February': 2, 'March': 3, 'April': 4,
        'May': 5, 'June': 6, 'July': 7, 'August': 8,
        'September': 9, 'October': 10, 'November': 11, 'December': 12
      };
      const monthNum = monthMap[month];
      
      const response = await api.post(`/api/payroll/validation/check/${monthNum}/${year}`);
      return response.data;
    } catch (error) {
      console.error('Validation check failed:', error);
      throw error;
    }
  };

  const handleRunPayroll = async (e) => {
    e.preventDefault();
    
    if (!runData.month || !runData.year) {
      alert('Please select month and year');
      return;
    }
    
    try {
      setLoading(true);
      
      // First check validation
      const validation = await checkPayrollValidation(runData.month, runData.year);
      
      if (!validation.can_run_payroll && !runData.force_run) {
        setValidationResult(validation);
        setShowValidationModal(true);
        setLoading(false);
        return;
      }
      
      // If validation passes, proceed with payroll
      
      const employeesWithSalary = employees.filter(employee => {
        // Check if employee is linked to any salary structure in database
        const linkedStructure = structures.find(structure => {
          if (!structure.employee_ids) return false;
          const storedIds = structure.employee_ids.split(',').filter(id => id.trim());
          // Convert stored IDs to match employee ID types
          const normalizedIds = storedIds.map(id => {
            const numId = parseInt(id);
            return isNaN(numId) ? id : numId;
          });
          return normalizedIds.includes(employee.id);
        });
        return linkedStructure;
      });
      
      if (employeesWithSalary.length === 0) {
        alert('No employees with salary structures found to process payroll.');
        return;
      }
      
      console.log('Employees with salary structures:', employeesWithSalary.map(e => ({ id: e.id, name: e.name, employee_code: e.employee_code })));
      
      const payrollPromises = employeesWithSalary.map(async (employee) => {
        try {
          console.log(`\n=== Processing Employee: ${employee.name} ===`);
          console.log(`Employee data:`, {
            id: employee.id,
            original_user_id: employee.original_user_id,
            employee_code: employee.employee_code,
            name: employee.name
          });
          
          // Find employee's salary structure from database
          const linkedStructure = structures.find(structure => {
            if (!structure.employee_ids) return false;
            const storedIds = structure.employee_ids.split(',').filter(id => id.trim());
            // Convert stored IDs to match employee ID types
            const normalizedIds = storedIds.map(id => {
              const numId = parseInt(id);
              return isNaN(numId) ? id : numId;
            });
            return normalizedIds.includes(employee.id);
          });
          
          if (!linkedStructure) {
            console.warn(`❌ No salary structure linked for employee ${employee.name}`);
            return null;
          }
          
          console.log(`✅ Found salary structure ${linkedStructure.id} for ${employee.name}`);
          
          const salaryStructure = linkedStructure;
          
          // Calculate attendance data
          const attendanceRes = await api.get(`/api/attendance/punches/`, {
            params: {
              employee_id: employee.original_user_id || employee.id,
              month: runData.month,
              year: runData.year
            }
          });
          
          // Calculate leave data  
          const leaveRes = await api.get(`/api/leave/applications/`, {
            params: {
              employee_id: employee.original_user_id || employee.id,
              status: 'Approved',
              from_date: `${runData.year}-${String(months.indexOf(runData.month) + 1).padStart(2, '0')}-01`,
              to_date: `${runData.year}-${String(months.indexOf(runData.month) + 1).padStart(2, '0')}-31`
            }
          });
          
          // Process attendance data
          const monthlyAttendance = attendanceRes.data.filter(record => {
            const recordDate = new Date(record.date);
            return recordDate.getMonth() === months.indexOf(runData.month) && 
                   recordDate.getFullYear() === runData.year &&
                   record.employee_id == (employee.original_user_id || employee.id);
          });
          
          // Process leave data
          const monthlyLeaves = leaveRes.data.filter(leave => {
            const fromDate = new Date(leave.from_date);
            const toDate = new Date(leave.to_date);
            const monthStart = new Date(runData.year, months.indexOf(runData.month), 1);
            const monthEnd = new Date(runData.year, months.indexOf(runData.month) + 1, 0);
            
            return leave.employee_id == (employee.original_user_id || employee.id) &&
                   leave.status === 'Approved' &&
                   ((fromDate >= monthStart && fromDate <= monthEnd) ||
                    (toDate >= monthStart && toDate <= monthEnd) ||
                    (fromDate <= monthStart && toDate >= monthEnd));
          });
          
          const presentDays = monthlyAttendance.filter(record => 
            record.status === 'Present' || record.status === 'Late'
          ).length;
          
          const leaveDays = monthlyLeaves.reduce((total, leave) => {
            const fromDate = new Date(leave.from_date);
            const toDate = new Date(leave.to_date);
            const monthStart = new Date(runData.year, months.indexOf(runData.month), 1);
            const monthEnd = new Date(runData.year, months.indexOf(runData.month) + 1, 0);
            
            const actualFromDate = fromDate < monthStart ? monthStart : fromDate;
            const actualToDate = toDate > monthEnd ? monthEnd : toDate;
            
            const timeDiff = actualToDate.getTime() - actualFromDate.getTime();
            const daysDiff = Math.ceil(timeDiff / (1000 * 3600 * 24)) + 1;
            
            return total + Math.max(0, daysDiff);
          }, 0);
          
          const daysInMonth = new Date(runData.year, months.indexOf(runData.month) + 1, 0).getDate();
          const lopDays = Math.max(0, daysInMonth - presentDays - leaveDays);
          
          // Calculate salary
          const monthlyCTC = (salaryStructure.ctc || 0) / 12;
          const basicSalary = (monthlyCTC * (salaryStructure.basic_percent || 40)) / 100;
          const hraSalary = (monthlyCTC * (salaryStructure.hra_percent || 20)) / 100;
          const allowances = monthlyCTC - basicSalary - hraSalary;
          
          const grossSalary = monthlyCTC;
          const lopDeduction = (grossSalary / 30) * lopDays;
          const netSalary = grossSalary - lopDeduction;
          
          // Create payroll run record and save to database
          const payrollData = {
            employee_id: employee.original_user_id || employee.id,
            employee_name: employee.name,
            employee_code: employee.employee_code,
            month: runData.month,
            year: runData.year,
            present_days: presentDays,
            leave_days: leaveDays,
            lop_days: lopDays,
            basic_salary: basicSalary,
            hra_salary: hraSalary,
            allowances: allowances,
            gross_salary: grossSalary,
            lop_deduction: lopDeduction,
            net_salary: netSalary,
            status: 'Completed',
            processed_date: new Date().toISOString()
          };
          
          // Save to database
          await api.post("/api/payroll/runs", payrollData);
          return payrollData;
        } catch (error) {
          console.error(`Error processing payroll for ${employee.name}:`, error);
          return null;
        }
      });
      
      const payrollResults = await Promise.all(payrollPromises);
      const validResults = payrollResults.filter(result => result !== null);
      
      // Fetch updated data from database
      await fetchRuns();
      setShowRunModal(false);
      setRunData({ month: "", year: new Date().getFullYear() });
      
      alert(`Payroll processed successfully for ${validResults.length} employees!`);
    } catch (error) {
      console.error("Error running payroll:", error);
      
      // Check if it's a validation error
      if (error.response?.status === 400 && error.response?.data?.detail?.validation_required) {
        const validationError = error.response.data.detail;
        setValidationResult({
          can_run_payroll: false,
          total_issues: validationError.total_issues,
          critical_issues: validationError.critical_issues,
          issues: validationError.issues || []
        });
        setShowValidationModal(true);
      } else {
        alert('Failed to process payroll. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  };

  // Remove localStorage initialization comments

  const handleViewPayroll = (run) => {
    setSelectedRun(run);
    setShowViewModal(true);
  };

  const handleDownloadPayslip = (run) => {
    // Use the PDF payslip download endpoint
    const downloadUrl = `${api.defaults.baseURL}/api/payroll/payslip/${run.id}/download`;
    
    const link = document.createElement('a');
    link.href = downloadUrl;
    link.download = `payslip_${run.employee_code}_${run.month}_${run.year}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportCSV = () => {
    const downloadUrl = `${api.defaults.baseURL}/api/payroll/runs/export`;
    
    const link = document.createElement('a');
    link.href = downloadUrl;
    link.download = `payroll_runs_export.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const filteredRuns = runs.filter(run => {
    const matchesSearch = run.employee_name?.toLowerCase().includes(searchTerm.toLowerCase()) || 
                         run.employee_code?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         run.month?.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesMonth = !selectedMonth || run.month === selectedMonth;
    return matchesSearch && matchesMonth;
  });

  const months = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];

  // Get employees with salary structures from database
  console.log('Structures:', structures);
  console.log('All employees:', employees.map(e => ({ id: e.id, original_user_id: e.original_user_id, name: e.name, employee_code: e.employee_code })));
  
  const employeesWithSalary = employees.filter(employee => {
    // Check if employee is linked to any salary structure in database
    const linkedStructure = structures.find(structure => {
      if (!structure.employee_ids) return false;
      const storedIds = structure.employee_ids.split(',').filter(id => id.trim());
      // Convert stored IDs to match employee ID types
      const normalizedIds = storedIds.map(id => {
        const numId = parseInt(id);
        return isNaN(numId) ? id : numId;
      });
      return normalizedIds.includes(employee.id);
    });
    return linkedStructure;
  });
  
  console.log('Employees with salary structures:', employeesWithSalary.map(e => ({ id: e.id, name: e.name })));
  const activeEmployeesCount = employeesWithSalary.length;
  const completedRunsCount = runs.filter(r => r.status === 'Completed').length;
  const thisMonthCount = runs.filter(r => r.month === months[new Date().getMonth()]).length;
  const totalRunsCount = runs.length;

  return (
    <div className="bg-white rounded-lg shadow-sm">
      {/* Header */}
      <div className="p-6 border-b border-gray-200">
        <div className="flex justify-between items-center">
          <div>
            <h2 className="text-xl font-semibold text-gray-900">Payroll Run</h2>
            <p className="text-gray-600 mt-1">Process monthly payroll using attendance & leave data</p>
          </div>
          <button 
            onClick={() => setShowRunModal(true)}
            className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
          >
            <Play size={16} />
            Run Payroll
          </button>
        </div>
      </div>

      {/* Filters */}
      <div className="p-6 border-b border-gray-200">
        <div className="flex gap-4">
          <div className="relative flex-1 max-w-md">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={16} />
            <input
              type="text"
              placeholder="Search by employee or month..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent w-full"
            />
          </div>
          <select
            value={selectedMonth}
            onChange={(e) => setSelectedMonth(e.target.value)}
            className="border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          >
            <option value="">All Months</option>
            {months.map(month => (
              <option key={month} value={month}>{month}</option>
            ))}
          </select>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="p-6 border-b border-gray-200">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-blue-50 rounded-lg p-4">
            <div className="flex items-center">
              <Users className="h-8 w-8 text-blue-600" />
              <div className="ml-3">
                <p className="text-sm font-medium text-blue-600">Active Employees</p>
                <p className="text-2xl font-semibold text-blue-900">{activeEmployeesCount}</p>
              </div>
            </div>
          </div>
          <div className="bg-green-50 rounded-lg p-4">
            <div className="flex items-center">
              <Play className="h-8 w-8 text-green-600" />
              <div className="ml-3">
                <p className="text-sm font-medium text-green-600">Completed Runs</p>
                <p className="text-2xl font-semibold text-green-900">{completedRunsCount}</p>
              </div>
            </div>
          </div>
          <div className="bg-yellow-50 rounded-lg p-4">
            <div className="flex items-center">
              <Calendar className="h-8 w-8 text-yellow-600" />
              <div className="ml-3">
                <p className="text-sm font-medium text-yellow-600">This Month</p>
                <p className="text-2xl font-semibold text-yellow-900">{thisMonthCount}</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Employee</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Month</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Present Days</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">LOP Days</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Gross Salary</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Net Salary</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {filteredRuns.length === 0 ? (
              <tr>
                <td colSpan="8" className="px-6 py-12 text-center">
                  <Play className="mx-auto h-12 w-12 text-gray-400" />
                  <h3 className="mt-2 text-sm font-medium text-gray-900">No payroll runs yet</h3>
                  <p className="mt-1 text-sm text-gray-500">
                    Start by running payroll for your employees.
                  </p>
                  <div className="mt-6">
                    <button 
                      onClick={() => setShowRunModal(true)}
                      className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 mx-auto transition-colors"
                    >
                      <Play size={16} />
                      Run First Payroll
                    </button>
                  </div>
                </td>
              </tr>
            ) : (
              filteredRuns.map((run, index) => (
                <tr key={index} className="hover:bg-gray-50">
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm font-medium text-gray-900">{run.employee_name}</div>
                    <div className="text-sm text-gray-500">Code: {run.employee_code}</div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm text-gray-900">{run.month} {run.year}</div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm text-gray-900">{run.present_days}</div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm text-gray-900">{run.lop_days}</div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm text-gray-900">₹{run.gross_salary?.toLocaleString()}</div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm font-medium text-gray-900">₹{run.net_salary?.toLocaleString()}</div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                      {run.status}
                    </span>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <div className="flex items-center gap-2">
                      <button 
                        onClick={() => handleViewPayroll(run)}
                        className="text-blue-600 hover:text-blue-900 p-1 rounded"
                        title="View Details"
                      >
                        <Eye size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* View Payroll Modal */}
      {showViewModal && selectedRun && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-2xl max-h-[80vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-lg font-semibold">Payroll Details</h3>
              <button 
                onClick={() => setShowViewModal(false)}
                className="text-gray-400 hover:text-gray-600"
              >
                ✕
              </button>
            </div>
            
            <div className="space-y-6">
              {/* Employee Info */}
              <div className="bg-gray-50 rounded-lg p-4">
                <h4 className="font-medium text-gray-900 mb-2">Employee Information</h4>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">Name:</span>
                    <span className="ml-2 font-medium">{selectedRun.employee_name}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">Code:</span>
                    <span className="ml-2 font-medium">{selectedRun.employee_code}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">Month:</span>
                    <span className="ml-2 font-medium">{selectedRun.month} {selectedRun.year}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">Status:</span>
                    <span className="ml-2">
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                        {selectedRun.status}
                      </span>
                    </span>
                  </div>
                </div>
              </div>

              {/* Attendance Details */}
              <div className="bg-blue-50 rounded-lg p-4">
                <h4 className="font-medium text-gray-900 mb-2">Attendance Summary</h4>
                <div className="grid grid-cols-3 gap-4 text-sm">
                  <div className="text-center">
                    <div className="text-2xl font-bold text-blue-600">{selectedRun.present_days}</div>
                    <div className="text-gray-500">Present Days</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-green-600">{selectedRun.leave_days || 0}</div>
                    <div className="text-gray-500">Leave Days</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-red-600">{selectedRun.lop_days}</div>
                    <div className="text-gray-500">LOP Days</div>
                  </div>
                </div>
              </div>

              {/* Salary Breakdown */}
              <div className="bg-green-50 rounded-lg p-4">
                <h4 className="font-medium text-gray-900 mb-4">Salary Breakdown</h4>
                <div className="space-y-3">
                  <div className="flex justify-between items-center py-2 border-b border-green-200">
                    <span className="text-gray-600">Basic Salary</span>
                    <span className="font-medium">₹{selectedRun.basic_salary?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 border-b border-green-200">
                    <span className="text-gray-600">HRA</span>
                    <span className="font-medium">₹{selectedRun.hra_salary?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 border-b border-green-200">
                    <span className="text-gray-600">Allowances</span>
                    <span className="font-medium">₹{selectedRun.allowances?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 border-b-2 border-green-300 font-semibold">
                    <span className="text-gray-800">Gross Salary</span>
                    <span className="text-green-600">₹{selectedRun.gross_salary?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 text-red-600">
                    <span>LOP Deduction</span>
                    <span className="font-medium">-₹{selectedRun.lop_deduction?.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between items-center py-3 bg-green-100 px-4 rounded-lg font-bold text-lg">
                    <span className="text-gray-800">Net Salary</span>
                    <span className="text-green-700">₹{selectedRun.net_salary?.toLocaleString()}</span>
                  </div>
                </div>
              </div>
            </div>
            
            <div className="flex gap-4 mt-6">
              <button
                onClick={() => setShowViewModal(false)}
                className="flex-1 px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Validation Issues Modal */}
      {showValidationModal && validationResult && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-4xl max-h-[80vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-6">
              <h3 className={`text-lg font-semibold ${
                validationResult.critical_issues > 0 
                  ? 'text-red-600' 
                  : 'text-yellow-600'
              }`}>
                {validationResult.critical_issues > 0 
                  ? '❌ Cannot Run Payroll' 
                  : '⚠️ Payroll Validation Results'
                }
              </h3>
              <button 
                onClick={() => setShowValidationModal(false)}
                className="text-gray-400 hover:text-gray-600"
              >
                ✕
              </button>
            </div>
            
            <div className="space-y-6">
              {/* Summary */}
              <div className={`border rounded-lg p-4 ${
                validationResult.critical_issues > 0 
                  ? 'bg-red-50 border-red-200' 
                  : 'bg-yellow-50 border-yellow-200'
              }`}>
                <h4 className={`font-medium mb-2 ${
                  validationResult.critical_issues > 0 
                    ? 'text-red-800' 
                    : 'text-yellow-800'
                }`}>
                  {validationResult.critical_issues > 0 
                    ? 'Critical Issues Found' 
                    : 'Validation Warnings'
                  }
                </h4>
                <div className={`text-sm ${
                  validationResult.critical_issues > 0 
                    ? 'text-red-700' 
                    : 'text-yellow-700'
                }`}>
                  {validationResult.critical_issues > 0 && (
                    <>
                      <p><strong>Critical Issues:</strong> {validationResult.critical_issues}</p>
                      <p className="mt-2">Please resolve all critical issues before running payroll.</p>
                    </>
                  )}
                  {validationResult.warning_issues > 0 && (
                    <p><strong>Warnings:</strong> {validationResult.warning_issues} (absent days will result in LOP deductions)</p>
                  )}
                  <p><strong>Total Issues:</strong> {validationResult.total_issues}</p>
                </div>
              </div>

              {/* Issues List */}
              {validationResult.issues && validationResult.issues.length > 0 && (
                <div>
                  <h4 className="font-medium text-gray-900 mb-4">Issues Details:</h4>
                  
                  {/* Critical Issues */}
                  {validationResult.issues.filter(issue => issue.severity === 'critical').length > 0 && (
                    <div className="mb-6">
                      <h5 className="font-medium text-red-800 mb-3">🚨 Critical Issues (Must be resolved):</h5>
                      <div className="space-y-3">
                        {validationResult.issues
                          .filter(issue => issue.severity === 'critical')
                          .map((issue, index) => (
                          <div key={index} className="border-l-4 border-red-500 bg-red-50 p-4 rounded-r-lg">
                            <div className="flex justify-between items-start">
                              <div className="flex-1">
                                <div className="font-medium text-gray-900">
                                  {issue.employee_name} ({issue.employee_id})
                                </div>
                                <div className="text-sm mt-1 text-red-700">
                                  <strong>{issue.issue_type}:</strong> {issue.issue_description}
                                </div>
                                <div className="text-xs text-gray-600 mt-2">
                                  <strong>Action Required:</strong> {issue.action_required}
                                </div>
                              </div>
                              <span className="px-2 py-1 rounded-full text-xs font-medium bg-red-100 text-red-800">
                                CRITICAL
                              </span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                  
                  {/* Warning Issues */}
                  {validationResult.issues.filter(issue => issue.severity === 'warning').length > 0 && (
                    <div>
                      <h5 className="font-medium text-yellow-800 mb-3">⚠️ Warnings (Payroll can run with LOP deductions):</h5>
                      <div className="space-y-3">
                        {validationResult.issues
                          .filter(issue => issue.severity === 'warning')
                          .map((issue, index) => (
                          <div key={index} className="border-l-4 border-yellow-500 bg-yellow-50 p-4 rounded-r-lg">
                            <div className="flex justify-between items-start">
                              <div className="flex-1">
                                <div className="font-medium text-gray-900">
                                  {issue.employee_name} ({issue.employee_id})
                                </div>
                                <div className="text-sm mt-1 text-yellow-700">
                                  <strong>{issue.issue_type}:</strong> {issue.issue_description}
                                </div>
                                <div className="text-xs text-gray-600 mt-2">
                                  <strong>Action Required:</strong> {issue.action_required}
                                </div>
                              </div>
                              <span className="px-2 py-1 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800">
                                WARNING
                              </span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
            
            <div className="flex gap-4 mt-6">
              <button
                onClick={() => setShowValidationModal(false)}
                className="flex-1 px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50"
              >
                Close
              </button>
              <button
                onClick={() => {
                  setShowValidationModal(false);
                  // Optionally navigate to relevant sections to fix issues
                }}
                className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
              >
                Go Fix Issues
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Run Payroll Modal */}
      {showRunModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md max-h-[90vh] overflow-y-auto">
            <h3 className="text-lg font-semibold mb-4">Run Payroll</h3>
            <form onSubmit={handleRunPayroll} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Month</label>
                <select
                  value={runData.month}
                  onChange={(e) => setRunData({...runData, month: e.target.value})}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                >
                  <option value="">Select Month</option>
                  {months.map(month => (
                    <option key={month} value={month}>{month}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Year</label>
                <input
                  type="number"
                  value={runData.year}
                  onChange={(e) => setRunData({...runData, year: parseInt(e.target.value)})}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                />
              </div>
              
              {/* Validation Check Button */}
              {runData.month && runData.year && (
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                  <button
                    type="button"
                    onClick={async () => {
                      try {
                        const validation = await checkPayrollValidation(runData.month, runData.year);
                        setValidationResult(validation);
                        setValidationChecked(true);
                      } catch (error) {
                        alert('🔴 Validation check failed. Please try again.');
                      }
                    }}
                    className="w-full px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm"
                  >
                    🔍 Check Validation First
                  </button>
                  <p className="text-xs text-blue-600 mt-1 text-center">
                    Recommended: Check for issues before running payroll
                  </p>
                </div>
              )}
              
              {/* Validation Results */}
              {validationChecked && validationResult && (
                <div className="mt-4">
                  {validationResult.can_run_payroll ? (
                    <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                      <div className="flex items-center">
                        <span className="text-green-600 text-xl mr-2">✅</span>
                        <div>
                          <h4 className="font-medium text-green-800">Validation Passed!</h4>
                          <p className="text-sm text-green-700">No critical issues found. You can run payroll safely.</p>
                        </div>
                      </div>
                    </div>
                  ) : (
                    <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                      <div className="flex items-start">
                        <span className="text-red-600 text-xl mr-2">❌</span>
                        <div className="flex-1">
                          <h4 className="font-medium text-red-800">Cannot Run Payroll</h4>
                          <p className="text-sm text-red-700 mb-3">
                            Found {validationResult.critical_issues} critical issues that must be resolved.
                          </p>
                          
                          {/* Critical Issues Only */}
                          <div className="space-y-2">
                            {validationResult.issues
                              .filter(issue => issue.severity === 'critical')
                              .map((issue, index) => (
                              <div key={index} className="bg-white border border-red-200 rounded p-2 text-xs">
                                <div className="font-medium text-red-800">
                                  {issue.employee_name} ({issue.employee_id})
                                </div>
                                <div className="text-red-700">
                                  <strong>{issue.issue_type}:</strong> {issue.issue_description}
                                </div>
                              </div>
                            ))}
                          </div>
                          
                          {/* Show warning count if any - only if critical issues exist */}
                          {validationResult.critical_issues > 0 && validationResult.warning_issues > 0 && (
                            <div className="mt-2 p-2 bg-yellow-50 border border-yellow-200 rounded text-xs">
                              <div className="text-yellow-700">
                                <strong>Note:</strong> {validationResult.warning_issues} absent days (LOP deductions)
                              </div>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              )}
              
              {/* Validation Scenarios Info */}
              <div className="bg-gray-50 border border-gray-200 rounded-lg p-3">
                <h5 className="font-medium text-gray-800 mb-2">📋 Checks:</h5>
                <div className="text-xs text-gray-600 space-y-1">
                  <div>• Pending approvals • Missing punches • Absent days</div>
                </div>
              </div>
              <div className="flex gap-4 pt-4">
                <button
                  type="button"
                  onClick={() => setShowRunModal(false)}
                  className="flex-1 px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading || (validationChecked && validationResult && !validationResult.can_run_payroll)}
                  className={`flex-1 px-4 py-2 rounded-lg ${
                    loading || (validationChecked && validationResult && !validationResult.can_run_payroll)
                      ? 'bg-gray-400 cursor-not-allowed' 
                      : 'bg-green-600 hover:bg-green-700'
                  } text-white`}
                >
                  {loading ? "Processing..." : "Run Payroll"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
