import { useEffect, useState } from "react";
import { FileText, Download, Send, Search, Eye, Calendar, Printer } from "lucide-react";
import api from "../../api";
import Toast from "../../components/Toast";
import useToast from "../../utils/useToast";
import { hasPermission, isAdmin } from "../../utils/permissions";

export default function Payslips() {
  const [colors, setColors] = useState({ primary: '#2862e9', secondary: '#474e71' });
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedMonth, setSelectedMonth] = useState("");
  const [payslips, setPayslips] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [payrollRuns, setPayrollRuns] = useState([]);
  const [loading, setLoading] = useState(false);
  const [selectedPayslip, setSelectedPayslip] = useState(null);
  const [showViewModal, setShowViewModal] = useState(false);
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [showEmailConfirmModal, setShowEmailConfirmModal] = useState(false);
  const [emailForm, setEmailForm] = useState({ email: '', payslip: null });
  const { toast, showToast, hideToast } = useToast();

  // Permission checks
  const canView = isAdmin() || hasPermission("view_salary_slips") || hasPermission("view_self");
  const canGenerate = isAdmin() || hasPermission("generate_salary_slips");
  const canDownload = isAdmin() || hasPermission("download_salary_slips") || hasPermission("view_self");
  const canEmail = isAdmin() || hasPermission("email_salary_slips");

  const fetchColors = async () => {
    try {
      const tenantCode = localStorage.getItem('tenantCode');
      if (tenantCode) {
        const res = await api.get(`/auth/branding/${tenantCode}`);
        setColors({
          primary: res.data.primary_color || '#2862e9',
          secondary: res.data.secondary_color || '#474e71'
        });
      }
    } catch (err) {
      console.error('Failed to fetch colors:', err);
    }
  };

  if (!canView) {
    return (
      <div className="p-6 text-center">
        <div className="bg-white rounded-2xl border border-gray-200 p-8 max-w-md mx-auto">
          <h3 className="text-lg font-medium text-gray-900 mb-2">Access Denied</h3>
          <p className="text-gray-600">You do not have permission to view salary slips.</p>
        </div>
      </div>
    );
  }

  const months = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];

  useEffect(() => {
    fetchEmployees();
    fetchPayrollRuns();
    fetchColors();
  }, []);

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      // Fetch employees from EIS system
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`${api.defaults.baseURL}/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process employees same as EIS
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        email: emp.candidate_email || 'N/A',
        designation: emp.job_title,
        department: emp.department,
        employee_code: emp.employee_id,
        status: 'Active'
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          email: user.email,
          designation: user.designation || 'N/A',
          department: user.department_name,
          employee_code: user.employee_code,
          status: user.status || 'Active'
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
      showToast("Failed to load employees", "error");
      setEmployees([]);
    }
  };

  const fetchPayrollRuns = async () => {
    try {
      setLoading(true);
      const res = await api.get("/api/payroll/runs");
      setPayrollRuns(res.data || []);
      
      // Get adjustments to calculate final net salary
      const adjRes = await api.get(`/api/payroll/adjustments`);
      const adjustments = adjRes.data || [];
      
      // Convert payroll runs to payslips format with adjusted net salary
      const generatedPayslips = (res.data || []).map(run => {
        // Find adjustments for this employee and month
        const empAdjustments = adjustments.filter(adj => 
          adj.employee_id == run.employee_id && 
          adj.month === run.month && 
          adj.status === 'Active'
        );
        
        // Calculate adjustment totals
        const additions = empAdjustments.filter(adj => adj.adjustment_type !== 'Deduction')
          .reduce((sum, adj) => sum + (adj.amount || 0), 0);
        const deductions = empAdjustments.filter(adj => adj.adjustment_type === 'Deduction')
          .reduce((sum, adj) => sum + (adj.amount || 0), 0);
        
        // Calculate final net salary with adjustments
        const finalNetSalary = (run.net_salary || 0) + additions - deductions;
        
        return {
          id: run.id,
          employee_id: run.employee_id,
          employee_name: run.employee_name || getEmployeeName(run.employee_id),
          employee_code: run.employee_code || getEmployeeCode(run.employee_id),
          month: run.month,
          year: run.year || new Date().getFullYear(),
          gross_salary: run.gross_salary,
          net_salary: finalNetSalary, // Use adjusted net salary
          status: run.status === 'Completed' ? 'Generated' : 'Pending',
          generated_at: run.created_at
        };
      });
      
      // Remove duplicates based on employee_id and month
      const uniquePayslips = generatedPayslips.filter((payslip, index, self) => 
        index === self.findIndex(p => 
          p.employee_id === payslip.employee_id && 
          p.month === payslip.month && 
          p.year === payslip.year
        )
      );
      
      setPayslips(uniquePayslips);
    } catch (error) {
      console.error("Error fetching payroll runs:", error);
      showToast("Failed to load payslips", "error");
      setPayrollRuns([]);
      setPayslips([]);
    } finally {
      setLoading(false);
    }
  };

  const getEmployeeName = (employeeId) => {
    const employee = employees.find(emp => emp.id === employeeId);
    return employee ? employee.name : `Employee #${employeeId}`;
  };

  const getEmployeeCode = (employeeId) => {
    const employee = employees.find(emp => emp.id === employeeId);
    return employee ? employee.employee_code || employeeId : employeeId;
  };

  const handleGeneratePayslips = async () => {
    if (!canGenerate) {
      showToast("You do not have permission to generate payslips", "error");
      return;
    }
    try {
      setLoading(true);
      // Generate payslips for completed payroll runs
      const completedRuns = payrollRuns.filter(run => run.status === 'Completed');
      
      if (completedRuns.length === 0) {
        showToast('No completed payroll runs found. Please run payroll first.', 'error');
        return;
      }
      
      // In a real implementation, this would call a payslip generation API
      showToast(`Generated ${completedRuns.length} payslips successfully!`, "success");
      await fetchPayrollRuns();
    } catch (error) {
      console.error("Error generating payslips:", error);
      showToast('Failed to generate payslips. Please try again.', 'error');
    } finally {
      setLoading(false);
    }
  };

  const handleSendEmail = async () => {
    if (!canEmail) {
      showToast("You do not have permission to email payslips", "error");
      return;
    }
    try {
      setLoading(true);
      const generatedPayslips = payslips.filter(p => p.status === 'Generated');
      
      if (generatedPayslips.length === 0) {
        showToast('No generated payslips found to send.', 'error');
        return;
      }
      
      const payslipIds = generatedPayslips.map(p => p.id);
      const res = await api.post('/api/payroll/payslips/send-bulk-email', {
        payslip_ids: payslipIds
      });
      
      if (res.data.success_count > 0) {
        showToast(`Email sending completed. Sent: ${res.data.success_count}, Failed: ${res.data.failed_count}`, "success");
        
        // Update status to 'Sent' for successful sends
        const updatedPayslips = payslips.map(p => 
          p.status === 'Generated' ? {...p, status: 'Sent'} : p
        );
        setPayslips(updatedPayslips);
      } else {
        showToast('No emails were sent. Please check employee email addresses.', 'error');
      }
    } catch (error) {
      console.error("Error sending payslips:", error);
      showToast('Failed to send payslips. Please check your email configuration.', 'error');
    } finally {
      setLoading(false);
    }
  };

  const handleViewPayslip = async (payslip) => {
    try {
      // Get full payroll run data
      const fullPayrollData = payrollRuns.find(run => run.id === payslip.id);
      
      // Get adjustments for this employee and month
      const adjRes = await api.get(`/api/payroll/adjustments`);
      const adjustments = adjRes.data.filter(adj => 
        adj.employee_id == payslip.employee_id && 
        adj.month === payslip.month
      );
      
      // Calculate adjustment totals
      const additions = adjustments.filter(adj => adj.adjustment_type !== 'Deduction')
        .reduce((sum, adj) => sum + (adj.amount || 0), 0);
      const deductions = adjustments.filter(adj => adj.adjustment_type === 'Deduction')
        .reduce((sum, adj) => sum + (adj.amount || 0), 0);
      
      // Use the stored calculations from payroll run
      const totalEarnings = (fullPayrollData?.gross_salary || 0) + additions;
      const pfDeduction = (fullPayrollData?.basic_salary || 0) * 0.12;
      const esiDeduction = (fullPayrollData?.gross_salary || 0) * 0.0175;
      const totalDeductions = (fullPayrollData?.lop_deduction || 0) + pfDeduction + esiDeduction + deductions;
      
      // Use the net salary from database which already accounts for adjustments
      const finalNetSalary = (fullPayrollData?.net_salary || 0) + additions - deductions;
      
      setSelectedPayslip({
        ...payslip,
        ...fullPayrollData,
        adjustments,
        totalEarnings,
        totalDeductions,
        finalNetSalary,
        pfDeduction,
        esiDeduction
      });
      setShowViewModal(true);
    } catch (error) {
      console.error('Error fetching payslip details:', error);
      showToast(`Error loading payslip details`, 'error');
    }
  };

  const handleDownloadPayslip = async (payslip) => {
    if (!canDownload) {
      showToast("You do not have permission to download payslips", "error");
      return;
    }
    try {
      const token = localStorage.getItem('access_token');
      const response = await fetch(`${api.defaults.baseURL}/api/payroll/payslips/payslip/${payslip.id}/download`, {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });
      
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `payslip_${payslip.employee_name}_${payslip.month}_${payslip.year}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      
    } catch (error) {
      console.error('Download error:', error);
      showToast(`Error downloading payslip for ${payslip.employee_name}`, 'error');
    }
  };

  const handlePrintPayslip = async (payslip) => {
    if (!canDownload) {
      showToast("You do not have permission to print payslips", "error");
      return;
    }
    try {
      const token = localStorage.getItem('access_token');
      const response = await fetch(`${api.defaults.baseURL}/api/payroll/payslips/payslip/${payslip.id}/download`, {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });
      
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      
      // Open PDF in new window for printing
      const printWindow = window.open(url, '_blank');
      if (printWindow) {
        printWindow.onload = () => {
          printWindow.print();
        };
      }
      
      // Clean up
      setTimeout(() => {
        window.URL.revokeObjectURL(url);
      }, 1000);
      
    } catch (error) {
      console.error('Print error:', error);
      showToast(`Error printing payslip for ${payslip.employee_name}`, 'error');
    }
  };

  const handleSendIndividual = async (payslip) => {
    if (!canEmail) {
      showToast("You do not have permission to email payslips", "error");
      return;
    }
    try {
      // Find employee by employee_id first
      let employee = employees.find(emp => 
        emp.id === payslip.employee_id || 
        emp.original_user_id === payslip.employee_id ||
        emp.id == payslip.employee_id ||
        emp.original_user_id == payslip.employee_id
      );
      
      // If not found by ID, try to find by employee code from payslip
      if (!employee && payslip.employee_code) {
        employee = employees.find(emp => emp.employee_code === payslip.employee_code);
      }
      
      let defaultEmail = '';
      if (employee?.email) {
        defaultEmail = employee.email;
        console.log(`Found email for employee code ${payslip.employee_code}: ${defaultEmail}`);
      } else {
        console.log(`No email found for employee code ${payslip.employee_code}`);
      }
      
      setEmailForm({ email: defaultEmail, payslip });
      setShowEmailModal(true);
    } catch (error) {
      console.error('Error preparing email:', error);
      setEmailForm({ email: '', payslip });
      setShowEmailModal(true);
    }
  };

  const filteredPayslips = payslips.filter(payslip => {
    const matchesSearch = payslip.employee_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         payslip.employee_id?.toString().includes(searchTerm);
    const matchesMonth = !selectedMonth || payslip.month === selectedMonth;
    return matchesSearch && matchesMonth;
  });

  return (
    <div className="bg-white rounded-2xl border border-black overflow-hidden">
      {/* Header */}
      <div className="p-6 border-b border-black">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gray-100 rounded-xl flex items-center justify-center">
            <FileText className="w-5 h-5 text-gray-600" />
          </div>
          <div>
            <h2 className="text-lg font-medium text-gray-900">Salary Slips & Payment</h2>
            <p className="text-sm text-gray-600">Generate payslips and manage bank payments</p>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="p-6">
        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-3 mb-6">
          {canGenerate && (
            <button 
              onClick={handleGeneratePayslips}
              disabled={loading}
              onMouseEnter={(e) => e.target.style.backgroundColor = colors.secondary}
              onMouseLeave={(e) => e.target.style.backgroundColor = colors.primary}
              className="px-6 py-3 rounded-xl flex items-center gap-2 transition-colors text-sm font-medium border border-black justify-center text-white disabled:opacity-50 disabled:cursor-not-allowed"
              style={{ backgroundColor: colors.primary }}
            >
              <FileText size={18} />
              {loading ? "Generating..." : "Generate Payslips"}
            </button>
          )}
          {canEmail && (
            <button 
              onClick={handleSendEmail}
              disabled={loading}
              onMouseEnter={(e) => e.target.style.backgroundColor = colors.secondary}
              onMouseLeave={(e) => e.target.style.backgroundColor = colors.primary}
              className="px-6 py-3 rounded-xl flex items-center gap-2 transition-colors text-sm font-medium border border-black justify-center text-white disabled:opacity-50 disabled:cursor-not-allowed"
              style={{ backgroundColor: colors.primary }}
            >
              <Send size={18} />
              {loading ? "Sending..." : "Send via Email"}
            </button>
          )}
        </div>
        {/* Filters */}
        <div className="mb-6">
          <div className="flex flex-col sm:flex-row gap-4">
            <div className="relative flex-1 max-w-md">
              <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400" size={18} />
              <input
                type="text"
                placeholder="Search by employee name or ID..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-12 pr-4 py-3 border border-black rounded-xl focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent w-full text-sm"
              />
            </div>
            <select
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(e.target.value)}
              className="border border-black rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent text-sm w-full sm:w-auto"
            >
              <option value="">All Months</option>
              {months.map(month => (
                <option key={month} value={month}>{month}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="mb-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <div className="bg-gray-50 rounded-xl p-6 border border-black">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-600 text-sm font-medium">Total Payslips</p>
                  <p className="text-3xl font-bold text-gray-900">{payslips.length}</p>
                </div>
                <div className="p-3 bg-gray-100 rounded-xl">
                  <FileText className="h-10 w-10 text-gray-600" />
                </div>
              </div>
            </div>
            <div className="bg-gray-50 rounded-xl p-6 border border-black">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-600 text-sm font-medium">Sent</p>
                  <p className="text-3xl font-bold text-gray-900">{payslips.filter(p => p.status === 'Sent').length}</p>
                </div>
                <div className="p-3 bg-gray-100 rounded-xl">
                  <Send className="h-10 w-10 text-gray-600" />
                </div>
              </div>
            </div>
            <div className="bg-gray-50 rounded-xl p-6 border border-black">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-600 text-sm font-medium">Generated</p>
                  <p className="text-3xl font-bold text-gray-900">{payslips.filter(p => p.status === 'Generated').length}</p>
                </div>
                <div className="p-3 bg-gray-100 rounded-xl">
                  <Calendar className="h-10 w-10 text-gray-600" />
                </div>
              </div>
            </div>
            <div className="bg-gray-50 rounded-xl p-6 border border-black">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-600 text-sm font-medium">Pending</p>
                  <p className="text-3xl font-bold text-gray-900">{payslips.filter(p => p.status === 'Pending').length}</p>
                </div>
                <div className="p-3 bg-gray-100 rounded-xl">
                  <Download className="h-10 w-10 text-gray-600" />
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Table */}
        <div className="bg-white rounded-2xl border border-black overflow-hidden">
          {/* Desktop Table View */}
          <div className="hidden md:block overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-100 border-b border-black">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Employee</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Month</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Gross Salary</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Net Salary</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                  {loading ? (
                    <tr>
                      <td colSpan="6" className="px-6 py-8 text-center">
                        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
                      </td>
                    </tr>
                  ) : filteredPayslips.length === 0 ? (
                    <tr>
                      <td colSpan="6" className="px-6 py-12 text-center">
                        <FileText className="mx-auto h-12 w-12 text-gray-400" />
                        <h3 className="mt-2 text-sm font-medium text-gray-900">No payslips found</h3>
                        <p className="mt-1 text-sm text-gray-500">
                          {searchTerm || selectedMonth ? "No payslips match your search criteria." : "Generate payslips for employees to view them here."}
                        </p>
                        {!searchTerm && !selectedMonth && canGenerate && (
                          <div className="mt-6">
                            <button 
                              onClick={handleGeneratePayslips}
                              onMouseEnter={(e) => e.target.style.backgroundColor = colors.secondary}
                              onMouseLeave={(e) => e.target.style.backgroundColor = colors.primary}
                              className="text-white px-4 py-2 rounded-lg flex items-center gap-2 mx-auto transition-colors border border-black"
                              style={{ backgroundColor: colors.primary }}
                            >
                              <FileText size={16} />
                              Generate First Payslip
                            </button>
                          </div>
                        )}
                      </td>
                    </tr>
                  ) : (
                    filteredPayslips.map((payslip) => (
                      <tr key={payslip.id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm font-medium text-gray-900">{payslip.employee_name}</div>
                          <div className="text-sm text-gray-500">Code: {payslip.employee_code}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{payslip.month} {payslip.year}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">₹{payslip.gross_salary?.toLocaleString() || 0}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm font-medium text-gray-900">₹{payslip.net_salary?.toLocaleString() || 0}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800 border border-gray-300">
                            {payslip.status}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                          <div className="flex items-center gap-2">
                            <button 
                              onClick={() => handleViewPayslip(payslip)}
                              className="text-gray-600 hover:text-gray-900 p-1 rounded border border-gray-300 hover:border-gray-400"
                              title="View Payslip"
                            >
                              <Eye size={16} />
                            </button>
                            {canDownload && (
                              <button 
                                onClick={() => handleDownloadPayslip(payslip)}
                                className="text-gray-600 hover:text-gray-900 p-1 rounded border border-gray-300 hover:border-gray-400"
                                title="Download Payslip"
                              >
                                <Download size={16} />
                              </button>
                            )}
                            {canDownload && (
                              <button 
                                onClick={() => handlePrintPayslip(payslip)}
                                className="text-gray-600 hover:text-gray-900 p-1 rounded border border-gray-300 hover:border-gray-400"
                                title="Print Payslip"
                              >
                                <Printer size={16} />
                              </button>
                            )}
                            {canEmail && (
                              <button 
                                onClick={() => handleSendIndividual(payslip)}
                                className="text-gray-600 hover:text-gray-900 p-1 rounded border border-gray-300 hover:border-gray-400"
                                title="Send via Email"
                              >
                                <Send size={16} />
                              </button>
                            )}
                          </div>
                        </td>
                      </tr>
                    ))
                  )}
              </tbody>
            </table>
          </div>

          {/* Mobile Card View */}
          <div className="md:hidden">
            {loading ? (
              <div className="p-6 text-center">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
              </div>
            ) : filteredPayslips.length === 0 ? (
              <div className="p-6 text-center">
                <FileText className="mx-auto h-12 w-12 text-gray-400" />
                <h3 className="mt-2 text-sm font-medium text-gray-900">No payslips found</h3>
                <p className="mt-1 text-sm text-gray-500">
                  {searchTerm || selectedMonth ? "No payslips match your search criteria." : "Generate payslips for employees to view them here."}
                </p>
                {!searchTerm && !selectedMonth && canGenerate && (
                  <div className="mt-6">
                    <button 
                      onClick={handleGeneratePayslips}
                      onMouseEnter={(e) => e.target.style.backgroundColor = colors.secondary}
                      onMouseLeave={(e) => e.target.style.backgroundColor = colors.primary}
                      className="text-white px-4 py-2 rounded-lg flex items-center gap-2 mx-auto transition-colors border border-black"
                      style={{ backgroundColor: colors.primary }}
                    >
                      <FileText size={16} />
                      Generate First Payslip
                    </button>
                  </div>
                )}
              </div>
            ) : (
              filteredPayslips.map((payslip) => (
                <div key={payslip.id} className="p-4 border-b border-gray-200 hover:bg-gray-50">
                  <div className="flex items-center justify-between mb-3">
                    <div>
                      <div className="text-sm font-medium text-gray-900">{payslip.employee_name}</div>
                      <div className="text-sm text-gray-500">Code: {payslip.employee_code}</div>
                    </div>
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800 border border-gray-300">
                      {payslip.status}
                    </span>
                  </div>
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <span className="text-sm font-medium text-gray-900">Month:</span>
                      <span className="text-sm text-gray-600">{payslip.month} {payslip.year}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-sm font-medium text-gray-900">Gross Salary:</span>
                      <span className="text-sm text-gray-600">₹{payslip.gross_salary?.toLocaleString() || 0}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-sm font-medium text-gray-900">Net Salary:</span>
                      <span className="text-sm font-medium text-gray-900">₹{payslip.net_salary?.toLocaleString() || 0}</span>
                    </div>
                  </div>
                  <div className="flex items-center justify-end gap-2 mt-3 pt-3 border-t border-gray-100">
                    <button 
                      onClick={() => handleViewPayslip(payslip)}
                      className="flex items-center gap-1 text-gray-600 hover:text-gray-900 px-3 py-1 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                    >
                      <Eye size={14} />
                      View
                    </button>
                    {canDownload && (
                      <button 
                        onClick={() => handleDownloadPayslip(payslip)}
                        className="flex items-center gap-1 text-gray-600 hover:text-gray-900 px-3 py-1 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                      >
                        <Download size={14} />
                        Download
                      </button>
                    )}
                    {canDownload && (
                      <button 
                        onClick={() => handlePrintPayslip(payslip)}
                        className="flex items-center gap-1 text-gray-600 hover:text-gray-900 px-3 py-1 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                      >
                        <Printer size={14} />
                        Print
                      </button>
                    )}
                    {canEmail && (
                      <button 
                        onClick={() => handleSendIndividual(payslip)}
                        className="flex items-center gap-1 text-gray-600 hover:text-gray-900 px-3 py-1 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                      >
                        <Send size={14} />
                        Email
                      </button>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-gray-50 border border-black border-t-0 rounded-b-2xl mt-6">
          <div className="flex justify-between items-center text-sm text-gray-600">
            <span>Total Payslips: {payslips.length}</span>
            <span>Generated: {payslips.filter(p => p.status === 'Generated').length}</span>
            <span>Sent: {payslips.filter(p => p.status === 'Sent').length}</span>
          </div>
        </div>

        {/* Email Modal */}
        {showEmailModal && emailForm.payslip && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-lg p-6 w-full max-w-md">
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-lg font-semibold">Send Payslip via Email</h3>
                <button 
                  onClick={() => setShowEmailModal(false)}
                  className="text-gray-500 hover:text-gray-700"
                >
                  ✕
                </button>
              </div>
              
              <div className="mb-4">
                <p className="text-sm text-gray-600 mb-2">
                  Sending payslip for: <strong>{emailForm.payslip.employee_name}</strong>
                </p>
                <p className="text-sm text-gray-600">
                  Month: <strong>{emailForm.payslip.month} {emailForm.payslip.year}</strong>
                </p>
              </div>
              
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-2">Email Address</label>
                <input
                  type="email"
                  value={emailForm.email}
                  onChange={(e) => setEmailForm({...emailForm, email: e.target.value})}
                  className="w-full border border-black rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-gray-500"
                  placeholder="Enter email address"
                  required
                />
              </div>
              
              <div className="flex gap-4">
                <button
                  onClick={() => setShowEmailModal(false)}
                  className="flex-1 px-4 py-2 border border-black rounded-xl text-gray-600 hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  onClick={async () => {
                    if (!emailForm.email) {
                      showToast('Please enter an email address', 'error');
                      return;
                    }
                    try {
                      setLoading(true);
                      await api.post('/api/payroll/payslips/send-email', {
                        payslip_id: emailForm.payslip.id,
                        email: emailForm.email
                      });
                      showToast(`Payslip sent successfully to ${emailForm.email}`, "success");
                      setShowEmailModal(false);
                    } catch (error) {
                      console.error('Email sending error:', error);
                      showToast('Failed to send email. Please try again.', 'error');
                    } finally {
                      setLoading(false);
                    }
                  }}
                  disabled={loading}
                  onMouseEnter={(e) => e.target.style.backgroundColor = colors.secondary}
                  onMouseLeave={(e) => e.target.style.backgroundColor = colors.primary}
                  className="flex-1 text-white px-4 py-2 rounded-xl disabled:opacity-50"
                  style={{ backgroundColor: colors.primary }}
                >
                  {loading ? 'Sending...' : 'Send Email'}
                </button>
              </div>
            </div>
          </div>
        )}
        {showViewModal && selectedPayslip && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-lg p-4 sm:p-6 w-full max-w-4xl max-h-[90vh] overflow-y-auto">
              <div className="flex justify-between items-center mb-6">
                <h3 className="text-lg font-semibold">Payslip Details - {selectedPayslip.employee_name}</h3>
                <button 
                  onClick={() => setShowViewModal(false)}
                  className="text-gray-500 hover:text-gray-700"
                >
                  ✕
                </button>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Employee Info */}
                <div className="bg-gray-50 rounded-lg p-4">
                  <h4 className="font-medium text-gray-900 mb-3">Employee Information</h4>
                  <div className="space-y-2 text-sm">
                    <div><span className="text-gray-600">Name:</span> <span className="ml-2 font-medium">{selectedPayslip.employee_name}</span></div>
                    <div><span className="text-gray-600">Code:</span> <span className="ml-2 font-medium">{selectedPayslip.employee_code}</span></div>
                    <div><span className="text-gray-600">Month:</span> <span className="ml-2 font-medium">{selectedPayslip.month} {selectedPayslip.year}</span></div>
                  </div>
                </div>

                {/* Attendance */}
                <div className="bg-gray-50 rounded-lg p-4">
                  <h4 className="font-medium text-gray-900 mb-3">Attendance Summary</h4>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 text-sm">
                    <div className="text-center">
                      <div className="text-xl font-bold text-blue-600">{selectedPayslip.present_days}</div>
                      <div className="text-gray-600">Present</div>
                    </div>
                    <div className="text-center">
                      <div className="text-xl font-bold text-green-600">{selectedPayslip.leave_days}</div>
                      <div className="text-gray-600">Leave</div>
                    </div>
                    <div className="text-center">
                      <div className="text-xl font-bold text-red-600">{selectedPayslip.lop_days}</div>
                      <div className="text-gray-600">LOP</div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
                {/* Earnings */}
                <div className="bg-green-50 rounded-lg p-4">
                  <h4 className="font-medium text-gray-900 mb-3">Earnings</h4>
                  <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span>Basic Salary</span>
                      <span>₹{selectedPayslip.basic_salary?.toLocaleString()}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>HRA</span>
                      <span>₹{selectedPayslip.hra_salary?.toLocaleString()}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Allowances</span>
                      <span>₹{selectedPayslip.allowances?.toLocaleString()}</span>
                    </div>
                    {selectedPayslip.adjustments?.filter(adj => adj.adjustment_type !== 'Deduction').map((adj, idx) => (
                      <div key={idx} className="flex justify-between text-green-600">
                        <span>{adj.adjustment_type} - {adj.description}</span>
                        <span>+₹{adj.amount?.toLocaleString()}</span>
                      </div>
                    ))}
                    <div className="flex justify-between font-bold border-t pt-2">
                      <span>Total Earnings</span>
                      <span className="text-green-600">₹{selectedPayslip.totalEarnings?.toLocaleString()}</span>
                    </div>
                  </div>
                </div>

                {/* Deductions */}
                <div className="bg-red-50 rounded-lg p-4">
                  <h4 className="font-medium text-gray-900 mb-3">Deductions</h4>
                  <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span>LOP Deduction</span>
                      <span>₹{selectedPayslip.lop_deduction?.toLocaleString()}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>PF (12%)</span>
                      <span>₹{selectedPayslip.pfDeduction?.toLocaleString()}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>ESI (1.75%)</span>
                      <span>₹{selectedPayslip.esiDeduction?.toLocaleString()}</span>
                    </div>
                    {selectedPayslip.adjustments?.filter(adj => adj.adjustment_type === 'Deduction').map((adj, idx) => (
                      <div key={idx} className="flex justify-between text-red-600">
                        <span>{adj.adjustment_type} - {adj.description}</span>
                        <span>-₹{adj.amount?.toLocaleString()}</span>
                      </div>
                    ))}
                    <div className="flex justify-between font-bold border-t pt-2">
                      <span>Total Deductions</span>
                      <span className="text-red-600">₹{selectedPayslip.totalDeductions?.toLocaleString()}</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Net Salary */}
              <div className="mt-6 text-center">
                <div className="bg-green-50 border-2 border-green-500 rounded-lg p-4 inline-block">
                  <h3 className="text-lg font-bold text-green-700">NET SALARY: ₹{selectedPayslip.finalNetSalary?.toLocaleString()}</h3>
                </div>
              </div>

              <div className="flex gap-4 mt-6">
                <button
                  onClick={() => handleDownloadPayslip(selectedPayslip)}
                  onMouseEnter={(e) => e.target.style.backgroundColor = colors.secondary}
                  onMouseLeave={(e) => e.target.style.backgroundColor = colors.primary}
                  className="flex-1 px-4 py-2 text-white rounded-lg flex items-center justify-center gap-2"
                  style={{ backgroundColor: colors.primary }}
                >
                  <Download size={16} />
                  Download Payslip
                </button>
                <button
                  onClick={() => setShowViewModal(false)}
                  className="px-4 py-2 border border-gray-200 rounded-lg text-gray-600 hover:bg-gray-50"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}