import { useEffect, useState } from "react";
import { Plus, Search, Edit, Trash2, Eye, Users, Link } from "lucide-react";
import api from "../../api";

export default function SalaryStructure() {
  const [structures, setStructures] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [grades, setGrades] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [showModal, setShowModal] = useState(false);
  const [showLinkModal, setShowLinkModal] = useState(false);
  const [editingStructure, setEditingStructure] = useState(null);
  const [linkingStructure, setLinkingStructure] = useState(null);
  const [selectedEmployees, setSelectedEmployees] = useState([]);
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    name: "",
    ctc: 0,
    basic_percent: 40,
    hra_percent: 20,
    allowances: "",
    deductions: "",
    is_active: true
  });

  useEffect(() => {
    fetchStructures();
    fetchEmployees();
  }, []);

  const fetchStructures = async () => {
    try {
      setLoading(true);
      const res = await api.get("/api/payroll/salary-structures");
      setStructures(res.data || []);
    } catch (error) {
      console.error("Error fetching salary structures:", error);
      setStructures([]);
    } finally {
      setLoading(false);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      // Use the exact same logic as EIS system
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees (same as EIS)
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        email: emp.candidate_email || 'N/A',
        designation: emp.job_title,
        department: emp.department,
        employee_code: emp.employee_id,
        joining_date: emp.joining_date,
        source: 'onboarding'
      }));
      
      // Process user management employees (same as EIS)
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          email: user.email,
          designation: user.designation || 'N/A',
          department: user.department_name,
          employee_code: user.employee_code,
          joining_date: user.joining_date,
          source: 'user_management'
        }));
      
      // Combine and remove duplicates (same as EIS)
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      console.log('All employees for payroll:', allEmployees);
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
      setEmployees([]);
    }
  };



  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      setLoading(true);
      const payload = {
        ...formData,
        allowances: formData.allowances || "",
        deductions: formData.deductions || ""
      };
      
      if (editingStructure) {
        await api.put(`/api/payroll/salary-structures/${editingStructure.id}`, payload);
      } else {
        await api.post("/api/payroll/salary-structures", payload);
      }
      await fetchStructures();
      handleCloseModal();
    } catch (error) {
      console.error("Error saving salary structure:", error);
      alert("Failed to save salary structure. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm("Are you sure you want to delete this salary structure?")) {
      try {
        await api.delete(`/api/payroll/salary-structures/${id}`);
        fetchStructures();
      } catch (error) {
        console.error("Error deleting salary structure:", error);
      }
    }
  };

  const handleOpenModal = (structure = null) => {
    if (structure) {
      setEditingStructure(structure);
      setFormData({
        name: structure.name || "",
        ctc: structure.ctc || 0,
        basic_percent: structure.basic_percent || 40,
        hra_percent: structure.hra_percent || 20,
        allowances: structure.allowances || "",
        deductions: structure.deductions || "",
        is_active: structure.is_active ?? true
      });
    } else {
      setEditingStructure(null);
      setFormData({
        name: "",
        ctc: 0,
        basic_percent: 40,
        hra_percent: 20,
        allowances: "",
        deductions: "",
        is_active: true
      });
    }
    setShowModal(true);
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setEditingStructure(null);
  };

  const handleOpenLinkModal = (structure) => {
    setLinkingStructure(structure);
    // Get currently linked employees from localStorage
    const existingLinks = JSON.parse(localStorage.getItem('employee_salary_links') || '{}');
    const linkedEmployeeIds = existingLinks[structure.id] || [];
    setSelectedEmployees(linkedEmployeeIds);
    setShowLinkModal(true);
  };

  const handleCloseLinkModal = () => {
    setShowLinkModal(false);
    setLinkingStructure(null);
    setSelectedEmployees([]);
  };

  const handleLinkEmployees = async () => {
    try {
      setLoading(true);
      
      // For now, store the linking in localStorage until backend endpoint is ready
      const existingLinks = JSON.parse(localStorage.getItem('employee_salary_links') || '{}');
      
      // Remove employees from other structures first
      Object.keys(existingLinks).forEach(structureId => {
        if (structureId !== linkingStructure.id.toString()) {
          existingLinks[structureId] = existingLinks[structureId]?.filter(empId => 
            !selectedEmployees.includes(empId)
          ) || [];
        }
      });
      
      // Add employees to current structure
      existingLinks[linkingStructure.id] = selectedEmployees;
      
      localStorage.setItem('employee_salary_links', JSON.stringify(existingLinks));
      
      alert(`Successfully linked ${selectedEmployees.length} employee(s) to ${linkingStructure.name}`);
      await fetchEmployees();
      handleCloseLinkModal();
    } catch (error) {
      console.error("Error linking employees:", error);
      alert("Failed to link employees. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const toggleEmployeeSelection = (employeeId) => {
    setSelectedEmployees(prev => 
      prev.includes(employeeId) 
        ? prev.filter(id => id !== employeeId)
        : [...prev, employeeId]
    );
  };

  const handleViewStructure = (structure) => {
    alert(`Structure Details:\n\nName: ${structure.name}\nAnnual CTC: ₹${structure.ctc?.toLocaleString()}\nMonthly: ₹${((structure.ctc || 0) / 12).toLocaleString()}\nBasic: ${structure.basic_percent}%\nHRA: ${structure.hra_percent}%\nStatus: ${structure.is_active ? 'Active' : 'Inactive'}`);
  };

  const filteredStructures = structures.filter(structure =>
    structure.name?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="bg-white rounded-lg shadow-sm">
      {/* Header */}
      <div className="p-6 border-b border-gray-200">
        <div className="flex justify-between items-center">
          <div>
            <h2 className="text-xl font-semibold text-gray-900">Salary Structure</h2>
            <p className="text-gray-600 mt-1">Define CTC structure, earnings and deductions</p>
          </div>
          <button 
            onClick={() => handleOpenModal()}
            className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
          >
            <Plus size={16} />
            Add Salary Structure
          </button>
        </div>
      </div>

      {/* Search */}
      <div className="p-6 border-b border-gray-200">
        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={16} />
          <input
            type="text"
            placeholder="Search salary structures..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent w-full"
          />
        </div>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        {loading ? (
          <div className="flex justify-center items-center py-8">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
          </div>
        ) : (
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Structure Name</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Annual CTC</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Basic %</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">HRA %</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Employees</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {filteredStructures.length === 0 ? (
                <tr>
                  <td colSpan="7" className="px-6 py-8 text-center text-gray-500">
                    {searchTerm ? "No salary structures found matching your search." : "No salary structures configured yet."}
                  </td>
                </tr>
              ) : (
                filteredStructures.map((structure) => {
                  // Get linked employees from localStorage
                  const existingLinks = JSON.parse(localStorage.getItem('employee_salary_links') || '{}');
                  const linkedEmployeeIds = existingLinks[structure.id] || [];
                  const employeeCount = linkedEmployeeIds.length;
                  
                  return (
                    <tr key={structure.id} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-medium text-gray-900">{structure.name}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">₹{structure.ctc?.toLocaleString()}/year</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">{structure.basic_percent}%</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">{structure.hra_percent}%</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">{employeeCount} employees</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                          structure.is_active ? "bg-green-100 text-green-800" : "bg-gray-100 text-gray-800"
                        }`}>
                          {structure.is_active ? "Active" : "Inactive"}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                        <div className="flex items-center gap-2">
                          <button 
                            onClick={() => handleViewStructure(structure)}
                            className="text-blue-600 hover:text-blue-900 p-1 rounded"
                            title="View Details"
                          >
                            <Eye size={16} />
                          </button>
                          <button 
                            onClick={() => handleOpenLinkModal(structure)}
                            className="text-green-600 hover:text-green-900 p-1 rounded"
                            title="Link Employees"
                          >
                            <Link size={16} />
                          </button>
                          <button 
                            onClick={() => handleOpenModal(structure)}
                            className="text-indigo-600 hover:text-indigo-900 p-1 rounded"
                            title="Edit Structure"
                          >
                            <Edit size={16} />
                          </button>
                          <button 
                            onClick={() => handleDelete(structure.id)}
                            className="text-red-600 hover:text-red-900 p-1 rounded"
                            title="Delete Structure"
                          >
                            <Trash2 size={16} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        )}
      </div>

      {/* Stats Footer */}
      <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">
        <div className="flex justify-between items-center text-sm text-gray-600">
          <span>Total: {structures.length} salary structures</span>
          <span>Active: {structures.filter(s => s.is_active).length}</span>
        </div>
      </div>

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <h3 className="text-lg font-semibold mb-4">
              {editingStructure ? "Edit Salary Structure" : "Add Salary Structure"}
            </h3>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Structure Name</label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({...formData, name: e.target.value})}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="e.g., Senior Developer, Manager Level"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Cost to Company (CTC) - Annually</label>
                <input
                  type="number"
                  value={formData.ctc}
                  onChange={(e) => setFormData({...formData, ctc: parseFloat(e.target.value) || 0})}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="Enter annual CTC amount"
                  required
                />
                <p className="text-xs text-gray-500 mt-1">Enter the total annual cost to company</p>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Basic %</label>
                  <input
                    type="number"
                    value={formData.basic_percent}
                    onChange={(e) => setFormData({...formData, basic_percent: parseFloat(e.target.value) || 0})}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">HRA %</label>
                  <input
                    type="number"
                    value={formData.hra_percent}
                    onChange={(e) => setFormData({...formData, hra_percent: parseFloat(e.target.value) || 0})}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    required
                  />
                </div>
              </div>
              <div>
                <label className="flex items-center">
                  <input
                    type="checkbox"
                    checked={formData.is_active}
                    onChange={(e) => setFormData({...formData, is_active: e.target.checked})}
                    className="mr-2"
                  />
                  Active
                </label>
              </div>
              <div className="flex gap-4 pt-4">
                <button
                  type="button"
                  onClick={handleCloseModal}
                  className="flex-1 px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {loading ? "Saving..." : (editingStructure ? "Update" : "Create")}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Link Employees Modal */}
      {showLinkModal && linkingStructure && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-2xl max-h-[80vh] overflow-y-auto">
            <h3 className="text-lg font-semibold mb-4">
              Link Employees to {linkingStructure.name}
            </h3>
            <div className="space-y-2 mb-6">
              {employees.length === 0 ? (
                <p className="text-gray-500 text-center py-4">No employees found</p>
              ) : (
                employees.map((employee) => {
                  // Check if employee is linked to another structure
                  const existingLinks = JSON.parse(localStorage.getItem('employee_salary_links') || '{}');
                  const isLinkedToOther = Object.keys(existingLinks).some(structureId => 
                    structureId !== linkingStructure.id.toString() && 
                    existingLinks[structureId]?.includes(employee.id)
                  );
                  
                  return (
                    <div key={employee.id} className="flex items-center p-3 border rounded-lg hover:bg-gray-50">
                      <input
                        type="checkbox"
                        checked={selectedEmployees.includes(employee.id)}
                        onChange={() => toggleEmployeeSelection(employee.id)}
                        className="mr-3"
                      />
                      <div className="flex-1">
                        <div className="font-medium">{employee.name}</div>
                        <div className="text-sm text-gray-500">{employee.email}</div>
                        <div className="text-sm text-gray-500">{employee.designation || 'No designation'}</div>
                        <div className="text-xs text-blue-600">Code: {employee.employee_code}</div>
                      </div>
                      {isLinkedToOther && (
                        <span className="text-xs bg-yellow-100 text-yellow-800 px-2 py-1 rounded">Already linked</span>
                      )}
                    </div>
                  );
                })
              )}
            </div>
            <div className="flex gap-4">
              <button
                type="button"
                onClick={handleCloseLinkModal}
                className="flex-1 px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleLinkEmployees}
                disabled={loading || selectedEmployees.length === 0}
                className="flex-1 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading ? "Linking..." : `Link ${selectedEmployees.length} Employee(s)`}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
