import { useEffect, useState } from "react";
import { Plus, Search, Edit, Trash2, Eye, Users, Link, DollarSign } from "lucide-react";
import api from "../../api";

export default function SalaryStructure() {
  const [structures, setStructures] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [grades, setGrades] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [showModal, setShowModal] = useState(false);
  const [showLinkModal, setShowLinkModal] = useState(false);
  const [editingStructure, setEditingStructure] = useState(null);
  const [linkingStructure, setLinkingStructure] = useState(null);
  const [selectedEmployees, setSelectedEmployees] = useState([]);
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    name: "",
    ctc: 0,
    basic_percent: 40,
    hra_percent: 20,
    allowances: "",
    deductions: "",
    is_active: true
  });

  useEffect(() => {
    fetchStructures();
    fetchEmployees();
  }, []);

  const fetchStructures = async () => {
    try {
      setLoading(true);
      const res = await api.get("/api/payroll/salary-structures");
      setStructures(res.data || []);
    } catch (error) {
      console.error("Error fetching salary structures:", error);
      setStructures([]);
    } finally {
      setLoading(false);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      // Use the exact same logic as EIS system
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees (same as EIS)
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        email: emp.candidate_email || 'N/A',
        designation: emp.job_title,
        department: emp.department,
        employee_code: emp.employee_id,
        joining_date: emp.joining_date,
        source: 'onboarding'
      }));
      
      // Process user management employees (same as EIS)
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          email: user.email,
          designation: user.designation || 'N/A',
          department: user.department_name,
          employee_code: user.employee_code,
          joining_date: user.joining_date,
          source: 'user_management'
        }));
      
      // Combine and remove duplicates (same as EIS)
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      console.log('All employees for payroll:', allEmployees);
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
      setEmployees([]);
    }
  };



  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      setLoading(true);
      const payload = {
        ...formData,
        allowances: formData.allowances || "",
        deductions: formData.deductions || ""
      };
      
      if (editingStructure) {
        await api.put(`/api/payroll/salary-structures/${editingStructure.id}`, payload);
      } else {
        await api.post("/api/payroll/salary-structures", payload);
      }
      await fetchStructures();
      handleCloseModal();
    } catch (error) {
      console.error("Error saving salary structure:", error);
      alert("Failed to save salary structure. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm("Are you sure you want to delete this salary structure?")) {
      try {
        await api.delete(`/api/payroll/salary-structures/${id}`);
        fetchStructures();
      } catch (error) {
        console.error("Error deleting salary structure:", error);
      }
    }
  };

  const handleOpenModal = (structure = null) => {
    if (structure) {
      setEditingStructure(structure);
      setFormData({
        name: structure.name || "",
        ctc: structure.ctc || 0,
        basic_percent: structure.basic_percent || 40,
        hra_percent: structure.hra_percent || 20,
        allowances: structure.allowances || "",
        deductions: structure.deductions || "",
        is_active: structure.is_active ?? true
      });
    } else {
      setEditingStructure(null);
      setFormData({
        name: "",
        ctc: 0,
        basic_percent: 40,
        hra_percent: 20,
        allowances: "",
        deductions: "",
        is_active: true
      });
    }
    setShowModal(true);
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setEditingStructure(null);
  };

  const handleOpenLinkModal = (structure) => {
    setLinkingStructure(structure);
    // Get currently linked employees from database
    const linkedEmployeeIds = structure.employee_ids ? structure.employee_ids.split(',').filter(id => id.trim()) : [];
    console.log('Opening link modal - stored employee IDs:', linkedEmployeeIds);
    console.log('Available employee IDs:', employees.map(emp => emp.id));
    // Convert stored IDs to match employee ID types
    const normalizedIds = linkedEmployeeIds.map(id => {
      const numId = parseInt(id);
      return isNaN(numId) ? id : numId;
    });
    setSelectedEmployees(normalizedIds);
    setShowLinkModal(true);
  };

  const handleCloseLinkModal = () => {
    setShowLinkModal(false);
    setLinkingStructure(null);
    setSelectedEmployees([]);
  };

  const handleLinkEmployees = async () => {
    try {
      setLoading(true);
      
      console.log('Linking employees - Selected IDs:', selectedEmployees);
      console.log('Available employees for reference:', employees.map(emp => ({ id: emp.id, name: emp.name, code: emp.employee_code })));
      
      // Save to database instead of localStorage
      await api.post(`/api/payroll/salary-structures/${linkingStructure.id}/link-employees`, {
        employee_ids: selectedEmployees
      });
      
      alert(`Successfully linked ${selectedEmployees.length} employee(s) to ${linkingStructure.name}`);
      await fetchStructures();
      handleCloseLinkModal();
    } catch (error) {
      console.error("Error linking employees:", error);
      alert("Failed to link employees. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const toggleEmployeeSelection = (employeeId) => {
    setSelectedEmployees(prev => 
      prev.includes(employeeId) 
        ? prev.filter(id => id !== employeeId)
        : [...prev, employeeId]
    );
  };

  const handleViewStructure = (structure) => {
    alert(`Structure Details:\n\nName: ${structure.name}\nAnnual CTC: ₹${structure.ctc?.toLocaleString()}\nMonthly: ₹${((structure.ctc || 0) / 12).toLocaleString()}\nBasic: ${structure.basic_percent}%\nHRA: ${structure.hra_percent}%\nStatus: ${structure.is_active ? 'Active' : 'Inactive'}`);
  };

  const filteredStructures = structures.filter(structure =>
    structure.name?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="bg-white rounded-2xl border border-black overflow-hidden">
      {/* Header */}
      <div className="p-6 border-b border-black">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gray-100 rounded-xl flex items-center justify-center">
            <DollarSign className="w-5 h-5 text-gray-600" />
          </div>
          <div>
            <h2 className="text-lg font-medium text-gray-900">Salary Structure</h2>
            <p className="text-sm text-gray-600">Define CTC structure, earnings and deductions</p>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="p-6">
        {/* Search and Add Button */}
        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center mb-6 gap-4">
          <div className="relative max-w-md w-full sm:w-auto">
            <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400" size={18} />
            <input
              type="text"
              placeholder="Search salary structures..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-12 pr-4 py-3 border border-black rounded-xl focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent w-full text-sm"
            />
          </div>
          <button 
            onClick={() => handleOpenModal()}
            className="bg-gray-900 hover:bg-gray-800 text-white px-6 py-3 rounded-xl flex items-center gap-2 transition-colors text-sm font-medium border border-black w-full sm:w-auto justify-center"
          >
            <Plus size={18} />
            Add Structure
          </button>
        </div>

        {/* Table */}
        <div className="overflow-x-auto border border-black rounded-xl">
          {loading ? (
            <div className="flex justify-center items-center py-8">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-600"></div>
            </div>
          ) : (
            <table className="w-full">
              <thead className="bg-gray-100 border-b border-black">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Structure Name</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Annual CTC</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Basic %</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">HRA %</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Employees</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {filteredStructures.length === 0 ? (
                  <tr>
                    <td colSpan="7" className="px-6 py-8 text-center text-gray-500">
                      {searchTerm ? "No salary structures found matching your search." : "No salary structures configured yet."}
                    </td>
                  </tr>
                ) : (
                  filteredStructures.map((structure) => {
                    const linkedEmployeeIds = structure.employee_ids ? structure.employee_ids.split(',').filter(id => id) : [];
                    const employeeCount = linkedEmployeeIds.length;
                    
                    return (
                      <tr key={structure.id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm font-medium text-gray-900">{structure.name}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">₹{structure.ctc?.toLocaleString()}/year</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{structure.basic_percent}%</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{structure.hra_percent}%</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{employeeCount} employees</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${
                            structure.is_active ? "bg-gray-100 text-gray-800 border-gray-300" : "bg-gray-50 text-gray-600 border-gray-200"
                          }`}>
                            {structure.is_active ? "Active" : "Inactive"}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                          <div className="flex items-center gap-1 flex-wrap">
                            <button 
                              onClick={() => handleViewStructure(structure)}
                              className="text-gray-600 hover:text-gray-900 p-1 rounded border border-gray-300 hover:border-gray-400"
                              title="View Details"
                            >
                              <Eye size={16} />
                            </button>
                            <button 
                              onClick={() => handleOpenLinkModal(structure)}
                              className="text-gray-600 hover:text-gray-900 p-1 rounded border border-gray-300 hover:border-gray-400"
                              title="Link Employees"
                            >
                              <Link size={16} />
                            </button>
                            <button 
                              onClick={() => handleOpenModal(structure)}
                              className="text-gray-600 hover:text-gray-900 p-1 rounded border border-gray-300 hover:border-gray-400"
                              title="Edit Structure"
                            >
                              <Edit size={16} />
                            </button>
                            <button 
                              onClick={() => handleDelete(structure.id)}
                              className="text-gray-600 hover:text-gray-900 p-1 rounded border border-gray-300 hover:border-gray-400"
                              title="Delete Structure"
                            >
                              <Trash2 size={16} />
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          )}
        </div>
      </div>

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg border border-black p-4 sm:p-6 w-full max-w-md max-h-[90vh] overflow-y-auto">
            <h3 className="text-lg font-semibold mb-4">
              {editingStructure ? "Edit Salary Structure" : "Add Salary Structure"}
            </h3>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Structure Name</label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({...formData, name: e.target.value})}
                  className="w-full border border-black rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent text-sm"
                  placeholder="e.g., Senior Developer, Manager Level"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Cost to Company (CTC) - Annually</label>
                <input
                  type="number"
                  value={formData.ctc}
                  onChange={(e) => setFormData({...formData, ctc: parseFloat(e.target.value) || 0})}
                  className="w-full border border-black rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent text-sm"
                  placeholder="Enter annual CTC amount"
                  required
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Basic %</label>
                  <input
                    type="number"
                    value={formData.basic_percent}
                    onChange={(e) => setFormData({...formData, basic_percent: parseFloat(e.target.value) || 0})}
                    className="w-full border border-black rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent text-sm"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">HRA %</label>
                  <input
                    type="number"
                    value={formData.hra_percent}
                    onChange={(e) => setFormData({...formData, hra_percent: parseFloat(e.target.value) || 0})}
                    className="w-full border border-black rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent text-sm"
                    required
                  />
                </div>
              </div>
              <div>
                <label className="flex items-center">
                  <input
                    type="checkbox"
                    checked={formData.is_active}
                    onChange={(e) => setFormData({...formData, is_active: e.target.checked})}
                    className="mr-2"
                  />
                  Active
                </label>
              </div>
              <div className="flex gap-4 pt-4">
                <button
                  type="button"
                  onClick={handleCloseModal}
                  className="flex-1 px-4 py-2 border border-black rounded-xl text-gray-700 hover:bg-gray-50 text-sm font-medium"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="flex-1 px-4 py-2 bg-gray-900 text-white rounded-xl hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed text-sm font-medium border border-black"
                >
                  {loading ? "Saving..." : (editingStructure ? "Update" : "Create")}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Link Employees Modal */}
      {showLinkModal && linkingStructure && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg border border-black p-4 sm:p-6 w-full max-w-2xl max-h-[80vh] overflow-y-auto">
            <h3 className="text-lg font-semibold mb-4">
              Link Employees to {linkingStructure.name}
            </h3>
            <div className="space-y-2 mb-6">
              {employees.length === 0 ? (
                <p className="text-center py-4 text-gray-600">No employees found</p>
              ) : (
                employees.map((employee) => {
                  // Check if employee is linked to another structure
                  const isLinkedToOther = structures.some(s => 
                    s.id !== linkingStructure.id && 
                    s.employee_ids && 
                    s.employee_ids.split(',').includes(employee.id)
                  );
                  
                  const isCurrentlySelected = selectedEmployees.includes(employee.id);
                  console.log(`Employee ${employee.name} (ID: ${employee.id}) - Selected: ${isCurrentlySelected}`);
                  
                  return (
                    <div key={employee.id} className="flex items-center p-3 border border-black rounded-lg hover:bg-gray-50">
                      <input
                        type="checkbox"
                        checked={isCurrentlySelected}
                        onChange={() => toggleEmployeeSelection(employee.id)}
                        className="mr-3"
                      />
                      <div className="flex-1">
                        <div className="font-medium">{employee.name}</div>
                        <div className="text-sm text-gray-600">{employee.email}</div>
                        <div className="text-sm text-gray-600">{employee.designation || 'No designation'}</div>
                        <div className="text-xs text-gray-700">Code: {employee.employee_code}</div>
                      </div>
                      {isLinkedToOther && (
                        <span className="text-xs bg-gray-100 text-gray-800 px-2 py-1 rounded border border-gray-300">Already linked</span>
                      )}
                    </div>
                  );
                })
              )}
            </div>
            <div className="flex gap-4">
              <button
                type="button"
                onClick={handleCloseLinkModal}
                className="flex-1 px-4 py-2 border border-black rounded-lg text-gray-700 hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleLinkEmployees}
                disabled={loading}
                className={`flex-1 px-4 py-2 rounded-lg text-white border border-black ${
                  selectedEmployees.length === 0 
                    ? 'bg-gray-400 cursor-not-allowed' 
                    : 'bg-gray-900 hover:bg-gray-800'
                }`}
              >
                {loading ? "Linking..." : 
                 selectedEmployees.length === 0 ? "Select Employees" : 
                 `Link ${selectedEmployees.length} Employee(s)`}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
