import { useEffect, useState } from "react";
import { Plus, Search, Edit, Trash2, Eye, Users, Link, DollarSign } from "lucide-react";
import api from "../../api";
import useToast from "../../utils/useToast";
import Toast from "../../components/Toast";
import { hasPermission, isAdmin } from "../../utils/permissions";

export default function SalaryStructure() {
  const { toast, showToast, hideToast } = useToast();
  const [structures, setStructures] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [grades, setGrades] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("active");
  const [showModal, setShowModal] = useState(false);
  const [showLinkModal, setShowLinkModal] = useState(false);
  const [editingStructure, setEditingStructure] = useState(null);
  const [linkingStructure, setLinkingStructure] = useState(null);
  const [selectedEmployees, setSelectedEmployees] = useState([]);
  const [loading, setLoading] = useState(false);
  const [colors, setColors] = useState({ primary: '#2862e9', secondary: '#474e71' });
  const [formData, setFormData] = useState({
    name: "",
    ctc: 0,
    basic_percent: 40,
    hra_percent: 20,
    allowances: "",
    deductions: "",
    is_active: true
  });

  // Permission checks
  const canView = isAdmin() || hasPermission("view_salary_structure");
  const canAdd = isAdmin() || hasPermission("add_salary_structure");
  const canEdit = isAdmin() || hasPermission("edit_salary_structure");
  const canDelete = isAdmin() || hasPermission("delete_salary_structure");
  const canViewDetails = isAdmin() || hasPermission("view_salary_structure");
  const canLinkEmployees = isAdmin() || hasPermission("edit_salary_structure");

  if (!canView) {
    return (
      <div className="p-6 text-center">
        <div className="bg-white rounded-2xl border-0 p-8 max-w-md mx-auto">
          <h3 className="text-lg font-medium text-gray-900 mb-2">Access Denied</h3>
          <p className="text-gray-600">You do not have permission to view salary structures.</p>
        </div>
      </div>
    );
  }

  useEffect(() => {
    fetchColors();
    fetchStructures();
    fetchEmployees();
  }, [statusFilter]);

  const fetchColors = async () => {
    try {
      const tenantCode = localStorage.getItem('tenant_code');
      if (tenantCode) {
        const response = await api.get(`/auth/branding/${tenantCode}`);
        if (response.data.primary_color && response.data.secondary_color) {
          const newColors = {
            primary: response.data.primary_color,
            secondary: response.data.secondary_color
          };
          setColors(newColors);
          document.documentElement.style.setProperty('--primary-color', newColors.primary);
          document.documentElement.style.setProperty('--secondary-color', newColors.secondary);
        }
      }
    } catch (error) {
      console.error('Error fetching colors:', error);
    }
  };

  const fetchStructures = async () => {
    try {
      setLoading(true);
      const res = await api.get(`/api/payroll/salary-structures?status=${statusFilter}`);
      setStructures(res.data || []);
    } catch (error) {
      console.error("Error fetching salary structures:", error);
      showToast("Failed to load salary structures", "error");
      setStructures([]);
    } finally {
      setLoading(false);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      // Use the exact same logic as EIS system
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`${api.defaults.baseURL}/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees (same as EIS)
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        email: emp.candidate_email || 'N/A',
        designation: emp.job_title,
        department: emp.department,
        employee_code: emp.employee_id,
        joining_date: emp.joining_date,
        source: 'onboarding'
      }));
      
      // Process user management employees (same as EIS)
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          email: user.email,
          designation: user.designation || 'N/A',
          department: user.department_name,
          employee_code: user.employee_code,
          joining_date: user.joining_date,
          source: 'user_management'
        }));
      
      // Combine and remove duplicates (same as EIS)
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      console.log('All employees for payroll:', allEmployees);
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
      showToast("Failed to load employees", "error");
      setEmployees([]);
    }
  };



  const handleSubmit = async (e) => {
    e.preventDefault();
    if (editingStructure && !canEdit) {
      showToast("You do not have permission to edit salary structures", "error");
      return;
    }
    if (!editingStructure && !canAdd) {
      showToast("You do not have permission to add salary structures", "error");
      return;
    }
    try {
      setLoading(true);
      const payload = {
        ...formData,
        allowances: formData.allowances || "",
        deductions: formData.deductions || ""
      };
      
      if (editingStructure) {
        await api.put(`/api/payroll/salary-structures/${editingStructure.id}`, payload);
        showToast("Salary structure updated successfully!", "success");
      } else {
        await api.post("/api/payroll/salary-structures", payload);
        showToast("Salary structure created successfully!", "success");
      }
      await fetchStructures();
      handleCloseModal();
    } catch (error) {
      console.error("Error saving salary structure:", error);
      showToast("Failed to save salary structure. Please try again.", "error");
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id) => {
    if (!canDelete) {
      showToast("You do not have permission to delete salary structures", "error");
      return;
    }
    if (window.confirm("Are you sure you want to delete this salary structure?")) {
      try {
        await api.delete(`/api/payroll/salary-structures/${id}`);
        showToast("Salary structure deleted successfully!", "success");
        fetchStructures();
      } catch (error) {
        console.error("Error deleting salary structure:", error);
        showToast("Failed to delete salary structure", "error");
      }
    }
  };

  const handleOpenModal = (structure = null) => {
    if (structure) {
      setEditingStructure(structure);
      setFormData({
        name: structure.name || "",
        ctc: structure.ctc || 0,
        basic_percent: structure.basic_percent || 40,
        hra_percent: structure.hra_percent || 20,
        allowances: structure.allowances || "",
        deductions: structure.deductions || "",
        is_active: structure.is_active ?? true
      });
    } else {
      setEditingStructure(null);
      setFormData({
        name: "",
        ctc: 0,
        basic_percent: 40,
        hra_percent: 20,
        allowances: "",
        deductions: "",
        is_active: true
      });
    }
    setShowModal(true);
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setEditingStructure(null);
  };

  const handleOpenLinkModal = (structure) => {
    if (!canLinkEmployees) {
      showToast("You do not have permission to link employees to salary structures", "error");
      return;
    }
    setLinkingStructure(structure);
    // Get currently linked employees from database
    const linkedEmployeeIds = structure.employee_ids ? structure.employee_ids.split(',').filter(id => id.trim()) : [];
    console.log('Opening link modal - stored employee IDs:', linkedEmployeeIds);
    console.log('Available employee IDs:', employees.map(emp => emp.id));
    // Convert stored IDs to match employee ID types
    const normalizedIds = linkedEmployeeIds.map(id => {
      const numId = parseInt(id);
      return isNaN(numId) ? id : numId;
    });
    setSelectedEmployees(normalizedIds);
    setShowLinkModal(true);
  };

  const handleCloseLinkModal = () => {
    setShowLinkModal(false);
    setLinkingStructure(null);
    setSelectedEmployees([]);
  };

  const handleLinkEmployees = async () => {
    try {
      setLoading(true);
      
      console.log('Linking employees - Selected IDs:', selectedEmployees);
      console.log('Available employees for reference:', employees.map(emp => ({ id: emp.id, name: emp.name, code: emp.employee_code })));
      
      // Save to database instead of localStorage
      await api.post(`/api/payroll/salary-structures/${linkingStructure.id}/link-employees`, {
        employee_ids: selectedEmployees
      });
      
      showToast(`Successfully linked ${selectedEmployees.length} employee(s) to ${linkingStructure.name}`, "success");
      await fetchStructures();
      handleCloseLinkModal();
    } catch (error) {
      console.error("Error linking employees:", error);
      showToast("Failed to link employees. Please try again.", "error");
    } finally {
      setLoading(false);
    }
  };

  const toggleEmployeeSelection = (employeeId) => {
    setSelectedEmployees(prev => 
      prev.includes(employeeId) 
        ? prev.filter(id => id !== employeeId)
        : [...prev, employeeId]
    );
  };

  const handleViewStructure = (structure) => {
    if (!canViewDetails) {
      showToast("You do not have permission to view salary structure details", "error");
      return;
    }
    showToast(`Structure Details:\n\nName: ${structure.name}\nAnnual CTC: ₹${structure.ctc?.toLocaleString()}\nMonthly: ₹${((structure.ctc || 0) / 12).toLocaleString()}\nBasic: ${structure.basic_percent}%\nHRA: ${structure.hra_percent}%\nStatus: ${structure.is_active ? 'Active' : 'Inactive'}`, "success");
  };

  const filteredStructures = structures.filter(structure =>
    structure.name?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="rounded-2xl overflow-hidden relative" style={{
      background: `linear-gradient(135deg, white 0%, ${colors.primary}05 100%)`,
      border: `1px solid ${colors.primary}`
    }}>
      <div className="absolute top-0 right-0 w-32 h-32 rounded-full blur-3xl opacity-20" style={{
        backgroundColor: colors.primary,
        transform: 'translate(40%, -40%)'
      }}></div>
      {/* Header */}
      <div className="p-6 relative z-10" style={{
        borderBottom: `1px solid ${colors.primary}`
      }}>
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{
            backgroundColor: `${colors.primary}20`
          }}>
            <DollarSign className="w-5 h-5" style={{ color: colors.primary }} />
          </div>
          <div>
            <h2 className="text-lg font-medium text-gray-900">Salary Structure</h2>
            <p className="text-sm text-gray-600">Define CTC structure, earnings and deductions</p>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="p-6 relative z-10">
        {/* Search and Add Button */}
        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center mb-6 gap-4">
          <div className="flex flex-col sm:flex-row gap-4 sm:items-center">
            <div className="flex items-center gap-4">
              <label className="text-sm font-medium text-gray-700">Status:</label>
              <select 
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                className="px-3 py-2 rounded-xl focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent text-sm"
                style={{
                  backgroundColor: `${colors.primary}10`,
                  border: `1px solid ${colors.primary}`
                }}
              >
                <option value="active">Active</option>
                <option value="inactive">Inactive</option>
                <option value="all">All</option>
              </select>
            </div>
            <div className="relative max-w-md w-full sm:w-auto">
              <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400" size={18} />
              <input 
                type="text"
                placeholder="Search salary structures..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-12 pr-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent w-full text-sm"
                style={{
                  backgroundColor: `${colors.primary}10`,
                  border: `1px solid ${colors.primary}`
                }}
              />
            </div>
          </div>
          {canAdd && (
            <button 
              onClick={() => handleOpenModal()}
              className="px-6 py-3 rounded-xl flex items-center gap-2 transition-colors text-sm font-medium w-full sm:w-auto justify-center text-white"
              style={{
                backgroundColor: colors.primary,
                borderColor: colors.primary
              }}
              onMouseEnter={(e) => e.currentTarget.style.backgroundColor = colors.secondary}
              onMouseLeave={(e) => e.currentTarget.style.backgroundColor = colors.primary}
            >
              <Plus size={18} />
              Add Structure
            </button>
          )}
        </div>

        {/* Table */}
        <div className="rounded-2xl overflow-hidden" style={{
          border: `1px solid ${colors.primary}`
        }}>
          {loading ? (
            <div className="flex justify-center items-center py-8">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-600"></div>
            </div>
          ) : (
            <>
              {/* Desktop Table View */}
              <div className="hidden md:block overflow-x-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
                <table className="w-full">
                  <thead className="border-b" style={{
                    backgroundColor: `${colors.primary}10`,
                    borderColor: colors.primary
                  }}>
                    <tr>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Structure Name</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Annual CTC</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Basic %</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">HRA %</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Employees</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {filteredStructures.length === 0 ? (
                      <tr>
                        <td colSpan="7" className="px-6 py-8 text-center text-gray-500">
                          {searchTerm ? "No salary structures found matching your search." : "No salary structures configured yet."}
                        </td>
                      </tr>
                    ) : (
                      filteredStructures.map((structure) => {
                        const linkedEmployeeIds = structure.employee_ids ? structure.employee_ids.split(',').filter(id => id) : [];
                        const employeeCount = linkedEmployeeIds.length;
                        
                        return (
                          <tr key={structure.id} className="hover:bg-gray-50">
                            <td className="px-6 py-4 whitespace-nowrap">
                              <div className="text-sm font-medium text-gray-900">{structure.name}</div>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                              <div className="text-sm text-gray-900">₹{structure.ctc?.toLocaleString()}/year</div>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                              <div className="text-sm text-gray-900">{structure.basic_percent}%</div>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                              <div className="text-sm text-gray-900">{structure.hra_percent}%</div>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                              <div className="text-sm text-gray-900">{employeeCount} employees</div>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                              <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${
                                structure.is_active ? "bg-green-100 text-green-800 border-green-300" : "bg-red-100 text-red-800 border-red-300"
                              }`}>
                                {structure.is_active ? "Active" : "Inactive"}
                              </span>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                              <div className="flex items-center gap-1 flex-wrap">
                                {canViewDetails && (
                                  <button 
                                    onClick={() => handleViewStructure(structure)}
                                    className="p-2 text-blue-600 hover:text-blue-700 hover:bg-blue-50 rounded-lg transition-colors"
                                    title="View Details"
                                    aria-label={`View details for ${structure.name}`}
                                  >
                                    <Eye size={16} />
                                  </button>
                                )}
                                {canLinkEmployees && (
                                  <button 
                                    onClick={() => handleOpenLinkModal(structure)}
                                    className="p-2 text-green-600 hover:text-green-700 hover:bg-green-50 rounded-lg transition-colors"
                                    title="Link Employees"
                                    aria-label={`Link employees to ${structure.name}`}
                                  >
                                    <Link size={16} />
                                  </button>
                                )}
                                {canEdit && (
                                  <button 
                                    onClick={() => handleOpenModal(structure)}
                                    className="p-2 text-yellow-600 hover:text-yellow-700 hover:bg-yellow-50 rounded-lg transition-colors"
                                    title="Edit Structure"
                                    aria-label={`Edit ${structure.name}`}
                                  >
                                    <Edit size={16} />
                                  </button>
                                )}
                                {canDelete && (
                                  <button 
                                    onClick={() => handleDelete(structure.id)}
                                    className="p-2 text-red-600 hover:text-red-700 hover:bg-red-50 rounded-lg transition-colors"
                                    title="Delete Structure"
                                    aria-label={`Delete ${structure.name}`}
                                  >
                                    <Trash2 size={16} />
                                  </button>
                                )}
                              </div>
                            </td>
                          </tr>
                        );
                      })
                    )}
                  </tbody>
                </table>
              </div>

              {/* Mobile Card View */}
              <div className="md:hidden">
                {filteredStructures.length === 0 ? (
                  <div className="p-6 text-center text-gray-500">
                    {searchTerm ? "No salary structures found matching your search." : "No salary structures configured yet."}
                  </div>
                ) : (
                  filteredStructures.map((structure) => {
                    const linkedEmployeeIds = structure.employee_ids ? structure.employee_ids.split(',').filter(id => id) : [];
                    const employeeCount = linkedEmployeeIds.length;
                    
                    return (
                      <div key={structure.id} className="p-4 border-b-0 hover:bg-gray-50 relative overflow-hidden" style={{
                        border: `1px solid ${colors.primary}20`
                      }}>
                        <div className="absolute top-0 right-0 w-16 h-16 rounded-full blur-2xl opacity-15" style={{
                          backgroundColor: colors.primary,
                          transform: 'translate(30%, -30%)'
                        }}></div>
                        <div className="flex items-center justify-between mb-3 relative z-10">
                          <div>
                            <div className="text-sm font-medium text-gray-900">{structure.name}</div>
                            <div className="text-sm text-gray-600">₹{structure.ctc?.toLocaleString()}/year</div>
                          </div>
                          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${
                            structure.is_active ? "bg-green-100 text-green-800 border-green-300" : "bg-red-100 text-red-800 border-red-300"
                          }`}>
                            {structure.is_active ? "Active" : "Inactive"}
                          </span>
                        </div>
                        <div className="space-y-2 relative z-10">
                          <div className="flex justify-between">
                            <span className="text-sm font-medium text-gray-900">Basic:</span>
                            <span className="text-sm text-gray-600">{structure.basic_percent}%</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-sm font-medium text-gray-900">HRA:</span>
                            <span className="text-sm text-gray-600">{structure.hra_percent}%</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-sm font-medium text-gray-900">Employees:</span>
                            <span className="text-sm text-gray-600">{employeeCount} employees</span>
                          </div>
                        </div>
                        <div className="flex items-center justify-end gap-2 mt-3 pt-3 border-t border-gray-100 relative z-10">
                          {canViewDetails && (
                            <button 
                              onClick={() => handleViewStructure(structure)}
                              className="flex items-center gap-1 text-gray-600 hover:text-gray-900 px-3 py-1 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                              aria-label={`View details for ${structure.name}`}
                            >
                              <Eye size={14} />
                              View
                            </button>
                          )}
                          {canLinkEmployees && (
                            <button 
                              onClick={() => handleOpenLinkModal(structure)}
                              className="flex items-center gap-1 text-gray-600 hover:text-gray-900 px-3 py-1 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                              aria-label={`Link employees to ${structure.name}`}
                            >
                              <Link size={14} />
                              Link
                            </button>
                          )}
                          {canEdit && (
                            <button 
                              onClick={() => handleOpenModal(structure)}
                              className="flex items-center gap-1 text-gray-600 hover:text-gray-900 px-3 py-1 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                              aria-label={`Edit ${structure.name}`}
                            >
                              <Edit size={14} />
                              Edit
                            </button>
                          )}
                          {canDelete && (
                            <button 
                              onClick={() => handleDelete(structure.id)}
                              className="flex items-center gap-1 text-red-600 hover:text-red-900 px-3 py-1 rounded-lg hover:bg-red-50 transition-colors text-sm"
                              aria-label={`Delete ${structure.name}`}
                            >
                              <Trash2 size={14} />
                              Delete
                            </button>
                          )}
                        </div>
                      </div>
                    );
                  })
                )}
              </div>
            </>
          )}
        </div>
      </div>

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg border border-black p-4 sm:p-6 w-full max-w-md max-h-[90vh] overflow-y-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
            <h3 className="text-lg font-semibold mb-4">
              {editingStructure ? "Edit Salary Structure" : "Add Salary Structure"}
            </h3>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Structure Name</label>
                <input 
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({...formData, name: e.target.value})}
                  className="w-full rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent text-sm"
                  placeholder="e.g., Senior Developer, Manager Level"
                  required
                  style={{
                    backgroundColor: `${colors.primary}10`,
                    border: `1px solid ${colors.primary}`
                  }}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Cost to Company (CTC) - Annually</label>
                <input 
                  type="number"
                  value={formData.ctc}
                  onChange={(e) => setFormData({...formData, ctc: parseFloat(e.target.value) || 0})}
                  className="w-full rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent text-sm"
                  placeholder="Enter annual CTC amount"
                  required
                  style={{
                    backgroundColor: `${colors.primary}10`,
                    border: `1px solid ${colors.primary}`
                  }}
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Basic %</label>
                  <input 
                    type="number"
                    value={formData.basic_percent}
                    onChange={(e) => setFormData({...formData, basic_percent: parseFloat(e.target.value) || 0})}
                    className="w-full rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent text-sm"
                    required
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">HRA %</label>
                  <input 
                    type="number"
                    value={formData.hra_percent}
                    onChange={(e) => setFormData({...formData, hra_percent: parseFloat(e.target.value) || 0})}
                    className="w-full rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent text-sm"
                    required
                    style={{
                      backgroundColor: `${colors.primary}10`,
                      border: `1px solid ${colors.primary}`
                    }}
                  />
                </div>
              </div>
              <div>
                <label className="flex items-center">
                  <input 
                    type="checkbox"
                    checked={formData.is_active}
                    onChange={(e) => setFormData({...formData, is_active: e.target.checked})}
                    className="mr-2"
                    style={{
                      accentColor: colors.primary
                    }}
                  />
                  Active
                </label>
              </div>
              <div className="flex gap-4 pt-4">
                <button
                  type="button"
                  onClick={handleCloseModal}
                  className="flex-1 px-4 py-2 rounded-xl text-gray-700 hover:bg-gray-50 text-sm font-medium"
                  style={{
                    border: `1px solid ${colors.primary}20`
                  }}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="flex-1 px-4 py-2 text-white rounded-xl disabled:opacity-50 disabled:cursor-not-allowed text-sm font-medium transition-colors"
                  style={{
                    backgroundColor: colors.primary,
                    borderColor: colors.primary
                  }}
                  onMouseEnter={(e) => !loading && (e.currentTarget.style.backgroundColor = colors.secondary)}
                  onMouseLeave={(e) => !loading && (e.currentTarget.style.backgroundColor = colors.primary)}
                >
                  {loading ? "Saving..." : (editingStructure ? "Update" : "Create")}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Link Employees Modal */}
      {showLinkModal && linkingStructure && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg border border-black p-4 sm:p-6 w-full max-w-2xl max-h-[80vh] overflow-y-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
            <h3 className="text-lg font-semibold mb-4">
              Link Employees to {linkingStructure.name}
            </h3>
            <div className="space-y-2 mb-6">
              {employees.length === 0 ? (
                <p className="text-center py-4 text-gray-600">No employees found</p>
              ) : (
                employees.map((employee) => {
                  // Check if employee is linked to another structure
                  const isLinkedToOther = structures.some(s => 
                    s.id !== linkingStructure.id && 
                    s.employee_ids && 
                    s.employee_ids.split(',').includes(employee.id)
                  );
                  
                  const isCurrentlySelected = selectedEmployees.includes(employee.id);
                  console.log(`Employee ${employee.name} (ID: ${employee.id}) - Selected: ${isCurrentlySelected}`);
                  
                  return (
                    <div key={employee.id} className="flex items-center p-3 rounded-lg hover:bg-gray-50" style={{
                      border: `1px solid ${colors.primary}20`
                    }}>
                      <input 
                        type="checkbox"
                        checked={isCurrentlySelected}
                        onChange={() => toggleEmployeeSelection(employee.id)}
                        className="mr-3"
                        style={{
                          accentColor: colors.primary
                        }}
                      />
                      <div className="flex-1">
                        <div className="font-medium">{employee.name}</div>
                        <div className="text-sm text-gray-600">{employee.email}</div>
                        <div className="text-sm text-gray-600">{employee.designation || 'No designation'}</div>
                        <div className="text-xs text-gray-700">Code: {employee.employee_code}</div>
                      </div>
                      {isLinkedToOther && (
                        <span className="text-xs bg-gray-100 text-gray-800 px-2 py-1 rounded border border-gray-300">Already linked</span>
                      )}
                    </div>
                  );
                })
              )}
            </div>
            <div className="flex gap-4">
              <button
                type="button"
                onClick={handleCloseLinkModal}
                className="flex-1 px-4 py-2 rounded-lg text-gray-700 hover:bg-gray-50"
                style={{
                  border: `1px solid ${colors.primary}20`
                }}
              >
                Cancel
              </button>
              <button
                onClick={handleLinkEmployees}
                disabled={loading}
                className={`flex-1 px-4 py-2 rounded-lg text-white border transition-colors ${
                  selectedEmployees.length === 0 
                    ? 'bg-gray-400 cursor-not-allowed border-gray-400' 
                    : ''
                }`}
                style={{
                  backgroundColor: selectedEmployees.length === 0 ? '#9ca3af' : colors.primary,
                  borderColor: selectedEmployees.length === 0 ? '#9ca3af' : colors.primary
                }}
                onMouseEnter={(e) => {
                  if (selectedEmployees.length > 0 && !loading) {
                    e.currentTarget.style.backgroundColor = colors.secondary;
                  }
                }}
                onMouseLeave={(e) => {
                  if (selectedEmployees.length > 0 && !loading) {
                    e.currentTarget.style.backgroundColor = colors.primary;
                  }
                }}
              >
                {loading ? "Linking..." : 
                 selectedEmployees.length === 0 ? "Select Employees" : 
                 `Link ${selectedEmployees.length} Employee(s)`}
              </button>
            </div>
          </div>
        </div>
      )}
      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}

