"""init master tables

Revision ID: 8f08415706d4
Revises: 
Create Date: 2025-11-27 12:48:14.529321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f08415706d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('db_name', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('logo', sa.String(length=512), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_db_name'), 'hospitals', ['db_name'], unique=True)
    op.create_index(op.f('ix_hospitals_email'), 'hospitals', ['email'], unique=True)
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_hospitals_tenant_id'), 'hospitals', ['tenant_id'], unique=True)
    op.create_table('master_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_users_email'), 'master_users', ['email'], unique=True)
    op.create_index(op.f('ix_master_users_id'), 'master_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_users_id'), table_name='master_users')
    op.drop_index(op.f('ix_master_users_email'), table_name='master_users')
    op.drop_table('master_users')
    op.drop_index(op.f('ix_hospitals_tenant_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_email'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_db_name'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
