import { useState, useEffect } from "react";
import { ChevronDown, ChevronUp, Calendar, Plus } from "lucide-react";
import api from "../../api";

export default function Shift() {
  console.log("Shift component loaded!");
  const [shifts, setShifts] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [rosterData, setRosterData] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [showShifts, setShowShifts] = useState(false);
  const [selectedDepartment, setSelectedDepartment] = useState("");
  const [selectedRole, setSelectedRole] = useState("");
  const [selectedUser, setSelectedUser] = useState("");
  const [roles, setRoles] = useState([]);
  const [users, setUsers] = useState([]);
  const [allocatedUsers, setAllocatedUsers] = useState([]);
  const [editingCell, setEditingCell] = useState(null);
  const [bulkShift, setBulkShift] = useState("");
  const [viewMode, setViewMode] = useState("week");
  const [currentDate, setCurrentDate] = useState(new Date());
  const [bulkDateRange, setBulkDateRange] = useState({
    start: new Date().toISOString().split('T')[0],
    end: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
  });
  const [showCreateShift, setShowCreateShift] = useState(false);
  const [newShift, setNewShift] = useState({ name: "", start_time: "", end_time: "" });
  const [selectedUsersForBulk, setSelectedUsersForBulk] = useState([]);

  useEffect(() => {
    fetchShifts();
    fetchEmployees();
    fetchDepartments();
    fetchRoles();
    fetchUsers();
  }, []);

  useEffect(() => {
    fetchRosterData();
  }, [currentDate, viewMode, selectedDepartment]);

  const fetchShifts = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      const response = await fetch(`http://localhost:8000/shifts/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        setShifts(data.shifts || []);
      }
    } catch (error) {
      console.error("Error fetching shifts:", error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      // Fetch from both onboarding and user management (same as Employee Directory)
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees (same logic as Employee Directory)
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        email: emp.candidate_email || 'N/A',
        designation: emp.job_title,
        department_name: emp.department,
        employee_code: emp.employee_id,
        joining_date: emp.joining_date,
        work_location: emp.work_location,
        reporting_manager: emp.reporting_manager,
        status: 'Active',
        source: 'onboarding'
      }));
      
      // Process user management employees (users with employee codes)
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: `user_${user.id}`,
          original_user_id: user.id,
          name: user.name,
          email: user.email,
          designation: user.designation || 'N/A',
          department_name: user.department_name,
          employee_code: user.employee_code,
          joining_date: user.joining_date,
          work_location: 'N/A',
          reporting_manager: 'N/A',
          status: user.status || 'Active',
          source: 'user_management'
        }));
      
      // Combine and remove duplicates (prefer user management data for same employee codes)
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      console.log('Fetched employees for shifts:', allEmployees.length, allEmployees);
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
    }
  };

  const fetchRosterData = async () => {
    try {
      const token = localStorage.getItem("access_token");
      if (!token) return;
      
      const dates = getDateRange();
      const startDate = dates[0];
      const endDate = dates[dates.length - 1];
      
      const url = `http://localhost:8000/api/roster/schedule?start_date=${startDate}&end_date=${endDate}${selectedDepartment ? `&department=${selectedDepartment}` : ''}`;
      
      const response = await fetch(url, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        setRosterData(data.roster || []);
        
        if (data.roster && data.roster.length > 0) {
          const uniqueUsers = data.roster.reduce((acc, entry) => {
            if (!acc.find(u => u.id === entry.employee_id)) {
              acc.push({
                id: entry.employee_id,
                name: entry.employee_name || `User ${entry.employee_id}`,
                department_name: entry.department || "Unknown",
                role_name: "Unknown",
                roster: {}
              });
            }
            return acc;
          }, []);
          
          data.roster.forEach(empData => {
            const user = uniqueUsers.find(u => u.id === empData.employee_id);
            if (user && empData.schedule) {
              empData.schedule.forEach(dayData => {
                if (dayData.shift_id) {
                  user.roster[dayData.date] = dayData.shift_id;
                }
              });
            }
          });
          
          // Merge with existing allocated users to preserve locally added users
          setAllocatedUsers(prevUsers => {
            const existingIds = prevUsers.map(u => u.id);
            const newUsers = uniqueUsers.filter(u => !existingIds.includes(u.id));
            return [...prevUsers.map(prevUser => {
              const dbUser = uniqueUsers.find(u => u.id === prevUser.id);
              return dbUser ? { ...prevUser, roster: dbUser.roster } : prevUser;
            }), ...newUsers];
          });
        }
      }
    } catch (error) {
      console.error("Error fetching roster data:", error);
    }
  };

  const fetchDepartments = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      const response = await fetch(`http://localhost:8000/hospitals/departments/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        setDepartments(data.departments || []);
      }
    } catch (error) {
      console.error("Error fetching departments:", error);
    }
  };

  const saveRosterEntry = async (employeeId, date, shiftId, status = "Scheduled") => {
    try {
      const token = localStorage.getItem("access_token");
      
      const response = await fetch("http://localhost:8000/api/roster/save", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          employee_id: employeeId,
          date: date,
          shift_id: shiftId,
          status: status
        })
      });
      
      if (response.ok) {
        console.log("Roster entry saved successfully");
      }
    } catch (error) {
      console.error("Error saving roster:", error);
    }
  };

  const fetchRoles = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      const response = await fetch(`http://localhost:8000/hospitals/roles/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        setRoles(data.roles || []);
      }
    } catch (error) {
      console.error("Error fetching roles:", error);
    }
  };

  const fetchUsers = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant || !token) return;
      
      const response = await fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        setUsers(data.users || []);
      }
    } catch (error) {
      console.error("Error fetching users:", error);
    }
  };

  const getFilteredUsers = () => {
    return users.filter(user => {
      const matchesDept = !selectedDepartment || user.department_id === parseInt(selectedDepartment);
      const matchesRole = !selectedRole || user.role_id === parseInt(selectedRole);
      const notAlreadyInRoster = !allocatedUsers.find(allocated => allocated.id === user.id);
      console.log("Filtering user:", { user: user.name, userDeptId: user.department_id, selectedDept: selectedDepartment, userRoleId: user.role_id, selectedRole: selectedRole, notAlreadyInRoster });
      return matchesDept && matchesRole && notAlreadyInRoster;
    });
  };

  const addUserToRoster = async () => {
    if (!selectedUser) {
      alert("Please select a user first");
      return;
    }
    
    const user = users.find(u => u.id == selectedUser);
    if (!user) {
      alert("User not found");
      return;
    }
    
    const alreadyAllocated = allocatedUsers.find(allocated => allocated.id === user.id);
    if (alreadyAllocated) {
      alert("User already in roster");
      return;
    }
    
    // Add to local state immediately
    setAllocatedUsers([...allocatedUsers, { ...user, roster: {} }]);
    
    // Save a placeholder entry to database
    const today = new Date().toISOString().split('T')[0];
    await saveRosterEntry(user.id, today, null, "Unscheduled");
    
    // Clear selections
    setSelectedUser("");
    setSelectedDepartment("");
    setSelectedRole("");
    
    alert(`${user.name} added to roster successfully!`);
  };

  const bulkAllocateShifts = async () => {
    if (!bulkShift || selectedUsersForBulk.length === 0) {
      alert("Please select users and shift for bulk allocation");
      return;
    }
    
    const start = new Date(bulkDateRange.start);
    const end = new Date(bulkDateRange.end);
    const updatedUsers = [...allocatedUsers];
    
    for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
      const dateStr = new Date(d).toISOString().split('T')[0];
      
      for (const user of updatedUsers) {
        if (selectedUsersForBulk.includes(user.id)) {
          if (!user.roster) user.roster = {};
          user.roster[dateStr] = bulkShift;
          
          const shiftId = bulkShift === "OFF" ? null : parseInt(bulkShift);
          const status = bulkShift === "OFF" ? "OFF" : "Scheduled";
          await saveRosterEntry(user.id, dateStr, shiftId, status);
        }
      }
    }
    
    setAllocatedUsers(updatedUsers);
    setBulkShift("");
    setSelectedUsersForBulk([]);
    fetchRosterData();
  };

  const removeUserFromRoster = (userId) => {
    setAllocatedUsers(allocatedUsers.filter(user => user.id !== userId));
  };

  const updateUserRoster = (userId, date, shiftId) => {
    setAllocatedUsers(allocatedUsers.map(user => {
      if (user.id === userId) {
        return {
          ...user,
          roster: {
            ...user.roster,
            [date]: shiftId
          }
        };
      }
      return user;
    }));
  };

  const createShift = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!newShift.name || !newShift.start_time || !newShift.end_time) {
        alert("Please fill all fields");
        return;
      }
      
      const response = await fetch(`http://localhost:8000/shifts/${tenant}/create`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify(newShift)
      });
      
      if (response.ok) {
        alert("Shift created successfully!");
        setNewShift({ name: "", start_time: "", end_time: "" });
        setShowCreateShift(false);
        fetchShifts();
      }
    } catch (error) {
      console.error("Error creating shift:", error);
    }
  };

  const deleteShift = async (shiftId) => {
    if (!confirm("Are you sure you want to delete this shift?")) {
      return;
    }
    
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      const response = await fetch(`http://localhost:8000/shifts/${tenant}/${shiftId}`, {
        method: "DELETE",
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      
      if (response.ok) {
        alert("Shift deleted successfully!");
        fetchShifts();
      } else {
        alert("Failed to delete shift");
      }
    } catch (error) {
      console.error("Error deleting shift:", error);
      alert("Error deleting shift");
    }
  };

  const getDayName = (dateStr) => {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', { weekday: 'short' });
  };

  const getDateRange = () => {
    const dates = [];
    let start, end;
    
    if (viewMode === "week") {
      const curr = new Date(currentDate);
      const first = curr.getDate() - curr.getDay() + 1;
      start = new Date(curr.setDate(first));
      end = new Date(curr.setDate(first + 6));
    } else {
      start = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1);
      end = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0);
    }
    
    for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
      dates.push(new Date(d).toISOString().split('T')[0]);
    }
    
    return dates;
  };

  const navigateDate = (direction) => {
    const newDate = new Date(currentDate);
    if (viewMode === "week") {
      newDate.setDate(newDate.getDate() + (direction * 7));
    } else {
      newDate.setMonth(newDate.getMonth() + direction);
    }
    setCurrentDate(newDate);
  };

  const getCalendarTitle = () => {
    if (viewMode === "week") {
      const dates = getDateRange();
      const start = new Date(dates[0]);
      const end = new Date(dates[dates.length - 1]);
      return `${start.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} - ${end.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;
    } else {
      return currentDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
    }
  };

  return (
    <div className="w-full overflow-hidden">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 px-4 py-4">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-gradient-to-br from-orange-500 to-amber-600 rounded-lg flex-shrink-0">
              <Calendar className="text-white" size={20} />
            </div>
            <div>
              <h1 className="text-xl font-bold text-gray-900">Shift & Roster Management</h1>
              <p className="text-gray-600 mt-1">Create shifts and manage employee roster assignments</p>
            </div>
          </div>
          <div className="flex flex-col sm:flex-row gap-3">
            <button
              onClick={() => setShowCreateShift(!showCreateShift)}
              className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition-colors whitespace-nowrap"
            >
              <Plus size={16} /> Create Shift
            </button>
            <button
              onClick={() => setShowShifts(!showShifts)}
              className="inline-flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 text-gray-700 text-sm font-medium rounded-lg hover:bg-gray-50 transition-colors whitespace-nowrap"
            >
              View Shifts ({shifts.length}) {showShifts ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
            </button>
          </div>
        </div>
      </div>

      <div className="p-4 space-y-6">
        {/* Shift Management */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200">

          <div className="p-6">
            {showCreateShift && (
              <div className="mb-6 p-6 bg-gray-50 rounded-lg border border-gray-200">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Create New Shift</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Shift Name</label>
                    <input
                      type="text"
                      value={newShift.name}
                      onChange={(e) => setNewShift({...newShift, name: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                      placeholder="e.g., Morning Shift"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Start Time</label>
                    <input
                      type="time"
                      value={newShift.start_time}
                      onChange={(e) => setNewShift({...newShift, start_time: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">End Time</label>
                    <input
                      type="time"
                      value={newShift.end_time}
                      onChange={(e) => setNewShift({...newShift, end_time: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                    />
                  </div>
                </div>
                <div className="flex gap-3 mt-6">
                  <button
                    onClick={createShift}
                    className="px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition-colors"
                  >
                    Create Shift
                  </button>
                  <button
                    onClick={() => setShowCreateShift(false)}
                    className="px-4 py-2 bg-white border border-gray-300 text-gray-700 text-sm font-medium rounded-lg hover:bg-gray-50 transition-colors"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            )}

            {showShifts && (
              <div className="overflow-hidden">
                <div className="overflow-x-auto">
                  <table className="min-w-full table-fixed divide-y divide-gray-200">
                    <thead className="bg-gray-50">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-48">Shift Name</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-32">Start Time</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-32">End Time</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-32">Duration</th>
                        <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider w-24">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {shifts.length === 0 ? (
                        <tr>
                          <td colSpan="5" className="px-6 py-12 text-center">
                            <div className="flex flex-col items-center gap-3">
                              <div className="w-12 h-12 bg-gray-100 rounded-full flex items-center justify-center">
                                <Calendar size={24} className="text-gray-400" />
                              </div>
                              <div>
                                <p className="text-gray-900 font-medium">No shifts found</p>
                                <p className="text-gray-500 text-sm mt-1">Create your first shift to get started</p>
                              </div>
                            </div>
                          </td>
                        </tr>
                      ) : (
                        shifts.map((shift) => {
                          const calculateDuration = (start, end) => {
                            const startTime = new Date(`2000-01-01 ${start}`);
                            const endTime = new Date(`2000-01-01 ${end}`);
                            let diff = endTime - startTime;
                            if (diff < 0) diff += 24 * 60 * 60 * 1000;
                            const hours = Math.floor(diff / (1000 * 60 * 60));
                            return `${hours} hours`;
                          };
                          
                          return (
                            <tr key={shift.id} className="hover:bg-gray-50">
                              <td className="px-4 py-4 whitespace-nowrap">
                                <div className="text-sm font-medium text-gray-900 truncate" title={shift.name}>{shift.name}</div>
                              </td>
                              <td className="px-4 py-4 whitespace-nowrap text-sm text-gray-900">{shift.start_time}</td>
                              <td className="px-4 py-4 whitespace-nowrap text-sm text-gray-900">{shift.end_time}</td>
                              <td className="px-4 py-4 whitespace-nowrap text-sm text-gray-500">
                                {calculateDuration(shift.start_time, shift.end_time)}
                              </td>
                              <td className="px-4 py-4 whitespace-nowrap text-center">
                                <button 
                                  onClick={() => deleteShift(shift.id)}
                                  className="inline-flex items-center p-1.5 bg-red-100 text-red-700 text-sm font-medium rounded-md hover:bg-red-200 transition-colors"
                                >
                                  <Trash2 size={12} />
                                </button>
                              </td>
                            </tr>
                          );
                        })
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Roster Management */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200">
          <div className="px-6 py-4 border-b border-gray-200">
            <h2 className="text-lg font-semibold text-gray-900">Roster Management</h2>
            <p className="text-gray-600 text-sm mt-1">Assign employees to shifts and manage schedules</p>
          </div>
          
          <div className="p-6">
            {/* Add Employee Section */}
            <div className="mb-6 p-6 bg-blue-50 rounded-lg border border-blue-200">
              <h3 className="text-md font-semibold text-blue-900 mb-4">Add Employee to Roster</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Employee</label>
                  <select
                    value={selectedUser}
                    onChange={(e) => setSelectedUser(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                  >
                    <option value="">Select Employee</option>
                    {employees.map((employee) => (
                      <option key={employee.id} value={employee.id}>
                        {employee.employee_code} - {employee.name}
                      </option>
                    ))}
                  </select>
                </div>
                
                <div className="flex items-end">
                  <button
                    onClick={async () => {
                      if (!selectedUser) {
                        alert("Please select an employee first");
                        return;
                      }
                      
                      const employee = employees.find(e => e.id == selectedUser);
                      if (employee) {
                        setAllocatedUsers([...allocatedUsers, { ...employee, roster: {} }]);
                        const today = new Date().toISOString().split('T')[0];
                        await saveRosterEntry(employee.id, today, null, "Unscheduled");
                        setSelectedUser("");
                        alert(`${employee.name} added to roster successfully!`);
                      }
                    }}
                    className="w-full px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition-colors"
                  >
                    Add to Roster
                  </button>
                </div>
              </div>
            </div>

            {/* Bulk Allocation Section */}
            {allocatedUsers.length > 0 && (
              <div className="mb-6 p-6 bg-green-50 rounded-lg border border-green-200">
                <h3 className="text-md font-semibold text-green-900 mb-4">Bulk Shift Allocation</h3>
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">From Date</label>
                    <input
                      type="date"
                      value={bulkDateRange.start}
                      onChange={(e) => setBulkDateRange({...bulkDateRange, start: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                    />
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">To Date</label>
                    <input
                      type="date"
                      value={bulkDateRange.end}
                      onChange={(e) => setBulkDateRange({...bulkDateRange, end: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                    />
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Shift</label>
                    <select
                      value={bulkShift}
                      onChange={(e) => setBulkShift(e.target.value)}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                    >
                      <option value="">Select Shift</option>
                      {shifts.map((shift) => (
                        <option key={shift.id} value={shift.id}>{shift.name}</option>
                      ))}
                      <option value="OFF">OFF</option>
                    </select>
                  </div>
                  
                  <div className="flex items-end">
                    <button
                      onClick={bulkAllocateShifts}
                      disabled={!bulkShift}
                      className="w-full px-4 py-2 bg-green-600 text-white text-sm font-medium rounded-lg hover:bg-green-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
                    >
                      Apply to Selected ({selectedUsersForBulk.length})
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* Calendar Controls */}
            <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg border border-gray-200 mb-6">
              <div className="flex items-center gap-4">
                <div className="flex bg-white rounded-lg border border-gray-300 overflow-hidden">
                  <button
                    onClick={() => setViewMode("week")}
                    className={`px-4 py-2 text-sm font-medium transition-colors ${
                      viewMode === "week" ? "bg-indigo-600 text-white" : "text-gray-700 hover:bg-gray-100"
                    }`}
                  >
                    Week
                  </button>
                  <button
                    onClick={() => setViewMode("month")}
                    className={`px-4 py-2 text-sm font-medium transition-colors ${
                      viewMode === "month" ? "bg-indigo-600 text-white" : "text-gray-700 hover:bg-gray-100"
                    }`}
                  >
                    Month
                  </button>
                </div>
                
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => navigateDate(-1)}
                    className="p-2 text-gray-600 hover:bg-white rounded-lg border border-gray-300 transition-colors"
                  >
                    <ChevronDown className="rotate-90" size={16} />
                  </button>
                  
                  <h3 className="text-lg font-semibold text-gray-800 min-w-[200px] text-center">
                    {getCalendarTitle()}
                  </h3>
                  
                  <button
                    onClick={() => navigateDate(1)}
                    className="p-2 text-gray-600 hover:bg-white rounded-lg border border-gray-300 transition-colors"
                  >
                    <ChevronDown className="-rotate-90" size={16} />
                  </button>
                </div>
              </div>
              
              <button
                onClick={() => setCurrentDate(new Date())}
                className="px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition-colors"
              >
                Today
              </button>
            </div>

        <div className="border rounded-lg overflow-hidden">
          <div className="px-4 py-3 bg-gray-100 border-b">
            <h3 className="font-semibold text-gray-800">
              {viewMode === "week" ? "Weekly" : "Monthly"} Roster Calendar
              {allocatedUsers.length > 0 && (
                <span className="ml-2 text-sm text-gray-600">({allocatedUsers.length} employees)</span>
              )}
            </h3>
          </div>
          <div className="overflow-x-auto max-w-full">
            <table className="w-full border-collapse table-fixed">
              <thead className="bg-gray-100">
                <tr>
                  <th className="px-2 py-3 text-center font-semibold text-gray-800 w-12 border-r border-gray-300">
                    <input
                      type="checkbox"
                      checked={selectedUsersForBulk.length === allocatedUsers.length && allocatedUsers.length > 0}
                      onChange={(e) => {
                        if (e.target.checked) {
                          setSelectedUsersForBulk(allocatedUsers.map(u => u.id));
                        } else {
                          setSelectedUsersForBulk([]);
                        }
                      }}
                      className="rounded"
                    />
                  </th>
                  <th className="px-4 py-3 text-left font-semibold text-gray-800 min-w-[180px] border-r border-gray-300">
                    Employee
                  </th>
                  {getDateRange().map((date) => {
                    const dayName = getDayName(date);
                    const dayNum = new Date(date).getDate();
                    const isWeekend = ['Sat', 'Sun'].includes(dayName);
                    
                    return (
                      <th key={date} className={`px-3 py-3 text-center min-w-[100px] border-r border-gray-300 ${
                        isWeekend ? 'bg-red-50' : ''
                      }`}>
                        <div className={`font-semibold text-sm ${
                          isWeekend ? 'text-red-600' : 'text-gray-800'
                        }`}>{dayName}</div>
                        <div className={`text-xs ${
                          isWeekend ? 'text-red-500' : 'text-gray-500'
                        }`}>{dayNum}</div>
                      </th>
                    );
                  })}
                  <th className="px-4 py-3 text-center font-semibold text-gray-800">Action</th>
                </tr>
              </thead>
              <tbody>
                {allocatedUsers.length === 0 ? (
                  <tr>
                    <td colSpan={getDateRange().length + 3} className="px-8 py-12 text-center text-gray-500">
                      <div className="flex flex-col items-center gap-3">
                        <Calendar size={48} className="text-gray-300" />
                        <p className="text-lg font-medium">No employees in roster</p>
                        <p className="text-sm">Add employees above to start scheduling shifts</p>
                      </div>
                    </td>
                  </tr>
                ) : (
                  allocatedUsers.map((user, index) => (
                    <tr key={user.id} className={`${index % 2 === 0 ? 'bg-gray-50' : 'bg-white'} hover:bg-blue-50 transition-colors`}>
                      <td className="px-2 py-3 text-center border-r border-gray-300">
                        <input
                          type="checkbox"
                          checked={selectedUsersForBulk.includes(user.id)}
                          onChange={(e) => {
                            if (e.target.checked) {
                              setSelectedUsersForBulk([...selectedUsersForBulk, user.id]);
                            } else {
                              setSelectedUsersForBulk(selectedUsersForBulk.filter(id => id !== user.id));
                            }
                          }}
                          className="rounded"
                        />
                      </td>
                      <td className="px-4 py-3 border-r border-gray-300">
                        <div className="flex items-center gap-3">
                          <div className="flex flex-col">
                            <div className="font-medium text-gray-900 text-sm">{user.name}</div>
                            <div className="text-xs text-gray-500">{user.department_name}</div>
                          </div>
                        </div>
                      </td>
                      {getDateRange().map((date) => {
                        const dayName = getDayName(date);
                        const isWeekend = ['Sat', 'Sun'].includes(dayName);
                        const shiftValue = user.roster?.[date] || "";
                        const shift = shifts.find(s => s.id == shiftValue);
                        
                        return (
                          <td key={date} className={`px-2 py-3 border-r border-gray-300 text-center ${
                            isWeekend ? 'bg-red-25' : ''
                          }`}>
                            {editingCell === `${user.id}-${date}` ? (
                              <select
                                value={shiftValue}
                                onChange={async (e) => {
                                  const shiftId = e.target.value ? parseInt(e.target.value) : null;
                                  const status = e.target.value === "OFF" ? "OFF" : "Scheduled";
                                  updateUserRoster(user.id, date, e.target.value);
                                  await saveRosterEntry(user.id, date, shiftId, status);
                                  setEditingCell(null);
                                }}
                                onBlur={() => setEditingCell(null)}
                                autoFocus
                                className="w-full px-2 py-1 text-sm border rounded focus:ring-2 focus:ring-blue-500"
                              >
                                <option value="">Select</option>
                                {shifts.map((shift) => (
                                  <option key={shift.id} value={shift.id}>{shift.name}</option>
                                ))}
                                <option value="OFF">OFF</option>
                              </select>
                            ) : shiftValue ? (
                              <div className="text-center">
                                <div 
                                  onClick={() => setEditingCell(`${user.id}-${date}`)}
                                  className={`px-2 py-1 text-xs rounded font-medium cursor-pointer hover:opacity-80 ${
                                    shiftValue === "OFF" ? 'bg-red-100 text-red-700' :
                                    'bg-green-100 text-green-700'
                                  }`}
                                >
                                  {shiftValue === "OFF" ? "OFF" : shift?.name || "Unknown"}
                                </div>
                                <button
                                  onClick={async () => {
                                    updateUserRoster(user.id, date, "");
                                    await saveRosterEntry(user.id, date, null, "Unscheduled");
                                  }}
                                  className="text-xs text-red-500 hover:text-red-700 mt-1"
                                >
                                  Clear
                                </button>
                              </div>
                            ) : (
                              <div 
                                onClick={() => setEditingCell(`${user.id}-${date}`)}
                                className="text-gray-400 text-xs cursor-pointer hover:text-blue-500 hover:bg-blue-50 py-1 rounded"
                              >
                                + Add
                              </div>
                            )}
                          </td>
                        );
                      })}
                      <td className="px-4 py-3 text-center">
                        <button 
                          onClick={() => removeUserFromRoster(user.id)}
                          className="px-2 py-1 bg-red-600 text-white text-xs rounded hover:bg-red-700"
                        >
                          Remove
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
          </div>
        </div>
      </div>
    </div>
  );
}
