import React, { useState, useEffect } from 'react';
import api from '../../api';

const ResignationTracking = () => {
  const [resignations, setResignations] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showApplyForm, setShowApplyForm] = useState(false);
  const [statusFilter, setStatusFilter] = useState('All');
  const [searchTerm, setSearchTerm] = useState('');
  const [formData, setFormData] = useState({
    employee_id: '',
    resignation_date: '',
    last_working_day: '',
    reason: '',
    notice_period: '30',
    notes: '',
    exit_interview_date: ''
  });

  useEffect(() => {
    fetchResignations();
    fetchEmployees();
  }, []);

  const fetchResignations = async () => {
    try {
      const response = await api.get('/api/resignation/list');
      setResignations(response.data.resignations || []);
    } catch (error) {
      console.error('Error fetching resignations:', error);
    } finally {
      setLoading(false);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: user.id,
          name: user.name,
          employee_code: user.employee_code
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const handleApplyResignation = async (e) => {
    e.preventDefault();
    try {
      const submitData = {
        employee_id: parseInt(formData.employee_id),
        resignation_date: formData.resignation_date,
        last_working_day: formData.last_working_day,
        reason: formData.reason,
        notice_period: formData.notice_period,
        notes: formData.notes
      };
      
      await api.post('/api/resignation/apply', submitData);
      setShowApplyForm(false);
      setFormData({
        employee_id: '',
        resignation_date: '',
        last_working_day: '',
        reason: '',
        notice_period: '30',
        notes: '',
        exit_interview_date: ''
      });
      fetchResignations();
      alert('Resignation applied successfully!');
    } catch (error) {
      console.error('Error applying resignation:', error);
      alert('Error applying resignation: ' + (error.response?.data?.detail || error.message));
    }
  };

  const updateStatus = async (resignationId, statusField, statusValue) => {
    try {
      await api.put(`/api/resignation/update/${resignationId}?status_field=${statusField}&status_value=${statusValue}`);
      fetchResignations();
    } catch (error) {
      console.error('Error updating status:', error);
    }
  };

  const calculateOverallStatus = (resignation) => {
    const handover = resignation.handover_status || 'Pending';
    const clearance = resignation.clearance_status || 'Pending';
    const assets = resignation.asset_return_status || 'Pending';
    const settlement = resignation.final_settlement_status || 'Pending';
    
    if (handover === 'Completed' && clearance === 'Completed' && assets === 'Completed' && settlement === 'Completed') {
      return 'Completed';
    } else if (handover !== 'Pending' || clearance !== 'Pending' || assets !== 'Pending' || settlement !== 'Pending') {
      return 'In Progress';
    }
    return 'Initiated';
  };

  const getStatusColor = (status) => {
    const colors = {
      'Pending': 'bg-yellow-200 text-yellow-800',
      'In Progress': 'bg-blue-200 text-blue-800',
      'Completed': 'bg-green-200 text-green-800',
      'Initiated': 'bg-gray-200 text-gray-800'
    };
    return colors[status] || 'bg-gray-200 text-gray-800';
  };

  const filteredResignations = resignations.filter(resignation => {
    const overallStatus = calculateOverallStatus(resignation);
    const matchesStatus = statusFilter === 'All' || overallStatus === statusFilter;
    const matchesSearch = resignation.employee_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         resignation.employee_code?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         resignation.reason?.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesStatus && matchesSearch;
  });

  if (loading) {
    return <div className="flex justify-center items-center h-64">Loading...</div>;
  }

  return (
    <div className="p-6 space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold">Resignation & Notice Tracking</h1>
        <button 
          onClick={() => setShowApplyForm(true)}
          className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
        >
          Apply Resignation
        </button>
      </div>

      {/* Summary Cards - Top Position */}
      <div className="grid grid-cols-3 gap-4">
        <div className="bg-white p-4 rounded-lg shadow text-center">
          <div className="text-2xl font-bold text-blue-600">{resignations.filter(r => calculateOverallStatus(r) === 'Initiated').length}</div>
          <div className="text-sm text-gray-500">Initiated</div>
        </div>
        <div className="bg-white p-4 rounded-lg shadow text-center">
          <div className="text-2xl font-bold text-orange-600">{resignations.filter(r => calculateOverallStatus(r) === 'In Progress').length}</div>
          <div className="text-sm text-gray-500">In Progress</div>
        </div>
        <div className="bg-white p-4 rounded-lg shadow text-center">
          <div className="text-2xl font-bold text-green-600">{resignations.filter(r => calculateOverallStatus(r) === 'Completed').length}</div>
          <div className="text-sm text-gray-500">Completed</div>
        </div>
      </div>

      {/* Filters */}
      <div className="bg-white p-4 rounded-lg shadow flex gap-4 items-center">
        <div className="flex-1">
          <input
            type="text"
            placeholder="Search by employee name, code, or reason..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full border rounded px-3 py-2"
          />
        </div>
        <div>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="border rounded px-3 py-2"
          >
            <option value="All">All Status</option>
            <option value="Initiated">Initiated</option>
            <option value="In Progress">In Progress</option>
            <option value="Completed">Completed</option>
          </select>
        </div>
      </div>

      {/* Apply Resignation Modal */}
      {showApplyForm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white p-6 rounded-lg max-w-md w-full mx-4">
            <h2 className="text-xl font-bold mb-4">Apply Resignation</h2>
            <form onSubmit={handleApplyResignation} className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">Employee</label>
                <select 
                  value={formData.employee_id} 
                  onChange={(e) => setFormData({...formData, employee_id: e.target.value})}
                  className="w-full border rounded px-3 py-2"
                  required
                >
                  <option value="">Select Employee ({employees.length} available)</option>
                  {employees.map(emp => (
                    <option key={emp.id} value={emp.id}>
                      {emp.employee_code || `EMP${emp.id}`} - {emp.name}
                    </option>
                  ))}
                </select>
              </div>
              
              <div>
                <label className="block text-sm font-medium mb-1">Resignation Date</label>
                <input
                  type="date"
                  value={formData.resignation_date}
                  onChange={(e) => setFormData({...formData, resignation_date: e.target.value})}
                  className="w-full border rounded px-3 py-2"
                  required
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium mb-1">Last Working Day</label>
                <input
                  type="date"
                  value={formData.last_working_day}
                  onChange={(e) => setFormData({...formData, last_working_day: e.target.value})}
                  className="w-full border rounded px-3 py-2"
                  required
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium mb-1">Notice Period (Days)</label>
                <input
                  type="number"
                  value={formData.notice_period}
                  onChange={(e) => setFormData({...formData, notice_period: e.target.value})}
                  className="w-full border rounded px-3 py-2"
                  placeholder="30"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium mb-1">Reason</label>
                <textarea
                  value={formData.reason}
                  onChange={(e) => setFormData({...formData, reason: e.target.value})}
                  className="w-full border rounded px-3 py-2"
                  placeholder="Reason for resignation"
                  rows="3"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium mb-1">Notes</label>
                <textarea
                  value={formData.notes}
                  onChange={(e) => setFormData({...formData, notes: e.target.value})}
                  className="w-full border rounded px-3 py-2"
                  placeholder="Additional notes"
                  rows="2"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium mb-1">Exit Interview Date (Optional)</label>
                <input
                  type="date"
                  value={formData.exit_interview_date}
                  onChange={(e) => setFormData({...formData, exit_interview_date: e.target.value})}
                  className="w-full border rounded px-3 py-2"
                />
              </div>
              
              <div className="flex gap-2">
                <button type="submit" className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
                  Apply Resignation
                </button>
                <button 
                  type="button" 
                  onClick={() => setShowApplyForm(false)}
                  className="bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-600"
                >
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Resignations Table */}
      <div className="bg-white rounded-lg shadow">
        <div className="p-4 border-b">
          <h2 className="text-lg font-semibold">Resignation List ({filteredResignations.length})</h2>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="text-left p-3 font-medium">Employee</th>
                <th className="text-left p-3 font-medium">Last Working Day</th>
                <th className="text-left p-3 font-medium">Notice Period</th>
                <th className="text-left p-3 font-medium">Overall Status</th>
                <th className="text-left p-3 font-medium">Reason</th>
                <th className="text-left p-3 font-medium">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredResignations.map((resignation) => {
                const overallStatus = calculateOverallStatus(resignation);
                return (
                  <tr key={resignation.id} className="border-b hover:bg-gray-50">
                    <td className="p-3">
                      <div>
                        <div className="font-medium">{resignation.employee_name}</div>
                        <div className="text-sm text-gray-500">{resignation.employee_code}</div>
                      </div>
                    </td>
                    <td className="p-3">
                      {resignation.last_working_day ? new Date(resignation.last_working_day).toLocaleDateString() : '-'}
                    </td>
                    <td className="p-3">
                      <div className="flex items-center gap-2">
                        {resignation.notice_period} days
                        {resignation.notice_served && <span className="text-green-500">✓</span>}
                      </div>
                    </td>
                    <td className="p-3">
                      <span className={`px-2 py-1 rounded text-xs ${getStatusColor(overallStatus)}`}>
                        {overallStatus}
                      </span>
                      <div className="text-xs text-gray-500 mt-1">
                        H: {resignation.handover_status || 'Pending'} | 
                        C: {resignation.clearance_status || 'Pending'}
                      </div>
                    </td>
                    <td className="p-3">
                      <div className="max-w-xs truncate" title={resignation.reason}>
                        {resignation.reason || '-'}
                      </div>
                    </td>
                    <td className="p-3">
                      <div className="flex flex-col gap-1">
                        <select 
                          onChange={(e) => updateStatus(resignation.id, 'handover_status', e.target.value)}
                          className="border rounded px-2 py-1 text-xs"
                          value={resignation.handover_status || 'Pending'}
                        >
                          <option value="Pending">Handover Pending</option>
                          <option value="In Progress">Handover In Progress</option>
                          <option value="Completed">Handover Completed</option>
                        </select>
                        
                        <select 
                          onChange={(e) => updateStatus(resignation.id, 'clearance_status', e.target.value)}
                          className="border rounded px-2 py-1 text-xs"
                          value={resignation.clearance_status || 'Pending'}
                        >
                          <option value="Pending">Clearance Pending</option>
                          <option value="In Progress">Clearance In Progress</option>
                          <option value="Completed">Clearance Done</option>
                        </select>
                        
                        <select 
                          onChange={(e) => updateStatus(resignation.id, 'asset_return_status', e.target.value)}
                          className="border rounded px-2 py-1 text-xs"
                          value={resignation.asset_return_status || 'Pending'}
                        >
                          <option value="Pending">Assets Pending</option>
                          <option value="Completed">Assets Returned</option>
                        </select>
                        
                        <select 
                          onChange={(e) => updateStatus(resignation.id, 'final_settlement', e.target.value)}
                          className="border rounded px-2 py-1 text-xs"
                          value={resignation.final_settlement_status || 'Pending'}
                        >
                          <option value="Pending">Settlement Pending</option>
                          <option value="Completed">Settlement Done</option>
                        </select>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          
          {filteredResignations.length === 0 && (
            <div className="text-center py-8 text-gray-500">
              {statusFilter !== 'All' || searchTerm ? 'No resignations match your filters' : 'No resignations found'}
            </div>
          )}
        </div>
      </div>


    </div>
  );
};

export default ResignationTracking;