import React, { useState, useEffect } from 'react';
import { Users, Clock, CheckCircle, FileText, Plus, Search } from 'lucide-react';
import api from '../../api';
import useToast from '../../utils/useToast';
import { hasPermission, isAdmin } from '../../utils/permissions';
import Toast from '../../components/Toast';

const ResignationTracking = () => {
  const { toast, showToast } = useToast();
  
  // Permission checks
  const canApply = isAdmin() || hasPermission('apply_resignation');
  const canView = isAdmin() || hasPermission('view_resignations');
  const canManageHandover = isAdmin() || hasPermission('manage_handover');
  const canManageClearance = isAdmin() || hasPermission('manage_clearance');
  const canManageAssets = isAdmin() || hasPermission('manage_assets');
  const canManageSettlement = isAdmin() || hasPermission('manage_settlement');
  
  if (!canView) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="text-center">
          <h3 className="text-lg font-medium text-gray-900 mb-2">Access Denied</h3>
          <p className="text-gray-600">You do not have permission to view resignations.</p>
        </div>
      </div>
    );
  }
  const [resignations, setResignations] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showApplyForm, setShowApplyForm] = useState(false);
  const [statusFilter, setStatusFilter] = useState('All');
  const [searchTerm, setSearchTerm] = useState('');
  const [formData, setFormData] = useState({
    employee_id: '',
    resignation_date: '',
    reason: '',
    notes: ''
  });

  useEffect(() => {
    fetchResignations();
    fetchEmployees();
  }, []);

  const fetchResignations = async () => {
    try {
      const response = await api.get('/api/resignation/list');
      setResignations(response.data.resignations || []);
    } catch (error) {
      console.error('Error fetching resignations:', error);
    } finally {
      setLoading(false);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: user.id,
          name: user.name,
          employee_code: user.employee_code
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const handleApplyResignation = async (e) => {
    e.preventDefault();
    try {
      const submitData = {
        employee_id: parseInt(formData.employee_id),
        resignation_date: formData.resignation_date,
        reason: formData.reason,
        notes: formData.notes
      };
      
      await api.post('/api/resignation/apply', submitData);
      setShowApplyForm(false);
      setFormData({
        employee_id: '',
        resignation_date: '',
        reason: '',
        notes: ''
      });
      fetchResignations();
      showToast('Resignation applied successfully!', 'success');
    } catch (error) {
      console.error('Error applying resignation:', error);
      showToast('Error applying resignation: ' + (error.response?.data?.detail || error.message), 'error');
    }
  };

  const updateStatus = async (resignationId, statusField, statusValue) => {
    try {
      await api.put(`/api/resignation/update/${resignationId}?status_field=${statusField}&status_value=${statusValue}`);
      fetchResignations();
    } catch (error) {
      console.error('Error updating status:', error);
    }
  };

  const calculateOverallStatus = (resignation) => {
    const handover = resignation.handover_status || 'Pending';
    const clearance = resignation.clearance_status || 'Pending';
    const assets = resignation.asset_return_status || 'Pending';
    const settlement = resignation.final_settlement_status || 'Pending';
    
    if (handover === 'Completed' && clearance === 'Completed' && assets === 'Completed' && settlement === 'Completed') {
      return 'Completed';
    } else if (handover !== 'Pending' || clearance !== 'Pending' || assets !== 'Pending' || settlement !== 'Pending') {
      return 'In Progress';
    }
    return 'Initiated';
  };

  const getStatusColor = (status) => {
    const colors = {
      'Pending': 'bg-gray-100 text-gray-800',
      'In Progress': 'bg-gray-200 text-gray-900',
      'Completed': 'bg-gray-300 text-gray-900',
      'Initiated': 'bg-gray-100 text-gray-800'
    };
    return colors[status] || 'bg-gray-100 text-gray-800';
  };

  const filteredResignations = resignations.filter(resignation => {
    const overallStatus = calculateOverallStatus(resignation);
    const matchesStatus = statusFilter === 'All' || overallStatus === statusFilter;
    const matchesSearch = resignation.employee_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         resignation.employee_code?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         resignation.reason?.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesStatus && matchesSearch;
  });

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-red-600"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-white rounded-xl p-4 border border-black">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-gray-600 text-sm font-medium">Total Resignations</p>
              <p className="text-2xl font-bold text-gray-900 mt-1">{resignations.length}</p>
            </div>
            <div className="p-2 bg-gray-100 rounded-lg border border-gray-300">
              <FileText className="h-5 w-5 text-gray-600" />
            </div>
          </div>
        </div>
        
        <div className="bg-white rounded-xl p-4 border border-black">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-gray-600 text-sm font-medium">In Progress</p>
              <p className="text-2xl font-bold text-gray-900 mt-1">{resignations.filter(r => calculateOverallStatus(r) === 'In Progress').length}</p>
            </div>
            <div className="p-2 bg-gray-100 rounded-lg border border-gray-300">
              <Clock className="h-5 w-5 text-gray-600" />
            </div>
          </div>
        </div>
        
        <div className="bg-white rounded-xl p-4 border border-black">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-gray-600 text-sm font-medium">Completed</p>
              <p className="text-2xl font-bold text-gray-900 mt-1">{resignations.filter(r => calculateOverallStatus(r) === 'Completed').length}</p>
            </div>
            <div className="p-2 bg-gray-100 rounded-lg border border-gray-300">
              <CheckCircle className="h-5 w-5 text-gray-600" />
            </div>
          </div>
        </div>
        
        <div className="bg-white rounded-xl p-4 border border-black">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-gray-600 text-sm font-medium">Initiated</p>
              <p className="text-2xl font-bold text-gray-900 mt-1">{resignations.filter(r => calculateOverallStatus(r) === 'Initiated').length}</p>
            </div>
            <div className="p-2 bg-gray-100 rounded-lg border border-gray-300">
              <Users className="h-5 w-5 text-gray-600" />
            </div>
          </div>
        </div>
      </div>

      {/* Controls */}
      <div className="rounded-xl border border-black p-4" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
        <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center justify-between">
          <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center flex-1">
            <div className="relative flex-1 max-w-md">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500" size={16} />
              <input
                type="text"
                placeholder="Search by employee name, code, or reason..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10 pr-4 py-2 border border-black rounded-xl focus:ring-2 focus:ring-gray-500 focus:border-gray-500 w-full transition-all duration-200"
              />
            </div>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="border border-black rounded-xl px-4 py-2 focus:ring-2 focus:ring-gray-500 focus:border-gray-500 transition-all duration-200"
            >
              <option value="All">All Status</option>
              <option value="Initiated">Initiated</option>
              <option value="In Progress">In Progress</option>
              <option value="Completed">Completed</option>
            </select>
          </div>
          {canApply && (
            <button 
              onClick={() => setShowApplyForm(true)}
              className="flex items-center gap-2 px-4 py-2 bg-gray-900 text-white rounded-xl hover:bg-gray-700 border border-black transition-all duration-200"
            >
              <Plus className="w-4 h-4" />
              Apply Resignation
            </button>
          )}
        </div>
      </div>

      {/* Apply Resignation Modal */}
      {showApplyForm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white p-6 rounded-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto shadow-2xl">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-2xl font-bold text-primary">Apply Resignation</h2>
              <button 
                onClick={() => setShowApplyForm(false)}
                className=" hover:text-secondary transition-colors" style={{color: 'var(--text-muted, #6b7280)'}}
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            
            <form onSubmit={handleApplyResignation} className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="md:col-span-2">
                  <label className="block text-sm font-semibold text-secondary mb-2">Employee</label>
                  <select 
                    value={formData.employee_id} 
                    onChange={(e) => setFormData({...formData, employee_id: e.target.value})}
                    className="w-full border border-black rounded-xl px-4 py-3 bg-white focus:ring-2 focus:ring-black focus:border-black transition-all duration-200"
                    required
                  >
                    <option value="">Select Employee ({employees.length} available)</option>
                    {employees.map(emp => (
                      <option key={emp.id} value={emp.id}>
                        {emp.employee_code || `EMP${emp.id}`} - {emp.name}
                      </option>
                    ))}
                  </select>
                </div>
                
                <div>
                  <label className="block text-sm font-semibold text-secondary mb-2">Resignation Date</label>
                  <input
                    type="date"
                    value={formData.resignation_date}
                    onChange={(e) => setFormData({...formData, resignation_date: e.target.value})}
                    className="w-full border border-black rounded-xl px-4 py-3 bg-white focus:ring-2 focus:ring-black focus:border-black transition-all duration-200"
                    required
                  />
                </div>
                
                <div className="md:col-span-2">
                  <label className="block text-sm font-semibold text-secondary mb-2">Reason for Resignation</label>
                  <textarea
                    value={formData.reason}
                    onChange={(e) => setFormData({...formData, reason: e.target.value})}
                    className="w-full border border-black rounded-xl px-4 py-3 bg-white focus:ring-2 focus:ring-black focus:border-black transition-all duration-200"
                    placeholder="Please provide reason for resignation"
                    rows="3"
                  />
                </div>
                
                <div className="md:col-span-2">
                  <label className="block text-sm font-semibold text-secondary mb-2">Additional Notes</label>
                  <textarea
                    value={formData.notes}
                    onChange={(e) => setFormData({...formData, notes: e.target.value})}
                    className="w-full border border-black rounded-xl px-4 py-3 bg-white focus:ring-2 focus:ring-black focus:border-black transition-all duration-200"
                    placeholder="Any additional notes or comments"
                    rows="2"
                  />
                </div>
              </div>
              
              <div className="flex gap-4 pt-4">
                <button 
                  type="submit" 
                  className="flex-1 bg-black text-white px-6 py-3 rounded-xl hover:bg-gray-800 font-semibold transition-all duration-200 border border-black"
                >
                  Apply Resignation
                </button>
                <button 
                  type="button" 
                  onClick={() => setShowApplyForm(false)}
                  className="flex-1 bg-white text-black px-6 py-3 rounded-xl hover:bg-gray-100 font-semibold transition-all duration-200 border border-black"
                >
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Resignations Table */}
      <div className="bg-white rounded-xl border border-black overflow-hidden">
        <div className="p-4 border-b border-black bg-gray-50">
          <h2 className="text-lg font-bold text-gray-900">Resignation List ({filteredResignations.length})</h2>
          <p className="text-sm text-gray-600 mt-1">Track and manage employee resignations</p>
        </div>
        
        {/* Desktop Table View */}
        <div className="hidden md:block overflow-x-auto">
          <table className="w-full border-collapse">
            <thead className="bg-gray-100">
              <tr>
                <th className="text-left px-4 py-3 text-xs font-semibold text-gray-700 uppercase tracking-wider border-b border-black">Employee</th>
                <th className="text-left px-4 py-3 text-xs font-semibold text-gray-700 uppercase tracking-wider border-b border-black">Last Working Day</th>
                <th className="text-left px-4 py-3 text-xs font-semibold text-gray-700 uppercase tracking-wider border-b border-black">Notice Period</th>
                <th className="text-left px-4 py-3 text-xs font-semibold text-gray-700 uppercase tracking-wider border-b border-black">Overall Status</th>
                <th className="text-left px-4 py-3 text-xs font-semibold text-gray-700 uppercase tracking-wider border-b border-black">Reason</th>
                <th className="text-left px-4 py-3 text-xs font-semibold text-gray-700 uppercase tracking-wider border-b border-black">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-black">
              {filteredResignations.map((resignation) => {
                const overallStatus = calculateOverallStatus(resignation);
                return (
                  <tr key={resignation.id} className="hover:bg-gray-50 transition-colors duration-150">
                    <td className="px-4 py-3">
                      <div>
                        <div className="font-semibold text-gray-900">{resignation.employee_name}</div>
                        <div className="text-sm text-gray-600">{resignation.employee_code}</div>
                      </div>
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-900">
                      {resignation.last_working_day ? new Date(resignation.last_working_day).toLocaleDateString() : '-'}
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-medium text-gray-900">{resignation.notice_period} days</span>
                        {resignation.notice_served && <span className="text-green-500 text-lg">✓</span>}
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-1 rounded-lg text-xs font-medium border border-black ${getStatusColor(overallStatus)}`}>
                        {overallStatus}
                      </span>
                      <div className="text-xs text-gray-600 mt-1 space-y-1">
                        <div>H: {resignation.handover_status || 'Pending'}</div>
                        <div>C: {resignation.clearance_status || 'Pending'}</div>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <div className="max-w-xs">
                        <p className="text-sm text-gray-900 truncate" title={resignation.reason}>
                          {resignation.reason || '-'}
                        </p>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex flex-col gap-2">
                        {canManageHandover && (
                          <select 
                            onChange={(e) => updateStatus(resignation.id, 'handover_status', e.target.value)}
                            className="border border-black rounded-lg px-2 py-1 text-xs focus:ring-2 focus:ring-gray-500 focus:border-gray-500 transition-all duration-200"
                            value={resignation.handover_status || 'Pending'}
                          >
                            <option value="Pending">Handover Pending</option>
                            <option value="In Progress">Handover In Progress</option>
                            <option value="Completed">Handover Completed</option>
                          </select>
                        )}
                        
                        {canManageClearance && (
                          <select 
                            onChange={(e) => updateStatus(resignation.id, 'clearance_status', e.target.value)}
                            className="border border-black rounded-lg px-2 py-1 text-xs focus:ring-2 focus:ring-gray-500 focus:border-gray-500 transition-all duration-200"
                            value={resignation.clearance_status || 'Pending'}
                          >
                            <option value="Pending">Clearance Pending</option>
                            <option value="In Progress">Clearance In Progress</option>
                            <option value="Completed">Clearance Done</option>
                          </select>
                        )}
                        
                        {canManageAssets && (
                          <select 
                            onChange={(e) => updateStatus(resignation.id, 'asset_return_status', e.target.value)}
                            className="border border-black rounded-lg px-2 py-1 text-xs focus:ring-2 focus:ring-gray-500 focus:border-gray-500 transition-all duration-200"
                            value={resignation.asset_return_status || 'Pending'}
                          >
                            <option value="Pending">Assets Pending</option>
                            <option value="Completed">Assets Returned</option>
                          </select>
                        )}
                        
                        {canManageSettlement && (
                          <select 
                            onChange={(e) => updateStatus(resignation.id, 'final_settlement', e.target.value)}
                            className="border border-black rounded-lg px-2 py-1 text-xs focus:ring-2 focus:ring-gray-500 focus:border-gray-500 transition-all duration-200"
                            value={resignation.final_settlement_status || 'Pending'}
                          >
                            <option value="Pending">Settlement Pending</option>
                            <option value="Completed">Settlement Done</option>
                          </select>
                        )}
                        
                        {!canManageHandover && !canManageClearance && !canManageAssets && !canManageSettlement && (
                          <span className="text-xs text-gray-500">View only</span>
                        )}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        {/* Mobile Card View */}
        <div className="md:hidden">
          {filteredResignations.map((resignation) => {
            const overallStatus = calculateOverallStatus(resignation);
            return (
              <div key={resignation.id} className="p-4 border-b border-black last:border-b-0">
                <div className="space-y-3">
                  {/* Employee Info */}
                  <div className="flex justify-between items-start">
                    <div>
                      <h3 className="font-semibold text-gray-900">{resignation.employee_name}</h3>
                      <p className="text-sm text-gray-600">{resignation.employee_code}</p>
                    </div>
                    <span className={`px-2 py-1 rounded-lg text-xs font-medium border border-black ${getStatusColor(overallStatus)}`}>
                      {overallStatus}
                    </span>
                  </div>

                  {/* Details */}
                  <div className="grid grid-cols-2 gap-3 text-sm">
                    <div>
                      <span className="text-gray-600">Last Working:</span>
                      <p className="font-medium text-gray-900">
                        {resignation.last_working_day ? new Date(resignation.last_working_day).toLocaleDateString() : '-'}
                      </p>
                    </div>
                    <div>
                      <span className="text-gray-600">Notice Period:</span>
                      <p className="font-medium text-gray-900">
                        {resignation.notice_period} days
                        {resignation.notice_served && <span className="text-green-500 ml-1">✓</span>}
                      </p>
                    </div>
                  </div>

                  {/* Status Details */}
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <div className="flex justify-between">
                      <span className="text-gray-600">Handover:</span>
                      <span className="font-medium">{resignation.handover_status || 'Pending'}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">Clearance:</span>
                      <span className="font-medium">{resignation.clearance_status || 'Pending'}</span>
                    </div>
                  </div>

                  {/* Reason */}
                  {resignation.reason && (
                    <div>
                      <span className="text-gray-600 text-sm">Reason:</span>
                      <p className="text-sm text-gray-900 mt-1">{resignation.reason}</p>
                    </div>
                  )}

                  {/* Actions */}
                  <div className="space-y-2">
                    {canManageHandover && (
                      <div>
                        <label className="block text-xs text-gray-600 mb-1">Handover Status</label>
                        <select 
                          onChange={(e) => updateStatus(resignation.id, 'handover_status', e.target.value)}
                          className="w-full border border-black rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-gray-500 focus:border-gray-500 transition-all duration-200"
                          value={resignation.handover_status || 'Pending'}
                        >
                          <option value="Pending">Handover Pending</option>
                          <option value="In Progress">Handover In Progress</option>
                          <option value="Completed">Handover Completed</option>
                        </select>
                      </div>
                    )}
                    
                    {canManageClearance && (
                      <div>
                        <label className="block text-xs text-gray-600 mb-1">Clearance Status</label>
                        <select 
                          onChange={(e) => updateStatus(resignation.id, 'clearance_status', e.target.value)}
                          className="w-full border border-black rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-gray-500 focus:border-gray-500 transition-all duration-200"
                          value={resignation.clearance_status || 'Pending'}
                        >
                          <option value="Pending">Clearance Pending</option>
                          <option value="In Progress">Clearance In Progress</option>
                          <option value="Completed">Clearance Done</option>
                        </select>
                      </div>
                    )}
                    
                    {canManageAssets && (
                      <div>
                        <label className="block text-xs text-gray-600 mb-1">Asset Return</label>
                        <select 
                          onChange={(e) => updateStatus(resignation.id, 'asset_return_status', e.target.value)}
                          className="w-full border border-black rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-gray-500 focus:border-gray-500 transition-all duration-200"
                          value={resignation.asset_return_status || 'Pending'}
                        >
                          <option value="Pending">Assets Pending</option>
                          <option value="Completed">Assets Returned</option>
                        </select>
                      </div>
                    )}
                    
                    {canManageSettlement && (
                      <div>
                        <label className="block text-xs text-gray-600 mb-1">Final Settlement</label>
                        <select 
                          onChange={(e) => updateStatus(resignation.id, 'final_settlement', e.target.value)}
                          className="w-full border border-black rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-gray-500 focus:border-gray-500 transition-all duration-200"
                          value={resignation.final_settlement_status || 'Pending'}
                        >
                          <option value="Pending">Settlement Pending</option>
                          <option value="Completed">Settlement Done</option>
                        </select>
                      </div>
                    )}
                    
                    {!canManageHandover && !canManageClearance && !canManageAssets && !canManageSettlement && (
                      <div className="text-center py-2">
                        <span className="text-sm text-gray-500">View only access</span>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
          
        {filteredResignations.length === 0 && (
          <div className="text-center py-12">
            <div className=" mb-4" style={{color: 'var(--text-muted, #6b7280)'}}>
              <FileText className="w-12 h-12 mx-auto" />
            </div>
            <h3 className="text-lg font-medium text-primary mb-2">
              {statusFilter !== 'All' || searchTerm ? 'No resignations match your filters' : 'No resignations found'}
            </h3>
            <p className="" style={{color: 'var(--text-muted, #6b7280)'}}>
              {statusFilter !== 'All' || searchTerm ? 'Try adjusting your search criteria' : 'Start by applying a resignation'}
            </p>
          </div>
        )}
      </div>
      <Toast {...toast} />
    </div>
  );
};

export default ResignationTracking;
