import { useEffect, useState } from "react";
import { FileText, Users, CheckCircle, AlertTriangle, Plus, Edit, Trash2, RotateCcw, Eye, EyeOff } from "lucide-react";
import api from "../../api";
import Toast from "../../components/Toast";
import useToast from "../../utils/useToast";
import { hasPermission, isAdmin } from "../../utils/permissions";

export default function LabourRegister() {
  // Permission checks
  const canView = isAdmin() || hasPermission("view_labour_register");
  const canAdd = isAdmin() || hasPermission("add_labour_register");
  const canEdit = isAdmin() || hasPermission("edit_labour_register");
  const canDelete = isAdmin() || hasPermission("delete_labour_register");
  const canViewDeleted = isAdmin() || hasPermission("view_deleted_labour_register");
  const canRestore = isAdmin() || hasPermission("restore_labour_register");

  if (!canView) {
    return (
      <div className="p-6 text-center">
        <div className="bg-white rounded-2xl border border-gray-200 p-8 max-w-md mx-auto">
          <h3 className="text-lg font-medium text-gray-900 mb-2">Access Denied</h3>
          <p className="text-gray-600">You do not have permission to view Labour Register.</p>
        </div>
      </div>
    );
  }
  const [form, setForm] = useState({
    employee_id: "",
    employee_name: "",
    register_type: "",
    register_number: "",
    issue_date: "",
    expiry_date: "",
    issuing_authority: "",
    compliance_status: "Active",
    month: "",
    year: "",
    department: "",
    designation: "",
    remarks: "",
  });

  const [registers, setRegisters] = useState([]);
  const [deletedRegisters, setDeletedRegisters] = useState([]);
  const [showDeleted, setShowDeleted] = useState(false);
  const [employees, setEmployees] = useState([]);
  const [editingRecord, setEditingRecord] = useState(null);
  const [showCustomRegisterType, setShowCustomRegisterType] = useState(false);
  const { toast, showToast, hideToast } = useToast();

  // Load existing labour registers and employees
  useEffect(() => {
    const fetchBrandingColors = async () => {
      try {
        const tenantCode = localStorage.getItem('tenant_code');
        if (tenantCode) {
          const response = await api.get(`/auth/branding/${tenantCode}`);
          document.documentElement.style.setProperty('--primary-color', response.data.primary_color || '#2862e9');
          document.documentElement.style.setProperty('--secondary-color', response.data.secondary_color || '#474e71');
        }
      } catch (error) {
        console.error('Error fetching branding colors:', error);
      }
    };
    fetchBrandingColors();

    async function fetchData() {
      try {
        const tenant = localStorage.getItem("tenant_db");
        const token = localStorage.getItem("access_token");
        
        console.log('Fetching employee data for Labour Register, tenant:', tenant);
        
        // Fetch employees from both onboarding and user management
        let allEmployees = [];
        
        try {
          const onboardingRes = await api.get('/recruitment/onboarding/list');
          console.log('Onboarding response:', onboardingRes.data);
          
          const onboardedEmployees = onboardingRes.data || [];
          
          // Process onboarded employees
          const validOnboardedEmployees = onboardedEmployees.filter(emp => {
            if (!emp.employee_id || emp.employee_id.trim() === '') return false;
            const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
            return !isAutoGenerated;
          });
          
          const onboardedData = validOnboardedEmployees.map(emp => ({
            id: emp.application_id || emp.id,
            employee_id: emp.employee_id,
            name: emp.candidate_name,
            department: emp.department,
            designation: emp.job_title
          }));
          
          allEmployees = [...onboardedData];
          console.log('Processed onboarded employees:', allEmployees);
        } catch (onboardingError) {
          console.error('Error fetching onboarding data:', onboardingError);
        }
        
        try {
          const usersRes = await api.get(`/hospitals/users/${tenant}/list`);
          console.log('Users response:', usersRes.data);
          
          const userEmployees = usersRes.data?.users || usersRes.data || [];
          
          // Process user management employees
          const userEmployeeData = userEmployees
            .filter(user => user.employee_code)
            .map(user => ({
              id: `user_${user.id}`,
              employee_id: user.employee_code,
              name: user.name,
              department: user.department_name,
              designation: user.designation || 'N/A'
            }));
          
          // Combine employees, avoiding duplicates
          userEmployeeData.forEach(userEmp => {
            const existingIndex = allEmployees.findIndex(emp => emp.employee_id === userEmp.employee_id);
            if (existingIndex === -1) {
              allEmployees.push(userEmp);
            } else {
              allEmployees[existingIndex] = userEmp;
            }
          });
          
          console.log('Final combined employees:', allEmployees);
        } catch (usersError) {
          console.error('Error fetching users data:', usersError);
        }
        
        // If no employees found, add some sample data for testing
        if (allEmployees.length === 0) {
          console.log('No employees found, adding sample data');
          allEmployees = [
            { id: 'sample1', employee_id: '1234', name: 'Shifana', department: 'HR', designation: 'Manager' },
            { id: 'sample2', employee_id: '52044', name: 'Harinie S', department: 'IT', designation: 'Developer' },
            { id: 'sample3', employee_id: '52045', name: 'Harinie S', department: 'IT', designation: 'Developer' },
            { id: 'sample4', employee_id: '5204', name: 'Rudra', department: 'Finance', designation: 'Analyst' },
            { id: 'sample5', employee_id: '9002', name: 'Arun A', department: 'Operations', designation: 'Executive' },
            { id: 'sample6', employee_id: '0626', name: 'Kamatchi', department: 'HR', designation: 'Executive' },
            { id: 'sample7', employee_id: '0987', name: 'Haru S', department: 'IT', designation: 'Developer' },
            { id: 'sample8', employee_id: '1105', name: 'Sushini', department: 'Marketing', designation: 'Executive' }
          ];
        }
        
        setEmployees(allEmployees);
        
        // Fetch labour registers
        const res = await api.get("/api/compliance/labour");
        setRegisters(res.data);
        
        // Fetch deleted labour registers only if user has permission
        if (canViewDeleted) {
          try {
            const deletedRes = await api.get("/api/compliance/labour/deleted");
            setDeletedRegisters(deletedRes.data);
          } catch (err) {
            console.log("No permission to view deleted records", err);
            setDeletedRegisters([]);
          }
        }
      } catch (err) {
        console.log("Error loading data", err);
      }
    }
    fetchData();
  }, []);

  function handleChange(e) {
    const { name, value } = e.target;
    
    // If employee is selected, auto-fill employee name
    if (name === 'employee_id' && value) {
      const selectedEmployee = employees.find(emp => emp.id.toString() === value);
      if (selectedEmployee) {
        setForm({ 
          ...form, 
          [name]: value,
          employee_name: selectedEmployee.name || selectedEmployee.first_name + ' ' + (selectedEmployee.last_name || ''),
          department: selectedEmployee.department || '',
          designation: selectedEmployee.designation || ''
        });
        return;
      }
    }
    
    setForm({ ...form, [name]: value });
  }

  async function handleSubmit(e) {
    e.preventDefault();
    try {
      // Use custom register type if "Other" is selected
      const submitData = {
        ...form,
        register_type: form.register_type === 'Other' ? form.custom_register_type : form.register_type
      };
      
      let response;
      if (editingRecord) {
        response = await api.put(`/api/compliance/labour/${editingRecord.id}`, submitData);
        showToast("Labour Register Updated Successfully!");
        setEditingRecord(null);
      } else {
        response = await api.post("/api/compliance/labour", submitData);
        showToast("Labour Register Added Successfully!");
      }
      
      // Reset form
      setForm({
        employee_id: "",
        employee_name: "",
        register_type: "",
        custom_register_type: "",
        register_number: "",
        issue_date: "",
        expiry_date: "",
        issuing_authority: "",
        compliance_status: "Active",
        month: "",
        year: "",
        department: "",
        designation: "",
        remarks: "",
      });
      setShowCustomRegisterType(false);
      
      // Refresh the list
      const res = await api.get("/api/compliance/labour");
      setRegisters(res.data);
      
      // Refresh deleted list only if user has permission
      if (canViewDeleted) {
        try {
          const deletedRes = await api.get("/api/compliance/labour/deleted");
          setDeletedRegisters(deletedRes.data);
        } catch (err) {
          console.log("No permission to view deleted records", err);
        }
      }
    } catch (err) {
      console.error('Failed to save labour register:', err);
      showToast("Failed to save labour register", 'error');
    }
  }

  function handleEdit(record) {
    setEditingRecord(record);
    setForm({
      employee_id: record.employee_id,
      employee_name: record.employee_name,
      register_type: record.register_type,
      register_number: "",
      issue_date: "",
      expiry_date: "",
      issuing_authority: "",
      compliance_status: record.compliance_status || "Active",
      month: record.month,
      year: record.year.toString(),
      department: "",
      designation: "",
      remarks: record.remarks || "",
    });
  }

  async function handleDelete(recordId) {
    if (!window.confirm('Are you sure you want to delete this record?')) return;
    
    try {
      await api.delete(`/api/compliance/labour/${recordId}`);
      showToast("Record deleted successfully!");
      
      // Refresh the list
      const res = await api.get("/api/compliance/labour");
      setRegisters(res.data);
      
      // Refresh deleted list only if user has permission
      if (canViewDeleted) {
        try {
          const deletedRes = await api.get("/api/compliance/labour/deleted");
          setDeletedRegisters(deletedRes.data);
        } catch (err) {
          console.log("No permission to view deleted records", err);
        }
      }
    } catch (err) {
      console.error('Failed to delete record:', err);
      showToast("Failed to delete record", 'error');
    }
  }

  async function handleRestore(recordId) {
    if (!window.confirm('Are you sure you want to restore this record?')) return;
    
    try {
      await api.put(`/api/compliance/labour/restore/${recordId}`);
      showToast("Record restored successfully!");
      
      // Refresh both lists
      const res = await api.get("/api/compliance/labour");
      setRegisters(res.data);
      
      if (canViewDeleted) {
        try {
          const deletedRes = await api.get("/api/compliance/labour/deleted");
          setDeletedRegisters(deletedRes.data);
        } catch (err) {
          console.log("No permission to view deleted records", err);
        }
      }
    } catch (err) {
      console.error('Failed to restore record:', err);
      showToast("Failed to restore record", 'error');
    }
  }

  function cancelEdit() {
    setEditingRecord(null);
    setForm({
      employee_id: "",
      employee_name: "",
      register_type: "",
      register_number: "",
      issue_date: "",
      expiry_date: "",
      issuing_authority: "",
      compliance_status: "Active",
      month: "",
      year: "",
      department: "",
      designation: "",
      remarks: "",
    });
  }

  return (
    <div className="space-y-6">
      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-white rounded-xl p-5 border border-gray-200 shadow-sm hover:shadow-md transition-all duration-200">
          <div className="flex items-center justify-between">
            <div className="min-w-0 flex-1">
              <p className="text-gray-500 text-xs font-medium uppercase tracking-wider mb-2">Total Records</p>
              <p className="text-2xl font-bold text-gray-900">{registers.length}</p>
              <p className="text-gray-400 text-xs mt-1">Active records</p>
            </div>
            <div className="p-3 rounded-lg" style={{
              backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
            }}>
              <FileText className="h-6 w-6" style={{
                color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
              }} />
            </div>
          </div>
        </div>
        
        <div className="bg-white rounded-xl p-5 border border-gray-200 shadow-sm hover:shadow-md transition-all duration-200">
          <div className="flex items-center justify-between">
            <div className="min-w-0 flex-1">
              <p className="text-gray-500 text-xs font-medium uppercase tracking-wider mb-2">Active</p>
              <p className="text-2xl font-bold text-gray-900">{registers.filter(r => r.compliance_status === 'Active').length}</p>
              <p className="text-gray-400 text-xs mt-1">Compliant</p>
            </div>
            <div className="p-3 rounded-lg" style={{
              backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
            }}>
              <CheckCircle className="h-6 w-6" style={{
                color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
              }} />
            </div>
          </div>
        </div>
        
        <div className="bg-white rounded-xl p-5 border border-gray-200 shadow-sm hover:shadow-md transition-all duration-200">
          <div className="flex items-center justify-between">
            <div className="min-w-0 flex-1">
              <p className="text-gray-500 text-xs font-medium uppercase tracking-wider mb-2">Pending</p>
              <p className="text-2xl font-bold text-gray-900">{registers.filter(r => r.compliance_status === 'Pending').length}</p>
              <p className="text-gray-400 text-xs mt-1">To review</p>
            </div>
            <div className="p-3 rounded-lg" style={{
              backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
            }}>
              <AlertTriangle className="h-6 w-6" style={{
                color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
              }} />
            </div>
          </div>
        </div>
        
        <div className="bg-white rounded-xl p-5 border border-gray-200 shadow-sm hover:shadow-md transition-all duration-200">
          <div className="flex items-center justify-between">
            <div className="min-w-0 flex-1">
              <p className="text-gray-500 text-xs font-medium uppercase tracking-wider mb-2">Employees</p>
              <p className="text-2xl font-bold text-gray-900">{new Set(registers.map(r => r.employee_id)).size}</p>
              <p className="text-gray-400 text-xs mt-1">Unique count</p>
            </div>
            <div className="p-3 rounded-lg" style={{
              backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
            }}>
              <Users className="h-6 w-6" style={{
                color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
              }} />
            </div>
          </div>
        </div>
      </div>

      {/* Form Section */}
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm">
        <div className="p-5 border-b border-gray-100">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg" style={{
              backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
            }}>
              <FileText className="h-5 w-5" style={{
                color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
              }} />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-gray-900">Add Labour Register Entry</h2>
              <p className="text-sm text-gray-600">Maintain employee records and labour law compliance</p>
            </div>
          </div>
        </div>
        
        <div className="p-6">
        <form onSubmit={handleSubmit} className="grid grid-cols-2 gap-6 mb-8">
          {/* Employee ID */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Employee ID <span className="text-red-500">*</span>
            </label>
            <select
              required
              name="employee_id"
              value={form.employee_id}
              onChange={(e) => {
                const selectedId = e.target.value;
                console.log('Selected employee ID:', selectedId);
                const selectedEmployee = employees.find(emp => emp.employee_id === selectedId);
                console.log('Found employee:', selectedEmployee);
                if (selectedEmployee) {
                  setForm({
                    ...form,
                    employee_id: selectedEmployee.employee_id,
                    employee_name: selectedEmployee.name,
                    department: selectedEmployee.department,
                    designation: selectedEmployee.designation
                  });
                } else {
                  setForm({ ...form, employee_id: selectedId });
                }
              }}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Employee ID</option>
              {employees && employees.length > 0 ? (
                employees.map((employee) => (
                  <option key={employee.id} value={employee.employee_id}>
                    {employee.employee_id} - {employee.name}
                  </option>
                ))
              ) : (
                <option value="" disabled>No employees found</option>
              )}
            </select>
          </div>

          {/* Employee Name */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Employee Name <span className="text-red-500">*</span>
            </label>
            <select
              required
              name="employee_name"
              value={form.employee_name}
              onChange={(e) => {
                const selectedName = e.target.value;
                console.log('Selected employee name:', selectedName);
                const selectedEmployee = employees.find(emp => emp.name === selectedName);
                console.log('Found employee by name:', selectedEmployee);
                if (selectedEmployee) {
                  setForm({
                    ...form,
                    employee_id: selectedEmployee.employee_id,
                    employee_name: selectedEmployee.name,
                    department: selectedEmployee.department,
                    designation: selectedEmployee.designation
                  });
                } else {
                  setForm({ ...form, employee_name: selectedName });
                }
              }}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Employee Name</option>
              {employees && employees.length > 0 ? (
                employees.map((employee) => (
                  <option key={employee.id} value={employee.name}>
                    {employee.name} ({employee.employee_id})
                  </option>
                ))
              ) : (
                <option value="" disabled>No employees found</option>
              )}
            </select>
          </div>

          {/* Register Type */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Register Type <span className="text-red-500">*</span>
            </label>
            <select
              required
              name="register_type"
              value={form.register_type}
              onChange={(e) => {
                const value = e.target.value;
                setShowCustomRegisterType(value === 'Other');
                setForm({ ...form, register_type: value, custom_register_type: value === 'Other' ? form.custom_register_type : '' });
              }}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Register Type</option>
              <option value="Form I - Muster Roll">Form I - Muster Roll</option>
              <option value="Form II - Register of Wages">Form II - Register of Wages</option>
              <option value="Form III - Register of Overtime">Form III - Register of Overtime</option>
              <option value="Form IV - Register of Deductions">Form IV - Register of Deductions</option>
              <option value="Form V - Register of Fines">Form V - Register of Fines</option>
              <option value="Form VI - Register of Advances">Form VI - Register of Advances</option>
              <option value="Form VII - Register of Damages">Form VII - Register of Damages</option>
              <option value="Form VIII - Register of Injuries">Form VIII - Register of Injuries</option>
              <option value="Form IX - Register of Adult Workers">Form IX - Register of Adult Workers</option>
              <option value="Form X - Register of Young Persons">Form X - Register of Young Persons</option>
              <option value="Other">Other</option>
            </select>
          </div>

          {/* Custom Register Type */}
          {showCustomRegisterType && (
            <div>
              <label className="block text-sm font-medium mb-1">
                Custom Register Type <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                required
                name="custom_register_type"
                value={form.custom_register_type || ''}
                onChange={handleChange}
                className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="Enter custom register type"
              />
            </div>
          )}

          {/* Register Number */}
          <div>
            <label className="block text-sm font-medium mb-1">Register Number</label>
            <input
              type="text"
              name="register_number"
              value={form.register_number}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Register Number"
            />
          </div>

          {/* Issue Date */}
          <div>
            <label className="block text-sm font-medium mb-1">Issue Date</label>
            <input
              type="date"
              name="issue_date"
              value={form.issue_date}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>

          {/* Expiry Date */}
          <div>
            <label className="block text-sm font-medium mb-1">Expiry Date</label>
            <input
              type="date"
              name="expiry_date"
              value={form.expiry_date}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>

          {/* Issuing Authority */}
          <div>
            <label className="block text-sm font-medium mb-1">Issuing Authority</label>
            <input
              type="text"
              name="issuing_authority"
              value={form.issuing_authority}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Issuing Authority"
            />
          </div>

          {/* Compliance Status */}
          <div>
            <label className="block text-sm font-medium mb-1">Compliance Status</label>
            <select
              name="compliance_status"
              value={form.compliance_status}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="Active">Active</option>
              <option value="Inactive">Inactive</option>
              <option value="Pending">Pending</option>
              <option value="Expired">Expired</option>
            </select>
          </div>

          {/* Month */}
          <div>
            <label className="block text-sm font-medium mb-1">Month</label>
            <select
              name="month"
              value={form.month}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Month</option>
              <option value="01">January</option>
              <option value="02">February</option>
              <option value="03">March</option>
              <option value="04">April</option>
              <option value="05">May</option>
              <option value="06">June</option>
              <option value="07">July</option>
              <option value="08">August</option>
              <option value="09">September</option>
              <option value="10">October</option>
              <option value="11">November</option>
              <option value="12">December</option>
            </select>
          </div>

          {/* Year */}
          <div>
            <label className="block text-sm font-medium mb-1">Year</label>
            <input
              type="number"
              name="year"
              value={form.year}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Year"
              min="2020"
              max="2030"
            />
          </div>

          {/* Remarks */}
          <div className="col-span-2">
            <label className="block text-sm font-medium mb-1">Remarks</label>
            <textarea
              name="remarks"
              value={form.remarks}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent h-24"
              placeholder="Enter any additional remarks or notes"
            />
          </div>

          {/* Submit */}
          <div className="col-span-2 flex gap-4">
            {canAdd && (
              <button
                type="submit"
                style={{ backgroundColor: 'var(--primary-color, #2862e9)' }}
                className="px-6 py-2 text-white rounded-lg border border-black transition-colors"
                onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--secondary-color, #474e71)'}
                onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--primary-color, #2862e9)'}
              >
                {editingRecord ? 'Update' : 'Add'} Labour Register Entry
              </button>
            )}
            {editingRecord && (
              <button
                type="button"
                onClick={cancelEdit}
                style={{ backgroundColor: 'var(--secondary-color, #474e71)' }}
                className="px-6 py-2 text-white rounded-lg border border-black transition-colors"
                onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--primary-color, #2862e9)'}
                onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--secondary-color, #474e71)'}
              >
                Cancel Edit
              </button>
            )}
          </div>
        </form>
        </div>
      </div>

      {/* Records Table */}
      {(registers.length > 0 || deletedRegisters.length > 0) && (
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
          <div className="p-5 border-b border-gray-100">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg" style={{
                  backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}20`
                }}>
                  <FileText className="h-5 w-5" style={{
                    color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'
                  }} />
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-gray-900">
                    {showDeleted ? 'Deleted Records' : 'Existing Labour Registers'}
                  </h2>
                  <p className="text-sm text-gray-600">
                    {(showDeleted ? deletedRegisters : registers).length} records found
                  </p>
                </div>
              </div>
              {canViewDeleted && (
                <button
                  onClick={() => setShowDeleted(!showDeleted)}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border transition-colors text-sm font-medium"
                  style={{
                    backgroundColor: showDeleted ? getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5' : 'white',
                    color: showDeleted ? 'white' : '#374151',
                    borderColor: '#e5e7eb'
                  }}
                >
                  {showDeleted ? <EyeOff size={16} /> : <Eye size={16} />}
                  {showDeleted ? 'Show Active' : 'Show Deleted'} ({showDeleted ? registers.length : deletedRegisters.length})
                </button>
              )}
            </div>
          </div>
            <div className="overflow-x-auto">
              {/* Desktop Table View */}
              <div className="hidden md:block">
                <table className="w-full border-collapse">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-gray-200">Employee ID</th>
                      <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-gray-200">Employee Name</th>
                      <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-gray-200">Register Type</th>
                      <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-gray-200">Status</th>
                      <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-gray-200">Month/Year</th>
                      {showDeleted && <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-gray-200">Deleted At</th>}
                      <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-gray-200">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {(showDeleted ? deletedRegisters : registers).map((register, index) => (
                      <tr key={index} className={`hover:bg-gray-50 transition-colors duration-150 ${showDeleted ? 'bg-red-50' : ''}`}>
                        <td className="px-4 py-3 text-sm text-gray-900">{register.employee_id}</td>
                        <td className="px-4 py-3 text-sm text-gray-900">{register.employee_name}</td>
                        <td className="px-4 py-3 text-sm text-gray-900">{register.register_type}</td>
                        <td className="px-4 py-3">
                          <span className={`px-2 py-1 rounded-full text-xs ${
                            register.compliance_status === 'Active' ? 'bg-green-100 text-green-800' :
                            register.compliance_status === 'Expired' ? 'bg-red-100 text-red-800' :
                            register.compliance_status === 'Pending' ? 'bg-yellow-100 text-yellow-800' :
                            register.compliance_status === 'Deleted' ? 'bg-red-100 text-red-800' :
                            'bg-gray-100 text-gray-900'
                          }`}>
                            {register.compliance_status}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-sm text-gray-900">{register.month}/{register.year}</td>
                        {showDeleted && (
                          <td className="px-4 py-3 text-sm text-gray-900">
                            {register.deleted_at ? new Date(register.deleted_at).toLocaleDateString() : 'N/A'}
                          </td>
                        )}
                        <td className="px-4 py-3">
                          <div className="flex gap-2">
                            {showDeleted ? (
                              canRestore && (
                                <button
                                  onClick={() => handleRestore(register.id)}
                                  className="text-green-600 hover:text-green-800 p-1 rounded"
                                  title="Restore"
                                >
                                  <RotateCcw size={16} />
                                </button>
                              )
                            ) : (
                              <>
                                {canEdit && (
                                  <button
                                    onClick={() => handleEdit(register)}
                                    className="text-blue-600 hover:text-blue-800 p-1 rounded"
                                    title="Edit"
                                  >
                                    <Edit size={16} />
                                  </button>
                                )}
                                {canDelete && (
                                  <button
                                    onClick={() => handleDelete(register.id)}
                                    className="text-red-600 hover:text-red-800 p-1 rounded"
                                    title="Delete"
                                  >
                                    <Trash2 size={16} />
                                  </button>
                                )}
                              </>
                            )}
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Mobile Card View */}
              <div className="md:hidden">
                {(showDeleted ? deletedRegisters : registers).map((register, index) => (
                  <div key={index} className={`p-4 border-b border-gray-200 last:border-b-0 hover:bg-gray-50 transition-colors ${showDeleted ? 'bg-red-50' : ''}`}>
                    <div className="flex justify-between items-start mb-3">
                      <div className="flex-1">
                        <h4 className="font-medium text-gray-900">{register.employee_name}</h4>
                        <p className="text-sm text-gray-600">{register.employee_id}</p>
                      </div>
                      <span className={`px-2 py-1 rounded-full text-xs ${
                        register.compliance_status === 'Active' ? 'bg-green-100 text-green-800' :
                        register.compliance_status === 'Expired' ? 'bg-red-100 text-red-800' :
                        register.compliance_status === 'Pending' ? 'bg-yellow-100 text-yellow-800' :
                        register.compliance_status === 'Deleted' ? 'bg-red-100 text-red-800' :
                        'bg-gray-100 text-gray-900'
                      }`}>
                        {register.compliance_status}
                      </span>
                    </div>
                    
                    <div className="space-y-2 mb-3">
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Register Type:</span>
                        <span className="text-gray-900">{register.register_type}</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Period:</span>
                        <span className="text-gray-900">{register.month}/{register.year}</span>
                      </div>
                      {showDeleted && (
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-600">Deleted At:</span>
                          <span className="text-gray-900">{register.deleted_at ? new Date(register.deleted_at).toLocaleDateString() : 'N/A'}</span>
                        </div>
                      )}
                    </div>
                    
                    <div className="flex flex-wrap gap-2">
                      {showDeleted ? (
                        canRestore && (
                          <button
                            onClick={() => handleRestore(register.id)}
                            className="flex items-center gap-1 px-3 py-1 text-xs bg-green-50 text-green-700 rounded-md border border-green-300 hover:bg-green-100"
                          >
                            <RotateCcw className="w-3 h-3" />
                            Restore
                          </button>
                        )
                      ) : (
                        <>
                          {canEdit && (
                            <button
                              onClick={() => handleEdit(register)}
                              className="flex items-center gap-1 px-3 py-1 text-xs bg-gray-50 text-gray-700 rounded-md border border-gray-300 hover:bg-gray-100"
                            >
                              <Edit className="w-3 h-3" />
                              Edit
                            </button>
                          )}
                          {canDelete && (
                            <button
                              onClick={() => handleDelete(register.id)}
                              className="flex items-center gap-1 px-3 py-1 text-xs bg-gray-50 text-gray-700 rounded-md border border-gray-300 hover:bg-gray-100"
                            >
                              <Trash2 className="w-3 h-3" />
                              Delete
                            </button>
                          )}
                        </>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
      )}
      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}
