import { useEffect, useState } from "react";
import { FileText, Users, CheckCircle, AlertTriangle, Plus, Edit, Trash2 } from "lucide-react";
import api from "../../api";

export default function LabourRegister() {
  const [form, setForm] = useState({
    employee_id: "",
    employee_name: "",
    register_type: "",
    register_number: "",
    issue_date: "",
    expiry_date: "",
    issuing_authority: "",
    compliance_status: "Active",
    month: "",
    year: "",
    department: "",
    designation: "",
    remarks: "",
  });

  const [registers, setRegisters] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [editingRecord, setEditingRecord] = useState(null);
  const [showCustomRegisterType, setShowCustomRegisterType] = useState(false);

  // Load existing labour registers and employees
  useEffect(() => {
    async function fetchData() {
      try {
        const tenant = localStorage.getItem("tenant_db");
        const token = localStorage.getItem("access_token");
        
        // Fetch employees from both onboarding and user management like Statutory does
        const [onboardingRes, usersRes] = await Promise.all([
          api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
          fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
            headers: { Authorization: `Bearer ${token}` }
          }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
        ]);
        
        const onboardedEmployees = onboardingRes.data || [];
        const userEmployees = usersRes.users || [];
        
        // Process onboarded employees
        const validOnboardedEmployees = onboardedEmployees.filter(emp => {
          if (!emp.employee_id || emp.employee_id.trim() === '') return false;
          const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
          return !isAutoGenerated;
        });
        
        const onboardedData = validOnboardedEmployees.map(emp => ({
          id: emp.application_id,
          employee_id: emp.employee_id,
          name: emp.candidate_name,
          department: emp.department,
          designation: emp.job_title
        }));
        
        // Process user management employees
        const userEmployeeData = userEmployees
          .filter(user => user.employee_code)
          .map(user => ({
            id: `user_${user.id}`,
            employee_id: user.employee_code,
            name: user.name,
            department: user.department_name,
            designation: user.designation || 'N/A'
          }));
        
        // Combine employees
        const allEmployees = [...onboardedData];
        userEmployeeData.forEach(userEmp => {
          const existingIndex = allEmployees.findIndex(emp => emp.employee_id === userEmp.employee_id);
          if (existingIndex === -1) {
            allEmployees.push(userEmp);
          } else {
            allEmployees[existingIndex] = userEmp;
          }
        });
        
        setEmployees(allEmployees);
        
        // Fetch labour registers
        const res = await api.get("/api/compliance/labour");
        setRegisters(res.data);
      } catch (err) {
        console.log("Error loading data", err);
      }
    }
    fetchData();
  }, []);

  function handleChange(e) {
    const { name, value } = e.target;
    
    // If employee is selected, auto-fill employee name
    if (name === 'employee_id' && value) {
      const selectedEmployee = employees.find(emp => emp.id.toString() === value);
      if (selectedEmployee) {
        setForm({ 
          ...form, 
          [name]: value,
          employee_name: selectedEmployee.name || selectedEmployee.first_name + ' ' + (selectedEmployee.last_name || ''),
          department: selectedEmployee.department || '',
          designation: selectedEmployee.designation || ''
        });
        return;
      }
    }
    
    setForm({ ...form, [name]: value });
  }

  async function handleSubmit(e) {
    e.preventDefault();
    try {
      // Use custom register type if "Other" is selected
      const submitData = {
        ...form,
        register_type: form.register_type === 'Other' ? form.custom_register_type : form.register_type
      };
      
      let response;
      if (editingRecord) {
        response = await api.put(`/api/compliance/labour/${editingRecord.id}`, submitData);
        alert("Labour Register Updated Successfully!");
        setEditingRecord(null);
      } else {
        response = await api.post("/api/compliance/labour", submitData);
        alert("Labour Register Added Successfully!");
      }
      
      // Reset form
      setForm({
        employee_id: "",
        employee_name: "",
        register_type: "",
        custom_register_type: "",
        register_number: "",
        issue_date: "",
        expiry_date: "",
        issuing_authority: "",
        compliance_status: "Active",
        month: "",
        year: "",
        department: "",
        designation: "",
        remarks: "",
      });
      setShowCustomRegisterType(false);
      
      // Refresh the list
      const res = await api.get("/api/compliance/labour");
      setRegisters(res.data);
    } catch (err) {
      console.error('Failed to save labour register:', err);
      alert("Failed to save labour register");
    }
  }

  function handleEdit(record) {
    setEditingRecord(record);
    setForm({
      employee_id: record.employee_id,
      employee_name: record.employee_name,
      register_type: record.register_type,
      register_number: "",
      issue_date: "",
      expiry_date: "",
      issuing_authority: "",
      compliance_status: record.compliance_status || "Active",
      month: record.month,
      year: record.year.toString(),
      department: "",
      designation: "",
      remarks: record.remarks || "",
    });
  }

  async function handleDelete(recordId) {
    if (!confirm('Are you sure you want to delete this record?')) return;
    
    try {
      await api.delete(`/api/compliance/labour/${recordId}`);
      alert("Record deleted successfully!");
      
      // Refresh the list
      const res = await api.get("/api/compliance/labour");
      setRegisters(res.data);
    } catch (err) {
      console.error('Failed to delete record:', err);
      alert("Failed to delete record");
    }
  }

  function cancelEdit() {
    setEditingRecord(null);
    setForm({
      employee_id: "",
      employee_name: "",
      register_type: "",
      register_number: "",
      issue_date: "",
      expiry_date: "",
      issuing_authority: "",
      compliance_status: "Active",
      month: "",
      year: "",
      department: "",
      designation: "",
      remarks: "",
    });
  }

  return (
    <div className="space-y-6">
      <div className="rounded-xl shadow-sm border border-black p-6" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
        <form onSubmit={handleSubmit} className="grid grid-cols-2 gap-6 mb-8">
          {/* Employee ID */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Employee ID <span className="text-red-500">*</span>
            </label>
            <select
              required
              name="employee_id"
              value={form.employee_id}
              onChange={(e) => {
                const selectedId = e.target.value;
                const selectedEmployee = employees.find(emp => emp.employee_id === selectedId);
                if (selectedEmployee) {
                  setForm({
                    ...form,
                    employee_id: selectedEmployee.employee_id,
                    employee_name: selectedEmployee.name,
                    department: selectedEmployee.department,
                    designation: selectedEmployee.designation
                  });
                } else {
                  setForm({ ...form, employee_id: selectedId });
                }
              }}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Employee ID</option>
              {employees.map((employee) => (
                <option key={employee.id} value={employee.employee_id}>
                  {employee.employee_id}
                </option>
              ))}
            </select>
          </div>

          {/* Employee Name */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Employee Name <span className="text-red-500">*</span>
            </label>
            <select
              required
              name="employee_name"
              value={form.employee_name}
              onChange={(e) => {
                const selectedName = e.target.value;
                const selectedEmployee = employees.find(emp => emp.name === selectedName);
                if (selectedEmployee) {
                  setForm({
                    ...form,
                    employee_id: selectedEmployee.employee_id,
                    employee_name: selectedEmployee.name,
                    department: selectedEmployee.department,
                    designation: selectedEmployee.designation
                  });
                } else {
                  setForm({ ...form, employee_name: selectedName });
                }
              }}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Employee Name</option>
              {employees.map((employee) => (
                <option key={employee.id} value={employee.name}>
                  {employee.name}
                </option>
              ))}
            </select>
          </div>

          {/* Register Type */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Register Type <span className="text-red-500">*</span>
            </label>
            <select
              required
              name="register_type"
              value={form.register_type}
              onChange={(e) => {
                const value = e.target.value;
                setShowCustomRegisterType(value === 'Other');
                setForm({ ...form, register_type: value, custom_register_type: value === 'Other' ? form.custom_register_type : '' });
              }}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Register Type</option>
              <option value="Form I - Muster Roll">Form I - Muster Roll</option>
              <option value="Form II - Register of Wages">Form II - Register of Wages</option>
              <option value="Form III - Register of Overtime">Form III - Register of Overtime</option>
              <option value="Form IV - Register of Deductions">Form IV - Register of Deductions</option>
              <option value="Form V - Register of Fines">Form V - Register of Fines</option>
              <option value="Form VI - Register of Advances">Form VI - Register of Advances</option>
              <option value="Form VII - Register of Damages">Form VII - Register of Damages</option>
              <option value="Form VIII - Register of Injuries">Form VIII - Register of Injuries</option>
              <option value="Form IX - Register of Adult Workers">Form IX - Register of Adult Workers</option>
              <option value="Form X - Register of Young Persons">Form X - Register of Young Persons</option>
              <option value="Other">Other</option>
            </select>
          </div>

          {/* Custom Register Type */}
          {showCustomRegisterType && (
            <div>
              <label className="block text-sm font-medium mb-1">
                Custom Register Type <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                required
                name="custom_register_type"
                value={form.custom_register_type || ''}
                onChange={handleChange}
                className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="Enter custom register type"
              />
            </div>
          )}

          {/* Register Number */}
          <div>
            <label className="block text-sm font-medium mb-1">Register Number</label>
            <input
              type="text"
              name="register_number"
              value={form.register_number}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Register Number"
            />
          </div>

          {/* Issue Date */}
          <div>
            <label className="block text-sm font-medium mb-1">Issue Date</label>
            <input
              type="date"
              name="issue_date"
              value={form.issue_date}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>

          {/* Expiry Date */}
          <div>
            <label className="block text-sm font-medium mb-1">Expiry Date</label>
            <input
              type="date"
              name="expiry_date"
              value={form.expiry_date}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>

          {/* Issuing Authority */}
          <div>
            <label className="block text-sm font-medium mb-1">Issuing Authority</label>
            <input
              type="text"
              name="issuing_authority"
              value={form.issuing_authority}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Issuing Authority"
            />
          </div>

          {/* Compliance Status */}
          <div>
            <label className="block text-sm font-medium mb-1">Compliance Status</label>
            <select
              name="compliance_status"
              value={form.compliance_status}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="Active">Active</option>
              <option value="Inactive">Inactive</option>
              <option value="Pending">Pending</option>
              <option value="Expired">Expired</option>
            </select>
          </div>

          {/* Month */}
          <div>
            <label className="block text-sm font-medium mb-1">Month</label>
            <select
              name="month"
              value={form.month}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Month</option>
              <option value="01">January</option>
              <option value="02">February</option>
              <option value="03">March</option>
              <option value="04">April</option>
              <option value="05">May</option>
              <option value="06">June</option>
              <option value="07">July</option>
              <option value="08">August</option>
              <option value="09">September</option>
              <option value="10">October</option>
              <option value="11">November</option>
              <option value="12">December</option>
            </select>
          </div>

          {/* Year */}
          <div>
            <label className="block text-sm font-medium mb-1">Year</label>
            <input
              type="number"
              name="year"
              value={form.year}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Year"
              min="2020"
              max="2030"
            />
          </div>

          {/* Remarks */}
          <div className="col-span-2">
            <label className="block text-sm font-medium mb-1">Remarks</label>
            <textarea
              name="remarks"
              value={form.remarks}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent h-24"
              placeholder="Enter any additional remarks or notes"
            />
          </div>

          {/* Submit */}
          <div className="col-span-2 flex gap-4">
            <button
              type="submit"
              className="bg-gray-800 px-6 py-2 text-white rounded-lg border border-black hover:bg-gray-900 transition-colors"
            >
              {editingRecord ? 'Update' : 'Add'} Labour Register Entry
            </button>
            {editingRecord && (
              <button
                type="button"
                onClick={cancelEdit}
                className="bg-gray-600 px-6 py-2 text-white rounded-lg border border-black hover:bg-gray-700 transition-colors"
              >
                Cancel Edit
              </button>
            )}
          </div>
        </form>

        {/* Display existing registers */}
        {registers.length > 0 && (
          <div>
            <h3 className="text-lg font-semibold mb-4">Existing Labour Registers</h3>
            <div className="overflow-x-auto">
              <table className="w-full border border-black">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Employee ID</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Employee Name</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Register Type</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Status</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Month/Year</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Actions</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-black">
                  {registers.map((register, index) => (
                    <tr key={index} className="hover:bg-gray-50 border-b border-black">
                      <td className="px-4 py-2 text-sm border-r border-black">{register.employee_id}</td>
                      <td className="px-4 py-2 text-sm border-r border-black">{register.employee_name}</td>
                      <td className="px-4 py-2 text-sm border-r border-black">{register.register_type}</td>
                      <td className="px-4 py-2 text-sm border-r border-black">
                        <span className={`px-2 py-1 rounded-full text-xs ${
                          register.compliance_status === 'Active' ? 'bg-green-100 text-green-800' :
                          register.compliance_status === 'Expired' ? 'bg-red-100 text-red-800' :
                          register.compliance_status === 'Pending' ? 'bg-yellow-100 text-yellow-800' :
                          'bg-gray-100 text-gray-900'
                        }`}>
                          {register.compliance_status}
                        </span>
                      </td>
                      <td className="px-4 py-2 text-sm border-r border-black">{register.month}/{register.year}</td>
                      <td className="px-4 py-2 text-sm">
                        <div className="flex gap-2">
                          <button
                            onClick={() => handleEdit(register)}
                            className="text-blue-600 hover:text-blue-800 p-1 rounded"
                            title="Edit"
                          >
                            <Edit size={16} />
                          </button>
                          <button
                            onClick={() => handleDelete(register.id)}
                            className="text-red-600 hover:text-red-800 p-1 rounded"
                            title="Delete"
                          >
                            <Trash2 size={16} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
