import { useEffect, useState } from "react";
import { Calendar, Users, TrendingUp, Clock, CheckCircle } from "lucide-react";
import api from "../../api";

export default function LeaveCompliance() {
  const [form, setForm] = useState({
    employee_id: "",
    employee_name: "",
    total_working_days: "",
    actual_working_days: "",
    leaves_taken: "",
    paid_leaves: "",
    unpaid_leaves: "",
    sick_leaves: "",
    casual_leaves: "",
    earned_leaves: "",
    overtime_hours: "",
    weekly_off_days: "",
    public_holidays: "",
    month: "",
    year: "",
    department: "",
    designation: "",
    compliance_status: "Compliant",
    remarks: "",
  });

  const [complianceRecords, setComplianceRecords] = useState([]);
  const [leaveRules, setLeaveRules] = useState(null);
  const [employees, setEmployees] = useState([]);

  // Load leave compliance data
  useEffect(() => {
    async function fetchData() {
      try {
        const tenant = localStorage.getItem("tenant_db");
        const token = localStorage.getItem("access_token");
        
        // Fetch employees from both onboarding and user management
        const [onboardingRes, usersRes] = await Promise.all([
          api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
          fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
            headers: { Authorization: `Bearer ${token}` }
          }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
        ]);
        
        const onboardedEmployees = onboardingRes.data || [];
        const userEmployees = usersRes.users || [];
        
        // Process onboarded employees
        const validOnboardedEmployees = onboardedEmployees.filter(emp => {
          if (!emp.employee_id || emp.employee_id.trim() === '') return false;
          const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
          return !isAutoGenerated;
        });
        
        const onboardedData = validOnboardedEmployees.map(emp => ({
          id: emp.application_id,
          employee_id: emp.employee_id,
          name: emp.candidate_name,
          department: emp.department,
          designation: emp.job_title
        }));
        
        // Process user management employees
        const userEmployeeData = userEmployees
          .filter(user => user.employee_code)
          .map(user => ({
            id: `user_${user.id}`,
            employee_id: user.employee_code,
            name: user.name,
            department: user.department_name,
            designation: user.designation || 'N/A'
          }));
        
        // Combine employees
        const allEmployees = [...onboardedData];
        userEmployeeData.forEach(userEmp => {
          const existingIndex = allEmployees.findIndex(emp => emp.employee_id === userEmp.employee_id);
          if (existingIndex === -1) {
            allEmployees.push(userEmp);
          } else {
            allEmployees[existingIndex] = userEmp;
          }
        });
        
        setEmployees(allEmployees);
        
        try {
          const rulesRes = await api.get("/api/leave/leave-rules");
          setLeaveRules(rulesRes.data);
        } catch (rulesErr) {
          console.log('Failed to load leave rules:', rulesErr);
          setLeaveRules(null);
        }
        
        try {
          const complianceRes = await api.get("/api/compliance/leave");
          setComplianceRecords(complianceRes.data || []);
        } catch (complianceErr) {
          console.log('Failed to load compliance records:', complianceErr);
          setComplianceRecords([]);
        }
      } catch (err) {
        console.log("No leave compliance data found", err);
      }
    }
    fetchData();
  }, []);

  function handleChange(e) {
    setForm({ ...form, [e.target.name]: e.target.value });
  }

  async function handleSubmit(e) {
    e.preventDefault();
    try {
      const res = await api.post("/api/compliance/leave", form);
      alert("Leave Compliance Check Completed Successfully");
      
      // Reset form
      setForm({
        employee_id: "",
        employee_name: "",
        total_working_days: "",
        actual_working_days: "",
        leaves_taken: "",
        paid_leaves: "",
        unpaid_leaves: "",
        sick_leaves: "",
        casual_leaves: "",
        earned_leaves: "",
        overtime_hours: "",
        weekly_off_days: "",
        public_holidays: "",
        month: "",
        year: "",
        department: "",
        designation: "",
        compliance_status: "Compliant",
        remarks: "",
      });
      
      try {
        // Refresh compliance records
        const complianceRes = await api.get("/api/compliance/leave");
        setComplianceRecords(complianceRes.data || []);
      } catch (refreshErr) {
        console.log('Failed to refresh compliance records:', refreshErr);
      }
    } catch (err) {
      console.error('Failed to check leave compliance:', err);
      alert("Failed to check leave compliance");
    }
  }

  // Calculate compliance metrics
  const calculateCompliance = () => {
    const totalDays = parseFloat(form.total_working_days) || 0;
    const actualDays = parseFloat(form.actual_working_days) || 0;
    const leavesTaken = parseFloat(form.leaves_taken) || 0;
    const overtimeHours = parseFloat(form.overtime_hours) || 0;
    
    const attendancePercentage = totalDays > 0 ? ((actualDays / totalDays) * 100) : 0;
    const leaveUtilization = totalDays > 0 ? ((leavesTaken / totalDays) * 100) : 0;
    const overtimeDays = overtimeHours / 8; // Assuming 8 hours per day
    
    return {
      attendancePercentage: attendancePercentage.toFixed(2),
      leaveUtilization: leaveUtilization.toFixed(2),
      overtimeDays: overtimeDays.toFixed(2),
      isCompliant: attendancePercentage >= 75 && leaveUtilization <= 30
    };
  };

  const compliance = calculateCompliance();

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl p-6 border border-blue-100">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-blue-100 rounded-xl">
            <Calendar className="w-6 h-6 text-blue-600" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-primary">Leave & Working Hours Compliance</h2>
            <p className=" mt-1" style={{color: 'var(--text-secondary, #374151)'}}>Monitor and ensure compliance with leave policies and working hour regulations</p>
          </div>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-content rounded-lg p-4">
          <div className="flex items-center">
            <Users className="h-8 w-8 text-blue-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-blue-600">Total Records</p>
              <p className="text-2xl font-semibold text-blue-900">{complianceRecords.length}</p>
            </div>
          </div>
        </div>
        <div className="bg-content rounded-lg p-4">
          <div className="flex items-center">
            <CheckCircle className="h-8 w-8 text-green-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-green-600">Compliant</p>
              <p className="text-2xl font-semibold text-green-900">{complianceRecords.filter(r => r.compliance_status === 'Compliant').length}</p>
            </div>
          </div>
        </div>
        <div className="bg-content rounded-lg p-4">
          <div className="flex items-center">
            <TrendingUp className="h-8 w-8 text-orange-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-orange-600">Avg Attendance</p>
              <p className="text-2xl font-semibold text-orange-900">
                {complianceRecords.length > 0 
                  ? (complianceRecords.reduce((sum, r) => sum + ((r.actual_working_days / r.total_working_days) * 100), 0) / complianceRecords.length).toFixed(1)
                  : 0}%
              </p>
            </div>
          </div>
        </div>
        <div className="bg-content rounded-lg p-4">
          <div className="flex items-center">
            <Clock className="h-8 w-8 text-purple-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-purple-600">Total OT Hours</p>
              <p className="text-2xl font-semibold text-purple-900">{complianceRecords.reduce((sum, r) => sum + (r.overtime_hours || 0), 0)}</p>
            </div>
          </div>
        </div>
      </div>

      <div className="rounded-xl shadow-sm border p-6" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
        {/* Leave Rules Display */}
        {leaveRules && (
          <div className="bg-blue-50 p-4 rounded-lg mb-6">
            <h3 className="text-lg font-medium mb-2">Current Leave Rules</h3>
            <div className="grid grid-cols-4 gap-4 text-sm">
              <div>Max Casual Leave: {leaveRules.max_casual_leave || 12} days</div>
              <div>Max Sick Leave: {leaveRules.max_sick_leave || 12} days</div>
              <div>Max Earned Leave: {leaveRules.max_earned_leave || 21} days</div>
              <div>Min Attendance: {leaveRules.min_attendance || 75}%</div>
            </div>
          </div>
        )}

        <form onSubmit={handleSubmit} className="grid grid-cols-2 gap-6 mb-8">
          {/* Employee ID */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Employee ID <span className="text-red-500">*</span>
            </label>
            <select
              required
              name="employee_id"
              value={form.employee_id}
              onChange={(e) => {
                const selectedId = e.target.value;
                const selectedEmployee = employees.find(emp => emp.employee_id === selectedId);
                if (selectedEmployee) {
                  setForm({
                    ...form,
                    employee_id: selectedEmployee.employee_id,
                    employee_name: selectedEmployee.name,
                    department: selectedEmployee.department,
                    designation: selectedEmployee.designation
                  });
                } else {
                  setForm({ ...form, employee_id: selectedId });
                }
              }}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Employee ID</option>
              {employees.map((employee) => (
                <option key={employee.id} value={employee.employee_id}>
                  {employee.employee_id}
                </option>
              ))}
            </select>
          </div>

          {/* Employee Name */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Employee Name <span className="text-red-500">*</span>
            </label>
            <select
              required
              name="employee_name"
              value={form.employee_name}
              onChange={(e) => {
                const selectedName = e.target.value;
                const selectedEmployee = employees.find(emp => emp.name === selectedName);
                if (selectedEmployee) {
                  setForm({
                    ...form,
                    employee_id: selectedEmployee.employee_id,
                    employee_name: selectedEmployee.name,
                    department: selectedEmployee.department,
                    designation: selectedEmployee.designation
                  });
                } else {
                  setForm({ ...form, employee_name: selectedName });
                }
              }}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Employee Name</option>
              {employees.map((employee) => (
                <option key={employee.id} value={employee.name}>
                  {employee.name}
                </option>
              ))}
            </select>
          </div>

          {/* Total Working Days */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Total Working Days <span className="text-red-500">*</span>
            </label>
            <input
              type="number"
              required
              name="total_working_days"
              value={form.total_working_days}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Total Working Days"
              min="0"
              max="31"
            />
          </div>

          {/* Actual Working Days */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Actual Working Days <span className="text-red-500">*</span>
            </label>
            <input
              type="number"
              required
              name="actual_working_days"
              value={form.actual_working_days}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Actual Working Days"
              min="0"
              max="31"
            />
          </div>

          {/* Total Leaves Taken */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Total Leaves Taken <span className="text-red-500">*</span>
            </label>
            <input
              type="number"
              required
              name="leaves_taken"
              value={form.leaves_taken}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Total Leaves Taken"
              min="0"
            />
          </div>

          {/* Paid Leaves */}
          <div>
            <label className="block text-sm font-medium mb-1">Paid Leaves</label>
            <input
              type="number"
              name="paid_leaves"
              value={form.paid_leaves}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Paid Leaves"
              min="0"
            />
          </div>

          {/* Unpaid Leaves */}
          <div>
            <label className="block text-sm font-medium mb-1">Unpaid Leaves</label>
            <input
              type="number"
              name="unpaid_leaves"
              value={form.unpaid_leaves}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Unpaid Leaves"
              min="0"
            />
          </div>

          {/* Sick Leaves */}
          <div>
            <label className="block text-sm font-medium mb-1">Sick Leaves</label>
            <input
              type="number"
              name="sick_leaves"
              value={form.sick_leaves}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Sick Leaves"
              min="0"
            />
          </div>

          {/* Casual Leaves */}
          <div>
            <label className="block text-sm font-medium mb-1">Casual Leaves</label>
            <input
              type="number"
              name="casual_leaves"
              value={form.casual_leaves}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Casual Leaves"
              min="0"
            />
          </div>

          {/* Earned Leaves */}
          <div>
            <label className="block text-sm font-medium mb-1">Earned Leaves</label>
            <input
              type="number"
              name="earned_leaves"
              value={form.earned_leaves}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Earned Leaves"
              min="0"
            />
          </div>

          {/* Overtime Hours */}
          <div>
            <label className="block text-sm font-medium mb-1">Overtime Hours</label>
            <input
              type="number"
              name="overtime_hours"
              value={form.overtime_hours}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Overtime Hours"
              min="0"
              step="0.5"
            />
          </div>

          {/* Month */}
          <div>
            <label className="block text-sm font-medium mb-1">Month</label>
            <select
              name="month"
              value={form.month}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Month</option>
              <option value="01">January</option>
              <option value="02">February</option>
              <option value="03">March</option>
              <option value="04">April</option>
              <option value="05">May</option>
              <option value="06">June</option>
              <option value="07">July</option>
              <option value="08">August</option>
              <option value="09">September</option>
              <option value="10">October</option>
              <option value="11">November</option>
              <option value="12">December</option>
            </select>
          </div>

          {/* Year */}
          <div>
            <label className="block text-sm font-medium mb-1">Year</label>
            <input
              type="number"
              name="year"
              value={form.year}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Year"
              min="2020"
              max="2030"
            />
          </div>

          {/* Remarks */}
          <div className="col-span-2">
            <label className="block text-sm font-medium mb-1">Remarks</label>
            <textarea
              name="remarks"
              value={form.remarks}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent h-24"
              placeholder="Enter any compliance notes or remarks"
            />
          </div>

          {/* Real-time Compliance Display */}
          {(form.total_working_days && form.actual_working_days) && (
            <div className={`col-span-2 p-4 rounded-lg ${
              compliance.isCompliant ? 'bg-green-50' : 'bg-red-50'
            }`}>
              <h4 className="font-medium mb-2">Compliance Metrics</h4>
              <div className="grid grid-cols-4 gap-4 text-sm">
                <div>Attendance: {compliance.attendancePercentage}%</div>
                <div>Leave Utilization: {compliance.leaveUtilization}%</div>
                <div>Overtime Days: {compliance.overtimeDays}</div>
                <div className={`font-semibold ${
                  compliance.isCompliant ? 'text-green-600' : 'text-red-600'
                }`}>
                  Status: {compliance.isCompliant ? 'Compliant' : 'Non-Compliant'}
                </div>
              </div>
            </div>
          )}

          {/* Submit */}
          <div className="col-span-2">
            <button
              type="submit"
              className="bg-blue-600 px-6 py-2 text-white rounded-lg hover:bg-blue-700"
            >
              Check Leave Compliance
            </button>
          </div>
        </form>

        {/* Display compliance records */}
        {complianceRecords.length > 0 && (
          <div>
            <h3 className="text-lg font-semibold mb-4">Leave Compliance Records</h3>
            <div className="overflow-x-auto">
              <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="w-full">
                <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-content">
                  <tr>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">Employee</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">Working Days</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">Leaves Taken</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">Attendance %</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">OT Hours</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">Status</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">Period</th>
                  </tr>
                </thead>
                <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-white divide-y">
                  {complianceRecords.map((record, index) => (
                    <tr key={index} className="hover:bg-content">
                      <td className="px-4 py-2 text-sm">
                        <div>
                          <div className="font-medium">{record.employee_name}</div>
                          <div className=" text-xs" style={{color: 'var(--text-muted, #6b7280)'}}>{record.employee_id}</div>
                        </div>
                      </td>
                      <td className="px-4 py-2 text-sm">{record.actual_working_days}/{record.total_working_days}</td>
                      <td className="px-4 py-2 text-sm">{record.leaves_taken}</td>
                      <td className="px-4 py-2 text-sm">
                        {((record.actual_working_days / record.total_working_days) * 100).toFixed(1)}%
                      </td>
                      <td className="px-4 py-2 text-sm">{record.overtime_hours}</td>
                      <td className="px-4 py-2 text-sm">
                        <span className={`px-2 py-1 rounded-full text-xs ${
                          record.compliance_status === 'Compliant' ? 'bg-green-100 text-green-800' :
                          record.compliance_status === 'Non-Compliant' ? 'bg-red-100 text-red-800' :
                          record.compliance_status === 'Under Review' ? 'bg-yellow-100 text-yellow-800' :
                          'bg-gray-100 text-primary'
                        }`}>
                          {record.compliance_status}
                        </span>
                      </td>
                      <td className="px-4 py-2 text-sm">{record.month}/{record.year}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
