import { useEffect, useState } from "react";
import { Calendar, Users, TrendingUp, Clock, CheckCircle, Edit, Trash2, RotateCcw, Eye, EyeOff } from "lucide-react";
import api from "../../api";
import Toast from "../../components/Toast";
import useToast from "../../utils/useToast";
import { hasPermission, isAdmin } from "../../utils/permissions";

export default function LeaveCompliance() {
  const canView = isAdmin() || hasPermission('view_leave_compliance');
  const canAdd = isAdmin() || hasPermission('add_leave_compliance');
  const canEdit = isAdmin() || hasPermission('edit_leave_compliance');
  const canDelete = isAdmin() || hasPermission('delete_leave_compliance');

  if (!canView) {
    return (
      <div className="p-6 text-center">
        <div className="bg-white rounded-2xl border-0 p-8 max-w-md mx-auto">
          <h3 className="text-lg font-medium text-gray-900 mb-2">Access Denied</h3>
          <p className="text-gray-600">You do not have permission to view Leave Compliance.</p>
        </div>
      </div>
    );
  }

  const [form, setForm] = useState({
    employee_id: "",
    employee_name: "",
    total_working_days: "",
    actual_working_days: "",
    leaves_taken: "",
    paid_leaves: "",
    unpaid_leaves: "",
    sick_leaves: "",
    casual_leaves: "",
    earned_leaves: "",
    overtime_hours: "",
    weekly_off_days: "",
    public_holidays: "",
    month: "",
    year: "",
    department: "",
    designation: "",
    compliance_status: "Compliant",
    remarks: "",
  });

  const [complianceRecords, setComplianceRecords] = useState([]);
  const [deletedComplianceRecords, setDeletedComplianceRecords] = useState([]);
  const [showDeleted, setShowDeleted] = useState(false);
  const [leaveRules, setLeaveRules] = useState(null);
  const [employees, setEmployees] = useState([]);
  const { toast, showToast, hideToast } = useToast();

  // Permission checks
  const canViewDeleted = isAdmin() || hasPermission("view_deleted_leave_compliance");
  const canRestore = isAdmin() || hasPermission("restore_leave_compliance");

  // Load leave compliance data
  useEffect(() => {
    const fetchBrandingColors = async () => {
      try {
        const tenantCode = localStorage.getItem('tenant_code');
        if (tenantCode) {
          const response = await api.get(`/auth/branding/${tenantCode}`);
          document.documentElement.style.setProperty('--primary-color', response.data.primary_color || '#2862e9');
          document.documentElement.style.setProperty('--secondary-color', response.data.secondary_color || '#474e71');
        }
      } catch (error) {
        console.error('Error fetching branding colors:', error);
      }
    };
    fetchBrandingColors();

    async function fetchData() {
      try {
        const tenant = localStorage.getItem("tenant_db");
        const token = localStorage.getItem("access_token");
        
        console.log('Fetching employee data for Leave Compliance, tenant:', tenant);
        
        // Fetch employees from both onboarding and user management
        let allEmployees = [];
        
        try {
          const onboardingRes = await api.get('/recruitment/onboarding/list');
          console.log('Onboarding response:', onboardingRes.data);
          
          const onboardedEmployees = onboardingRes.data || [];
          
          // Process onboarded employees
          const validOnboardedEmployees = onboardedEmployees.filter(emp => {
            if (!emp.employee_id || emp.employee_id.trim() === '') return false;
            const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
            return !isAutoGenerated;
          });
          
          const onboardedData = validOnboardedEmployees.map(emp => ({
            id: emp.application_id || emp.id,
            employee_id: emp.employee_id,
            name: emp.candidate_name,
            department: emp.department,
            designation: emp.job_title
          }));
          
          allEmployees = [...onboardedData];
          console.log('Processed onboarded employees:', allEmployees);
        } catch (onboardingError) {
          console.error('Error fetching onboarding data:', onboardingError);
        }
        
        try {
          const usersRes = await api.get(`/hospitals/users/${tenant}/list`);
          console.log('Users response:', usersRes.data);
          
          const userEmployees = usersRes.data?.users || usersRes.data || [];
          
          // Process user management employees
          const userEmployeeData = userEmployees
            .filter(user => user.employee_code)
            .map(user => ({
              id: `user_${user.id}`,
              employee_id: user.employee_code,
              name: user.name,
              department: user.department_name,
              designation: user.designation || 'N/A'
            }));
          
          // Combine employees, avoiding duplicates
          userEmployeeData.forEach(userEmp => {
            const existingIndex = allEmployees.findIndex(emp => emp.employee_id === userEmp.employee_id);
            if (existingIndex === -1) {
              allEmployees.push(userEmp);
            } else {
              allEmployees[existingIndex] = userEmp;
            }
          });
          
          console.log('Final combined employees:', allEmployees);
        } catch (usersError) {
          console.error('Error fetching users data:', usersError);
        }
        
        // If no employees found, add some sample data for testing
        if (allEmployees.length === 0) {
          console.log('No employees found, adding sample data');
          allEmployees = [
            { id: 'sample1', employee_id: '1234', name: 'Shifana', department: 'HR', designation: 'Manager' },
            { id: 'sample2', employee_id: '52044', name: 'Harinie S', department: 'IT', designation: 'Developer' },
            { id: 'sample3', employee_id: '52045', name: 'Harinie S', department: 'IT', designation: 'Developer' },
            { id: 'sample4', employee_id: '5204', name: 'Rudra', department: 'Finance', designation: 'Analyst' },
            { id: 'sample5', employee_id: '9002', name: 'Arun A', department: 'Operations', designation: 'Executive' },
            { id: 'sample6', employee_id: '0626', name: 'Kamatchi', department: 'HR', designation: 'Executive' },
            { id: 'sample7', employee_id: '0987', name: 'Haru S', department: 'IT', designation: 'Developer' },
            { id: 'sample8', employee_id: '1105', name: 'Sushini', department: 'Marketing', designation: 'Executive' }
          ];
        }
        
        setEmployees(allEmployees);
        
        try {
          const rulesRes = await api.get("/api/leave/leave-rules");
          setLeaveRules(rulesRes.data);
        } catch (rulesErr) {
          // Leave rules endpoint not available - continue without it
          setLeaveRules(null);
        }
        
        try {
          const complianceRes = await api.get("/api/compliance/leave");
          setComplianceRecords(complianceRes.data || []);
        } catch (complianceErr) {
          // Leave compliance data not available - continue without it
          setComplianceRecords([]);
        }
        
        // Load deleted records
        if (canViewDeleted) {
          try {
            const deletedRes = await api.get("/api/compliance/leave?show_deleted=true");
            setDeletedComplianceRecords(deletedRes.data || []);
          } catch (err) {
            console.log("No permission to view deleted records", err);
            setDeletedComplianceRecords([]);
          }
        }
      } catch (err) {
        console.log("No leave compliance data found", err);
      }
    }
    fetchData();
  }, []);

  function handleChange(e) {
    setForm({ ...form, [e.target.name]: e.target.value });
  }

  async function handleSubmit(e) {
    e.preventDefault();
    try {
      // Calculate compliance status based on the metrics
      const compliance = calculateCompliance();
      const complianceStatus = compliance.isCompliant ? "Compliant" : "Non-Compliant";
      
      // Update form data with calculated compliance status
      const submitData = {
        ...form,
        compliance_status: complianceStatus
      };
      
      const res = await api.post("/api/compliance/leave", submitData);
      showToast("Leave Compliance Check Completed Successfully");
      
      // Reset form
      setForm({
        employee_id: "",
        employee_name: "",
        total_working_days: "",
        actual_working_days: "",
        leaves_taken: "",
        paid_leaves: "",
        unpaid_leaves: "",
        sick_leaves: "",
        casual_leaves: "",
        earned_leaves: "",
        overtime_hours: "",
        weekly_off_days: "",
        public_holidays: "",
        month: "",
        year: "",
        department: "",
        designation: "",
        compliance_status: "Compliant",
        remarks: "",
      });
      
      try {
        // Refresh compliance records
        const complianceRes = await api.get("/api/compliance/leave");
        setComplianceRecords(complianceRes.data || []);
        
        // Refresh deleted list
        if (canViewDeleted) {
          try {
            const deletedRes = await api.get("/api/compliance/leave?show_deleted=true");
            setDeletedComplianceRecords(deletedRes.data || []);
          } catch (err) {
            console.log("No permission to view deleted records", err);
          }
        }
      } catch (refreshErr) {
        // Compliance records not available - continue without refresh
      }
    } catch (err) {
      console.error('Failed to check leave compliance:', err);
      showToast("Failed to check leave compliance", 'error');
    }
  }

  // Calculate compliance metrics
  const calculateCompliance = () => {
    const totalDays = parseFloat(form.total_working_days) || 0;
    const actualDays = parseFloat(form.actual_working_days) || 0;
    const leavesTaken = parseFloat(form.leaves_taken) || 0;
    const overtimeHours = parseFloat(form.overtime_hours) || 0;
    
    const attendancePercentage = totalDays > 0 ? ((actualDays / totalDays) * 100) : 0;
    const leaveUtilization = totalDays > 0 ? ((leavesTaken / totalDays) * 100) : 0;
    const overtimeDays = overtimeHours / 8; // Assuming 8 hours per day
    
    return {
      attendancePercentage: attendancePercentage.toFixed(2),
      leaveUtilization: leaveUtilization.toFixed(2),
      overtimeDays: overtimeDays.toFixed(2),
      isCompliant: attendancePercentage >= 75 && leaveUtilization <= 30
    };
  };

  const compliance = calculateCompliance();

  async function handleDelete(recordId) {
    if (!window.confirm('Are you sure you want to delete this record?')) return;
    
    try {
      await api.delete(`/api/compliance/leave/${recordId}`);
      showToast("Record deleted successfully!");
      
      // Refresh the list
      const complianceRes = await api.get("/api/compliance/leave");
      setComplianceRecords(complianceRes.data || []);
      
      // Refresh deleted list
      if (canViewDeleted) {
        try {
          const deletedRes = await api.get("/api/compliance/leave?show_deleted=true");
          setDeletedComplianceRecords(deletedRes.data || []);
        } catch (err) {
          console.log("No permission to view deleted records", err);
        }
      }
    } catch (err) {
      console.error('Failed to delete record:', err);
      showToast("Failed to delete record", 'error');
    }
  }

  async function handleRestore(recordId) {
    if (!window.confirm('Are you sure you want to restore this record?')) return;
    
    try {
      await api.put(`/api/compliance/leave/${recordId}/restore`);
      showToast("Record restored successfully!");
      
      // Refresh both lists
      const complianceRes = await api.get("/api/compliance/leave");
      setComplianceRecords(complianceRes.data || []);
      
      if (canViewDeleted) {
        try {
          const deletedRes = await api.get("/api/compliance/leave?show_deleted=true");
          setDeletedComplianceRecords(deletedRes.data || []);
        } catch (err) {
          console.log("No permission to view deleted records", err);
        }
      }
    } catch (err) {
      console.error('Failed to restore record:', err);
      showToast("Failed to restore record", 'error');
    }
  }

  return (
    <div className="space-y-6">
      <div className="rounded-xl shadow-sm overflow-hidden relative border p-6" style={{
        background: `linear-gradient(135deg, white 0%, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}05 100%)`,
        border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5'}`
      }}>
        <div className="absolute top-0 right-0 w-32 h-32 rounded-full blur-3xl opacity-10" style={{
          backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#4575b5',
          transform: 'translate(40%, -40%)'
        }}></div>
        <div className="relative z-10">
        {/* Leave Rules Display */}
        {leaveRules && (
          <div className="bg-blue-50 p-4 rounded-lg mb-6">
            <h3 className="text-lg font-medium mb-2">Current Leave Rules</h3>
            <div className="grid grid-cols-4 gap-4 text-sm">
              <div>Max Casual Leave: {leaveRules.max_casual_leave || 12} days</div>
              <div>Max Sick Leave: {leaveRules.max_sick_leave || 12} days</div>
              <div>Max Earned Leave: {leaveRules.max_earned_leave || 21} days</div>
              <div>Min Attendance: {leaveRules.min_attendance || 75}%</div>
            </div>
          </div>
        )}

        <form onSubmit={handleSubmit} className="grid grid-cols-2 gap-6 mb-8">
          {canAdd ? (
            <>
          {/* Employee ID */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Employee ID <span className="text-red-500">*</span>
            </label>
            <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              required
              name="employee_id"
              value={form.employee_id}
              onChange={(e) => {
                const selectedId = e.target.value;
                console.log('Selected employee ID:', selectedId);
                const selectedEmployee = employees.find(emp => emp.employee_id === selectedId);
                console.log('Found employee:', selectedEmployee);
                if (selectedEmployee) {
                  setForm({
                    ...form,
                    employee_id: selectedEmployee.employee_id,
                    employee_name: selectedEmployee.name,
                    department: selectedEmployee.department,
                    designation: selectedEmployee.designation
                  });
                } else {
                  setForm({ ...form, employee_id: selectedId });
                }
              }}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Employee ID</option>
              {employees && employees.length > 0 ? (
                employees.map((employee) => (
                  <option key={employee.id} value={employee.employee_id}>
                    {employee.employee_id} - {employee.name}
                  </option>
                ))
              ) : (
                <option value="" disabled>No employees found</option>
              )}
            </select>
          </div>

          {/* Employee Name */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Employee Name <span className="text-red-500">*</span>
            </label>
            <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              required
              name="employee_name"
              value={form.employee_name}
              onChange={(e) => {
                const selectedName = e.target.value;
                console.log('Selected employee name:', selectedName);
                const selectedEmployee = employees.find(emp => emp.name === selectedName);
                console.log('Found employee by name:', selectedEmployee);
                if (selectedEmployee) {
                  setForm({
                    ...form,
                    employee_id: selectedEmployee.employee_id,
                    employee_name: selectedEmployee.name,
                    department: selectedEmployee.department,
                    designation: selectedEmployee.designation
                  });
                } else {
                  setForm({ ...form, employee_name: selectedName });
                }
              }}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Employee Name</option>
              {employees && employees.length > 0 ? (
                employees.map((employee) => (
                  <option key={employee.id} value={employee.name}>
                    {employee.name} ({employee.employee_id})
                  </option>
                ))
              ) : (
                <option value="" disabled>No employees found</option>
              )}
            </select>
          </div>

          {/* Total Working Days */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Total Working Days <span className="text-red-500">*</span>
            </label>
            <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              type="number"
              required
              name="total_working_days"
              value={form.total_working_days}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Total Working Days"
              min="0"
              max="31"
            />
          </div>

          {/* Actual Working Days */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Actual Working Days <span className="text-red-500">*</span>
            </label>
            <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              type="number"
              required
              name="actual_working_days"
              value={form.actual_working_days}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Actual Working Days"
              min="0"
              max="31"
            />
          </div>

          {/* Total Leaves Taken */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Total Leaves Taken <span className="text-red-500">*</span>
            </label>
            <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              type="number"
              required
              name="leaves_taken"
              value={form.leaves_taken}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Total Leaves Taken"
              min="0"
            />
          </div>

          {/* Paid Leaves */}
          <div>
            <label className="block text-sm font-medium mb-1">Paid Leaves</label>
            <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              type="number"
              name="paid_leaves"
              value={form.paid_leaves}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Paid Leaves"
              min="0"
            />
          </div>

          {/* Unpaid Leaves */}
          <div>
            <label className="block text-sm font-medium mb-1">Unpaid Leaves</label>
            <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              type="number"
              name="unpaid_leaves"
              value={form.unpaid_leaves}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Unpaid Leaves"
              min="0"
            />
          </div>

          {/* Sick Leaves */}
          <div>
            <label className="block text-sm font-medium mb-1">Sick Leaves</label>
            <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              type="number"
              name="sick_leaves"
              value={form.sick_leaves}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Sick Leaves"
              min="0"
            />
          </div>

          {/* Casual Leaves */}
          <div>
            <label className="block text-sm font-medium mb-1">Casual Leaves</label>
            <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              type="number"
              name="casual_leaves"
              value={form.casual_leaves}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Casual Leaves"
              min="0"
            />
          </div>

          {/* Earned Leaves */}
          <div>
            <label className="block text-sm font-medium mb-1">Earned Leaves</label>
            <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              type="number"
              name="earned_leaves"
              value={form.earned_leaves}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Earned Leaves"
              min="0"
            />
          </div>

          {/* Overtime Hours */}
          <div>
            <label className="block text-sm font-medium mb-1">Overtime Hours</label>
            <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              type="number"
              name="overtime_hours"
              value={form.overtime_hours}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Overtime Hours"
              min="0"
              step="0.5"
            />
          </div>

          {/* Month */}
          <div>
            <label className="block text-sm font-medium mb-1">Month</label>
            <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              name="month"
              value={form.month}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Month</option>
              <option value="01">January</option>
              <option value="02">February</option>
              <option value="03">March</option>
              <option value="04">April</option>
              <option value="05">May</option>
              <option value="06">June</option>
              <option value="07">July</option>
              <option value="08">August</option>
              <option value="09">September</option>
              <option value="10">October</option>
              <option value="11">November</option>
              <option value="12">December</option>
            </select>
          </div>

          {/* Year */}
          <div>
            <label className="block text-sm font-medium mb-1">Year</label>
            <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              type="number"
              name="year"
              value={form.year}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Year"
              min="2020"
              max="2030"
            />
          </div>

          {/* Remarks */}
          <div className="col-span-2">
            <label className="block text-sm font-medium mb-1">Remarks</label>
            <textarea style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`, border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`}} 
              name="remarks"
              value={form.remarks}
              onChange={handleChange}
              className="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent h-24"
              placeholder="Enter any compliance notes or remarks"
            />
          </div>

          {/* Real-time Compliance Display */}
          {(form.total_working_days && form.actual_working_days) && (
            <div className={`col-span-2 p-4 rounded-lg ${
              compliance.isCompliant ? 'bg-green-50' : 'bg-red-50'
            }`}>
              <h4 className="font-medium mb-2">Compliance Metrics</h4>
              <div className="grid grid-cols-4 gap-4 text-sm">
                <div>Attendance: {compliance.attendancePercentage}%</div>
                <div>Leave Utilization: {compliance.leaveUtilization}%</div>
                <div>Overtime Days: {compliance.overtimeDays}</div>
                <div className={`font-semibold ${
                  compliance.isCompliant ? 'text-green-600' : 'text-red-600'
                }`}>
                  Status: {compliance.isCompliant ? 'Compliant' : 'Non-Compliant'}
                </div>
              </div>
            </div>
          )}

          {/* Submit */}
          <div className="col-span-2">
            <button
              type="submit"
              style={{ backgroundColor: 'var(--primary-color, #2862e9)' }}
              className="px-6 py-2 text-white rounded-lg border-0 transition-colors"
              onMouseEnter={(e) => e.currentTarget.style.backgroundColor = 'var(--secondary-color, #474e71)'}
              onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'var(--primary-color, #2862e9)'}
            >
              Check Leave Compliance
            </button>
          </div>
            </>
          ) : (
            <div className="col-span-2 text-center text-gray-500">
              You do not have permission to add leave compliance records.
            </div>
          )}
        </form>

        {/* Display compliance records */}
        {(complianceRecords.length > 0 || deletedComplianceRecords.length > 0) && (
          <div>
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">
                {showDeleted ? 'Deleted Leave Compliance Records' : 'Leave Compliance Records'}
              </h3>
              <div className="flex gap-2">
                {canViewDeleted && (
                  <button
                    onClick={() => setShowDeleted(!showDeleted)}
                    className={`px-4 py-2 rounded-lg border transition-colors flex items-center gap-2 ${
                      showDeleted 
                        ? 'bg-gray-800 text-white border-gray-200 hover:bg-gray-900' 
                        : 'bg-white text-gray-800 border-gray-200 hover:bg-gray-50'
                    }`}
                  >
                    {showDeleted ? <EyeOff size={16} /> : <Eye size={16} />}
                    {showDeleted ? 'Show Active' : 'Show Deleted'} ({showDeleted ? complianceRecords.length : deletedComplianceRecords.length})
                  </button>
                )}
              </div>
            </div>
            <div className="overflow-x-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
              {/* Desktop Table View */}
              <div className="hidden md:block">
                <table className="w-full border-0">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Employee</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Working Days</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Leaves Taken</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Attendance %</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">OT Hours</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Status</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Period</th>
                      {showDeleted && <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Deleted At</th>}
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {(showDeleted ? deletedComplianceRecords : complianceRecords).map((record, index) => (
                      <tr key={index} className={`hover:bg-gray-50 border-b-0 ${showDeleted ? 'bg-red-50' : ''}`}>
                        <td className="px-4 py-2 text-sm border-r-0">
                          <div>
                            <div className="font-medium">{record.employee_name}</div>
                            <div className="text-gray-500 text-xs">{record.employee_id}</div>
                          </div>
                        </td>
                        <td className="px-4 py-2 text-sm border-r-0">{record.actual_working_days}/{record.total_working_days}</td>
                        <td className="px-4 py-2 text-sm border-r-0">{record.leaves_taken}</td>
                        <td className="px-4 py-2 text-sm border-r-0">
                          {((record.actual_working_days / record.total_working_days) * 100).toFixed(1)}%
                        </td>
                        <td className="px-4 py-2 text-sm border-r-0">{record.overtime_hours}</td>
                        <td className="px-4 py-2 text-sm border-r-0">
                          <span className={`px-2 py-1 rounded-full text-xs ${
                            record.compliance_status === 'Compliant' ? 'bg-green-100 text-green-800' :
                            record.compliance_status === 'Non-Compliant' ? 'bg-red-100 text-red-800' :
                            record.compliance_status === 'Under Review' ? 'bg-yellow-100 text-yellow-800' :
                            'bg-gray-100 text-gray-900'
                          }`}>
                            {record.compliance_status}
                          </span>
                        </td>
                        <td className="px-4 py-2 text-sm">{record.month}/{record.year}</td>
                        {showDeleted && (
                          <td className="px-4 py-2 text-sm border-r-0">
                            {record.deleted_at ? new Date(record.deleted_at).toLocaleDateString() : 'N/A'}
                          </td>
                        )}
                        <td className="px-4 py-2 text-sm">
                          <div className="flex gap-2">
                            {showDeleted ? (
                              canRestore && (
                                <button
                                  onClick={() => handleRestore(record.id)}
                                  className="text-green-600 hover:text-green-800 p-1 rounded"
                                  title="Restore"
                                >
                                  <RotateCcw size={16} />
                                </button>
                              )
                            ) : (
                              canDelete && (
                                <button
                                  onClick={() => handleDelete(record.id)}
                                  className="text-red-600 hover:text-red-800 p-1 rounded"
                                  title="Delete"
                                >
                                  <Trash2 size={16} />
                                </button>
                              )
                            )}
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Mobile Card View */}
              <div className="md:hidden">
                {(showDeleted ? deletedComplianceRecords : complianceRecords).map((record, index) => (
                  <div key={index} className={`p-4 border-b-0 last:border-b-0 ${showDeleted ? 'bg-red-50' : ''}`}>
                    <div className="flex justify-between items-start mb-3">
                      <div className="flex-1">
                        <h4 className="font-medium text-gray-900">{record.employee_name}</h4>
                        <p className="text-sm text-gray-600">{record.employee_id}</p>
                      </div>
                      <span className={`px-2 py-1 rounded-full text-xs ${
                        record.compliance_status === 'Compliant' ? 'bg-green-100 text-green-800' :
                        record.compliance_status === 'Non-Compliant' ? 'bg-red-100 text-red-800' :
                        record.compliance_status === 'Under Review' ? 'bg-yellow-100 text-yellow-800' :
                        'bg-gray-100 text-gray-900'
                      }`}>
                        {record.compliance_status}
                      </span>
                    </div>
                    
                    <div className="space-y-2 mb-3">
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Working Days:</span>
                        <span className="text-gray-900">{record.actual_working_days}/{record.total_working_days}</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Leaves Taken:</span>
                        <span className="text-gray-900">{record.leaves_taken}</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Attendance:</span>
                        <span className="text-gray-900">{((record.actual_working_days / record.total_working_days) * 100).toFixed(1)}%</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">OT Hours:</span>
                        <span className="text-gray-900">{record.overtime_hours}</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Period:</span>
                        <span className="text-gray-900">{record.month}/{record.year}</span>
                      </div>
                      {showDeleted && (
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-600">Deleted At:</span>
                          <span className="text-gray-900">{record.deleted_at ? new Date(record.deleted_at).toLocaleDateString() : 'N/A'}</span>
                        </div>
                      )}
                    </div>
                    
                    <div className="flex flex-wrap gap-2">
                      {showDeleted ? (
                        canRestore && (
                          <button
                            onClick={() => handleRestore(record.id)}
                            className="flex items-center gap-1 px-3 py-1 text-xs bg-green-50 text-green-700 rounded-md border border-green-300 hover:bg-green-100"
                          >
                            <RotateCcw className="w-3 h-3" />
                            Restore
                          </button>
                        )
                      ) : (
                        canDelete && (
                          <button
                            onClick={() => handleDelete(record.id)}
                            className="flex items-center gap-1 px-3 py-1 text-xs bg-gray-50 text-gray-700 rounded-md border border-gray-300 hover:bg-gray-100"
                          >
                            <Trash2 className="w-3 h-3" />
                            Delete
                          </button>
                        )
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
        </div>
      </div>
      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}




