import { useEffect, useState } from "react";
import { Shield, Users, TrendingUp, Award, CheckCircle, Trash2, RotateCcw, Eye, EyeOff } from "lucide-react";
import api from "../../api";
import useToast from "../../utils/useToast";
import Toast from "../../components/Toast";
import { hasPermission, isAdmin } from "../../utils/permissions";

export default function NABHCompliance() {
  const canView = isAdmin() || hasPermission('view_nabh_compliance');
  const canAdd = isAdmin() || hasPermission('add_nabh_compliance');
  const canEdit = isAdmin() || hasPermission('edit_nabh_compliance');
  const canDelete = isAdmin() || hasPermission('delete_nabh_compliance');
  const canViewDeleted = isAdmin() || hasPermission("view_deleted_nabh_compliance");
  const canRestore = isAdmin() || hasPermission("restore_nabh_compliance");
  
  if (!canView) {
    return (
      <div className="p-6 text-center">
        <div className="bg-white rounded-2xl border-0 p-8 max-w-md mx-auto">
          <h3 className="text-lg font-medium text-gray-900 mb-2">Access Denied</h3>
          <p className="text-gray-600">You do not have permission to view NABH Compliance.</p>
        </div>
      </div>
    );
  }

  const { toast, showToast, hideToast } = useToast();
  const [form, setForm] = useState({
    employee_id: "",
    employee_name: "",
    department: "",
    designation: "",
    joining_date: "",
    
    // NABH HR Standards
    staff_qualification_verified: false,
    qualification_documents: "",
    medical_fitness_done: false,
    medical_fitness_date: "",
    medical_fitness_validity: "",
    credentialing_done: false,
    credentialing_date: "",
    credentialing_validity: "",
    
    // Training Requirements
    orientation_training_done: false,
    orientation_date: "",
    fire_safety_training_done: false,
    fire_safety_date: "",
    infection_control_training: false,
    infection_control_date: "",
    patient_safety_training: false,
    patient_safety_date: "",
    
    // Performance & Monitoring
    performance_monitoring_done: false,
    last_appraisal_date: "",
    next_appraisal_due: "",
    competency_assessment: false,
    competency_date: "",
    
    // Documentation
    background_verification: false,
    police_verification: false,
    reference_check: false,
    
    // Compliance Status
    overall_compliance_status: "Pending",
    compliance_percentage: "0",
    last_audit_date: "",
    next_audit_due: "",
    remarks: "",
  });

  const [complianceRecords, setComplianceRecords] = useState([]);
  const [deletedComplianceRecords, setDeletedComplianceRecords] = useState([]);
  const [showDeleted, setShowDeleted] = useState(false);
  const [nabhStandards, setNabhStandards] = useState(null);
  const [employees, setEmployees] = useState([]);

  // Load NABH compliance data
  useEffect(() => {
    const fetchBrandingColors = async () => {
      try {
        const tenantCode = localStorage.getItem('tenant_code');
        if (tenantCode) {
          const response = await api.get(`/auth/branding/${tenantCode}`);
          document.documentElement.style.setProperty('--primary-color', response.data.primary_color || '#2862e9');
          document.documentElement.style.setProperty('--secondary-color', response.data.secondary_color || '#474e71');
        }
      } catch (error) {
        console.error('Error fetching branding colors:', error);
      }
    };
    fetchBrandingColors();

    async function fetchData() {
      try {
        const tenant = localStorage.getItem("tenant_db");
        const token = localStorage.getItem("access_token");
        
        console.log('Fetching employee data for NABH Compliance, tenant:', tenant);
        
        // Fetch employees from both onboarding and user management
        let allEmployees = [];
        
        try {
          const onboardingRes = await api.get('/recruitment/onboarding/list');
          console.log('Onboarding response:', onboardingRes.data);
          
          const onboardedEmployees = onboardingRes.data || [];
          
          // Process onboarded employees
          const validOnboardedEmployees = onboardedEmployees.filter(emp => {
            if (!emp.employee_id || emp.employee_id.trim() === '') return false;
            const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
            return !isAutoGenerated;
          });
          
          const onboardedData = validOnboardedEmployees.map(emp => ({
            id: emp.application_id || emp.id,
            employee_id: emp.employee_id,
            name: emp.candidate_name,
            department: emp.department,
            designation: emp.job_title
          }));
          
          allEmployees = [...onboardedData];
          console.log('Processed onboarded employees:', allEmployees);
        } catch (onboardingError) {
          console.error('Error fetching onboarding data:', onboardingError);
        }
        
        try {
          const usersRes = await api.get(`/hospitals/users/${tenant}/list`);
          console.log('Users response:', usersRes.data);
          
          const userEmployees = usersRes.data?.users || usersRes.data || [];
          
          // Process user management employees
          const userEmployeeData = userEmployees
            .filter(user => user.employee_code)
            .map(user => ({
              id: `user_${user.id}`,
              employee_id: user.employee_code,
              name: user.name,
              department: user.department_name,
              designation: user.designation || 'N/A'
            }));
          
          // Combine employees, avoiding duplicates
          userEmployeeData.forEach(userEmp => {
            const existingIndex = allEmployees.findIndex(emp => emp.employee_id === userEmp.employee_id);
            if (existingIndex === -1) {
              allEmployees.push(userEmp);
            } else {
              allEmployees[existingIndex] = userEmp;
            }
          });
          
          console.log('Final combined employees:', allEmployees);
        } catch (usersError) {
          console.error('Error fetching users data:', usersError);
        }
        
        // If no employees found, add some sample data for testing
        if (allEmployees.length === 0) {
          console.log('No employees found, adding sample data');
          allEmployees = [
            { id: 'sample1', employee_id: '1234', name: 'Shifana', department: 'HR', designation: 'Manager' },
            { id: 'sample2', employee_id: '52044', name: 'Harinie S', department: 'IT', designation: 'Developer' },
            { id: 'sample3', employee_id: '52045', name: 'Harinie S', department: 'IT', designation: 'Developer' },
            { id: 'sample4', employee_id: '5204', name: 'Rudra', department: 'Finance', designation: 'Analyst' },
            { id: 'sample5', employee_id: '9002', name: 'Arun A', department: 'Operations', designation: 'Executive' },
            { id: 'sample6', employee_id: '0626', name: 'Kamatchi', department: 'HR', designation: 'Executive' },
            { id: 'sample7', employee_id: '0987', name: 'Haru S', department: 'IT', designation: 'Developer' },
            { id: 'sample8', employee_id: '1105', name: 'Sushini', department: 'Marketing', designation: 'Executive' }
          ];
        }
        
        setEmployees(allEmployees);
        
        // Skip NABH standards API call as it doesn't exist
        // const standardsRes = await api.get("/api/compliance/nabh/standards");
        // setNabhStandards(standardsRes.data);
        
        const complianceRes = await api.get("/api/compliance/nabh");
        setComplianceRecords(complianceRes.data);
        
        // Load deleted records
        if (canViewDeleted) {
          try {
            const deletedRes = await api.get("/api/compliance/nabh?show_deleted=true");
            setDeletedComplianceRecords(deletedRes.data || []);
          } catch (err) {
            console.log("No permission to view deleted records", err);
            setDeletedComplianceRecords([]);
          }
        }
      } catch (err) {
        console.log("No NABH compliance data found", err);
      }
    }
    fetchData();
  }, []);

  function handleChange(e) {
    const { name, value, type, checked } = e.target;
    setForm({ 
      ...form, 
      [name]: type === 'checkbox' ? checked : value 
    });
  }

  async function handleSubmit(e) {
    e.preventDefault();
    try {
      const res = await api.post("/api/compliance/nabh", form);
      showToast("NABH Compliance Record Saved Successfully", "success");
      
      // Reset form
      setForm({
        employee_id: "",
        employee_name: "",
        department: "",
        designation: "",
        joining_date: "",
        staff_qualification_verified: false,
        qualification_documents: "",
        medical_fitness_done: false,
        medical_fitness_date: "",
        medical_fitness_validity: "",
        credentialing_done: false,
        credentialing_date: "",
        credentialing_validity: "",
        orientation_training_done: false,
        orientation_date: "",
        fire_safety_training_done: false,
        fire_safety_date: "",
        infection_control_training: false,
        infection_control_date: "",
        patient_safety_training: false,
        patient_safety_date: "",
        performance_monitoring_done: false,
        last_appraisal_date: "",
        next_appraisal_due: "",
        competency_assessment: false,
        competency_date: "",
        background_verification: false,
        police_verification: false,
        reference_check: false,
        overall_compliance_status: "Pending",
        compliance_percentage: "0",
        last_audit_date: "",
        next_audit_due: "",
        remarks: "",
      });
      
      // Refresh compliance records
      const complianceRes = await api.get("/api/compliance/nabh");
      setComplianceRecords(complianceRes.data);
      
      // Refresh deleted list
      if (canViewDeleted) {
        try {
          const deletedRes = await api.get("/api/compliance/nabh?show_deleted=true");
          setDeletedComplianceRecords(deletedRes.data || []);
        } catch (err) {
          console.log("No permission to view deleted records", err);
        }
      }
    } catch (err) {
      console.error('Failed to save NABH compliance:', err);
      showToast("Failed to save NABH compliance record", "error");
    }
  }

  // Calculate compliance percentage
  const calculateCompliancePercentage = () => {
    const checkboxFields = [
      'staff_qualification_verified', 'medical_fitness_done', 'credentialing_done',
      'orientation_training_done', 'fire_safety_training_done', 'infection_control_training',
      'patient_safety_training', 'performance_monitoring_done', 'competency_assessment',
      'background_verification', 'police_verification', 'reference_check'
    ];
    
    const completedItems = checkboxFields.filter(field => form[field]).length;
    const percentage = (completedItems / checkboxFields.length) * 100;
    
    return percentage.toFixed(1);
  };

  const compliancePercentage = calculateCompliancePercentage();

  async function handleDelete(recordId) {
    if (!window.confirm('Are you sure you want to delete this record?')) return;
    
    try {
      await api.delete(`/api/compliance/nabh/${recordId}`);
      showToast("Record deleted successfully!");
      
      // Refresh the list
      const complianceRes = await api.get("/api/compliance/nabh");
      setComplianceRecords(complianceRes.data || []);
      
      // Refresh deleted list
      if (canViewDeleted) {
        try {
          const deletedRes = await api.get("/api/compliance/nabh?show_deleted=true");
          setDeletedComplianceRecords(deletedRes.data || []);
        } catch (err) {
          console.log("No permission to view deleted records", err);
        }
      }
    } catch (err) {
      console.error('Failed to delete record:', err);
      showToast("Failed to delete record", 'error');
    }
  }

  async function handleRestore(recordId) {
    if (!window.confirm('Are you sure you want to restore this record?')) return;
    
    try {
      await api.put(`/api/compliance/nabh/${recordId}/restore`);
      showToast("Record restored successfully!");
      
      // Refresh both lists
      const complianceRes = await api.get("/api/compliance/nabh");
      setComplianceRecords(complianceRes.data || []);
      
      if (canViewDeleted) {
        try {
          const deletedRes = await api.get("/api/compliance/nabh?show_deleted=true");
          setDeletedComplianceRecords(deletedRes.data || []);
        } catch (err) {
          console.log("No permission to view deleted records", err);
        }
      }
    } catch (err) {
      console.error('Failed to restore record:', err);
      showToast("Failed to restore record", 'error');
    }
  }

  return (
    <div className="space-y-6">
      <div className="rounded-xl shadow-sm border-0 p-6" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
        <form onSubmit={handleSubmit} className="space-y-8">
          {canAdd ? (
            <>
          {/* Basic Employee Information */}
          <div className="bg-gradient-to-br from-gray-50 to-white p-6 rounded-lg border-0 hover:shadow-md transition-shadow">
            <h3 className="text-lg font-semibold mb-4">Employee Information</h3>
            <div className="grid grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium mb-1">
                  Employee ID <span className="text-red-500">*</span>
                </label>
                <select
                  required
                  name="employee_id"
                  value={form.employee_id}
                  onChange={(e) => {
                    const selectedId = e.target.value;
                    console.log('Selected employee ID:', selectedId);
                    const selectedEmployee = employees.find(emp => emp.employee_id === selectedId);
                    console.log('Found employee:', selectedEmployee);
                    if (selectedEmployee) {
                      setForm({
                        ...form,
                        employee_id: selectedEmployee.employee_id,
                        employee_name: selectedEmployee.name,
                        department: selectedEmployee.department,
                        designation: selectedEmployee.designation
                      });
                    } else {
                      setForm({ ...form, employee_id: selectedId });
                    }
                  }}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="">Select Employee ID</option>
                  {employees && employees.length > 0 ? (
                    employees.map((employee) => (
                      <option key={employee.id} value={employee.employee_id}>
                        {employee.employee_id} - {employee.name}
                      </option>
                    ))
                  ) : (
                    <option value="" disabled>No employees found</option>
                  )}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">
                  Employee Name <span className="text-red-500">*</span>
                </label>
                <select
                  required
                  name="employee_name"
                  value={form.employee_name}
                  onChange={(e) => {
                    const selectedName = e.target.value;
                    console.log('Selected employee name:', selectedName);
                    const selectedEmployee = employees.find(emp => emp.name === selectedName);
                    console.log('Found employee by name:', selectedEmployee);
                    if (selectedEmployee) {
                      setForm({
                        ...form,
                        employee_id: selectedEmployee.employee_id,
                        employee_name: selectedEmployee.name,
                        department: selectedEmployee.department,
                        designation: selectedEmployee.designation
                      });
                    } else {
                      setForm({ ...form, employee_name: selectedName });
                    }
                  }}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="">Select Employee Name</option>
                  {employees && employees.length > 0 ? (
                    employees.map((employee) => (
                      <option key={employee.id} value={employee.name}>
                        {employee.name} ({employee.employee_id})
                      </option>
                    ))
                  ) : (
                    <option value="" disabled>No employees found</option>
                  )}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Department</label>
                <input
                  type="text"
                  name="department"
                  value={form.department}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-gray-100"
                  placeholder="Auto-filled from employee selection"
                  readOnly
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Designation</label>
                <input
                  type="text"
                  name="designation"
                  value={form.designation}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="Enter Designation"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Joining Date</label>
                <input
                  type="date"
                  name="joining_date"
                  value={form.joining_date}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
            </div>
          </div>

          {/* Qualification & Documentation */}
          <div className="bg-gradient-to-br from-gray-50 to-white p-6 rounded-lg border-0 hover:shadow-md transition-shadow">
            <h3 className="text-lg font-semibold mb-4">Qualification & Documentation</h3>
            <div className="grid grid-cols-2 gap-6">
              <div className="col-span-2">
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    name="staff_qualification_verified"
                    checked={form.staff_qualification_verified}
                    onChange={handleChange}
                    className="rounded"
                  />
                  <span className="text-sm font-medium">Staff Qualification Verified</span>
                </label>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Qualification Documents</label>
                <input
                  type="text"
                  name="qualification_documents"
                  value={form.qualification_documents}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="List qualification documents"
                />
              </div>

              <div className="col-span-2">
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    name="background_verification"
                    checked={form.background_verification}
                    onChange={handleChange}
                    className="rounded"
                  />
                  <span className="text-sm font-medium">Background Verification Completed</span>
                </label>
              </div>

              <div className="col-span-2">
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    name="police_verification"
                    checked={form.police_verification}
                    onChange={handleChange}
                    className="rounded"
                  />
                  <span className="text-sm font-medium">Police Verification Completed</span>
                </label>
              </div>

              <div className="col-span-2">
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    name="reference_check"
                    checked={form.reference_check}
                    onChange={handleChange}
                    className="rounded"
                  />
                  <span className="text-sm font-medium">Reference Check Completed</span>
                </label>
              </div>
            </div>
          </div>

          {/* Medical Fitness & Credentialing */}
          <div className="bg-gradient-to-br from-gray-50 to-white p-6 rounded-lg border-0 hover:shadow-md transition-shadow">
            <h3 className="text-lg font-semibold mb-4">Medical Fitness & Credentialing</h3>
            <div className="grid grid-cols-2 gap-6">
              <div className="col-span-2">
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    name="medical_fitness_done"
                    checked={form.medical_fitness_done}
                    onChange={handleChange}
                    className="rounded"
                  />
                  <span className="text-sm font-medium">Medical Fitness Completed</span>
                </label>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Medical Fitness Date</label>
                <input
                  type="date"
                  name="medical_fitness_date"
                  value={form.medical_fitness_date}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Medical Fitness Validity</label>
                <input
                  type="date"
                  name="medical_fitness_validity"
                  value={form.medical_fitness_validity}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div className="col-span-2">
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    name="credentialing_done"
                    checked={form.credentialing_done}
                    onChange={handleChange}
                    className="rounded"
                  />
                  <span className="text-sm font-medium">Credentialing Completed</span>
                </label>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Credentialing Date</label>
                <input
                  type="date"
                  name="credentialing_date"
                  value={form.credentialing_date}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Credentialing Validity</label>
                <input
                  type="date"
                  name="credentialing_validity"
                  value={form.credentialing_validity}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
            </div>
          </div>

          {/* Training Requirements */}
          <div className="bg-gradient-to-br from-gray-50 to-white p-6 rounded-lg border-0 hover:shadow-md transition-shadow">
            <h3 className="text-lg font-semibold mb-4">Training Requirements</h3>
            <div className="grid grid-cols-2 gap-6">
              <div className="col-span-2">
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    name="orientation_training_done"
                    checked={form.orientation_training_done}
                    onChange={handleChange}
                    className="rounded"
                  />
                  <span className="text-sm font-medium">Orientation Training Completed</span>
                </label>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Orientation Date</label>
                <input
                  type="date"
                  name="orientation_date"
                  value={form.orientation_date}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div className="col-span-2">
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    name="fire_safety_training_done"
                    checked={form.fire_safety_training_done}
                    onChange={handleChange}
                    className="rounded"
                  />
                  <span className="text-sm font-medium">Fire Safety Training Completed</span>
                </label>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Fire Safety Training Date</label>
                <input
                  type="date"
                  name="fire_safety_date"
                  value={form.fire_safety_date}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div className="col-span-2">
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    name="infection_control_training"
                    checked={form.infection_control_training}
                    onChange={handleChange}
                    className="rounded"
                  />
                  <span className="text-sm font-medium">Infection Control Training Completed</span>
                </label>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Infection Control Training Date</label>
                <input
                  type="date"
                  name="infection_control_date"
                  value={form.infection_control_date}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div className="col-span-2">
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    name="patient_safety_training"
                    checked={form.patient_safety_training}
                    onChange={handleChange}
                    className="rounded"
                  />
                  <span className="text-sm font-medium">Patient Safety Training Completed</span>
                </label>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Patient Safety Training Date</label>
                <input
                  type="date"
                  name="patient_safety_date"
                  value={form.patient_safety_date}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
            </div>
          </div>

          {/* Performance & Monitoring */}
          <div className="bg-gradient-to-br from-gray-50 to-white p-6 rounded-lg border-0 hover:shadow-md transition-shadow">
            <h3 className="text-lg font-semibold mb-4">Performance & Monitoring</h3>
            <div className="grid grid-cols-2 gap-6">
              <div className="col-span-2">
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    name="performance_monitoring_done"
                    checked={form.performance_monitoring_done}
                    onChange={handleChange}
                    className="rounded"
                  />
                  <span className="text-sm font-medium">Performance Monitoring Implemented</span>
                </label>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Last Appraisal Date</label>
                <input
                  type="date"
                  name="last_appraisal_date"
                  value={form.last_appraisal_date}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Next Appraisal Due</label>
                <input
                  type="date"
                  name="next_appraisal_due"
                  value={form.next_appraisal_due}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div className="col-span-2">
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    name="competency_assessment"
                    checked={form.competency_assessment}
                    onChange={handleChange}
                    className="rounded"
                  />
                  <span className="text-sm font-medium">Competency Assessment Completed</span>
                </label>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Competency Assessment Date</label>
                <input
                  type="date"
                  name="competency_date"
                  value={form.competency_date}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
            </div>
          </div>

          {/* Compliance Status */}
          <div className="bg-gradient-to-br from-gray-50 to-white p-6 rounded-lg border-0 hover:shadow-md transition-shadow">
            <h3 className="text-lg font-semibold mb-4">Compliance Status</h3>
            <div className="grid grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium mb-1">Overall Compliance Status</label>
                <select
                  name="overall_compliance_status"
                  value={form.overall_compliance_status}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="Pending">Pending</option>
                  <option value="Compliant">Compliant</option>
                  <option value="Non-Compliant">Non-Compliant</option>
                  <option value="Partially Compliant">Partially Compliant</option>
                  <option value="Under Review">Under Review</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Last Audit Date</label>
                <input
                  type="date"
                  name="last_audit_date"
                  value={form.last_audit_date}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Next Audit Due</label>
                <input
                  type="date"
                  name="next_audit_due"
                  value={form.next_audit_due}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div className="col-span-2">
                <label className="block text-sm font-medium mb-1">Remarks</label>
                <textarea
                  name="remarks"
                  value={form.remarks}
                  onChange={handleChange}
                  className="w-full border-0 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent h-24"
                  placeholder="Enter compliance remarks or notes"
                />
              </div>

              {/* Real-time Compliance Percentage */}
              <div className="col-span-2 bg-green-50 p-4 rounded-lg">
                <h4 className="font-medium mb-2">Compliance Score</h4>
                <div className="flex items-center space-x-4">
                  <div className="text-2xl font-bold text-green-600">{compliancePercentage}%</div>
                  <div className="flex-1 bg-gray-200 rounded-full h-4">
                    <div 
                      className={`h-4 rounded-full ${
                        compliancePercentage >= 85 ? 'bg-green-500' :
                        compliancePercentage >= 70 ? 'bg-yellow-500' : 'bg-red-500'
                      }`}
                      style={{ width: `${compliancePercentage}%` }}
                    ></div>
                  </div>
                  <div className={`text-sm font-medium ${
                    compliancePercentage >= 85 ? 'text-green-600' :
                    compliancePercentage >= 70 ? 'text-yellow-600' : 'text-red-600'
                  }`}>
                    {compliancePercentage >= 85 ? 'Compliant' :
                     compliancePercentage >= 70 ? 'Partially Compliant' : 'Non-Compliant'}
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Submit */}
          <div className="text-center">
            <button
              type="submit"
              style={{ backgroundColor: 'var(--primary-color, #2862e9)' }}
              className="px-8 py-3 text-white rounded-lg border-0 transition-colors text-lg"
              onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--secondary-color, #474e71)'}
              onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--primary-color, #2862e9)'}
            >
              Save NABH Compliance Record
            </button>
          </div>
            </>
          ) : (
            <div className="text-center text-gray-500">
              You do not have permission to add NABH compliance records.
            </div>
          )}
        </form>

        {/* Display compliance records */}
        {(complianceRecords.length > 0 || deletedComplianceRecords.length > 0) && (
          <div className="mt-8">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">
                {showDeleted ? 'Deleted NABH Compliance Records' : 'NABH Compliance Records'}
              </h3>
              <div className="flex gap-2">
                {canViewDeleted && (
                  <button
                    onClick={() => setShowDeleted(!showDeleted)}
                    className={`px-4 py-2 rounded-lg border transition-colors flex items-center gap-2 ${
                      showDeleted 
                        ? 'bg-gray-800 text-white border-gray-200 hover:bg-gray-900' 
                        : 'bg-white text-gray-800 border-gray-200 hover:bg-gray-50'
                    }`}
                  >
                    {showDeleted ? <EyeOff size={16} /> : <Eye size={16} />}
                    {showDeleted ? 'Show Active' : 'Show Deleted'} ({showDeleted ? complianceRecords.length : deletedComplianceRecords.length})
                  </button>
                )}
              </div>
            </div>
            <div className="overflow-x-auto">
              {/* Desktop Table View */}
              <div className="hidden md:block">
                <table className="w-full border-0">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Employee</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Department</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Compliance %</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Status</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Last Audit</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Next Audit</th>
                      {showDeleted && <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Deleted At</th>}
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b-0">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-black">
                    {(showDeleted ? deletedComplianceRecords : complianceRecords).map((record, index) => (
                      <tr key={index} className={`hover:bg-gray-50 border-b-0 ${showDeleted ? 'bg-red-50' : ''}`}>
                        <td className="px-4 py-2 text-sm border-r-0">
                          <div>
                            <div className="font-medium">{record.employee_name}</div>
                            <div className="text-gray-500 text-xs">{record.employee_id}</div>
                          </div>
                        </td>
                        <td className="px-4 py-2 text-sm border-r-0">{record.department}</td>
                        <td className="px-4 py-2 text-sm border-r-0">
                          <div className="flex items-center space-x-2">
                            <span className="font-medium">{record.compliance_percentage}%</span>
                            <div className="w-16 bg-gray-200 rounded-full h-2">
                              <div 
                                className={`h-2 rounded-full ${
                                  record.compliance_percentage >= 85 ? 'bg-green-500' :
                                  record.compliance_percentage >= 70 ? 'bg-yellow-500' : 'bg-red-500'
                                }`}
                                style={{ width: `${record.compliance_percentage}%` }}
                              ></div>
                            </div>
                          </div>
                        </td>
                        <td className="px-4 py-2 text-sm border-r-0">
                          <span className={`px-2 py-1 rounded-full text-xs ${
                            record.overall_compliance_status === 'Compliant' ? 'bg-green-100 text-green-800' :
                            record.overall_compliance_status === 'Non-Compliant' ? 'bg-red-100 text-red-800' :
                            record.overall_compliance_status === 'Partially Compliant' ? 'bg-yellow-100 text-yellow-800' :
                            'bg-gray-100 text-gray-900'
                          }`}>
                            {record.overall_compliance_status}
                          </span>
                        </td>
                        <td className="px-4 py-2 text-sm border-r-0">{record.last_audit_date || 'N/A'}</td>
                        <td className="px-4 py-2 text-sm border-r-0">{record.next_audit_due || 'N/A'}</td>
                        {showDeleted && (
                          <td className="px-4 py-2 text-sm border-r-0">
                            {record.deleted_at ? new Date(record.deleted_at).toLocaleDateString() : 'N/A'}
                          </td>
                        )}
                        <td className="px-4 py-2 text-sm">
                          <div className="flex gap-2">
                            {showDeleted ? (
                              canRestore && (
                                <button
                                  onClick={() => handleRestore(record.id)}
                                  className="text-green-600 hover:text-green-800 p-1 rounded"
                                  title="Restore"
                                >
                                  <RotateCcw size={16} />
                                </button>
                              )
                            ) : (
                              canDelete && (
                                <button
                                  onClick={() => handleDelete(record.id)}
                                  className="text-red-600 hover:text-red-800 p-1 rounded"
                                  title="Delete"
                                >
                                  <Trash2 size={16} />
                                </button>
                              )
                            )}
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Mobile Card View */}
              <div className="md:hidden">
                {(showDeleted ? deletedComplianceRecords : complianceRecords).map((record, index) => (
                  <div key={index} className={`p-4 border-b-0 last:border-b-0 ${showDeleted ? 'bg-red-50' : ''}`}>
                    <div className="flex justify-between items-start mb-3">
                      <div className="flex-1">
                        <h4 className="font-medium text-gray-900">{record.employee_name}</h4>
                        <p className="text-sm text-gray-600">{record.employee_id}</p>
                      </div>
                      <span className={`px-2 py-1 rounded-full text-xs ${
                        record.overall_compliance_status === 'Compliant' ? 'bg-green-100 text-green-800' :
                        record.overall_compliance_status === 'Non-Compliant' ? 'bg-red-100 text-red-800' :
                        record.overall_compliance_status === 'Partially Compliant' ? 'bg-yellow-100 text-yellow-800' :
                        'bg-gray-100 text-gray-900'
                      }`}>
                        {record.overall_compliance_status}
                      </span>
                    </div>
                    
                    <div className="space-y-2 mb-3">
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Department:</span>
                        <span className="text-gray-900">{record.department}</span>
                      </div>
                      <div className="flex justify-between items-center text-sm">
                        <span className="text-gray-600">Compliance:</span>
                        <div className="flex items-center space-x-2">
                          <span className="font-medium">{record.compliance_percentage}%</span>
                          <div className="w-16 bg-gray-200 rounded-full h-2">
                            <div 
                              className={`h-2 rounded-full ${
                                record.compliance_percentage >= 85 ? 'bg-green-500' :
                                record.compliance_percentage >= 70 ? 'bg-yellow-500' : 'bg-red-500'
                              }`}
                              style={{ width: `${record.compliance_percentage}%` }}
                            ></div>
                          </div>
                        </div>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Last Audit:</span>
                        <span className="text-gray-900">{record.last_audit_date || 'N/A'}</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Next Audit:</span>
                        <span className="text-gray-900">{record.next_audit_due || 'N/A'}</span>
                      </div>
                      {showDeleted && (
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-600">Deleted At:</span>
                          <span className="text-gray-900">{record.deleted_at ? new Date(record.deleted_at).toLocaleDateString() : 'N/A'}</span>
                        </div>
                      )}
                    </div>
                    
                    <div className="flex flex-wrap gap-2">
                      {showDeleted ? (
                        canRestore && (
                          <button
                            onClick={() => handleRestore(record.id)}
                            className="flex items-center gap-1 px-3 py-1 text-xs bg-green-50 text-green-700 rounded-md border border-green-300 hover:bg-green-100"
                          >
                            <RotateCcw className="w-3 h-3" />
                            Restore
                          </button>
                        )
                      ) : (
                        canDelete && (
                          <button
                            onClick={() => handleDelete(record.id)}
                            className="flex items-center gap-1 px-3 py-1 text-xs bg-gray-50 text-gray-700 rounded-md border border-gray-300 hover:bg-gray-100"
                          >
                            <Trash2 className="w-3 h-3" />
                            Delete
                          </button>
                        )
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}


