import { useEffect, useState } from "react";
import { DollarSign, Users, Calculator, FileText, Plus } from "lucide-react";
import api from "../../api";

export default function Statutory() {
  const [form, setForm] = useState({
    employee_id: "",
    employee_name: "",
    basic_salary: "",
    gross_salary: "",
    pf_enabled: true,
    pf_percentage: "12",
    esi_enabled: true,
    esi_percentage: "1.75",
    pt_enabled: true,
    pt_amount: "200",
    tds_enabled: false,
    tds_percentage: "10",
    month: "",
    year: "",
    department: "",
    designation: "",
  });

  const [calculations, setCalculations] = useState([]);
  const [statutoryRules, setStatutoryRules] = useState(null);
  const [employees, setEmployees] = useState([]);
  const [editingRecord, setEditingRecord] = useState(null);

  // Load statutory rules and calculations
  useEffect(() => {
    async function fetchData() {
      try {
        const tenant = localStorage.getItem("tenant_db");
        const token = localStorage.getItem("access_token");
        
        // Fetch employees from both onboarding and user management like EIS does
        const [onboardingRes, usersRes] = await Promise.all([
          api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
          fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
            headers: { Authorization: `Bearer ${token}` }
          }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
        ]);
        
        const onboardedEmployees = onboardingRes.data || [];
        const userEmployees = usersRes.users || [];
        
        // Process onboarded employees
        const validOnboardedEmployees = onboardedEmployees.filter(emp => {
          if (!emp.employee_id || emp.employee_id.trim() === '') return false;
          const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
          return !isAutoGenerated;
        });
        
        const onboardedData = validOnboardedEmployees.map(emp => ({
          id: emp.application_id,
          employee_id: emp.employee_id,
          name: emp.candidate_name,
          department: emp.department,
          designation: emp.job_title
        }));
        
        // Process user management employees
        const userEmployeeData = userEmployees
          .filter(user => user.employee_code)
          .map(user => ({
            id: `user_${user.id}`,
            employee_id: user.employee_code,
            name: user.name,
            department: user.department_name,
            designation: user.designation || 'N/A'
          }));
        
        // Combine employees
        const allEmployees = [...onboardedData];
        userEmployeeData.forEach(userEmp => {
          const existingIndex = allEmployees.findIndex(emp => emp.employee_id === userEmp.employee_id);
          if (existingIndex === -1) {
            allEmployees.push(userEmp);
          } else {
            allEmployees[existingIndex] = userEmp;
          }
        });
        
        setEmployees(allEmployees);
        
        const rulesRes = await api.get("/api/payroll/statutory");
        const rules = rulesRes.data;
        setStatutoryRules(rules);
        
        // Update form with actual statutory rules
        if (rules) {
          setForm(prev => ({
            ...prev,
            pf_percentage: rules.pf_percent?.toString() || "12",
            esi_percentage: rules.esi_percent?.toString() || "1.75",
            pt_amount: rules.pt_amount?.toString() || "200",
            tds_percentage: rules.tds_percent?.toString() || "10"
          }));
        }
        
        const calcRes = await api.get("/api/compliance/statutory");
        setCalculations(calcRes.data);
      } catch (err) {
        console.log("No data found", err);
      }
    }
    fetchData();
  }, []);

  function handleChange(e) {
    const { name, value, type, checked } = e.target;
    
    setForm({ 
      ...form, 
      [name]: type === 'checkbox' ? checked : value 
    });
  }

  async function handleSubmit(e) {
    e.preventDefault();
    
    try {
      let response;
      if (editingRecord) {
        response = await api.put(`/api/compliance/statutory/${editingRecord.id}`, form);
        alert("Statutory Deductions Updated Successfully!");
        setEditingRecord(null);
      } else {
        response = await api.post("/api/compliance/statutory/calculate", form);
        const data = response.data.data;
        alert(`Statutory Deductions Calculated Successfully!\nPF: ₹${data.pf_employee}\nESI: ₹${data.esi_employee}\nPT: ₹${data.professional_tax}\nTotal: ₹${data.total_deductions}`);
      }
      
      // Reset form
      setForm({
        employee_id: "",
        employee_name: "",
        basic_salary: "",
        gross_salary: "",
        pf_enabled: true,
        pf_percentage: statutoryRules?.pf_percent?.toString() || "12",
        esi_enabled: true,
        esi_percentage: statutoryRules?.esi_percent?.toString() || "1.75",
        pt_enabled: true,
        pt_amount: statutoryRules?.pt_amount?.toString() || "200",
        tds_enabled: false,
        tds_percentage: statutoryRules?.tds_percent?.toString() || "10",
        month: "",
        year: "",
        department: "",
        designation: "",
      });
      
      // Refresh calculations list
      const calcRes = await api.get("/api/compliance/statutory/");
      setCalculations(calcRes.data);
      
    } catch (err) {
      console.error('Failed to save statutory deductions:', err);
      alert("Failed to save statutory deductions");
    }
  }

  function handleEdit(record) {
    setEditingRecord(record);
    setForm({
      employee_id: record.employee_id,
      employee_name: record.employee_name,
      basic_salary: record.basic_salary.toString(),
      gross_salary: record.basic_salary.toString(),
      pf_enabled: record.pf_amount > 0,
      pf_percentage: "12",
      esi_enabled: record.esi_amount > 0,
      esi_percentage: "1.75",
      pt_enabled: record.pt_amount > 0,
      pt_amount: record.pt_amount.toString(),
      tds_enabled: false,
      tds_percentage: "10",
      month: record.month,
      year: record.year.toString(),
      department: "",
      designation: "",
    });
  }

  async function handleDelete(recordId) {
    if (!confirm('Are you sure you want to delete this record?')) return;
    
    try {
      await api.delete(`/api/compliance/statutory/${recordId}`);
      alert("Record deleted successfully!");
      
      // Refresh calculations list
      const calcRes = await api.get("/api/compliance/statutory/");
      setCalculations(calcRes.data);
    } catch (err) {
      console.error('Failed to delete record:', err);
      alert("Failed to delete record");
    }
  }

  function cancelEdit() {
    setEditingRecord(null);
    setForm({
      employee_id: "",
      employee_name: "",
      basic_salary: "",
      gross_salary: "",
      pf_enabled: true,
      pf_percentage: statutoryRules?.pf_percent?.toString() || "12",
      esi_enabled: true,
      esi_percentage: statutoryRules?.esi_percent?.toString() || "1.75",
      pt_enabled: true,
      pt_amount: statutoryRules?.pt_amount?.toString() || "200",
      tds_enabled: false,
      tds_percentage: statutoryRules?.tds_percent?.toString() || "10",
      month: "",
      year: "",
      department: "",
      designation: "",
    });
  }

  // Calculate deductions in real-time
  const calculateDeductions = () => {
    const basic = parseFloat(form.basic_salary) || 0;
    const gross = parseFloat(form.gross_salary) || 0;
    
    const pf = form.pf_enabled ? (basic * parseFloat(form.pf_percentage) / 100) : 0;
    const esi = form.esi_enabled ? (gross * parseFloat(form.esi_percentage) / 100) : 0;
    const pt = form.pt_enabled ? parseFloat(form.pt_amount) : 0;
    const tds = form.tds_enabled ? (gross * parseFloat(form.tds_percentage) / 100) : 0;
    
    return { pf, esi, pt, tds, total: pf + esi + pt + tds };
  };

  const deductions = calculateDeductions();

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl p-6 border border-blue-100">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-blue-100 rounded-xl">
            <Calculator className="w-6 h-6 text-blue-600" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-primary">Statutory Deductions Management</h2>
            <p className=" mt-1" style={{color: 'var(--text-secondary, #374151)'}}>Manage PF, ESI, Professional Tax, and TDS calculations</p>
          </div>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-content rounded-lg p-4">
          <div className="flex items-center">
            <Users className="h-8 w-8 text-blue-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-blue-600">Total Records</p>
              <p className="text-2xl font-semibold text-blue-900">{calculations.length}</p>
            </div>
          </div>
        </div>
        <div className="bg-content rounded-lg p-4">
          <div className="flex items-center">
            <DollarSign className="h-8 w-8 text-green-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-green-600">Total PF</p>
              <p className="text-2xl font-semibold text-green-900">₹{calculations.reduce((sum, calc) => sum + (calc.pf_amount || 0), 0).toLocaleString()}</p>
            </div>
          </div>
        </div>
        <div className="bg-content rounded-lg p-4">
          <div className="flex items-center">
            <FileText className="h-8 w-8 text-purple-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-purple-600">Total ESI</p>
              <p className="text-2xl font-semibold text-purple-900">₹{calculations.reduce((sum, calc) => sum + (calc.esi_amount || 0), 0).toLocaleString()}</p>
            </div>
          </div>
        </div>
        <div className="bg-content rounded-lg p-4">
          <div className="flex items-center">
            <Calculator className="h-8 w-8 text-orange-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-orange-600">Total Deductions</p>
              <p className="text-2xl font-semibold text-orange-900">₹{calculations.reduce((sum, calc) => sum + (calc.total_deductions || 0), 0).toLocaleString()}</p>
            </div>
          </div>
        </div>
      </div>

      <div className="rounded-xl shadow-sm border p-6" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
        {/* Statutory Rules Display */}
        {statutoryRules && (
          <div className="bg-blue-50 p-4 rounded-lg mb-6">
            <h3 className="text-lg font-medium mb-2">Current Statutory Rules</h3>
            <div className="grid grid-cols-4 gap-4 text-sm">
              <div>PF: {statutoryRules.pf_enabled ? `${statutoryRules.pf_percent}%` : 'Disabled'}</div>
              <div>ESI: {statutoryRules.esi_enabled ? `${statutoryRules.esi_percent}%` : 'Disabled'}</div>
              <div>PT: {statutoryRules.pt_enabled ? `₹${statutoryRules.pt_amount}` : 'Disabled'}</div>
              <div>TDS: {statutoryRules.tds_enabled ? `${statutoryRules.tds_percent}%` : 'Disabled'}</div>
            </div>
          </div>
        )}

        <form onSubmit={handleSubmit} className="grid grid-cols-2 gap-6 mb-8">
          {/* Employee ID */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Employee ID <span className="text-red-500">*</span>
            </label>
            <select
              required
              name="employee_id"
              value={form.employee_id}
              onChange={(e) => {
                const selectedId = e.target.value;
                const selectedEmployee = employees.find(emp => emp.employee_id === selectedId);
                if (selectedEmployee) {
                  setForm({
                    ...form,
                    employee_id: selectedEmployee.employee_id,
                    employee_name: selectedEmployee.name,
                    department: selectedEmployee.department,
                    designation: selectedEmployee.designation
                  });
                } else {
                  setForm({ ...form, employee_id: selectedId });
                }
              }}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Employee ID</option>
              {employees.map((employee) => (
                <option key={employee.id} value={employee.employee_id}>
                  {employee.employee_id}
                </option>
              ))}
            </select>
          </div>

          {/* Employee Name */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Employee Name <span className="text-red-500">*</span>
            </label>
            <select
              required
              name="employee_name"
              value={form.employee_name}
              onChange={(e) => {
                const selectedName = e.target.value;
                const selectedEmployee = employees.find(emp => emp.name === selectedName);
                if (selectedEmployee) {
                  setForm({
                    ...form,
                    employee_id: selectedEmployee.employee_id,
                    employee_name: selectedEmployee.name,
                    department: selectedEmployee.department,
                    designation: selectedEmployee.designation
                  });
                } else {
                  setForm({ ...form, employee_name: selectedName });
                }
              }}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Employee Name</option>
              {employees.map((employee) => (
                <option key={employee.id} value={employee.name}>
                  {employee.name}
                </option>
              ))}
            </select>
          </div>

          {/* Basic Salary */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Basic Salary <span className="text-red-500">*</span>
            </label>
            <input
              type="number"
              required
              name="basic_salary"
              value={form.basic_salary}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Basic Salary"
              min="0"
              step="0.01"
            />
          </div>

          {/* Gross Salary */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Gross Salary <span className="text-red-500">*</span>
            </label>
            <input
              type="number"
              required
              name="gross_salary"
              value={form.gross_salary}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Gross Salary"
              min="0"
              step="0.01"
            />
          </div>

          {/* PF Settings */}
          <div className="col-span-2">
            <div className="flex items-center space-x-4 mb-2">
              <label className="flex items-center">
                <input
                  type="checkbox"
                  name="pf_enabled"
                  checked={form.pf_enabled}
                  onChange={handleChange}
                  className="mr-2"
                />
                <span className="text-sm font-medium">Enable PF Deduction</span>
              </label>
              {form.pf_enabled && (
                <div className="flex items-center space-x-2">
                  <label className="text-sm">Percentage:</label>
                  <input
                    type="number"
                    name="pf_percentage"
                    value={form.pf_percentage}
                    onChange={handleChange}
                    className="w-20 border-dark rounded px-2 py-1 text-sm"
                    min="0"
                    max="100"
                    step="0.01"
                  />
                  <span className="text-sm">%</span>
                </div>
              )}
            </div>
          </div>

          {/* ESI Settings */}
          <div className="col-span-2">
            <div className="flex items-center space-x-4 mb-2">
              <label className="flex items-center">
                <input
                  type="checkbox"
                  name="esi_enabled"
                  checked={form.esi_enabled}
                  onChange={handleChange}
                  className="mr-2"
                />
                <span className="text-sm font-medium">Enable ESI Deduction</span>
              </label>
              {form.esi_enabled && (
                <div className="flex items-center space-x-2">
                  <label className="text-sm">Percentage:</label>
                  <input
                    type="number"
                    name="esi_percentage"
                    value={form.esi_percentage}
                    onChange={handleChange}
                    className="w-20 border-dark rounded px-2 py-1 text-sm"
                    min="0"
                    max="100"
                    step="0.01"
                  />
                  <span className="text-sm">%</span>
                </div>
              )}
            </div>
          </div>

          {/* PT Settings */}
          <div className="col-span-2">
            <div className="flex items-center space-x-4 mb-2">
              <label className="flex items-center">
                <input
                  type="checkbox"
                  name="pt_enabled"
                  checked={form.pt_enabled}
                  onChange={handleChange}
                  className="mr-2"
                />
                <span className="text-sm font-medium">Enable Professional Tax</span>
              </label>
              {form.pt_enabled && (
                <div className="flex items-center space-x-2">
                  <label className="text-sm">Amount:</label>
                  <input
                    type="number"
                    name="pt_amount"
                    value={form.pt_amount}
                    onChange={handleChange}
                    className="w-20 border-dark rounded px-2 py-1 text-sm"
                    min="0"
                    step="1"
                  />
                  <span className="text-sm">₹</span>
                </div>
              )}
            </div>
          </div>

          {/* TDS Settings */}
          <div className="col-span-2">
            <div className="flex items-center space-x-4 mb-2">
              <label className="flex items-center">
                <input
                  type="checkbox"
                  name="tds_enabled"
                  checked={form.tds_enabled}
                  onChange={handleChange}
                  className="mr-2"
                />
                <span className="text-sm font-medium">Enable TDS Deduction</span>
              </label>
              {form.tds_enabled && (
                <div className="flex items-center space-x-2">
                  <label className="text-sm">Percentage:</label>
                  <input
                    type="number"
                    name="tds_percentage"
                    value={form.tds_percentage}
                    onChange={handleChange}
                    className="w-20 border-dark rounded px-2 py-1 text-sm"
                    min="0"
                    max="100"
                    step="0.01"
                  />
                  <span className="text-sm">%</span>
                </div>
              )}
            </div>
          </div>

          {/* Month */}
          <div>
            <label className="block text-sm font-medium mb-1">Month</label>
            <select
              name="month"
              value={form.month}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Month</option>
              <option value="01">January</option>
              <option value="02">February</option>
              <option value="03">March</option>
              <option value="04">April</option>
              <option value="05">May</option>
              <option value="06">June</option>
              <option value="07">July</option>
              <option value="08">August</option>
              <option value="09">September</option>
              <option value="10">October</option>
              <option value="11">November</option>
              <option value="12">December</option>
            </select>
          </div>

          {/* Year */}
          <div>
            <label className="block text-sm font-medium mb-1">Year</label>
            <input
              type="number"
              name="year"
              value={form.year}
              onChange={handleChange}
              className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Year"
              min="2020"
              max="2030"
            />
          </div>

          {/* Real-time Calculation Display */}
          {(form.basic_salary || form.gross_salary) && (
            <div className="col-span-2 bg-green-50 p-4 rounded-lg">
              <h4 className="font-medium mb-2">Calculated Deductions</h4>
              <div className="grid grid-cols-5 gap-4 text-sm">
                <div>PF: ₹{deductions.pf.toFixed(2)}</div>
                <div>ESI: ₹{deductions.esi.toFixed(2)}</div>
                <div>PT: ₹{deductions.pt.toFixed(2)}</div>
                <div>TDS: ₹{deductions.tds.toFixed(2)}</div>
                <div className="font-semibold">Total: ₹{deductions.total.toFixed(2)}</div>
              </div>
            </div>
          )}

          {/* Submit */}
          <div className="col-span-2 flex gap-4">
            <button
              type="submit"
              className="bg-blue-600 px-6 py-2 text-white rounded-lg hover:bg-blue-700"
            >
              {editingRecord ? 'Update' : 'Calculate & Save'} Statutory Deductions
            </button>
            {editingRecord && (
              <button
                type="button"
                onClick={cancelEdit}
                className="bg-gray-600 px-6 py-2 text-white rounded-lg hover:bg-gray-700"
              >
                Cancel Edit
              </button>
            )}
          </div>
        </form>

        {/* Display existing calculations */}
        {calculations.length > 0 && (
          <div>
            <h3 className="text-lg font-semibold mb-4">Statutory Deduction History</h3>
            <div className="overflow-x-auto">
              <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="w-full">
                <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-content">
                  <tr>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">Employee</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">Basic Salary</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">PF</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">ESI</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">PT</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">Total</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">Period</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-muted uppercase tracking-wider">Actions</th>
                  </tr>
                </thead>
                <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-white divide-y">
                  {calculations.map((calc, index) => (
                    <tr key={index} className="hover:bg-content">
                      <td className="px-4 py-2 text-sm">
                        <div>
                          <div className="font-medium">{calc.employee_name}</div>
                          <div className=" text-xs" style={{color: 'var(--text-muted, #6b7280)'}}>{calc.employee_id}</div>
                        </div>
                      </td>
                      <td className="px-4 py-2 text-sm">₹{calc.basic_salary}</td>
                      <td className="px-4 py-2 text-sm">₹{calc.pf_amount}</td>
                      <td className="px-4 py-2 text-sm">₹{calc.esi_amount}</td>
                      <td className="px-4 py-2 text-sm">₹{calc.pt_amount}</td>
                      <td className="px-4 py-2 text-sm font-semibold">₹{calc.total_deductions}</td>
                      <td className="px-4 py-2 text-sm">{calc.month}/{calc.year}</td>
                      <td className="px-4 py-2 text-sm">
                        <div className="flex gap-2">
                          <button
                            onClick={() => handleEdit(calc)}
                            className="text-blue-600 hover:text-blue-800 text-xs"
                          >
                            Edit
                          </button>
                          <button
                            onClick={() => handleDelete(calc.id)}
                            className="text-red-600 hover:text-red-800 text-xs"
                          >
                            Delete
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
