import { useEffect, useState } from "react";
import { DollarSign, Users, Calculator, FileText, Plus, Edit, Trash2, RotateCcw, Eye, EyeOff } from "lucide-react";
import api from "../../api";
import Toast from "../../components/Toast";
import useToast from "../../utils/useToast";
import { hasPermission, isAdmin } from "../../utils/permissions";

export default function Statutory() {
  // Permission checks
  const canView = isAdmin() || hasPermission("view_statutory_calculations");
  const canAdd = isAdmin() || hasPermission("add_statutory_calculation");
  const canEdit = isAdmin() || hasPermission("edit_statutory_calculation");
  const canDelete = isAdmin() || hasPermission("delete_statutory_calculation");
  const canViewDeleted = isAdmin() || hasPermission("view_deleted_statutory");
  const canRestore = isAdmin() || hasPermission("restore_statutory_calculation");

  if (!canView) {
    return (
      <div className="p-6 text-center">
        <div className="bg-white rounded-2xl border border-gray-200 p-8 max-w-md mx-auto">
          <h3 className="text-lg font-medium text-gray-900 mb-2">Access Denied</h3>
          <p className="text-gray-600">You do not have permission to view Statutory Rules.</p>
        </div>
      </div>
    );
  }
  const [form, setForm] = useState({
    employee_id: "",
    employee_name: "",
    basic_salary: "",
    gross_salary: "",
    pf_enabled: true,
    pf_percentage: "12",
    esi_enabled: true,
    esi_percentage: "1.75",
    pt_enabled: true,
    pt_amount: "200",
    tds_enabled: false,
    tds_percentage: "10",
    month: "",
    year: "",
    department: "",
    designation: "",
  });

  const [calculations, setCalculations] = useState([]);
  const [deletedCalculations, setDeletedCalculations] = useState([]);
  const [showDeleted, setShowDeleted] = useState(false);
  const [statutoryRules, setStatutoryRules] = useState(null);
  const [employees, setEmployees] = useState([]);
  const [editingRecord, setEditingRecord] = useState(null);
  const { toast, showToast, hideToast } = useToast();

  // Load statutory rules and calculations
  useEffect(() => {
    const fetchBrandingColors = async () => {
      try {
        const tenantCode = localStorage.getItem('tenant_code');
        if (tenantCode) {
          const response = await api.get(`/auth/branding/${tenantCode}`);
          document.documentElement.style.setProperty('--primary-color', response.data.primary_color || '#2862e9');
          document.documentElement.style.setProperty('--secondary-color', response.data.secondary_color || '#474e71');
        }
      } catch (error) {
        console.error('Error fetching branding colors:', error);
      }
    };
    fetchBrandingColors();

    async function fetchData() {
      try {
        const tenant = localStorage.getItem("tenant_db");
        const token = localStorage.getItem("access_token");
        
        // Fetch employees from both onboarding and user management like EIS does
        const [onboardingRes, usersRes] = await Promise.all([
          api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
          api.get(`/hospitals/users/${tenant}/list`).then(res => res.data ? { users: res.data } : { users: [] }).catch(() => ({ users: [] }))
        ]);
        
        const onboardedEmployees = onboardingRes.data || [];
        const userEmployees = usersRes.users || [];
        
        // Process onboarded employees
        const validOnboardedEmployees = onboardedEmployees.filter(emp => {
          if (!emp.employee_id || emp.employee_id.trim() === '') return false;
          const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
          return !isAutoGenerated;
        });
        
        const onboardedData = validOnboardedEmployees.map(emp => ({
          id: emp.application_id,
          employee_id: emp.employee_id,
          name: emp.candidate_name,
          department: emp.department,
          designation: emp.job_title
        }));
        
        // Process user management employees
        const userEmployeeData = userEmployees
          .filter(user => user.employee_code)
          .map(user => ({
            id: `user_${user.id}`,
            employee_id: user.employee_code,
            name: user.name,
            department: user.department_name,
            designation: user.designation || 'N/A'
          }));
        
        // Combine employees
        const allEmployees = [...onboardedData];
        userEmployeeData.forEach(userEmp => {
          const existingIndex = allEmployees.findIndex(emp => emp.employee_id === userEmp.employee_id);
          if (existingIndex === -1) {
            allEmployees.push(userEmp);
          } else {
            allEmployees[existingIndex] = userEmp;
          }
        });
        
        setEmployees(allEmployees);
        
        const rulesRes = await api.get("/api/payroll/statutory");
        const rules = rulesRes.data;
        setStatutoryRules(rules);
        
        // Update form with actual statutory rules
        if (rules) {
          setForm(prev => ({
            ...prev,
            pf_percentage: rules.pf_percent?.toString() || "12",
            esi_percentage: rules.esi_percent?.toString() || "1.75",
            pt_amount: rules.pt_amount?.toString() || "200",
            tds_percentage: rules.tds_percent?.toString() || "10"
          }));
        }
        
        const calcRes = await api.get("/api/compliance/statutory");
        setCalculations(calcRes.data);
        
        // Load deleted records
        const deletedRes = await api.get("/api/compliance/statutory/deleted");
        setDeletedCalculations(deletedRes.data);
      } catch (err) {
        console.log("No data found", err);
      }
    }
    fetchData();
  }, []);

  function handleChange(e) {
    const { name, value, type, checked } = e.target;
    
    setForm({ 
      ...form, 
      [name]: type === 'checkbox' ? checked : value 
    });
  }

  async function handleSubmit(e) {
    e.preventDefault();
    
    try {
      let response;
      if (editingRecord) {
        response = await api.put(`/api/compliance/statutory/${editingRecord.id}`, form);
        showToast("Statutory Deductions Updated Successfully!");
        setEditingRecord(null);
      } else {
        response = await api.post("/api/compliance/statutory/calculate", form);
        const data = response.data.data;
        showToast(`Statutory Deductions Calculated Successfully! PF: ₹${data.pf_employee}, ESI: ₹${data.esi_employee}, PT: ₹${data.professional_tax}, Total: ₹${data.total_deductions}`);
      }
      
      // Reset form
      setForm({
        employee_id: "",
        employee_name: "",
        basic_salary: "",
        gross_salary: "",
        pf_enabled: true,
        pf_percentage: statutoryRules?.pf_percent?.toString() || "12",
        esi_enabled: true,
        esi_percentage: statutoryRules?.esi_percent?.toString() || "1.75",
        pt_enabled: true,
        pt_amount: statutoryRules?.pt_amount?.toString() || "200",
        tds_enabled: false,
        tds_percentage: statutoryRules?.tds_percent?.toString() || "10",
        month: "",
        year: "",
        department: "",
        designation: "",
      });
      
      // Refresh calculations list
      const calcRes = await api.get("/api/compliance/statutory/");
      setCalculations(calcRes.data);
      
      // Refresh deleted list
      const deletedRes = await api.get("/api/compliance/statutory/deleted");
      setDeletedCalculations(deletedRes.data);
      
    } catch (err) {
      console.error('Failed to save statutory deductions:', err);
      showToast("Failed to save statutory deductions", 'error');
    }
  }

  function handleEdit(record) {
    setEditingRecord(record);
    setForm({
      employee_id: record.employee_id,
      employee_name: record.employee_name,
      basic_salary: record.basic_salary.toString(),
      gross_salary: record.basic_salary.toString(),
      pf_enabled: record.pf_amount > 0,
      pf_percentage: "12",
      esi_enabled: record.esi_amount > 0,
      esi_percentage: "1.75",
      pt_enabled: record.pt_amount > 0,
      pt_amount: record.pt_amount.toString(),
      tds_enabled: false,
      tds_percentage: "10",
      month: record.month,
      year: record.year.toString(),
      department: "",
      designation: "",
    });
  }

  async function handleDelete(recordId) {
    if (!window.confirm('Are you sure you want to delete this record?')) return;
    
    try {
      await api.delete(`/api/compliance/statutory/${recordId}`);
      showToast("Record deleted successfully!");
      
      // Refresh calculations list
      const calcRes = await api.get("/api/compliance/statutory/");
      setCalculations(calcRes.data);
      
      // Refresh deleted list
      const deletedRes = await api.get("/api/compliance/statutory/deleted");
      setDeletedCalculations(deletedRes.data);
    } catch (err) {
      console.error('Failed to delete record:', err);
      showToast("Failed to delete record", 'error');
    }
  }

  async function handleRestore(recordId) {
    if (!window.confirm('Are you sure you want to restore this record?')) return;
    
    try {
      await api.put(`/api/compliance/statutory/restore/${recordId}`);
      showToast("Record restored successfully!");
      
      // Refresh both lists
      const calcRes = await api.get("/api/compliance/statutory/");
      setCalculations(calcRes.data);
      
      const deletedRes = await api.get("/api/compliance/statutory/deleted");
      setDeletedCalculations(deletedRes.data);
    } catch (err) {
      console.error('Failed to restore record:', err);
      showToast("Failed to restore record", 'error');
    }
  }

  function cancelEdit() {
    setEditingRecord(null);
    setForm({
      employee_id: "",
      employee_name: "",
      basic_salary: "",
      gross_salary: "",
      pf_enabled: true,
      pf_percentage: statutoryRules?.pf_percent?.toString() || "12",
      esi_enabled: true,
      esi_percentage: statutoryRules?.esi_percent?.toString() || "1.75",
      pt_enabled: true,
      pt_amount: statutoryRules?.pt_amount?.toString() || "200",
      tds_enabled: false,
      tds_percentage: statutoryRules?.tds_percent?.toString() || "10",
      month: "",
      year: "",
      department: "",
      designation: "",
    });
  }

  // Calculate deductions in real-time
  const calculateDeductions = () => {
    const basic = parseFloat(form.basic_salary) || 0;
    const gross = parseFloat(form.gross_salary) || 0;
    
    const pf = form.pf_enabled ? (basic * parseFloat(form.pf_percentage) / 100) : 0;
    const esi = form.esi_enabled ? (gross * parseFloat(form.esi_percentage) / 100) : 0;
    const pt = form.pt_enabled ? parseFloat(form.pt_amount) : 0;
    const tds = form.tds_enabled ? (gross * parseFloat(form.tds_percentage) / 100) : 0;
    
    return { pf, esi, pt, tds, total: pf + esi + pt + tds };
  };

  const deductions = calculateDeductions();

  return (
    <div className="space-y-6">
      <div className="rounded-xl shadow-sm border border-black p-6" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
        {/* Statutory Rules Display */}
        {statutoryRules && (
          <div className="bg-blue-50 p-4 rounded-lg mb-6">
            <h3 className="text-lg font-medium mb-2">Current Statutory Rules</h3>
            <div className="grid grid-cols-4 gap-4 text-sm">
              <div>PF: {statutoryRules.pf_enabled ? `${statutoryRules.pf_percent}%` : 'Disabled'}</div>
              <div>ESI: {statutoryRules.esi_enabled ? `${statutoryRules.esi_percent}%` : 'Disabled'}</div>
              <div>PT: {statutoryRules.pt_enabled ? `₹${statutoryRules.pt_amount}` : 'Disabled'}</div>
              <div>TDS: {statutoryRules.tds_enabled ? `${statutoryRules.tds_percent}%` : 'Disabled'}</div>
            </div>
          </div>
        )}

        <form onSubmit={handleSubmit} className="grid grid-cols-2 gap-6 mb-8">
          {/* Employee ID */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Employee ID <span className="text-red-500">*</span>
            </label>
            <select
              required
              name="employee_id"
              value={form.employee_id}
              onChange={(e) => {
                const selectedId = e.target.value;
                const selectedEmployee = employees.find(emp => emp.employee_id === selectedId);
                if (selectedEmployee) {
                  setForm({
                    ...form,
                    employee_id: selectedEmployee.employee_id,
                    employee_name: selectedEmployee.name,
                    department: selectedEmployee.department,
                    designation: selectedEmployee.designation
                  });
                } else {
                  setForm({ ...form, employee_id: selectedId });
                }
              }}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Employee ID</option>
              {employees.map((employee) => (
                <option key={employee.id} value={employee.employee_id}>
                  {employee.employee_id}
                </option>
              ))}
            </select>
          </div>

          {/* Employee Name */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Employee Name <span className="text-red-500">*</span>
            </label>
            <select
              required
              name="employee_name"
              value={form.employee_name}
              onChange={(e) => {
                const selectedName = e.target.value;
                const selectedEmployee = employees.find(emp => emp.name === selectedName);
                if (selectedEmployee) {
                  setForm({
                    ...form,
                    employee_id: selectedEmployee.employee_id,
                    employee_name: selectedEmployee.name,
                    department: selectedEmployee.department,
                    designation: selectedEmployee.designation
                  });
                } else {
                  setForm({ ...form, employee_name: selectedName });
                }
              }}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Employee Name</option>
              {employees.map((employee) => (
                <option key={employee.id} value={employee.name}>
                  {employee.name}
                </option>
              ))}
            </select>
          </div>

          {/* Basic Salary */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Basic Salary <span className="text-red-500">*</span>
            </label>
            <input
              type="number"
              required
              name="basic_salary"
              value={form.basic_salary}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Basic Salary"
              min="0"
              step="0.01"
            />
          </div>

          {/* Gross Salary */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Gross Salary <span className="text-red-500">*</span>
            </label>
            <input
              type="number"
              required
              name="gross_salary"
              value={form.gross_salary}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Gross Salary"
              min="0"
              step="0.01"
            />
          </div>

          {/* PF Settings */}
          <div className="col-span-2">
            <div className="flex items-center space-x-4 mb-2">
              <label className="flex items-center">
                <input
                  type="checkbox"
                  name="pf_enabled"
                  checked={form.pf_enabled}
                  onChange={handleChange}
                  className="mr-2"
                />
                <span className="text-sm font-medium">Enable PF Deduction</span>
              </label>
              {form.pf_enabled && (
                <div className="flex items-center space-x-2">
                  <label className="text-sm">Percentage:</label>
                  <input
                    type="number"
                    name="pf_percentage"
                    value={form.pf_percentage}
                    onChange={handleChange}
                    className="w-20 border border-black rounded px-2 py-1 text-sm"
                    min="0"
                    max="100"
                    step="0.01"
                  />
                  <span className="text-sm">%</span>
                </div>
              )}
            </div>
          </div>

          {/* ESI Settings */}
          <div className="col-span-2">
            <div className="flex items-center space-x-4 mb-2">
              <label className="flex items-center">
                <input
                  type="checkbox"
                  name="esi_enabled"
                  checked={form.esi_enabled}
                  onChange={handleChange}
                  className="mr-2"
                />
                <span className="text-sm font-medium">Enable ESI Deduction</span>
              </label>
              {form.esi_enabled && (
                <div className="flex items-center space-x-2">
                  <label className="text-sm">Percentage:</label>
                  <input
                    type="number"
                    name="esi_percentage"
                    value={form.esi_percentage}
                    onChange={handleChange}
                    className="w-20 border border-black rounded px-2 py-1 text-sm"
                    min="0"
                    max="100"
                    step="0.01"
                  />
                  <span className="text-sm">%</span>
                </div>
              )}
            </div>
          </div>

          {/* PT Settings */}
          <div className="col-span-2">
            <div className="flex items-center space-x-4 mb-2">
              <label className="flex items-center">
                <input
                  type="checkbox"
                  name="pt_enabled"
                  checked={form.pt_enabled}
                  onChange={handleChange}
                  className="mr-2"
                />
                <span className="text-sm font-medium">Enable Professional Tax</span>
              </label>
              {form.pt_enabled && (
                <div className="flex items-center space-x-2">
                  <label className="text-sm">Amount:</label>
                  <input
                    type="number"
                    name="pt_amount"
                    value={form.pt_amount}
                    onChange={handleChange}
                    className="w-20 border border-black rounded px-2 py-1 text-sm"
                    min="0"
                    step="1"
                  />
                  <span className="text-sm">₹</span>
                </div>
              )}
            </div>
          </div>

          {/* TDS Settings */}
          <div className="col-span-2">
            <div className="flex items-center space-x-4 mb-2">
              <label className="flex items-center">
                <input
                  type="checkbox"
                  name="tds_enabled"
                  checked={form.tds_enabled}
                  onChange={handleChange}
                  className="mr-2"
                />
                <span className="text-sm font-medium">Enable TDS Deduction</span>
              </label>
              {form.tds_enabled && (
                <div className="flex items-center space-x-2">
                  <label className="text-sm">Percentage:</label>
                  <input
                    type="number"
                    name="tds_percentage"
                    value={form.tds_percentage}
                    onChange={handleChange}
                    className="w-20 border border-black rounded px-2 py-1 text-sm"
                    min="0"
                    max="100"
                    step="0.01"
                  />
                  <span className="text-sm">%</span>
                </div>
              )}
            </div>
          </div>

          {/* Month */}
          <div>
            <label className="block text-sm font-medium mb-1">Month</label>
            <select
              name="month"
              value={form.month}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select Month</option>
              <option value="01">January</option>
              <option value="02">February</option>
              <option value="03">March</option>
              <option value="04">April</option>
              <option value="05">May</option>
              <option value="06">June</option>
              <option value="07">July</option>
              <option value="08">August</option>
              <option value="09">September</option>
              <option value="10">October</option>
              <option value="11">November</option>
              <option value="12">December</option>
            </select>
          </div>

          {/* Year */}
          <div>
            <label className="block text-sm font-medium mb-1">Year</label>
            <input
              type="number"
              name="year"
              value={form.year}
              onChange={handleChange}
              className="w-full border border-black rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter Year"
              min="2020"
              max="2030"
            />
          </div>

          {/* Real-time Calculation Display */}
          {(form.basic_salary || form.gross_salary) && (
            <div className="col-span-2 bg-green-50 p-4 rounded-lg">
              <h4 className="font-medium mb-2">Calculated Deductions</h4>
              <div className="grid grid-cols-5 gap-4 text-sm">
                <div>PF: ₹{deductions.pf.toFixed(2)}</div>
                <div>ESI: ₹{deductions.esi.toFixed(2)}</div>
                <div>PT: ₹{deductions.pt.toFixed(2)}</div>
                <div>TDS: ₹{deductions.tds.toFixed(2)}</div>
                <div className="font-semibold">Total: ₹{deductions.total.toFixed(2)}</div>
              </div>
            </div>
          )}

          {/* Submit */}
          <div className="col-span-2 flex gap-4">
            <button
              type="submit"
              style={{ backgroundColor: 'var(--primary-color, #2862e9)' }}
              className="px-6 py-2 text-white rounded-lg border border-black transition-colors"
              onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--secondary-color, #474e71)'}
              onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--primary-color, #2862e9)'}
            >
              {editingRecord ? 'Update' : 'Calculate & Save'} Statutory Deductions
            </button>
            {editingRecord && (
              <button
                type="button"
                onClick={cancelEdit}
                style={{ backgroundColor: 'var(--secondary-color, #474e71)' }}
                className="px-6 py-2 text-white rounded-lg border border-black transition-colors"
                onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--primary-color, #2862e9)'}
                onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--secondary-color, #474e71)'}
              >
                Cancel Edit
              </button>
            )}
          </div>
        </form>

        {/* Display existing calculations */}
        {(calculations.length > 0 || deletedCalculations.length > 0) && (
          <div>
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">
                {showDeleted ? 'Deleted Statutory Deduction History' : 'Statutory Deduction History'}
              </h3>
              <div className="flex gap-2">
                {canViewDeleted && (
                  <button
                    onClick={() => setShowDeleted(!showDeleted)}
                    className={`px-4 py-2 rounded-lg border transition-colors flex items-center gap-2 ${
                      showDeleted 
                        ? 'bg-gray-800 text-white border-black hover:bg-gray-900' 
                        : 'bg-white text-gray-800 border-black hover:bg-gray-50'
                    }`}
                  >
                    {showDeleted ? <EyeOff size={16} /> : <Eye size={16} />}
                    {showDeleted ? 'Show Active' : 'Show Deleted'} ({showDeleted ? calculations.length : deletedCalculations.length})
                  </button>
                )}
              </div>
            </div>
            <div className="overflow-x-auto">
              {/* Desktop Table View */}
              <div className="hidden md:block">
                <table className="w-full border border-black">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Employee</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Basic Salary</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">PF</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">ESI</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">PT</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Total</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Period</th>
                      {showDeleted && <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Deleted At</th>}
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-black">
                    {(showDeleted ? deletedCalculations : calculations).map((calc, index) => (
                      <tr key={index} className={`hover:bg-gray-50 border-b border-black ${showDeleted ? 'bg-red-50' : ''}`}>
                        <td className="px-4 py-2 text-sm border-r border-black">
                          <div>
                            <div className="font-medium">{calc.employee_name}</div>
                            <div className="text-gray-500 text-xs">{calc.employee_id}</div>
                          </div>
                        </td>
                        <td className="px-4 py-2 text-sm border-r border-black">₹{calc.basic_salary}</td>
                        <td className="px-4 py-2 text-sm border-r border-black">₹{calc.pf_amount}</td>
                        <td className="px-4 py-2 text-sm border-r border-black">₹{calc.esi_amount}</td>
                        <td className="px-4 py-2 text-sm border-r border-black">₹{calc.pt_amount}</td>
                        <td className="px-4 py-2 text-sm font-semibold border-r border-black">₹{calc.total_deductions}</td>
                        <td className="px-4 py-2 text-sm border-r border-black">{calc.month}/{calc.year}</td>
                        {showDeleted && (
                          <td className="px-4 py-2 text-sm border-r border-black">
                            {calc.deleted_at ? new Date(calc.deleted_at).toLocaleDateString() : 'N/A'}
                          </td>
                        )}
                        <td className="px-4 py-2 text-sm">
                          <div className="flex gap-2">
                            {showDeleted ? (
                              canRestore && (
                                <button
                                  onClick={() => handleRestore(calc.id)}
                                  className="text-green-600 hover:text-green-800 p-1 rounded"
                                  title="Restore"
                                >
                                  <RotateCcw size={16} />
                                </button>
                              )
                            ) : (
                              <>
                                {canEdit && (
                                  <button
                                    onClick={() => handleEdit(calc)}
                                    className="text-blue-600 hover:text-blue-800 p-1 rounded"
                                    title="Edit"
                                  >
                                    <Edit size={16} />
                                  </button>
                                )}
                                {canDelete && (
                                  <button
                                    onClick={() => handleDelete(calc.id)}
                                    className="text-red-600 hover:text-red-800 p-1 rounded"
                                    title="Delete"
                                  >
                                    <Trash2 size={16} />
                                  </button>
                                )}
                              </>
                            )}
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Mobile Card View */}
              <div className="md:hidden">
                {(showDeleted ? deletedCalculations : calculations).map((calc, index) => (
                  <div key={index} className={`p-4 border-b border-gray-200 last:border-b-0 ${showDeleted ? 'bg-red-50' : ''}`}>
                    <div className="flex justify-between items-start mb-3">
                      <div className="flex-1">
                        <h4 className="font-medium text-gray-900">{calc.employee_name}</h4>
                        <p className="text-sm text-gray-600">{calc.employee_id}</p>
                      </div>
                      <span className="text-sm font-semibold text-gray-900">₹{calc.total_deductions}</span>
                    </div>
                    
                    <div className="space-y-2 mb-3">
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Basic Salary:</span>
                        <span className="text-gray-900">₹{calc.basic_salary}</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">PF:</span>
                        <span className="text-gray-900">₹{calc.pf_amount}</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">ESI:</span>
                        <span className="text-gray-900">₹{calc.esi_amount}</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">PT:</span>
                        <span className="text-gray-900">₹{calc.pt_amount}</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Period:</span>
                        <span className="text-gray-900">{calc.month}/{calc.year}</span>
                      </div>
                      {showDeleted && (
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-600">Deleted At:</span>
                          <span className="text-gray-900">{calc.deleted_at ? new Date(calc.deleted_at).toLocaleDateString() : 'N/A'}</span>
                        </div>
                      )}
                    </div>
                    
                    <div className="flex flex-wrap gap-2">
                      {showDeleted ? (
                        canRestore && (
                          <button
                            onClick={() => handleRestore(calc.id)}
                            className="flex items-center gap-1 px-3 py-1 text-xs bg-green-50 text-green-700 rounded-md border border-green-300 hover:bg-green-100"
                          >
                            <RotateCcw className="w-3 h-3" />
                            Restore
                          </button>
                        )
                      ) : (
                        <>
                          {canEdit && (
                            <button
                              onClick={() => handleEdit(calc)}
                              className="flex items-center gap-1 px-3 py-1 text-xs bg-gray-50 text-gray-700 rounded-md border border-gray-300 hover:bg-gray-100"
                            >
                              <Edit className="w-3 h-3" />
                              Edit
                            </button>
                          )}
                          {canDelete && (
                            <button
                              onClick={() => handleDelete(calc.id)}
                              className="flex items-center gap-1 px-3 py-1 text-xs bg-gray-50 text-gray-700 rounded-md border border-gray-300 hover:bg-gray-100"
                            >
                              <Trash2 className="w-3 h-3" />
                              Delete
                            </button>
                          )}
                        </>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}
