import { useState, useEffect } from "react";
import { Plus, Award, User, Calendar, FileText, Edit, Trash2, Eye, ClipboardCheck } from "lucide-react";
import api from "../../api";

export default function Appraisal() {
  const [appraisals, setAppraisals] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [employees, setEmployees] = useState([]);
  const [showViewModal, setShowViewModal] = useState(false);
  const [viewAppraisal, setViewAppraisal] = useState(null);
  const [editingAppraisal, setEditingAppraisal] = useState(null);
  const [formData, setFormData] = useState({
    employee: "",
    reviewPeriod: "",
    appraiser: "",
    department: "",
    position: "",
    reviewType: "Annual",
    overallRating: 5,
    performanceScore: "",
    goalsAchievement: "",
    competencyRating: "",
    strengths: "",
    improvements: "",
    developmentPlan: "",
    comments: "",
    recommendations: "",
    status: "Draft"
  });

  const reviewTypes = ["Annual", "Semi-Annual", "Quarterly", "Probation", "Project-Based"];
  const statuses = ["Draft", "In Progress", "Completed", "Approved", "Rejected"];
  const ratings = [1, 2, 3, 4, 5];

  useEffect(() => {
    fetchEmployees();
    fetchAppraisals();
  }, []);

  const fetchAppraisals = async () => {
    try {
      const response = await api.get('/api/pms/appraisals');
      setAppraisals(response.data?.data || []);
    } catch (error) {
      console.error('Error fetching appraisals:', error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        email: emp.email || `${emp.employee_id}@company.com`,
        source: 'onboarding'
      }));
      
      const userEmployeeData = userEmployees
        .map(user => ({
          id: `user_${user.id}`,
          name: user.name,
          employee_code: user.employee_code || `USER_${user.id}`,
          email: user.email || `${user.employee_code || `user${user.id}`}@company.com`,
          source: 'user_management'
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const handleView = (appraisal) => {
    setViewAppraisal(appraisal);
    setShowViewModal(true);
  };

  const handleEdit = (appraisal) => {
    setEditingAppraisal(appraisal.id);
    setFormData({
      employee: appraisal.employee_name || "",
      reviewPeriod: appraisal.cycle || "",
      appraiser: "",
      department: "",
      position: "",
      reviewType: "Annual",
      overallRating: appraisal.final_rating || 5,
      performanceScore: appraisal.kpi_score?.toString() || "",
      goalsAchievement: "",
      competencyRating: appraisal.feedback_score?.toString() || "",
      strengths: appraisal.strengths || "",
      improvements: appraisal.improvements || "",
      developmentPlan: appraisal.development_plan || "",
      comments: appraisal.comments || "",
      recommendations: appraisal.recommendation || "",
      status: appraisal.status || "Draft"
    });
    setShowForm(true);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const getNumericId = (id) => {
        if (typeof id === 'string' && id.startsWith('user_')) {
          return parseInt(id.replace('user_', ''));
        }
        return id;
      };
      
      const appraisalData = {
        employee_id: getNumericId(employees.find(emp => emp.name === formData.employee)?.id) || 1,
        cycle: formData.reviewPeriod,
        kpi_score: parseFloat(formData.performanceScore) || 0,
        feedback_score: parseFloat(formData.competencyRating) || 0,
        final_rating: formData.overallRating,
        recommendation: formData.recommendations,
        strengths: formData.strengths,
        improvements: formData.improvements,
        development_plan: formData.developmentPlan,
        comments: formData.comments,
        status: formData.status
      };
      
      if (editingAppraisal) {
        await api.put(`/api/pms/appraisals/${editingAppraisal}`, appraisalData);
        alert('Appraisal updated successfully!');
      } else {
        await api.post('/api/pms/appraisals', appraisalData);
        alert('Appraisal created successfully!');
      }
      fetchAppraisals();
      
      setFormData({
        employee: "",
        reviewPeriod: "",
        appraiser: "",
        department: "",
        position: "",
        reviewType: "Annual",
        overallRating: 5,
        performanceScore: "",
        goalsAchievement: "",
        competencyRating: "",
        strengths: "",
        improvements: "",
        developmentPlan: "",
        comments: "",
        recommendations: "",
        status: "Draft"
      });
      setEditingAppraisal(null);
      setShowForm(false);
    } catch (error) {
      console.error('Error submitting appraisal:', error);
      alert(`Failed to ${editingAppraisal ? 'update' : 'create'} appraisal: ${error.response?.data?.detail || error.message}`);
    }
  };

  const handleDelete = async (id) => {
    if (confirm("Are you sure you want to delete this appraisal?")) {
      try {
        await api.delete(`/api/pms/appraisals/${id}`);
        alert('Appraisal deleted successfully!');
        fetchAppraisals();
      } catch (error) {
        console.error('Error deleting appraisal:', error);
        alert('Failed to delete appraisal. Please try again.');
      }
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "Completed": return "bg-gray-100 text-gray-800 border-gray-300";
      case "Approved": return "bg-gray-100 text-gray-800 border-gray-300";
      case "In Progress": return "bg-gray-100 text-gray-800 border-gray-300";
      case "Rejected": return "bg-gray-100 text-gray-800 border-gray-300";
      case "Draft": return "bg-gray-100 text-gray-800 border-gray-300";
      default: return "bg-gray-100 text-gray-800 border-gray-300";
    }
  };

  const getRatingColor = (rating) => {
    if (rating >= 4.5) return "text-green-600";
    if (rating >= 3.5) return "text-yellow-600";
    return "text-red-600";
  };

  const renderStars = (rating) => {
    return Array.from({ length: 5 }, (_, index) => (
      <Award
        key={index}
        className={`w-4 h-4 ${index < rating ? 'text-yellow-400 fill-current' : 'text-gray-300'}`}
      />
    ));
  };

  return (
    <div className="space-y-6">
      {/* Header with Create Appraisal Button */}
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center border border-gray-300">
            <ClipboardCheck className="w-5 h-5 text-gray-600" />
          </div>
          <div>
            <h2 className="text-lg font-medium text-gray-900">Appraisal</h2>
            <p className="text-sm text-gray-600">Conduct performance appraisals and evaluations</p>
          </div>
        </div>
        <button
          onClick={() => setShowForm(true)}
          className="bg-gray-900 text-white px-4 py-2 rounded-lg hover:bg-gray-700 border border-black flex items-center gap-2 text-sm sm:text-base w-fit"
        >
          <Plus className="w-4 h-4" />
          Create Appraisal
        </button>
      </div>

      {/* Add Appraisal Form */}
      {showForm && (
        <div className="bg-white rounded-lg shadow-sm border border-black">
          <div className="px-4 sm:px-6 py-4 border-b border-black">
            <h3 className="text-base sm:text-lg font-semibold text-gray-900">{editingAppraisal ? 'Edit Performance Appraisal' : 'Create Performance Appraisal'}</h3>
          </div>
          <form onSubmit={handleSubmit} className="p-4 sm:p-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Employee</label>
                <select
                  value={formData.employee}
                  onChange={(e) => {
                    const selectedEmp = employees.find(emp => emp.name === e.target.value);
                    setFormData({
                      ...formData, 
                      employee: e.target.value,
                      department: selectedEmp?.department || "",
                      position: selectedEmp?.position || ""
                    });
                  }}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                >
                  <option value="">Select Employee</option>
                  {employees.map(emp => (
                    <option key={emp.id} value={emp.name}>{emp.employee_code} - {emp.name}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Review Period</label>
                <input
                  type="text"
                  value={formData.reviewPeriod}
                  onChange={(e) => setFormData({...formData, reviewPeriod: e.target.value})}
                  placeholder="e.g., 2024 Annual Review, Q4 2024"
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Appraiser</label>
                <select
                  value={formData.appraiser}
                  onChange={(e) => setFormData({...formData, appraiser: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                >
                  <option value="">Select Appraiser</option>
                  {employees.map(emp => (
                    <option key={emp.id} value={emp.name}>{emp.employee_code} - {emp.name}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Review Type</label>
                <select
                  value={formData.reviewType}
                  onChange={(e) => setFormData({...formData, reviewType: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                >
                  {reviewTypes.map(type => (
                    <option key={type} value={type}>{type}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Overall Rating</label>
                <select
                  value={formData.overallRating}
                  onChange={(e) => setFormData({...formData, overallRating: parseInt(e.target.value)})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                >
                  {ratings.map(rating => (
                    <option key={rating} value={rating}>{rating} - {rating === 5 ? 'Excellent' : rating === 4 ? 'Good' : rating === 3 ? 'Average' : rating === 2 ? 'Below Average' : 'Poor'}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Performance Score (%)</label>
                <input
                  type="number"
                  min="0"
                  max="100"
                  value={formData.performanceScore}
                  onChange={(e) => setFormData({...formData, performanceScore: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                />
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">Key Strengths</label>
                <textarea
                  value={formData.strengths}
                  onChange={(e) => setFormData({...formData, strengths: e.target.value})}
                  rows={3}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  placeholder="List key strengths and achievements..."
                />
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">Areas for Improvement</label>
                <textarea
                  value={formData.improvements}
                  onChange={(e) => setFormData({...formData, improvements: e.target.value})}
                  rows={3}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  placeholder="Identify areas that need improvement..."
                />
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">Development Plan</label>
                <textarea
                  value={formData.developmentPlan}
                  onChange={(e) => setFormData({...formData, developmentPlan: e.target.value})}
                  rows={3}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  placeholder="Outline development plan and training needs..."
                />
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">Comments</label>
                <textarea
                  value={formData.comments}
                  onChange={(e) => setFormData({...formData, comments: e.target.value})}
                  rows={4}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  placeholder="Additional comments and observations..."
                />
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">Recommendations</label>
                <textarea
                  value={formData.recommendations}
                  onChange={(e) => setFormData({...formData, recommendations: e.target.value})}
                  rows={2}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  placeholder="Recommendations for promotion, role changes, etc..."
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Status</label>
                <select
                  value={formData.status}
                  onChange={(e) => setFormData({...formData, status: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                >
                  {statuses.map(status => (
                    <option key={status} value={status}>{status}</option>
                  ))}
                </select>
              </div>
            </div>

            <div className="mt-4 sm:mt-6 flex flex-col sm:flex-row justify-end space-y-2 sm:space-y-0 sm:space-x-3">
              <button
                type="button"
                onClick={() => setShowForm(false)}
                className="w-full sm:w-auto px-4 py-2 border border-black text-gray-700 rounded-md hover:bg-gray-50 text-sm sm:text-base"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="w-full sm:w-auto px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-700 border border-black text-sm sm:text-base"
              >
                {editingAppraisal ? 'Update Appraisal' : 'Create Appraisal'}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* View Appraisal Modal */}
      {showViewModal && viewAppraisal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-lg max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto border border-black">
            <div className="px-4 sm:px-6 py-4 border-b border-black">
              <h3 className="text-base sm:text-lg font-semibold text-gray-900">Appraisal Details</h3>
            </div>
            <div className="p-4 sm:p-6 space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700">Employee</label>
                  <p className="text-sm text-gray-900">{viewAppraisal.employee_name}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Review Period</label>
                  <p className="text-sm text-gray-900">{viewAppraisal.cycle}</p>
                </div>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700">Final Rating</label>
                  <div className="flex items-center">
                    {renderStars(viewAppraisal.final_rating || 0)}
                    <span className="ml-2 text-sm text-gray-600">({viewAppraisal.final_rating || 0}/5)</span>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Status</label>
                  <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${getStatusColor(viewAppraisal.status)}`}>
                    {viewAppraisal.status}
                  </span>
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">KPI Score</label>
                <p className="text-sm text-gray-900">{viewAppraisal.kpi_score || 'N/A'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Feedback Score</label>
                <p className="text-sm text-gray-900">{viewAppraisal.feedback_score || 'N/A'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Recommendations</label>
                <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded border border-black">{viewAppraisal.recommendation || 'No recommendations provided'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Key Strengths</label>
                <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded border border-black">{viewAppraisal.strengths || 'No strengths mentioned'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Areas for Improvement</label>
                <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded border border-black">{viewAppraisal.improvements || 'No improvements mentioned'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Development Plan</label>
                <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded border border-black">{viewAppraisal.development_plan || 'No development plan provided'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Comments</label>
                <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded border border-black">{viewAppraisal.comments || 'No comments provided'}</p>
              </div>
            </div>
            <div className="px-4 sm:px-6 py-4 border-t border-black flex justify-end">
              <button
                onClick={() => {
                  setShowViewModal(false);
                  setViewAppraisal(null);
                }}
                className="px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-700 border border-black text-sm sm:text-base"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Appraisals List */}
      <div className="bg-white rounded-lg shadow-sm border border-black">
        <div className="px-4 sm:px-6 py-4 border-b border-black">
          <h3 className="text-base sm:text-lg font-semibold text-gray-900">Performance Appraisals</h3>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200 border border-black">
            <thead className="bg-gray-50 border-b border-black">
              <tr>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Employee</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Review Period</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Rating</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {appraisals.map((appraisal) => (
                <tr key={appraisal.id}>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <div>
                      <div className="text-sm font-medium text-gray-900">{appraisal.employee_name}</div>
                      <div className="text-sm text-gray-500">ID: {appraisal.employee_id}</div>
                    </div>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <div className="text-sm text-gray-900">{appraisal.cycle}</div>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      {renderStars(appraisal.final_rating || 0)}
                      <span className={`ml-2 text-sm font-medium ${getRatingColor(appraisal.final_rating || 0)}`}>
                        {appraisal.final_rating || 0}/5
                      </span>
                    </div>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${getStatusColor(appraisal.status)}`}>
                      {appraisal.status}
                    </span>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <div className="flex flex-wrap gap-1 sm:gap-2">
                      <button 
                        onClick={() => handleView(appraisal)}
                        className="p-1 sm:p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-lg border border-gray-300" 
                        title="View Details"
                      >
                        <Eye className="w-3 h-3 sm:w-4 sm:h-4" />
                      </button>
                      <button 
                        onClick={() => handleEdit(appraisal)}
                        className="p-1 sm:p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-lg border border-gray-300" 
                        title="Edit"
                      >
                        <Edit className="w-3 h-3 sm:w-4 sm:h-4" />
                      </button>
                      <button
                        onClick={() => handleDelete(appraisal.id)}
                        className="p-1 sm:p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-lg border border-gray-300"
                        title="Delete"
                      >
                        <Trash2 className="w-3 h-3 sm:w-4 sm:h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}