import { useState, useEffect } from "react";
import { Plus, Award, User, Calendar, FileText, Edit, Trash2, Eye } from "lucide-react";
import api from "../../api";

export default function Appraisal() {
  const [appraisals, setAppraisals] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [employees, setEmployees] = useState([]);
  const [showViewModal, setShowViewModal] = useState(false);
  const [viewAppraisal, setViewAppraisal] = useState(null);
  const [editingAppraisal, setEditingAppraisal] = useState(null);
  const [formData, setFormData] = useState({
    employee: "",
    reviewPeriod: "",
    appraiser: "",
    department: "",
    position: "",
    reviewType: "Annual",
    overallRating: 5,
    performanceScore: "",
    goalsAchievement: "",
    competencyRating: "",
    strengths: "",
    improvements: "",
    developmentPlan: "",
    comments: "",
    recommendations: "",
    status: "Draft"
  });

  const reviewTypes = ["Annual", "Semi-Annual", "Quarterly", "Probation", "Project-Based"];
  const statuses = ["Draft", "In Progress", "Completed", "Approved", "Rejected"];
  const ratings = [1, 2, 3, 4, 5];

  useEffect(() => {
    fetchEmployees();
    fetchAppraisals();
  }, []);

  const fetchAppraisals = async () => {
    try {
      const response = await api.get('/api/pms/appraisals');
      setAppraisals(response.data?.data || []);
    } catch (error) {
      console.error('Error fetching appraisals:', error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      // Fetch from both onboarding and user management like EIS does
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        email: emp.email || `${emp.employee_id}@company.com`,
        source: 'onboarding'
      }));
      
      // Process user management employees (include all, not just those with employee_code)
      const userEmployeeData = userEmployees
        .map(user => ({
          id: `user_${user.id}`,
          name: user.name,
          employee_code: user.employee_code || `USER_${user.id}`, // Use fallback if no employee_code
          email: user.email || `${user.employee_code || `user${user.id}`}@company.com`,
          source: 'user_management'
        }));
      
      // Combine and remove duplicates
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const handleView = (appraisal) => {
    setViewAppraisal(appraisal);
    setShowViewModal(true);
  };

  const handleEdit = (appraisal) => {
    setEditingAppraisal(appraisal.id);
    setFormData({
      employee: appraisal.employee_name || "",
      reviewPeriod: appraisal.cycle || "",
      appraiser: "",
      department: "",
      position: "",
      reviewType: "Annual",
      overallRating: appraisal.final_rating || 5,
      performanceScore: appraisal.kpi_score?.toString() || "",
      goalsAchievement: "",
      competencyRating: appraisal.feedback_score?.toString() || "",
      strengths: appraisal.strengths || "",
      improvements: appraisal.improvements || "",
      developmentPlan: appraisal.development_plan || "",
      comments: appraisal.comments || "",
      recommendations: appraisal.recommendation || "",
      status: appraisal.status || "Draft"
    });
    setShowForm(true);
  };

  const handleDownload = (appraisal) => {
    const content = `Performance Appraisal Report

Employee: ${appraisal.employee_name}
Employee ID: ${appraisal.employee_id}
Review Period: ${appraisal.cycle}
Overall Rating: ${appraisal.final_rating}/5
KPI Score: ${appraisal.kpi_score || 'N/A'}
Feedback Score: ${appraisal.feedback_score || 'N/A'}
Status: ${appraisal.status}

Strengths:
${appraisal.strengths || 'Not provided'}

Areas for Improvement:
${appraisal.improvements || 'Not provided'}

Development Plan:
${appraisal.development_plan || 'Not provided'}

Comments:
${appraisal.comments || 'Not provided'}

Recommendations:
${appraisal.recommendation || 'Not provided'}

Generated on: ${new Date().toLocaleDateString()}`;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Performance_Appraisal_${appraisal.employee_name?.replace(/\s+/g, '_')}_${appraisal.cycle}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleStatusUpdate = async (appraisalId, newStatus) => {
    try {
      await api.put(`/api/pms/appraisals/${appraisalId}`, { status: newStatus });
      alert(`Appraisal status updated to ${newStatus}!`);
      fetchAppraisals();
    } catch (error) {
      console.error('Error updating status:', error);
      alert('Failed to update status. Please try again.');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const getNumericId = (id) => {
        if (typeof id === 'string' && id.startsWith('user_')) {
          return parseInt(id.replace('user_', ''));
        }
        return id;
      };
      
      const appraisalData = {
        employee_id: getNumericId(employees.find(emp => emp.name === formData.employee)?.id) || 1,
        cycle: formData.reviewPeriod,
        kpi_score: parseFloat(formData.performanceScore) || 0,
        feedback_score: parseFloat(formData.competencyRating) || 0,
        final_rating: formData.overallRating,
        recommendation: formData.recommendations,
        strengths: formData.strengths,
        improvements: formData.improvements,
        development_plan: formData.developmentPlan,
        comments: formData.comments,
        status: formData.status
      };
      
      if (editingAppraisal) {
        await api.put(`/api/pms/appraisals/${editingAppraisal}`, appraisalData);
        alert('Appraisal updated successfully!');
      } else {
        await api.post('/api/pms/appraisals', appraisalData);
        alert('Appraisal created successfully!');
      }
      fetchAppraisals();
      
      setFormData({
        employee: "",
        reviewPeriod: "",
        appraiser: "",
        department: "",
        position: "",
        reviewType: "Annual",
        overallRating: 5,
        performanceScore: "",
        goalsAchievement: "",
        competencyRating: "",
        strengths: "",
        improvements: "",
        developmentPlan: "",
        comments: "",
        recommendations: "",
        status: "Draft"
      });
      setEditingAppraisal(null);
      setShowForm(false);
    } catch (error) {
      console.error('Error submitting appraisal:', error);
      console.error('Error details:', error.response?.data);
      alert(`Failed to ${editingAppraisal ? 'update' : 'create'} appraisal: ${error.response?.data?.detail || error.message}`);
    }
  };

  const handleDelete = async (id) => {
    if (confirm("Are you sure you want to delete this appraisal?")) {
      try {
        await api.delete(`/api/pms/appraisals/${id}`);
        alert('Appraisal deleted successfully!');
        fetchAppraisals();
      } catch (error) {
        console.error('Error deleting appraisal:', error);
        alert('Failed to delete appraisal. Please try again.');
      }
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "Completed": return "bg-green-100 text-green-800";
      case "Approved": return "bg-blue-100 text-blue-800";
      case "In Progress": return "bg-yellow-100 text-yellow-800";
      case "Rejected": return "bg-red-100 text-red-800";
      case "Draft": return "bg-gray-100 text-gray-800";
      default: return "bg-gray-100 text-gray-800";
    }
  };

  const getRatingColor = (rating) => {
    if (rating >= 4.5) return "text-green-600";
    if (rating >= 3.5) return "text-yellow-600";
    return "text-red-600";
  };

  const renderStars = (rating) => {
    return Array.from({ length: 5 }, (_, index) => (
      <Award
        key={index}
        className={`w-4 h-4 ${index < rating ? 'text-yellow-400 fill-current' : 'text-gray-300'}`}
      />
    ));
  };

  return (
    <div className="space-y-6">
        {/* Header */}
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Performance Appraisal</h1>
            <p className="text-gray-600">Manage employee performance appraisals and evaluations</p>
          </div>
          <button
            onClick={() => {
              setEditingAppraisal(null);
              setFormData({
                employee: "",
                reviewPeriod: "",
                appraiser: "",
                department: "",
                position: "",
                reviewType: "Annual",
                overallRating: 5,
                performanceScore: "",
                goalsAchievement: "",
                competencyRating: "",
                strengths: "",
                improvements: "",
                developmentPlan: "",
                comments: "",
                recommendations: "",
                status: "Draft"
              });
              setShowForm(true);
            }}
            className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            <Plus className="w-4 h-4" />
            <span>Create Appraisal</span>
          </button>
        </div>

        {/* Add Appraisal Form */}
        {showForm && (
          <div className="bg-white rounded-lg shadow-sm border">
            <div className="px-6 py-4 border-b">
              <h3 className="text-lg font-semibold text-gray-900">Create Performance Appraisal</h3>
            </div>
            <form onSubmit={handleSubmit} className="p-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Employee</label>
                  <select
                    value={formData.employee}
                    onChange={(e) => {
                      const selectedEmp = employees.find(emp => emp.name === e.target.value);
                      setFormData({
                        ...formData, 
                        employee: e.target.value,
                        department: selectedEmp?.department || "",
                        position: selectedEmp?.position || ""
                      });
                    }}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required
                  >
                    <option value="">Select Employee</option>
                    {employees.map(emp => (
                      <option key={emp.id} value={emp.name}>{emp.employee_code} - {emp.name}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Review Period</label>
                  <input
                    type="text"
                    value={formData.reviewPeriod}
                    onChange={(e) => setFormData({...formData, reviewPeriod: e.target.value})}
                    placeholder="e.g., 2024 Annual Review, Q4 2024"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Appraiser</label>
                  <select
                    value={formData.appraiser}
                    onChange={(e) => setFormData({...formData, appraiser: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required
                  >
                    <option value="">Select Appraiser</option>
                    {employees.map(emp => (
                      <option key={emp.id} value={emp.name}>{emp.employee_code} - {emp.name}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Review Type</label>
                  <select
                    value={formData.reviewType}
                    onChange={(e) => setFormData({...formData, reviewType: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    {reviewTypes.map(type => (
                      <option key={type} value={type}>{type}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Department</label>
                  <input
                    type="text"
                    value={formData.department}
                    onChange={(e) => setFormData({...formData, department: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Enter department"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Position</label>
                  <input
                    type="text"
                    value={formData.position}
                    onChange={(e) => setFormData({...formData, position: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Enter position"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Overall Rating</label>
                  <select
                    value={formData.overallRating}
                    onChange={(e) => setFormData({...formData, overallRating: parseInt(e.target.value)})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    {ratings.map(rating => (
                      <option key={rating} value={rating}>{rating} - {rating === 5 ? 'Excellent' : rating === 4 ? 'Good' : rating === 3 ? 'Average' : rating === 2 ? 'Below Average' : 'Poor'}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Performance Score (%)</label>
                  <input
                    type="number"
                    min="0"
                    max="100"
                    value={formData.performanceScore}
                    onChange={(e) => setFormData({...formData, performanceScore: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Goals Achievement</label>
                  <input
                    type="text"
                    value={formData.goalsAchievement}
                    onChange={(e) => setFormData({...formData, goalsAchievement: e.target.value})}
                    placeholder="e.g., 90%, 8/10 goals"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Competency Rating</label>
                  <input
                    type="number"
                    min="1"
                    max="5"
                    step="0.1"
                    value={formData.competencyRating}
                    onChange={(e) => setFormData({...formData, competencyRating: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>

                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 mb-2">Key Strengths</label>
                  <textarea
                    value={formData.strengths}
                    onChange={(e) => setFormData({...formData, strengths: e.target.value})}
                    rows={3}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="List key strengths and achievements..."
                  />
                </div>

                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 mb-2">Areas for Improvement</label>
                  <textarea
                    value={formData.improvements}
                    onChange={(e) => setFormData({...formData, improvements: e.target.value})}
                    rows={3}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Identify areas that need improvement..."
                  />
                </div>

                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 mb-2">Development Plan</label>
                  <textarea
                    value={formData.developmentPlan}
                    onChange={(e) => setFormData({...formData, developmentPlan: e.target.value})}
                    rows={3}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Outline development plan and training needs..."
                  />
                </div>

                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 mb-2">Comments</label>
                  <textarea
                    value={formData.comments}
                    onChange={(e) => setFormData({...formData, comments: e.target.value})}
                    rows={4}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Additional comments and observations..."
                  />
                </div>

                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 mb-2">Recommendations</label>
                  <textarea
                    value={formData.recommendations}
                    onChange={(e) => setFormData({...formData, recommendations: e.target.value})}
                    rows={2}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Recommendations for promotion, role changes, etc..."
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Status</label>
                  <select
                    value={formData.status}
                    onChange={(e) => setFormData({...formData, status: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    {statuses.map(status => (
                      <option key={status} value={status}>{status}</option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="mt-6 flex justify-end space-x-3">
                <button
                  type="button"
                  onClick={() => setShowForm(false)}
                  className="px-4 py-2 border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
                >
                  {editingAppraisal ? 'Update Appraisal' : 'Create Appraisal'}
                </button>
              </div>
            </form>
          </div>
        )}

        {/* View Appraisal Modal */}
        {showViewModal && viewAppraisal && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white rounded-lg shadow-lg max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto">
              <div className="px-6 py-4 border-b">
                <h3 className="text-lg font-semibold text-gray-900">Appraisal Details</h3>
              </div>
              <div className="p-6 space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700">Employee</label>
                    <p className="text-sm text-gray-900">{viewAppraisal.employee_name}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700">Review Period</label>
                    <p className="text-sm text-gray-900">{viewAppraisal.cycle}</p>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700">Final Rating</label>
                    <div className="flex items-center">
                      {renderStars(viewAppraisal.final_rating || 0)}
                      <span className="ml-2 text-sm text-gray-600">({viewAppraisal.final_rating || 0}/5)</span>
                    </div>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700">Status</label>
                    <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${getStatusColor(viewAppraisal.status)}`}>
                      {viewAppraisal.status}
                    </span>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">KPI Score</label>
                  <p className="text-sm text-gray-900">{viewAppraisal.kpi_score || 'N/A'}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Feedback Score</label>
                  <p className="text-sm text-gray-900">{viewAppraisal.feedback_score || 'N/A'}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Recommendations</label>
                  <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded">{viewAppraisal.recommendation || 'No recommendations provided'}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Key Strengths</label>
                  <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded">{viewAppraisal.strengths || 'No strengths mentioned'}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Areas for Improvement</label>
                  <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded">{viewAppraisal.improvements || 'No improvements mentioned'}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Development Plan</label>
                  <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded">{viewAppraisal.development_plan || 'No development plan provided'}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Comments</label>
                  <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded">{viewAppraisal.comments || 'No comments provided'}</p>
                </div>
              </div>
              <div className="px-6 py-4 border-t flex justify-end">
                <button
                  onClick={() => {
                    setShowViewModal(false);
                    setViewAppraisal(null);
                  }}
                  className="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Appraisals List */}
        <div className="bg-white rounded-lg shadow-sm border">
          <div className="px-6 py-4 border-b">
            <h3 className="text-lg font-semibold text-gray-900">Performance Appraisals</h3>
          </div>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Employee</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Review Period</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Rating</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Progress</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {appraisals.map((appraisal) => (
                  <tr key={appraisal.id}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <div className="text-sm font-medium text-gray-900">{appraisal.employee_name}</div>
                        <div className="text-sm text-gray-500">ID: {appraisal.employee_id}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-gray-900">{appraisal.cycle}</div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        {renderStars(appraisal.final_rating || 0)}
                        <span className={`ml-2 text-sm font-medium ${getRatingColor(appraisal.final_rating || 0)}`}>
                          {appraisal.final_rating || 0}/5
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center space-x-2">
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div
                            className="h-2 bg-blue-500 rounded-full"
                            style={{ width: `${appraisal.progress_percentage || 0}%` }}
                          ></div>
                        </div>
                        <span className="text-sm text-gray-600 whitespace-nowrap">{appraisal.progress || "0%"}</span>
                        <div className="flex space-x-1">
                          {appraisal.status === "Draft" && (
                            <button
                              onClick={() => handleStatusUpdate(appraisal.id, "In Progress")}
                              className="px-2 py-1 text-xs bg-blue-600 text-white rounded hover:bg-blue-700"
                              title="Start Review"
                            >
                              Start
                            </button>
                          )}
                          {appraisal.status === "Proposed" && (
                            <button
                              onClick={() => handleStatusUpdate(appraisal.id, "In Progress")}
                              className="px-2 py-1 text-xs bg-blue-600 text-white rounded hover:bg-blue-700"
                              title="Start Review"
                            >
                              Start
                            </button>
                          )}
                          {appraisal.status === "In Progress" && (
                            <button
                              onClick={() => handleStatusUpdate(appraisal.id, "Completed")}
                              className="px-2 py-1 text-xs bg-green-600 text-white rounded hover:bg-green-700"
                              title="Complete Review"
                            >
                              Complete
                            </button>
                          )}
                          {appraisal.status === "Completed" && (
                            <button
                              onClick={() => handleStatusUpdate(appraisal.id, "Approved")}
                              className="px-2 py-1 text-xs bg-purple-600 text-white rounded hover:bg-purple-700"
                              title="Approve"
                            >
                              Approve
                            </button>
                          )}
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${getStatusColor(appraisal.status)}`}>
                        {appraisal.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                      <div className="flex space-x-2">
                        <button 
                          onClick={() => handleView(appraisal)}
                          className="text-blue-600 hover:text-blue-900" 
                          title="View Details"
                        >
                          <Eye className="w-4 h-4" />
                        </button>
                        <button 
                          onClick={() => handleEdit(appraisal)}
                          className="text-blue-600 hover:text-blue-900" 
                          title="Edit"
                        >
                          <Edit className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleDelete(appraisal.id)}
                          className="text-red-600 hover:text-red-900"
                          title="Delete"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
    </div>
  );
}