import { useState, useEffect } from "react";
import { Plus, Award, User, Calendar, FileText, Edit, Trash2, Eye, ClipboardCheck } from "lucide-react";
import api from "../../api";
import Toast from "../../components/Toast";
import useToast from "../../utils/useToast";
import { hasPermission, isAdmin } from "../../utils/permissions";

export default function Appraisal() {
  // Check permissions
  if (!hasPermission('view_appraisals') && !isAdmin()) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <div className="text-6xl mb-4">🔒</div>
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Access Denied</h2>
          <p className="text-gray-600">You don't have permission to view appraisals.</p>
        </div>
      </div>
    );
  }
  const [appraisals, setAppraisals] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [employees, setEmployees] = useState([]);
  const [showViewModal, setShowViewModal] = useState(false);
  const [viewAppraisal, setViewAppraisal] = useState(null);
  const [editingAppraisal, setEditingAppraisal] = useState(null);
  const [showDeleted, setShowDeleted] = useState(false);
  const [deletedCount, setDeletedCount] = useState(0);
  const { toast, showToast, hideToast } = useToast();
  const [formData, setFormData] = useState({
    employee: "",
    reviewPeriod: "",
    appraiser: "",
    department: "",
    position: "",
    reviewType: "Annual",
    overallRating: 5,
    performanceScore: "",
    goalsAchievement: "",
    competencyRating: "",
    strengths: "",
    improvements: "",
    developmentPlan: "",
    comments: "",
    recommendations: "",
    status: "Draft"
  });

  const reviewTypes = ["Annual", "Semi-Annual", "Quarterly", "Probation", "Project-Based"];
  const statuses = ["Draft", "In Progress", "Completed", "Approved", "Rejected"];
  const ratings = [1, 2, 3, 4, 5];

  useEffect(() => {
    fetchEmployees();
    fetchAppraisals();
    
    const fetchColors = async () => {
      try {
        const tenantCode = localStorage.getItem('tenant_code');
        if (tenantCode) {
          const response = await api.get(`/auth/branding/${tenantCode}`);
          document.documentElement.style.setProperty('--primary-color', response.data.primary_color || '#2862e9');
          document.documentElement.style.setProperty('--secondary-color', response.data.secondary_color || '#474e71');
        }
      } catch (error) {
        console.error('Failed to fetch branding colors:', error);
      }
    };
    fetchColors();
  }, [showDeleted]);

  const fetchAppraisals = async () => {
    try {
      const response = await api.get(`/api/pms/appraisals${showDeleted ? '?include_deleted=true' : ''}`);
      setAppraisals(response.data?.data || []);
      
      // Fetch deleted count
      if (!showDeleted) {
        try {
          const deletedResponse = await api.get('/api/pms/appraisals/deleted-count');
          setDeletedCount(deletedResponse.data?.count || 0);
        } catch (error) {
          console.error('Error fetching deleted count:', error);
          setDeletedCount(0);
        }
      }
    } catch (error) {
      console.error('Error fetching appraisals:', error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`${api.defaults.baseURL}/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        email: emp.email || `${emp.employee_id}@company.com`,
        source: 'onboarding'
      }));
      
      const userEmployeeData = userEmployees
        .map(user => ({
          id: `user_${user.id}`,
          name: user.name,
          employee_code: user.employee_code || `USER_${user.id}`,
          email: user.email || `${user.employee_code || `user${user.id}`}@company.com`,
          source: 'user_management'
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const handleView = (appraisal) => {
    setViewAppraisal(appraisal);
    setShowViewModal(true);
  };

  const handleEdit = (appraisal) => {
    setEditingAppraisal(appraisal.id);
    setFormData({
      employee: appraisal.employee_name || "",
      reviewPeriod: appraisal.cycle || "",
      appraiser: "",
      department: "",
      position: "",
      reviewType: "Annual",
      overallRating: appraisal.final_rating || 5,
      performanceScore: appraisal.kpi_score?.toString() || "",
      goalsAchievement: "",
      competencyRating: appraisal.feedback_score?.toString() || "",
      strengths: appraisal.strengths || "",
      improvements: appraisal.improvements || "",
      developmentPlan: appraisal.development_plan || "",
      comments: appraisal.comments || "",
      recommendations: appraisal.recommendation || "",
      status: appraisal.status || "Draft"
    });
    setShowForm(true);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const getNumericId = (id) => {
        if (typeof id === 'string' && id.startsWith('user_')) {
          return parseInt(id.replace('user_', ''));
        }
        return id;
      };
      
      const appraisalData = {
        employee_id: getNumericId(employees.find(emp => emp.name === formData.employee)?.id) || 1,
        cycle: formData.reviewPeriod,
        kpi_score: parseFloat(formData.performanceScore) || 0,
        feedback_score: parseFloat(formData.competencyRating) || 0,
        final_rating: formData.overallRating,
        recommendation: formData.recommendations,
        strengths: formData.strengths,
        improvements: formData.improvements,
        development_plan: formData.developmentPlan,
        comments: formData.comments,
        status: formData.status
      };
      
      if (editingAppraisal) {
        await api.put(`/api/pms/appraisals/${editingAppraisal}`, appraisalData);
        showToast('Appraisal updated successfully!');
      } else {
        await api.post('/api/pms/appraisals', appraisalData);
        showToast('Appraisal created successfully!');
      }
      fetchAppraisals();
      
      setFormData({
        employee: "",
        reviewPeriod: "",
        appraiser: "",
        department: "",
        position: "",
        reviewType: "Annual",
        overallRating: 5,
        performanceScore: "",
        goalsAchievement: "",
        competencyRating: "",
        strengths: "",
        improvements: "",
        developmentPlan: "",
        comments: "",
        recommendations: "",
        status: "Draft"
      });
      setEditingAppraisal(null);
      setShowForm(false);
    } catch (error) {
      console.error('Error submitting appraisal:', error);
      showToast(`Failed to ${editingAppraisal ? 'update' : 'create'} appraisal: ${error.response?.data?.detail || error.message}`, 'error');
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm("Are you sure you want to delete this appraisal? It will be moved to deleted items.")) {
      try {
        await api.delete(`/api/pms/appraisals/${id}`);
        showToast('Appraisal deleted successfully!');
        fetchAppraisals();
      } catch (error) {
        console.error('Error deleting appraisal:', error);
        showToast('Failed to delete appraisal. Please try again.', 'error');
      }
    }
  };

  const handleRestore = async (id) => {
    if (window.confirm("Are you sure you want to restore this appraisal?")) {
      try {
        await api.put(`/api/pms/appraisals/${id}/restore`);
        showToast('Appraisal restored successfully!');
        fetchAppraisals();
      } catch (error) {
        console.error('Error restoring appraisal:', error);
        showToast('Failed to restore appraisal. Please try again.', 'error');
      }
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "Completed": return "bg-gray-100 text-gray-800 border-gray-300";
      case "Approved": return "bg-gray-100 text-gray-800 border-gray-300";
      case "In Progress": return "bg-gray-100 text-gray-800 border-gray-300";
      case "Rejected": return "bg-gray-100 text-gray-800 border-gray-300";
      case "Draft": return "bg-gray-100 text-gray-800 border-gray-300";
      default: return "bg-gray-100 text-gray-800 border-gray-300";
    }
  };

  const getRatingColor = (rating) => {
    if (rating >= 4.5) return "text-green-600";
    if (rating >= 3.5) return "text-yellow-600";
    return "text-red-600";
  };

  const renderStars = (rating) => {
    return Array.from({ length: 5 }, (_, index) => (
      <Award
        key={index}
        className={`w-4 h-4 ${index < rating ? 'text-yellow-400 fill-current' : 'text-gray-300'}`}
      />
    ));
  };

  return (
    <div className="space-y-6">
      {/* Header with Create Appraisal Button */}
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center border border-gray-300">
            <ClipboardCheck className="w-5 h-5 text-gray-600" />
          </div>
          <div>
            <h2 className="text-lg font-medium text-gray-900">Appraisal</h2>
            <p className="text-sm text-gray-600">Conduct performance appraisals and evaluations</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          {!showDeleted && deletedCount > 0 && (hasPermission('show_deleted_appraisals') || isAdmin()) && (
            <button
              onClick={() => setShowDeleted(true)}
              className="bg-gray-600 text-white px-4 py-2 rounded-lg hover:bg-gray-700 text-sm whitespace-nowrap"
            >
              Show Deleted ({deletedCount})
            </button>
          )}
          {showDeleted && (hasPermission('show_deleted_appraisals') || isAdmin()) && (
            <button
              onClick={() => setShowDeleted(false)}
              className="bg-gray-600 text-white px-4 py-2 rounded-lg hover:bg-gray-700 text-sm whitespace-nowrap"
            >
              Hide Deleted
            </button>
          )}
          <button
            onClick={() => setShowForm(true)}
            className="text-white px-4 py-2 rounded-lg border border-black flex items-center gap-2 text-sm sm:text-base w-fit transition-colors"
            style={{
              backgroundColor: 'var(--primary-color)',
              display: (hasPermission('add_appraisal') || isAdmin()) ? 'flex' : 'none'
            }}
            onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--secondary-color)'}
            onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--primary-color)'}
          >
            <Plus className="w-4 h-4" />
            Create Appraisal
          </button>
        </div>
      </div>

      {/* Add Appraisal Form */}
      {showForm && (
        <div className="bg-white rounded-lg shadow-sm border border-black">
          <div className="px-4 sm:px-6 py-4 border-b border-black">
            <h3 className="text-base sm:text-lg font-semibold text-gray-900">{editingAppraisal ? 'Edit Performance Appraisal' : 'Create Performance Appraisal'}</h3>
          </div>
          <form onSubmit={handleSubmit} className="p-4 sm:p-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Employee</label>
                <select
                  value={formData.employee}
                  onChange={(e) => {
                    const selectedEmp = employees.find(emp => emp.name === e.target.value);
                    setFormData({
                      ...formData, 
                      employee: e.target.value,
                      department: selectedEmp?.department || "",
                      position: selectedEmp?.position || ""
                    });
                  }}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                >
                  <option value="">Select Employee</option>
                  {employees.map(emp => (
                    <option key={emp.id} value={emp.name}>{emp.employee_code} - {emp.name}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Review Period</label>
                <input
                  type="text"
                  value={formData.reviewPeriod}
                  onChange={(e) => setFormData({...formData, reviewPeriod: e.target.value})}
                  placeholder="e.g., 2024 Annual Review, Q4 2024"
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Appraiser</label>
                <select
                  value={formData.appraiser}
                  onChange={(e) => setFormData({...formData, appraiser: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                >
                  <option value="">Select Appraiser</option>
                  {employees.map(emp => (
                    <option key={emp.id} value={emp.name}>{emp.employee_code} - {emp.name}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Review Type</label>
                <select
                  value={formData.reviewType}
                  onChange={(e) => setFormData({...formData, reviewType: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                >
                  {reviewTypes.map(type => (
                    <option key={type} value={type}>{type}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Overall Rating</label>
                <select
                  value={formData.overallRating}
                  onChange={(e) => setFormData({...formData, overallRating: parseInt(e.target.value)})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                >
                  {ratings.map(rating => (
                    <option key={rating} value={rating}>{rating} - {rating === 5 ? 'Excellent' : rating === 4 ? 'Good' : rating === 3 ? 'Average' : rating === 2 ? 'Below Average' : 'Poor'}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Performance Score (%)</label>
                <input
                  type="number"
                  min="0"
                  max="100"
                  value={formData.performanceScore}
                  onChange={(e) => setFormData({...formData, performanceScore: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                />
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">Key Strengths</label>
                <textarea
                  value={formData.strengths}
                  onChange={(e) => setFormData({...formData, strengths: e.target.value})}
                  rows={3}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  placeholder="List key strengths and achievements..."
                />
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">Areas for Improvement</label>
                <textarea
                  value={formData.improvements}
                  onChange={(e) => setFormData({...formData, improvements: e.target.value})}
                  rows={3}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  placeholder="Identify areas that need improvement..."
                />
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">Development Plan</label>
                <textarea
                  value={formData.developmentPlan}
                  onChange={(e) => setFormData({...formData, developmentPlan: e.target.value})}
                  rows={3}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  placeholder="Outline development plan and training needs..."
                />
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">Comments</label>
                <textarea
                  value={formData.comments}
                  onChange={(e) => setFormData({...formData, comments: e.target.value})}
                  rows={4}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  placeholder="Additional comments and observations..."
                />
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">Recommendations</label>
                <textarea
                  value={formData.recommendations}
                  onChange={(e) => setFormData({...formData, recommendations: e.target.value})}
                  rows={2}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  placeholder="Recommendations for promotion, role changes, etc..."
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Status</label>
                <select
                  value={formData.status}
                  onChange={(e) => setFormData({...formData, status: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                >
                  {statuses.map(status => (
                    <option key={status} value={status}>{status}</option>
                  ))}
                </select>
              </div>
            </div>

            <div className="mt-4 sm:mt-6 flex flex-col sm:flex-row justify-end space-y-2 sm:space-y-0 sm:space-x-3">
              <button
                type="button"
                onClick={() => setShowForm(false)}
                className="w-full sm:w-auto px-4 py-2 border border-black text-gray-700 rounded-md hover:bg-gray-50 text-sm sm:text-base"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="w-full sm:w-auto px-4 py-2 text-white rounded-md font-medium transition-all duration-200 text-sm sm:text-base"
                style={{
                  backgroundColor: 'var(--primary-color)'
                }}
                onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--secondary-color)'}
                onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--primary-color)'}
              >
                {editingAppraisal ? 'Update Appraisal' : 'Create Appraisal'}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* View Appraisal Modal */}
      {showViewModal && viewAppraisal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-lg max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto border border-black">
            <div className="px-4 sm:px-6 py-4 border-b border-black">
              <h3 className="text-base sm:text-lg font-semibold text-gray-900">Appraisal Details</h3>
            </div>
            <div className="p-4 sm:p-6 space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700">Employee</label>
                  <p className="text-sm text-gray-900">{viewAppraisal.employee_name}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Review Period</label>
                  <p className="text-sm text-gray-900">{viewAppraisal.cycle}</p>
                </div>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700">Final Rating</label>
                  <div className="flex items-center">
                    {renderStars(viewAppraisal.final_rating || 0)}
                    <span className="ml-2 text-sm text-gray-600">({viewAppraisal.final_rating || 0}/5)</span>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Status</label>
                  <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${getStatusColor(viewAppraisal.status)}`}>
                    {viewAppraisal.status}
                  </span>
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">KPI Score</label>
                <p className="text-sm text-gray-900">{viewAppraisal.kpi_score || 'N/A'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Feedback Score</label>
                <p className="text-sm text-gray-900">{viewAppraisal.feedback_score || 'N/A'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Recommendations</label>
                <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded border border-black">{viewAppraisal.recommendation || 'No recommendations provided'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Key Strengths</label>
                <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded border border-black">{viewAppraisal.strengths || 'No strengths mentioned'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Areas for Improvement</label>
                <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded border border-black">{viewAppraisal.improvements || 'No improvements mentioned'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Development Plan</label>
                <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded border border-black">{viewAppraisal.development_plan || 'No development plan provided'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Comments</label>
                <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded border border-black">{viewAppraisal.comments || 'No comments provided'}</p>
              </div>
            </div>
            <div className="px-4 sm:px-6 py-4 border-t border-black flex justify-end">
              <button
                onClick={() => {
                  setShowViewModal(false);
                  setViewAppraisal(null);
                }}
                className="px-4 py-2 text-white rounded-md border border-black text-sm sm:text-base transition-colors"
                style={{
                  backgroundColor: 'var(--primary-color)'
                }}
                onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--secondary-color)'}
                onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--primary-color)'}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Appraisals List */}
      <div className="bg-white rounded-lg shadow-sm border border-black">
        <div className="px-4 sm:px-6 py-4 border-b border-black">
          <h3 className="text-base sm:text-lg font-semibold text-gray-900">Performance Appraisals</h3>
        </div>
        
        {/* Desktop Table View */}
        <div className="hidden md:block overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200 border border-black">
            <thead className="bg-gray-50 border-b border-black">
              <tr>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Employee</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Review Period</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Rating</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {appraisals.map((appraisal) => (
                <tr key={appraisal.id} className={appraisal.is_active === false ? 'bg-red-50 opacity-75' : ''}>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <div>
                      <div className="text-sm font-medium text-gray-900">
                        {appraisal.employee_name}
                        {appraisal.is_active === false && <span className="ml-2 text-xs text-red-600 font-semibold">(DELETED)</span>}
                      </div>
                      <div className="text-sm text-gray-500">ID: {appraisal.employee_id}</div>
                    </div>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <div className="text-sm text-gray-900">{appraisal.cycle}</div>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      {renderStars(appraisal.final_rating || 0)}
                      <span className={`ml-2 text-sm font-medium ${getRatingColor(appraisal.final_rating || 0)}`}>
                        {appraisal.final_rating || 0}/5
                      </span>
                    </div>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${getStatusColor(appraisal.status)}`}>
                      {appraisal.status}
                    </span>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <div className="flex flex-wrap gap-1 sm:gap-2">
                      {appraisal.is_active === false ? (
                        (hasPermission('restore_appraisal') || isAdmin()) && (
                        <button
                          onClick={() => handleRestore(appraisal.id)}
                          className="p-1 sm:p-2 text-green-600 hover:text-green-900 hover:bg-green-50 rounded-lg border border-green-300"
                          title="Restore Appraisal"
                        >
                          <Award className="w-3 h-3 sm:w-4 sm:h-4" />
                        </button>
                        )
                      ) : (
                        <>
                          <button 
                            onClick={() => handleView(appraisal)}
                            className="p-1 sm:p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-lg border border-gray-300" 
                            title="View Details"
                            style={{ display: (hasPermission('view_appraisals') || isAdmin()) ? 'inline-block' : 'none' }}
                          >
                            <Eye className="w-3 h-3 sm:w-4 sm:h-4" />
                          </button>
                          {(hasPermission('edit_appraisal') || isAdmin()) && (
                          <button 
                            onClick={() => handleEdit(appraisal)}
                            className="p-1 sm:p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-lg border border-gray-300" 
                            title="Edit"
                          >
                            <Edit className="w-3 h-3 sm:w-4 sm:h-4" />
                          </button>
                          )}
                          {(hasPermission('delete_appraisal') || isAdmin()) && (
                          <button
                            onClick={() => handleDelete(appraisal.id)}
                            className="p-1 sm:p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-lg border border-gray-300"
                            title="Delete"
                          >
                            <Trash2 className="w-3 h-3 sm:w-4 sm:h-4" />
                          </button>
                          )}
                        </>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Mobile Card View */}
        <div className="md:hidden">
          {appraisals.length === 0 ? (
            <div className="p-6 text-center text-gray-500">
              <p>No appraisals found</p>
            </div>
          ) : (
            appraisals.map((appraisal) => (
              <div key={appraisal.id} className={`p-4 border-b border-gray-200 hover:bg-gray-50 ${appraisal.is_active === false ? 'bg-red-50 opacity-75' : ''}`}>
                <div className="flex items-center justify-between mb-3">
                  <div>
                    <div className="text-sm font-medium text-gray-900">
                      {appraisal.employee_name}
                      {appraisal.is_active === false && <span className="ml-2 text-xs text-red-600 font-semibold">(DELETED)</span>}
                    </div>
                    <div className="text-sm text-gray-500">ID: {appraisal.employee_id}</div>
                  </div>
                  <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${getStatusColor(appraisal.status)}`}>
                    {appraisal.status}
                  </span>
                </div>
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <span className="text-sm font-medium text-gray-900">Review Period:</span>
                    <span className="text-sm text-gray-600">{appraisal.cycle}</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-sm font-medium text-gray-900">Rating:</span>
                    <div className="flex items-center">
                      {renderStars(appraisal.final_rating || 0)}
                      <span className={`ml-2 text-sm font-medium ${getRatingColor(appraisal.final_rating || 0)}`}>
                        {appraisal.final_rating || 0}/5
                      </span>
                    </div>
                  </div>
                </div>
                <div className="flex items-center justify-end gap-2 mt-3 pt-3 border-t border-gray-100">
                  {appraisal.is_active === false ? (
                    (hasPermission('restore_appraisal') || isAdmin()) && (
                    <button
                      onClick={() => handleRestore(appraisal.id)}
                      className="flex items-center gap-1 text-green-600 hover:text-green-900 px-3 py-1 rounded-lg hover:bg-green-50 transition-colors text-sm"
                    >
                      <Award className="w-4 h-4" />
                      Restore
                    </button>
                    )
                  ) : (
                    <>
                      <button
                        onClick={() => handleView(appraisal)}
                        className="flex items-center gap-1 text-gray-600 hover:text-gray-900 px-3 py-1 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                        style={{ display: (hasPermission('view_appraisals') || isAdmin()) ? 'flex' : 'none' }}
                      >
                        <Eye className="w-4 h-4" />
                        View
                      </button>
                      {(hasPermission('edit_appraisal') || isAdmin()) && (
                        <button
                          onClick={() => handleEdit(appraisal)}
                          className="flex items-center gap-1 text-blue-600 hover:text-blue-900 px-3 py-1 rounded-lg hover:bg-blue-50 transition-colors text-sm"
                        >
                          <Edit className="w-4 h-4" />
                          Edit
                        </button>
                      )}
                      {(hasPermission('delete_appraisal') || isAdmin()) && (
                        <button
                          onClick={() => handleDelete(appraisal.id)}
                          className="flex items-center gap-1 text-red-600 hover:text-red-900 px-3 py-1 rounded-lg hover:bg-red-50 transition-colors text-sm"
                        >
                          <Trash2 className="w-4 h-4" />
                          Delete
                        </button>
                      )}
                    </>
                  )}
                </div>
              </div>
            ))
          )}
        </div>
      </div>
      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}