import { useState, useEffect } from "react";
import { Plus, MessageSquare, Star, User, Calendar, Edit, Trash2, Eye } from "lucide-react";
import api from "../../api";

export default function Feedback() {
  const [feedbacks, setFeedbacks] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [employees, setEmployees] = useState([]);
  const [showViewModal, setShowViewModal] = useState(false);
  const [viewFeedback, setViewFeedback] = useState(null);
  const [editingFeedback, setEditingFeedback] = useState(null);
  const [formData, setFormData] = useState({
    type: "Manager to Employee",
    customType: "",
    fromEmployee: "",
    toEmployee: "",
    category: "Performance",
    rating: 5,
    feedback: "",
    strengths: "",
    improvements: "",
    goals: "",
    isAnonymous: false,
    status: "Draft"
  });

  const feedbackTypes = [
    "Manager to Employee",
    "Employee to Manager", 
    "Peer to Peer",
    "Self Assessment",
    "360 Degree",
    "Other"
  ];

  const categories = [
    "Performance",
    "Behavior",
    "Skills",
    "Communication",
    "Leadership",
    "Teamwork",
    "Innovation"
  ];

  const statuses = ["Draft", "Submitted", "Reviewed", "Acknowledged"];

  useEffect(() => {
    fetchEmployees();
    fetchFeedbacks();
  }, []);

  const fetchFeedbacks = async () => {
    try {
      const response = await api.get('/api/pms/feedback');
      setFeedbacks(response.data?.data || []);
    } catch (error) {
      console.error('Error fetching feedbacks:', error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      // Fetch from both onboarding and user management like EIS does
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        email: emp.email || `${emp.employee_id}@company.com`,
        source: 'onboarding'
      }));
      
      // Process user management employees (include all, not just those with employee_code)
      const userEmployeeData = userEmployees
        .map(user => ({
          id: `user_${user.id}`,
          name: user.name,
          employee_code: user.employee_code || `USER_${user.id}`, // Use fallback if no employee_code
          email: user.email || `${user.employee_code || `user${user.id}`}@company.com`,
          source: 'user_management'
        }));
      
      // Combine and remove duplicates
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const handleView = (feedback) => {
    setViewFeedback(feedback);
    setShowViewModal(true);
  };

  const handleEdit = (feedback) => {
    setEditingFeedback(feedback.id);
    setFormData({
      type: feedback.relationship === "Manager to Employee" || feedback.relationship === "Employee to Manager" || feedback.relationship === "Peer to Peer" || feedback.relationship === "Self Assessment" || feedback.relationship === "360 Degree" ? feedback.relationship : "Other",
      customType: feedback.relationship === "Manager to Employee" || feedback.relationship === "Employee to Manager" || feedback.relationship === "Peer to Peer" || feedback.relationship === "Self Assessment" || feedback.relationship === "360 Degree" ? "" : feedback.relationship,
      fromEmployee: feedback.from_employee_name,
      toEmployee: feedback.to_employee_name,
      category: "Performance",
      rating: feedback.rating,
      feedback: feedback.comments,
      strengths: feedback.strengths || "",
      improvements: feedback.improvements || "",
      goals: feedback.goals || "",
      isAnonymous: false,
      status: "Draft"
    });
    setShowForm(true);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const fromEmployee = employees.find(emp => emp.name === formData.fromEmployee);
      const toEmployee = employees.find(emp => emp.name === formData.toEmployee);
      
      // Extract numeric ID from user_X format
      const getNumericId = (id) => {
        if (typeof id === 'string' && id.startsWith('user_')) {
          return parseInt(id.replace('user_', ''));
        }
        return id;
      };
      
      const feedbackData = {
        from_employee_id: getNumericId(fromEmployee?.id) || 1,
        to_employee_id: getNumericId(toEmployee?.id) || 1,
        relationship: formData.type === "Other" ? formData.customType : formData.type,
        cycle: "2024",
        rating: formData.rating,
        comments: formData.feedback,
        strengths: formData.strengths,
        improvements: formData.improvements,
        goals: formData.goals
      };
      
      if (editingFeedback) {
        await api.put(`/api/pms/feedback/${editingFeedback}`, feedbackData);
        alert('Feedback updated successfully!');
      } else {
        await api.post('/api/pms/feedback', feedbackData);
        alert('Feedback submitted successfully!');
      }
      fetchFeedbacks();
      
      setFormData({
        type: "Manager to Employee",
        customType: "",
        fromEmployee: "",
        toEmployee: "",
        category: "Performance",
        rating: 5,
        feedback: "",
        strengths: "",
        improvements: "",
        goals: "",
        isAnonymous: false,
        status: "Draft"
      });
      setEditingFeedback(null);
      setShowForm(false);
    } catch (error) {
      console.error('Error submitting feedback:', error);
      alert('Failed to submit feedback. Please try again.');
    }
  };

  const handleDelete = async (id) => {
    if (confirm("Are you sure you want to delete this feedback?")) {
      try {
        await api.delete(`/api/pms/feedback/${id}`);
        alert('Feedback deleted successfully!');
        fetchFeedbacks();
      } catch (error) {
        console.error('Error deleting feedback:', error);
        alert('Failed to delete feedback. Please try again.');
      }
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "Submitted": return "bg-blue-100 text-blue-800";
      case "Reviewed": return "bg-green-100 text-green-800";
      case "Acknowledged": return "bg-purple-100 text-purple-800";
      case "Draft": return "bg-yellow-100 text-yellow-800";
      default: return "bg-gray-100 text-gray-800";
    }
  };

  const renderStars = (rating) => {
    return Array.from({ length: 5 }, (_, index) => (
      <Star
        key={index}
        className={`w-4 h-4 ${index < rating ? 'text-yellow-400 fill-current' : 'text-gray-300'}`}
      />
    ));
  };

  return (
    <div className="space-y-6">
        {/* Header */}
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Feedback Management</h1>
            <p className="text-gray-600">Manage employee feedback and 360-degree reviews</p>
          </div>
          <button
            onClick={() => setShowForm(true)}
            className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            <Plus className="w-4 h-4" />
            <span>Give Feedback</span>
          </button>
        </div>

        {/* Add Feedback Form */}
        {showForm && (
          <div className="bg-white rounded-lg shadow-sm border">
            <div className="px-6 py-4 border-b">
              <h3 className="text-lg font-semibold text-gray-900">{editingFeedback ? 'Edit Feedback' : 'Give Feedback'}</h3>
            </div>
            <form onSubmit={handleSubmit} className="p-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Feedback Type</label>
                  <select
                    value={formData.type}
                    onChange={(e) => setFormData({...formData, type: e.target.value, customType: e.target.value === "Other" ? formData.customType : ""})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    {feedbackTypes.map(type => (
                      <option key={type} value={type}>{type}</option>
                    ))}
                  </select>
                  {formData.type === "Other" && (
                    <input
                      type="text"
                      value={formData.customType}
                      onChange={(e) => setFormData({...formData, customType: e.target.value})}
                      placeholder="Enter custom feedback type"
                      className="w-full mt-2 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                      required
                    />
                  )}
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Category</label>
                  <select
                    value={formData.category}
                    onChange={(e) => setFormData({...formData, category: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    {categories.map(category => (
                      <option key={category} value={category}>{category}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">From Employee</label>
                  <select
                    value={formData.fromEmployee}
                    onChange={(e) => setFormData({...formData, fromEmployee: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required
                  >
                    <option value="">Select Employee</option>
                    {employees.map(emp => (
                      <option key={emp.id} value={emp.name}>{emp.employee_code} - {emp.name}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">To Employee</label>
                  <select
                    value={formData.toEmployee}
                    onChange={(e) => setFormData({...formData, toEmployee: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required
                  >
                    <option value="">Select Employee</option>
                    {employees.map(emp => (
                      <option key={emp.id} value={emp.name}>{emp.employee_code} - {emp.name}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Overall Rating</label>
                  <select
                    value={formData.rating}
                    onChange={(e) => setFormData({...formData, rating: parseInt(e.target.value)})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    {[1, 2, 3, 4, 5].map(rating => (
                      <option key={rating} value={rating}>{rating} Star{rating > 1 ? 's' : ''}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Status</label>
                  <select
                    value={formData.status}
                    onChange={(e) => setFormData({...formData, status: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    {statuses.map(status => (
                      <option key={status} value={status}>{status}</option>
                    ))}
                  </select>
                </div>

                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 mb-2">Feedback</label>
                  <textarea
                    value={formData.feedback}
                    onChange={(e) => setFormData({...formData, feedback: e.target.value})}
                    rows={4}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Provide detailed feedback..."
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Strengths</label>
                  <textarea
                    value={formData.strengths}
                    onChange={(e) => setFormData({...formData, strengths: e.target.value})}
                    rows={3}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="List key strengths..."
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Areas for Improvement</label>
                  <textarea
                    value={formData.improvements}
                    onChange={(e) => setFormData({...formData, improvements: e.target.value})}
                    rows={3}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Suggest areas for improvement..."
                  />
                </div>

                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 mb-2">Future Goals</label>
                  <textarea
                    value={formData.goals}
                    onChange={(e) => setFormData({...formData, goals: e.target.value})}
                    rows={2}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Suggest future goals and development areas..."
                  />
                </div>

                <div className="md:col-span-2">
                  <label className="flex items-center">
                    <input
                      type="checkbox"
                      checked={formData.isAnonymous}
                      onChange={(e) => setFormData({...formData, isAnonymous: e.target.checked})}
                      className="mr-2"
                    />
                    <span className="text-sm text-gray-700">Submit as anonymous feedback</span>
                  </label>
                </div>
              </div>

              <div className="mt-6 flex justify-end space-x-3">
                <button
                  type="button"
                  onClick={() => setShowForm(false)}
                  className="px-4 py-2 border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
                >
                  {editingFeedback ? 'Update Feedback' : 'Submit Feedback'}
                </button>
              </div>
            </form>
          </div>
        )}

        {/* View Feedback Modal */}
        {showViewModal && viewFeedback && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white rounded-lg shadow-lg max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto">
              <div className="px-6 py-4 border-b">
                <h3 className="text-lg font-semibold text-gray-900">Feedback Details</h3>
              </div>
              <div className="p-6 space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700">Type</label>
                    <p className="text-sm text-gray-900">{viewFeedback.relationship}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700">Rating</label>
                    <div className="flex items-center">
                      {renderStars(viewFeedback.rating || 0)}
                      <span className="ml-2 text-sm text-gray-600">({viewFeedback.rating || 0}/5)</span>
                    </div>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700">From</label>
                    <p className="text-sm text-gray-900">{viewFeedback.from_employee_name}</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700">To</label>
                    <p className="text-sm text-gray-900">{viewFeedback.to_employee_name}</p>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Feedback Comments</label>
                  <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded">{viewFeedback.comments || 'No comments provided'}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Strengths</label>
                  <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded">{viewFeedback.strengths || 'No strengths mentioned'}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Areas for Improvement</label>
                  <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded">{viewFeedback.improvements || 'No improvements mentioned'}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Future Goals</label>
                  <p className="text-sm text-gray-900 bg-gray-50 p-3 rounded">{viewFeedback.goals || 'No goals mentioned'}</p>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Date</label>
                  <p className="text-sm text-gray-900">{viewFeedback.created_at ? new Date(viewFeedback.created_at).toLocaleDateString() : 'N/A'}</p>
                </div>
              </div>
              <div className="px-6 py-4 border-t flex justify-end">
                <button
                  onClick={() => {
                    setShowViewModal(false);
                    setViewFeedback(null);
                  }}
                  className="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Feedback List */}
        <div className="bg-white rounded-lg shadow-sm border">
          <div className="px-6 py-4 border-b">
            <h3 className="text-lg font-semibold text-gray-900">Feedback History</h3>
          </div>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">From/To</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Rating</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {feedbacks.map((feedback) => (
                  <tr key={feedback.id}>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{feedback.relationship}</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-gray-900">
                        <div>From: {feedback.from_employee_name}</div>
                        <div>To: {feedback.to_employee_name}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        {renderStars(feedback.rating || 0)}
                        <span className="ml-2 text-sm text-gray-600">({feedback.rating || 0}/5)</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{feedback.created_at ? new Date(feedback.created_at).toLocaleDateString() : 'N/A'}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                      <div className="flex space-x-2">
                        <button 
                          onClick={() => handleView(feedback)}
                          className="text-blue-600 hover:text-blue-900" 
                          title="View Details"
                        >
                          <Eye className="w-4 h-4" />
                        </button>
                        <button 
                          onClick={() => handleEdit(feedback)}
                          className="text-blue-600 hover:text-blue-900" 
                          title="Edit"
                        >
                          <Edit className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleDelete(feedback.id)}
                          className="text-red-600 hover:text-red-900"
                          title="Delete"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
    </div>
  );
}