import { useState, useEffect } from "react";
import { Plus, Calendar, Users, Clock, Edit, Trash2, Play, Pause, Target, RefreshCw } from "lucide-react";
import api from "../../api";
import useToast from "../../utils/useToast";
import Toast from "../../components/Toast";
import { hasPermission, isAdmin } from "../../utils/permissions";

export default function ReviewCycle() {
  // Check permissions
  if (!hasPermission('view_review_cycles') && !isAdmin()) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <div className="text-6xl mb-4">🔒</div>
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Access Denied</h2>
          <p className="text-gray-600">You don't have permission to view review cycles.</p>
        </div>
      </div>
    );
  }
  const { toast, showToast } = useToast();
  const [cycles, setCycles] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [employees, setEmployees] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [showDeleted, setShowDeleted] = useState(false);
  const [deletedCount, setDeletedCount] = useState(0);
  const [formData, setFormData] = useState({
    name: "",
    description: "",
    type: "Annual",
    startDate: "",
    endDate: "",
    departments: [],
    employees: [],
    status: "Draft"
  });

  const reviewTypes = ["Annual", "Semi-Annual", "Quarterly", "Monthly", "Project-Based"];
  const statuses = ["Draft", "Active", "Completed", "Cancelled"];
  const [editingCycle, setEditingCycle] = useState(null);
  const [showProgressModal, setShowProgressModal] = useState(false);
  const [progressCycle, setProgressCycle] = useState(null);

  useEffect(() => {
    fetchEmployees();
    fetchDepartments();
    fetchCycles();
    
    const fetchColors = async () => {
      try {
        const tenantCode = localStorage.getItem('tenant_code');
        if (tenantCode) {
          const response = await api.get(`/auth/branding/${tenantCode}`);
          document.documentElement.style.setProperty('--primary-color', response.data.primary_color || '#2862e9');
          document.documentElement.style.setProperty('--secondary-color', response.data.secondary_color || '#474e71');
        }
      } catch (error) {
        console.error('Failed to fetch branding colors:', error);
      }
    };
    fetchColors();
  }, [showDeleted]);

  const fetchCycles = async () => {
    try {
      const response = await api.get(`/api/pms/reviews${showDeleted ? '?include_deleted=true' : ''}`);
      setCycles(response.data?.data || []);
      
      // Fetch deleted count
      if (!showDeleted) {
        try {
          const deletedResponse = await api.get('/api/pms/reviews/deleted-count');
          setDeletedCount(deletedResponse.data?.count || 0);
        } catch (error) {
          console.error('Error fetching deleted count:', error);
          setDeletedCount(0);
        }
      }
    } catch (error) {
      console.error('Error fetching review cycles:', error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`${api.defaults.baseURL}/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        email: emp.email || `${emp.employee_id}@company.com`,
        source: 'onboarding'
      }));
      
      const userEmployeeData = userEmployees
        .map(user => ({
          id: `user_${user.id}`,
          name: user.name,
          employee_code: user.employee_code || `USER_${user.id}`,
          email: user.email || `${user.employee_code || `user${user.id}`}@company.com`,
          source: 'user_management'
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const fetchDepartments = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      const response = await fetch(`${api.defaults.baseURL}/hospitals/departments/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (response.ok) {
        const data = await response.json();
        setDepartments(data.departments || []);
      }
    } catch (error) {
      console.error('Error fetching departments:', error);
    }
  };

  const handleEdit = (cycle) => {
    setEditingCycle(cycle.id);
    setFormData({
      name: cycle.cycle,
      description: cycle.review_type,
      type: cycle.review_type,
      startDate: "",
      endDate: "",
      departments: [],
      employees: [],
      status: cycle.status
    });
    setShowForm(true);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const reviewData = {
        employee_id: 1, // Default employee ID
        cycle: formData.name,
        review_type: formData.type,
        status: formData.status
      };
      
      if (editingCycle) {
        await api.put(`/api/pms/reviews/${editingCycle}`, reviewData);
        showToast('Review cycle updated successfully!', 'success');
      } else {
        await api.post('/api/pms/reviews', reviewData);
        showToast('Review cycle created successfully!', 'success');
      }
      fetchCycles();
      
      setFormData({
        name: "",
        description: "",
        type: "Annual",
        startDate: "",
        endDate: "",
        departments: [],
        employees: [],
        status: "Draft"
      });
      setEditingCycle(null);
      setShowForm(false);
    } catch (error) {
      console.error('Error creating review cycle:', error);
      showToast('Failed to create review cycle. Please try again.', 'error');
    }
  };

  const handleDelete = async (id) => {
    if (confirm("Are you sure you want to delete this review cycle? It will be moved to deleted items.")) {
      try {
        await api.delete(`/api/pms/reviews/${id}`);
        showToast('Review cycle deleted successfully!', 'success');
        fetchCycles();
      } catch (error) {
        console.error('Error deleting review cycle:', error);
        showToast('Failed to delete review cycle. Please try again.', 'error');
      }
    }
  };

  const handleRestore = async (id) => {
    if (confirm("Are you sure you want to restore this review cycle?")) {
      try {
        await api.put(`/api/pms/reviews/${id}/restore`);
        showToast('Review cycle restored successfully!', 'success');
        fetchCycles();
      } catch (error) {
        console.error('Error restoring review cycle:', error);
        showToast('Failed to restore review cycle. Please try again.', 'error');
      }
    }
  };

  const handleStatusChange = async (id, newStatus) => {
    try {
      await api.put(`/api/pms/reviews/${id}`, { status: newStatus });
      fetchCycles();
    } catch (error) {
      console.error('Error updating review cycle status:', error);
      showToast('Failed to update status. Please try again.', 'error');
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "Active": return "bg-gray-100 text-gray-800 border-gray-300";
      case "Completed": return "bg-gray-100 text-gray-800 border-gray-300";
      case "Draft": return "bg-gray-100 text-gray-800 border-gray-300";
      case "Cancelled": return "bg-gray-100 text-gray-800 border-gray-300";
      default: return "bg-gray-100 text-gray-800 border-gray-300";
    }
  };

  const handleProgressUpdate = (cycle) => {
    setProgressCycle(cycle);
    setShowProgressModal(true);
  };

  const handleProgressSubmit = async (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    const selfScore = formData.get('selfScore');
    const managerScore = formData.get('managerScore');
    
    try {
      await api.put(`/api/pms/reviews/${progressCycle.id}`, {
        self_score: selfScore ? parseFloat(selfScore) : null,
        manager_score: managerScore ? parseFloat(managerScore) : null
      });
      showToast('Progress updated successfully!', 'success');
      fetchCycles();
      setShowProgressModal(false);
      setProgressCycle(null);
    } catch (error) {
      console.error('Error updating progress:', error);
      showToast('Failed to update progress. Please try again.', 'error');
    }
  };

  return (
    <div className="space-y-6">
      {/* Header with Create Review Cycle Button */}
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg flex items-center justify-center" style={{
            backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#2862e9'}20`
          }}>
            <RefreshCw className="w-5 h-5" style={{
              color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#2862e9'
            }} />
          </div>
          <div>
            <h2 className="text-lg font-medium text-gray-900">Review Cycle</h2>
            <p className="text-sm text-gray-600">Manage performance review cycles and schedules</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          {!showDeleted && deletedCount > 0 && (hasPermission('view_deleted_review_cycles') || isAdmin()) && (
            <button
              onClick={() => setShowDeleted(true)}
              className="text-white px-4 py-2 rounded-lg transition-colors text-sm whitespace-nowrap"
              style={{ backgroundColor: 'var(--primary-color)' }}
              onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--secondary-color)'}
              onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--primary-color)'}
            >
              Show Deleted ({deletedCount})
            </button>
          )}
          {showDeleted && (hasPermission('view_deleted_review_cycles') || isAdmin()) && (
            <button
              onClick={() => setShowDeleted(false)}
              className="text-white px-4 py-2 rounded-lg transition-colors text-sm whitespace-nowrap"
              style={{ backgroundColor: 'var(--primary-color)' }}
              onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--secondary-color)'}
              onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--primary-color)'}
            >
              Hide Deleted
            </button>
          )}
          {(hasPermission('create_review_cycle') || isAdmin()) && (
            <button
              onClick={() => setShowForm(true)}
              className="text-white px-4 py-2 rounded-lg  flex items-center gap-2 text-sm sm:text-base w-fit transition-colors"
              style={{
                backgroundColor: 'var(--primary-color)'
              }}
              onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--secondary-color)'}
              onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--primary-color)'}
            >
              <Plus className="w-4 h-4" />
              Create Review Cycle
            </button>
          )}
        </div>
      </div>

      {/* Add Review Cycle Form */}
      {showForm && (
        <div className="bg-white rounded-lg shadow-sm ">
          <div className="px-4 sm:px-6 py-4 border-b border-gray-200">
            <h3 className="text-base sm:text-lg font-semibold text-gray-900">{editingCycle ? 'Edit Review Cycle' : 'Create New Review Cycle'}</h3>
          </div>
          <form onSubmit={handleSubmit} className="p-4 sm:p-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Cycle Name</label>
                <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({...formData, name: e.target.value})}
                  className="w-full px-3 py-2  rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Review Type</label>
                <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
                  value={formData.type}
                  onChange={(e) => setFormData({...formData, type: e.target.value})}
                  className="w-full px-3 py-2  rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                >
                  {reviewTypes.map(type => (
                    <option key={type} value={type}>{type}</option>
                  ))}
                </select>
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">Description</label>
                <textarea style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
                  value={formData.description}
                  onChange={(e) => setFormData({...formData, description: e.target.value})}
                  rows={3}
                  className="w-full px-3 py-2  rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Start Date</label>
                <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
                  type="date"
                  value={formData.startDate}
                  onChange={(e) => setFormData({...formData, startDate: e.target.value})}
                  className="w-full px-3 py-2  rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">End Date</label>
                <input style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
                  type="date"
                  value={formData.endDate}
                  onChange={(e) => setFormData({...formData, endDate: e.target.value})}
                  className="w-full px-3 py-2  rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Status</label>
                <select style={{backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`}} 
                  value={formData.status}
                  onChange={(e) => setFormData({...formData, status: e.target.value})}
                  className="w-full px-3 py-2  rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                >
                  {statuses.map(status => (
                    <option key={status} value={status}>{status}</option>
                  ))}
                </select>
              </div>
            </div>

            <div className="mt-4 sm:mt-6 flex flex-col sm:flex-row justify-end space-y-2 sm:space-y-0 sm:space-x-3">
              <button
                type="button"
                onClick={() => setShowForm(false)}
                className="w-full sm:w-auto px-4 py-2  text-gray-700 rounded-md hover:bg-gray-50 text-sm sm:text-base"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="w-full sm:w-auto px-4 py-2 text-white rounded-md  text-sm sm:text-base transition-colors"
                style={{
                  backgroundColor: 'var(--primary-color)'
                }}
                onMouseEnter={(e) => e.target.style.backgroundColor = 'var(--secondary-color)'}
                onMouseLeave={(e) => e.target.style.backgroundColor = 'var(--primary-color)'}
              >
                {editingCycle ? 'Update Cycle' : 'Create Cycle'}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Review Cycles List */}
      <div className="bg-white rounded-lg shadow-sm ">
        <div className="px-4 sm:px-6 py-4 border-b border-gray-200">
          <h3 className="text-base sm:text-lg font-semibold text-gray-900">Review Cycles</h3>
        </div>
        
        {/* Desktop Table View */}
        <div className="hidden md:block overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200 ">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Cycle Name</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Type</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Duration</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Participants</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Progress</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {cycles.map((cycle) => (
                <tr key={cycle.id} className={cycle.is_active === false ? 'bg-red-50 opacity-75' : ''}>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <div>
                      <div className="text-sm font-medium text-gray-900">
                        {cycle.cycle}
                        {cycle.is_active === false && <span className="ml-2 text-xs text-red-600 font-semibold">(DELETED)</span>}
                      </div>
                      <div className="text-sm text-gray-500">{cycle.review_type}</div>
                    </div>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm text-gray-900">{cycle.review_type}</td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {cycle.start_date} to {cycle.end_date}
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {cycle.participants || 0} {(cycle.participants || 0) === 1 ? 'employee' : 'employees'}
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      <div className="w-16 sm:w-full bg-gray-200 rounded-full h-2 mr-2 ">
                        <div
                          className="h-2 bg-gray-500 rounded-full"
                          style={{ width: `${cycle.progress_percentage || 0}%` }}
                        ></div>
                      </div>
                      <span className="text-sm text-gray-600">
                        {cycle.progress || "0%"}
                      </span>
                    </div>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${getStatusColor(cycle.status)}`}>
                      {cycle.status}
                    </span>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <div className="flex flex-wrap gap-1 sm:gap-2">
                      {cycle.is_active === false ? (
                        (hasPermission('restore_review_cycle') || isAdmin()) && (
                          <button
                            onClick={() => handleRestore(cycle.id)}
                            className="p-1 sm:p-2 text-green-600 hover:text-green-900 hover:bg-green-50 rounded-lg "
                            title="Restore Cycle"
                          >
                            <RefreshCw className="w-3 h-3 sm:w-4 sm:h-4" />
                          </button>
                        )
                      ) : (
                        <>
                          {cycle.status === "Active" && (hasPermission('close_review_cycle') || isAdmin()) && (
                            <button
                              onClick={() => handleStatusChange(cycle.id, "Completed")}
                              className="p-1 sm:p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-lg "
                              title="Complete Cycle"
                            >
                              <Pause className="w-3 h-3 sm:w-4 sm:h-4" />
                            </button>
                          )}
                          {(hasPermission('edit_review_cycle') || isAdmin()) && (
                            <button 
                              onClick={() => handleEdit(cycle)}
                              className="p-1 sm:p-2 text-green-600 hover:text-green-900 hover:bg-green-50 rounded-lg"
                            >
                              <Edit className="w-3 h-3 sm:w-4 sm:h-4" />
                            </button>
                          )}
                          {(hasPermission('delete_review_cycle') || isAdmin()) && (
                            <button
                              onClick={() => handleDelete(cycle.id)}
                              className="p-1 sm:p-2 text-red-600 hover:text-red-900 hover:bg-red-50 rounded-lg"
                            >
                              <Trash2 className="w-3 h-3 sm:w-4 sm:h-4" />
                            </button>
                          )}
                        </>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Mobile Card View */}
        <div className="md:hidden">
          {cycles.map((cycle) => (
            <div key={cycle.id} className={`p-4 border-b border-gray-200 last:border-b-0 ${cycle.is_active === false ? 'bg-red-50 opacity-75' : ''}`}>
              <div className="flex justify-between items-start mb-3">
                <div className="flex-1">
                  <h4 className="font-medium text-gray-900">
                    {cycle.cycle}
                    {cycle.is_active === false && <span className="ml-2 text-xs text-red-600 font-semibold">(DELETED)</span>}
                  </h4>
                  <p className="text-sm text-gray-600">{cycle.review_type}</p>
                </div>
                <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${getStatusColor(cycle.status)}`}>
                  {cycle.status}
                </span>
              </div>
              
              <div className="space-y-2 mb-3">
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">Duration:</span>
                  <span className="text-gray-900">{cycle.start_date} to {cycle.end_date}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">Participants:</span>
                  <span className="text-gray-900">{cycle.participants || 0} {(cycle.participants || 0) === 1 ? 'employee' : 'employees'}</span>
                </div>
                <div className="flex justify-between items-center text-sm">
                  <span className="text-gray-600">Progress:</span>
                  <div className="flex items-center">
                    <div className="w-16 bg-gray-200 rounded-full h-2 mr-2 ">
                      <div
                        className="h-2 bg-gray-500 rounded-full"
                        style={{ width: `${cycle.progress_percentage || 0}%` }}
                      ></div>
                    </div>
                    <span className="text-gray-600">{cycle.progress || "0%"}</span>
                  </div>
                </div>
              </div>
              
              <div className="flex flex-wrap gap-2">
                {cycle.is_active === false ? (
                  (hasPermission('restore_review_cycle') || isAdmin()) && (
                    <button
                      onClick={() => handleRestore(cycle.id)}
                      className="flex items-center gap-1 px-3 py-1 text-xs bg-green-50 text-green-700 rounded-md  hover:bg-green-100"
                    >
                      <RefreshCw className="w-3 h-3" />
                      Restore
                    </button>
                  )
                ) : (
                  <>
                    {cycle.status === "Active" && (hasPermission('close_review_cycle') || isAdmin()) && (
                      <button
                        onClick={() => handleStatusChange(cycle.id, "Completed")}
                        className="flex items-center gap-1 px-3 py-1 text-xs bg-gray-50 text-gray-700 rounded-md  hover:bg-gray-100"
                      >
                        <Pause className="w-3 h-3" />
                        Complete
                      </button>
                    )}
                    {(hasPermission('edit_review_cycle') || isAdmin()) && (
                      <button 
                        onClick={() => handleEdit(cycle)}
                        className="flex items-center gap-1 px-3 py-1 text-xs bg-gray-50 text-gray-700 rounded-md  hover:bg-gray-100"
                      >
                        <Edit className="w-3 h-3" />
                        Edit
                      </button>
                    )}
                    {(hasPermission('delete_review_cycle') || isAdmin()) && (
                      <button
                        onClick={() => handleDelete(cycle.id)}
                        className="flex items-center gap-1 px-3 py-1 text-xs bg-gray-50 text-gray-700 rounded-md  hover:bg-gray-100"
                      >
                        <Trash2 className="w-3 h-3" />
                        Delete
                      </button>
                    )}
                  </>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
      <Toast {...toast} />
    </div>
  );
}
