import { useState, useEffect } from "react";
import { Plus, Calendar, Users, Clock, Edit, Trash2, Play, Pause, Target, RefreshCw } from "lucide-react";
import api from "../../api";

export default function ReviewCycle() {
  const [cycles, setCycles] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [employees, setEmployees] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [formData, setFormData] = useState({
    name: "",
    description: "",
    type: "Annual",
    startDate: "",
    endDate: "",
    departments: [],
    employees: [],
    status: "Draft"
  });

  const reviewTypes = ["Annual", "Semi-Annual", "Quarterly", "Monthly", "Project-Based"];
  const statuses = ["Draft", "Active", "Completed", "Cancelled"];
  const [editingCycle, setEditingCycle] = useState(null);
  const [showProgressModal, setShowProgressModal] = useState(false);
  const [progressCycle, setProgressCycle] = useState(null);

  useEffect(() => {
    fetchEmployees();
    fetchDepartments();
    fetchCycles();
  }, []);

  const fetchCycles = async () => {
    try {
      const response = await api.get('/api/pms/reviews');
      setCycles(response.data?.data || []);
    } catch (error) {
      console.error('Error fetching review cycles:', error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      if (!tenant) return;
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        email: emp.email || `${emp.employee_id}@company.com`,
        source: 'onboarding'
      }));
      
      const userEmployeeData = userEmployees
        .map(user => ({
          id: `user_${user.id}`,
          name: user.name,
          employee_code: user.employee_code || `USER_${user.id}`,
          email: user.email || `${user.employee_code || `user${user.id}`}@company.com`,
          source: 'user_management'
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const fetchDepartments = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      const response = await fetch(`http://localhost:8000/hospitals/departments/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (response.ok) {
        const data = await response.json();
        setDepartments(data.departments || []);
      }
    } catch (error) {
      console.error('Error fetching departments:', error);
    }
  };

  const handleEdit = (cycle) => {
    setEditingCycle(cycle.id);
    setFormData({
      name: cycle.cycle,
      description: cycle.review_type,
      type: cycle.review_type,
      startDate: "",
      endDate: "",
      departments: [],
      employees: [],
      status: cycle.status
    });
    setShowForm(true);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const cycleData = {
        employee_id: employees[0]?.id || 1,
        cycle: formData.name,
        review_type: formData.type,
        status: formData.status
      };
      
      if (editingCycle) {
        await api.put(`/api/pms/reviews/${editingCycle}`, cycleData);
        alert('Review cycle updated successfully!');
      } else {
        await api.post('/api/pms/reviews', cycleData);
        alert('Review cycle created successfully!');
      }
      fetchCycles();
      
      setFormData({
        name: "",
        description: "",
        type: "Annual",
        startDate: "",
        endDate: "",
        departments: [],
        employees: [],
        status: "Draft"
      });
      setEditingCycle(null);
      setShowForm(false);
    } catch (error) {
      console.error('Error creating review cycle:', error);
      alert('Failed to create review cycle. Please try again.');
    }
  };

  const handleDelete = async (id) => {
    if (confirm("Are you sure you want to delete this review cycle?")) {
      try {
        await api.delete(`/api/pms/reviews/${id}`);
        alert('Review cycle deleted successfully!');
        fetchCycles();
      } catch (error) {
        console.error('Error deleting review cycle:', error);
        alert('Failed to delete review cycle. Please try again.');
      }
    }
  };

  const handleStatusChange = async (id, newStatus) => {
    try {
      await api.put(`/api/pms/reviews/${id}`, { status: newStatus });
      fetchCycles();
    } catch (error) {
      console.error('Error updating review cycle status:', error);
      alert('Failed to update status. Please try again.');
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "Active": return "bg-gray-100 text-gray-800 border-gray-300";
      case "Completed": return "bg-gray-100 text-gray-800 border-gray-300";
      case "Draft": return "bg-gray-100 text-gray-800 border-gray-300";
      case "Cancelled": return "bg-gray-100 text-gray-800 border-gray-300";
      default: return "bg-gray-100 text-gray-800 border-gray-300";
    }
  };

  const handleProgressUpdate = (cycle) => {
    setProgressCycle(cycle);
    setShowProgressModal(true);
  };

  const handleProgressSubmit = async (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    const selfScore = formData.get('selfScore');
    const managerScore = formData.get('managerScore');
    
    try {
      await api.put(`/api/pms/reviews/${progressCycle.id}`, {
        self_score: selfScore ? parseFloat(selfScore) : null,
        manager_score: managerScore ? parseFloat(managerScore) : null
      });
      alert('Progress updated successfully!');
      fetchCycles();
      setShowProgressModal(false);
      setProgressCycle(null);
    } catch (error) {
      console.error('Error updating progress:', error);
      alert('Failed to update progress. Please try again.');
    }
  };

  return (
    <div className="space-y-6">
      {/* Header with Create Review Cycle Button */}
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center border border-gray-300">
            <RefreshCw className="w-5 h-5 text-gray-600" />
          </div>
          <div>
            <h2 className="text-lg font-medium text-gray-900">Review Cycle</h2>
            <p className="text-sm text-gray-600">Manage performance review cycles and schedules</p>
          </div>
        </div>
        <button
          onClick={() => setShowForm(true)}
          className="bg-gray-900 text-white px-4 py-2 rounded-lg hover:bg-gray-700 border border-black flex items-center gap-2 text-sm sm:text-base w-fit"
        >
          <Plus className="w-4 h-4" />
          Create Review Cycle
        </button>
      </div>

      {/* Add Review Cycle Form */}
      {showForm && (
        <div className="bg-white rounded-lg shadow-sm border border-black">
          <div className="px-4 sm:px-6 py-4 border-b border-black">
            <h3 className="text-base sm:text-lg font-semibold text-gray-900">{editingCycle ? 'Edit Review Cycle' : 'Create New Review Cycle'}</h3>
          </div>
          <form onSubmit={handleSubmit} className="p-4 sm:p-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Cycle Name</label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({...formData, name: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Review Type</label>
                <select
                  value={formData.type}
                  onChange={(e) => setFormData({...formData, type: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                >
                  {reviewTypes.map(type => (
                    <option key={type} value={type}>{type}</option>
                  ))}
                </select>
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">Description</label>
                <textarea
                  value={formData.description}
                  onChange={(e) => setFormData({...formData, description: e.target.value})}
                  rows={3}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Start Date</label>
                <input
                  type="date"
                  value={formData.startDate}
                  onChange={(e) => setFormData({...formData, startDate: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">End Date</label>
                <input
                  type="date"
                  value={formData.endDate}
                  onChange={(e) => setFormData({...formData, endDate: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Departments</label>
                <select
                  multiple
                  value={formData.departments}
                  onChange={(e) => setFormData({...formData, departments: Array.from(e.target.selectedOptions, option => option.value)})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  size={4}
                >
                  {departments.map(dept => (
                    <option key={dept.id} value={dept.name}>{dept.name}</option>
                  ))}
                </select>
                <p className="text-xs text-gray-500 mt-1">Hold Ctrl/Cmd to select multiple</p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Employees</label>
                <select
                  multiple
                  value={formData.employees}
                  onChange={(e) => setFormData({...formData, employees: Array.from(e.target.selectedOptions, option => option.value)})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  size={4}
                >
                  {employees.map(emp => (
                    <option key={emp.id} value={emp.name}>{emp.employee_code} - {emp.name}</option>
                  ))}
                </select>
                <p className="text-xs text-gray-500 mt-1">Hold Ctrl/Cmd to select multiple</p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Status</label>
                <select
                  value={formData.status}
                  onChange={(e) => setFormData({...formData, status: e.target.value})}
                  className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                >
                  {statuses.map(status => (
                    <option key={status} value={status}>{status}</option>
                  ))}
                </select>
              </div>
            </div>

            <div className="mt-4 sm:mt-6 flex flex-col sm:flex-row justify-end space-y-2 sm:space-y-0 sm:space-x-3">
              <button
                type="button"
                onClick={() => setShowForm(false)}
                className="w-full sm:w-auto px-4 py-2 border border-black text-gray-700 rounded-md hover:bg-gray-50 text-sm sm:text-base"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="w-full sm:w-auto px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-700 border border-black text-sm sm:text-base"
              >
                {editingCycle ? 'Update Cycle' : 'Create Cycle'}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Progress Update Modal */}
      {showProgressModal && progressCycle && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-lg max-w-md w-full mx-4 border border-black">
            <div className="px-4 sm:px-6 py-4 border-b border-black">
              <h3 className="text-base sm:text-lg font-semibold text-gray-900">Update Review Progress</h3>
              <p className="text-sm text-gray-600">{progressCycle.cycle} - {progressCycle.review_type}</p>
            </div>
            <form onSubmit={handleProgressSubmit} className="p-4 sm:p-6">
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Self Score (1-5)</label>
                  <input
                    type="number"
                    name="selfScore"
                    min="1"
                    max="5"
                    step="0.1"
                    defaultValue={progressCycle.self_score || ''}
                    className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Manager Score (1-5)</label>
                  <input
                    type="number"
                    name="managerScore"
                    min="1"
                    max="5"
                    step="0.1"
                    defaultValue={progressCycle.manager_score || ''}
                    className="w-full px-3 py-2 border border-black rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm sm:text-base"
                  />
                </div>
              </div>
              <div className="mt-4 sm:mt-6 flex flex-col sm:flex-row justify-end space-y-2 sm:space-y-0 sm:space-x-3">
                <button
                  type="button"
                  onClick={() => {
                    setShowProgressModal(false);
                    setProgressCycle(null);
                  }}
                  className="w-full sm:w-auto px-4 py-2 border border-black text-gray-700 rounded-md hover:bg-gray-50 text-sm sm:text-base"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="w-full sm:w-auto px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-700 border border-black text-sm sm:text-base"
                >
                  Update Progress
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Review Cycles List */}
      <div className="bg-white rounded-lg shadow-sm border border-black">
        <div className="px-4 sm:px-6 py-4 border-b border-black">
          <h3 className="text-base sm:text-lg font-semibold text-gray-900">Review Cycles</h3>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200 border border-black">
            <thead className="bg-gray-50 border-b border-black">
              <tr>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Cycle Name</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Type</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Duration</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Participants</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Progress</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Status</th>
                <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {cycles.map((cycle) => (
                <tr key={cycle.id}>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <div>
                      <div className="text-sm font-medium text-gray-900">{cycle.cycle}</div>
                      <div className="text-sm text-gray-500">{cycle.review_type}</div>
                    </div>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm text-gray-900">{cycle.review_type}</td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {cycle.created_at ? new Date(cycle.created_at).toLocaleDateString() : 'N/A'}
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    1 employee
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      <div className="w-16 sm:w-full bg-gray-200 rounded-full h-2 mr-2 border border-black">
                        <div
                          className="h-2 bg-gray-500 rounded-full"
                          style={{ width: `${cycle.progress_percentage || 0}%` }}
                        ></div>
                      </div>
                      <span className="text-sm text-gray-600">
                        {cycle.progress || "0%"}
                      </span>
                    </div>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap">
                    <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full border ${getStatusColor(cycle.status)}`}>
                      {cycle.status}
                    </span>
                  </td>
                  <td className="px-3 sm:px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <div className="flex flex-wrap gap-1 sm:gap-2">
                      {cycle.status === "Draft" && (
                        <button
                          onClick={() => handleStatusChange(cycle.id, "Active")}
                          className="p-1 sm:p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-lg border border-gray-300"
                          title="Start Cycle"
                        >
                          <Play className="w-3 h-3 sm:w-4 sm:h-4" />
                        </button>
                      )}
                      {cycle.status === "Active" && (
                        <button
                          onClick={() => handleStatusChange(cycle.id, "Completed")}
                          className="p-1 sm:p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-lg border border-gray-300"
                          title="Complete Cycle"
                        >
                          <Pause className="w-3 h-3 sm:w-4 sm:h-4" />
                        </button>
                      )}
                      <button
                        onClick={() => handleProgressUpdate(cycle)}
                        className="p-1 sm:p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-lg border border-gray-300"
                        title="Update Progress"
                      >
                        <Target className="w-3 h-3 sm:w-4 sm:h-4" />
                      </button>
                      <button 
                        onClick={() => handleEdit(cycle)}
                        className="p-1 sm:p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-lg border border-gray-300"
                      >
                        <Edit className="w-3 h-3 sm:w-4 sm:h-4" />
                      </button>
                      <button
                        onClick={() => handleDelete(cycle.id)}
                        className="p-1 sm:p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-lg border border-gray-300"
                      >
                        <Trash2 className="w-3 h-3 sm:w-4 sm:h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}