import { useState, useEffect } from "react";
import { Plus, Edit, Trash2, CheckCircle, Clock, XCircle, ClipboardList } from "lucide-react";
import api from "../../api";
import useToast from "../../utils/useToast";
import Toast from "../../components/Toast";
import { hasPermission, isAdmin } from "../../utils/permissions";

// Helper function to get status icon
const getStatusIcon = (status) => {
  switch (status) {
    case "Completed":
      return <CheckCircle className="w-4 h-4 text-green-600" />;
    case "Partially Completed":
      return <Clock className="w-4 h-4 text-yellow-600" />;
    case "Not Completed":
    default:
      return <XCircle className="w-4 h-4 text-red-600" />;
  }
};

export default function WorkAssignments() {
  // Check permissions
  if (!hasPermission('view_work_assignments') && !isAdmin()) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <div className="text-6xl mb-4">🔒</div>
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Access Denied</h2>
          <p className="text-gray-600">You don't have permission to view work assignments.</p>
        </div>
      </div>
    );
  }
  const [assignments, setAssignments] = useState([]);
  const [myAssignments, setMyAssignments] = useState([]);
  const [reviewCycles, setReviewCycles] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [showModal, setShowModal] = useState(false);
  const [showStatusModal, setShowStatusModal] = useState(false);
  const [selectedAssignment, setSelectedAssignment] = useState(null);
  const [showDeleted, setShowDeleted] = useState(false);
  const [deletedCount, setDeletedCount] = useState(0);
  const [formData, setFormData] = useState({
    title: "",
    category: "Operational",
    weightage_percentage: "",
    frequency: "Monthly",
    review_cycle_id: "",
    assigned_employee_id: ""
  });
  const [currentCycle, setCurrentCycle] = useState(null);
  const [employeePMSData, setEmployeePMSData] = useState(null);
  const { toast, showToast, hideToast } = useToast();

  useEffect(() => {
    createSampleData();
    fetchData();
    
    const fetchColors = async () => {
      try {
        const tenantCode = localStorage.getItem('tenant_code');
        if (tenantCode) {
          const response = await api.get(`/auth/branding/${tenantCode}`);
          document.documentElement.style.setProperty('--primary-color', response.data.primary_color || '#2862e9');
          document.documentElement.style.setProperty('--secondary-color', response.data.secondary_color || '#474e71');
        }
      } catch (error) {
        console.error('Failed to fetch branding colors:', error);
      }
    };
    fetchColors();
  }, [showDeleted]);

  const createSampleData = async () => {
    try {
      await api.post("/api/pms/work-assignments/create-sample-data");
    } catch (error) {
      console.error("Error creating sample data:", error);
    }
  };

  const [statusData, setStatusData] = useState({
    completion_status: "Not Completed",
    remarks: ""
  });

  const fetchEmployeeReviewCycle = async (employeeId) => {
    try {
      const response = await api.get(`/api/pms/goals/employee-review-cycle/${employeeId}`);
      setCurrentCycle(response.data.data);
    } catch (error) {
      console.error("Error fetching employee review cycle:", error);
    }
  };

  const fetchEmployeePMSData = async (employeeId) => {
    try {
      const response = await api.get(`/api/pms/goals/employee-pms-data/${employeeId}`);
      setEmployeePMSData(response.data.data);
    } catch (error) {
      console.error("Error fetching employee PMS data:", error);
    }
  };
  
  const fetchEmployeesLikeLeaveApp = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      // Fetch from both onboarding and user management like Leave Applications does
      const [onboardingRes, usersRes] = await Promise.allSettled([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`${api.defaults.baseURL}/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.status === 'fulfilled' ? onboardingRes.value.data || [] : [];
      const userEmployees = usersRes.status === 'fulfilled' ? usersRes.value.users || [] : [];
      
      // Process onboarded employees (filter out auto-generated codes)
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id
      }));
      
      // Process user management employees
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: user.id,
          name: user.name,
          employee_code: user.employee_code
        }));
      
      // Combine and remove duplicates
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      return { data: allEmployees };
    } catch (error) {
      console.error("Error fetching employees:", error);
      return { data: [] };
    }
  };

  const fetchData = async () => {
    try {
      console.log("Fetching data...");
      
      // Fetch data with individual error handling
      const results = await Promise.allSettled([
        api.get(`/api/pms/work-assignments/assignments?include_deleted=${showDeleted}`),
        api.get("/api/pms/work-assignments/my-assignments"),
        api.get("/api/pms/reviews"),
        fetchEmployeesLikeLeaveApp(),
        api.get("/api/pms/work-assignments/deleted-count")
      ]);

      // Handle assignments
      if (results[0].status === 'fulfilled') {
        setAssignments(results[0].value.data.data || []);
      } else {
        console.error("Error fetching assignments:", results[0].reason);
      }

      // Handle my assignments
      if (results[1].status === 'fulfilled') {
        setMyAssignments(results[1].value.data.data || []);
        if (results[1].value.data.data && results[1].value.data.data.length > 0) {
          const currentUser = JSON.parse(localStorage.getItem('user') || '{}');
          if (currentUser.id) {
            fetchEmployeeReviewCycle(currentUser.id);
            fetchEmployeePMSData(currentUser.id);
          }
        }
      } else {
        console.error("Error fetching my assignments:", results[1].reason);
        setMyAssignments([]);
      }

      // Handle review cycles
      if (results[2].status === 'fulfilled') {
        setReviewCycles(results[2].value.data?.data || []);
      } else {
        console.error("Error fetching review cycles:", results[2].reason);
      }

      // Handle employees
      if (results[3].status === 'fulfilled') {
        const employeesData = results[3].value.data || [];
        console.log("Processed employees data:", employeesData);
        setEmployees(employeesData);
      } else {
        console.error("Error fetching employees:", results[3].reason);
        setEmployees([]);
      }
      
      // Handle deleted count
      if (results[4].status === 'fulfilled') {
        setDeletedCount(results[4].value.data.count || 0);
      } else {
        console.error("Error fetching deleted count:", results[4].reason);
        setDeletedCount(0);
      }
      
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await api.post("/api/pms/work-assignments/assignments", formData);
      setShowModal(false);
      setFormData({
        title: "",
        category: "Operational",
        weightage_percentage: "",
        frequency: "Monthly",
        review_cycle_id: "",
        assigned_employee_id: ""
      });
      fetchData();
      showToast('Work assignment created successfully!', 'success');
    } catch (error) {
      console.error("Error creating assignment:", error);
      showToast('Failed to create work assignment. Please try again.', 'error');
    }
  };

  const handleStatusUpdate = async (e) => {
    e.preventDefault();
    try {
      await api.put(`/api/pms/work-assignments/assignments/${selectedAssignment.id}/status`, statusData);
      setShowStatusModal(false);
      setSelectedAssignment(null);
      setStatusData({ completion_status: "Not Completed", remarks: "" });
      fetchData();
      showToast('Assignment status updated successfully!', 'success');
    } catch (error) {
      console.error("Error updating status:", error);
      showToast('Failed to update assignment status. Please try again.', 'error');
    }
  };

  const handleDelete = async (assignmentId) => {
    if (!window.confirm('Are you sure you want to delete this assignment?')) return;
    
    try {
      await api.delete(`/api/pms/work-assignments/assignments/${assignmentId}`);
      fetchData();
      showToast('Assignment deleted successfully!', 'success');
    } catch (error) {
      console.error("Error deleting assignment:", error);
      showToast('Failed to delete assignment. Please try again.', 'error');
    }
  };

  const handleRestore = async (assignmentId) => {
    try {
      await api.put(`/api/pms/work-assignments/assignments/${assignmentId}/restore`);
      fetchData();
      showToast('Assignment restored successfully!', 'success');
    } catch (error) {
      console.error("Error restoring assignment:", error);
      showToast('Failed to restore assignment. Please try again.', 'error');
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg flex items-center justify-center" style={{
            backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#2862e9'}20`
          }}>
            <ClipboardList className="w-5 h-5" style={{
              color: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#2862e9'
            }} />
          </div>
          <div>
            <h2 className="text-lg font-medium text-gray-900">Work Assignments</h2>
            <p className="text-sm text-gray-600">Manage and track employee work assignments</p>
          </div>
        </div>
        <div className="flex flex-col sm:flex-row gap-2">
          {!showDeleted && deletedCount > 0 && (
            <button
              onClick={() => setShowDeleted(true)}
              className="text-white px-4 py-2 rounded-lg text-sm whitespace-nowrap transition-colors"
              style={{
                backgroundColor: 'var(--primary-color)'
              }}
              onMouseEnter={(e) => e.currentTarget.style.backgroundColor = 'var(--secondary-color)'}
              onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'var(--primary-color)'}
            >
              Show Deleted ({deletedCount})
            </button>
          )}
          {showDeleted && (
            <button
              onClick={() => setShowDeleted(false)}
              className="text-white px-4 py-2 rounded-lg text-sm whitespace-nowrap transition-colors"
              style={{
                backgroundColor: 'var(--primary-color)'
              }}
              onMouseEnter={(e) => e.currentTarget.style.backgroundColor = 'var(--secondary-color)'}
              onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'var(--primary-color)'}
            >
              Hide Deleted
            </button>
          )}
          {(hasPermission('add_work_assignment') || isAdmin()) && (
            <button
              onClick={() => setShowModal(true)}
              className="text-white px-4 py-2 rounded-lg flex items-center gap-2 text-sm whitespace-nowrap transition-colors"
              style={{
                backgroundColor: 'var(--primary-color)'
              }}
              onMouseEnter={(e) => e.currentTarget.style.backgroundColor = 'var(--secondary-color)'}
              onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'var(--primary-color)'}
            >
              <Plus className="w-4 h-4" />
              New Assignment
            </button>
          )}
        </div>
      </div>

      {/* Current Review Cycle Info */}
      {currentCycle && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="font-semibold text-blue-900">Current Review Cycle: {currentCycle.cycle_name}</h3>
              <p className="text-sm text-blue-700">
                {currentCycle.start_date} to {currentCycle.end_date} | Status: {currentCycle.status}
              </p>
            </div>
            <div className="text-right">
              <div className="text-lg font-bold text-blue-900">{currentCycle.kpi_score}%</div>
              <div className={`text-sm px-2 py-1 rounded ${currentCycle.performance_status === 'On Track' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                {currentCycle.performance_status}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* My Assignments */}
      <div className="relative rounded-xl shadow-sm p-5 overflow-hidden" style={{
        background: `linear-gradient(135deg, white 0%, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#2862e9'}05 100%)`,
        border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#2862e9'}20`
      }}>
        <div className="absolute top-0 right-0 w-32 h-32 rounded-full blur-3xl opacity-10" style={{
          backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#2862e9',
          transform: 'translate(40%, -40%)'
        }} />
        <div className="absolute bottom-0 left-0 w-32 h-32 rounded-full blur-3xl opacity-10" style={{
          backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#2862e9',
          transform: 'translate(-40%, 40%)'
        }} />
        <div className="relative z-10">
        <h3 className="text-lg font-semibold mb-4">My Assignments</h3>
        
        {/* Desktop Table View */}
        <div className="hidden md:block overflow-x-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
          <table className="w-full text-sm">
            <thead>
              <tr className="-b">
                <th className="text-left p-2">Title</th>
                <th className="text-left p-2">Category</th>
                <th className="text-left p-2">Weightage</th>
                <th className="text-left p-2">Status</th>
                <th className="text-left p-2">Score Impact</th>
                <th className="text-left p-2">Actions</th>
              </tr>
            </thead>
            <tbody>
              {myAssignments.map((assignment) => (
                <tr key={assignment.id} className="-b">
                  <td className="p-2">{assignment.title}</td>
                  <td className="p-2">{assignment.category}</td>
                  <td className="p-2">{assignment.weightage_percentage}%</td>
                  <td className="p-2">
                    <div className="flex items-center gap-2">
                      {getStatusIcon(assignment.completion_status)}
                      {assignment.completion_status}
                    </div>
                  </td>
                  <td className="p-2">
                    <span className="text-sm font-medium">
                      +{((assignment.weightage_percentage * assignment.completion_percentage) / 100).toFixed(1)}%
                    </span>
                  </td>
                  <td className="p-2">
                    <button
                      onClick={() => {
                        setSelectedAssignment(assignment);
                        setStatusData({
                          completion_status: assignment.completion_status,
                          remarks: assignment.remarks
                        });
                        setShowStatusModal(true);
                      }}
                      className="text-blue-600 hover:text-blue-800 text-sm px-2 py-1  rounded hover:bg-blue-50"
                    >
                      Update Status
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Mobile Card View */}
        <div className="md:hidden space-y-4">
          {myAssignments.length === 0 ? (
            <p className="text-gray-500 text-center py-4">No assignments found</p>
          ) : (
            myAssignments.map((assignment) => (
              <div key={assignment.id} className=" border-gray-200 rounded-lg p-4">
                <div className="flex justify-between items-start mb-3">
                  <h4 className="font-medium text-gray-900">{assignment.title}</h4>
                  <div className="flex items-center gap-2">
                    {getStatusIcon(assignment.completion_status)}
                  </div>
                </div>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span className="text-gray-600">Category:</span>
                    <span className="font-medium">{assignment.category}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Weightage:</span>
                    <span className="font-medium">{assignment.weightage_percentage}%</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Status:</span>
                    <span className="font-medium">{assignment.completion_status}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Score Impact:</span>
                    <span className="font-medium text-green-600">
                      +{((assignment.weightage_percentage * assignment.completion_percentage) / 100).toFixed(1)}%
                    </span>
                  </div>
                </div>
                <div className="mt-3 pt-3 border-t border-gray-100">
                  <button
                    onClick={() => {
                      setSelectedAssignment(assignment);
                      setStatusData({
                        completion_status: assignment.completion_status,
                        remarks: assignment.remarks
                      });
                      setShowStatusModal(true);
                    }}
                    className="w-full text-blue-600 hover:text-blue-800 text-sm px-3 py-2  rounded hover:bg-blue-50 transition-colors"
                  >
                    Update Status
                  </button>
                </div>
              </div>
            ))
          )}
        </div>
        </div>
      </div>

      {/* All Assignments */}
      <div className="relative rounded-xl shadow-sm p-5 overflow-hidden" style={{
        background: `linear-gradient(135deg, white 0%, ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#2862e9'}05 100%)`,
        border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#2862e9'}20`
      }}>
        <div className="absolute top-0 right-0 w-32 h-32 rounded-full blur-3xl opacity-10" style={{
          backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#2862e9',
          transform: 'translate(40%, -40%)'
        }} />
        <div className="absolute bottom-0 left-0 w-32 h-32 rounded-full blur-3xl opacity-10" style={{
          backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color') || '#2862e9',
          transform: 'translate(-40%, 40%)'
        }} />
        <div className="relative z-10">
        <h3 className="text-lg font-semibold mb-4">All Assignments</h3>
        
        {/* Desktop Table View */}
        <div className="hidden md:block overflow-x-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
          <table className="w-full text-sm">
            <thead>
              <tr className="-b">
                <th className="text-left p-2">Title</th>
                <th className="text-left p-2">Employee</th>
                <th className="text-left p-2">Category</th>
                <th className="text-left p-2">Weightage</th>
                <th className="text-left p-2">Frequency</th>
                <th className="text-left p-2">Cycle</th>
                {showDeleted && <th className="text-left p-2">Status</th>}
                <th className="text-left p-2">Actions</th>
              </tr>
            </thead>
            <tbody>
              {assignments.map((assignment) => (
                <tr key={assignment.id} className="-b">
                  <td className="p-2">{assignment.title}</td>
                  <td className="p-2">{assignment.employee_name}</td>
                  <td className="p-2">{assignment.category}</td>
                  <td className="p-2">{assignment.weightage_percentage}%</td>
                  <td className="p-2">{assignment.frequency}</td>
                  <td className="p-2">{assignment.cycle_name}</td>
                  {showDeleted && (
                    <td className="p-2">
                      <span className={`px-2 py-1 rounded text-xs ${
                        assignment.deleted_at ? 'bg-red-100 text-red-800' : 'bg-green-100 text-green-800'
                      }`}>
                        {assignment.deleted_at ? 'Deleted' : 'Active'}
                      </span>
                    </td>
                  )}
                  <td className="p-2">
                    <div className="flex gap-2">
                      {assignment.deleted_at ? (
                        <button
                          onClick={() => handleRestore(assignment.id)}
                          className="text-green-600 hover:text-green-800 text-sm px-2 py-1  rounded hover:bg-green-50"
                        >
                          Restore
                        </button>
                      ) : (
                        (hasPermission('delete_work_assignment') || isAdmin()) && (
                          <button
                            onClick={() => handleDelete(assignment.id)}
                            className="text-red-600 hover:text-red-800 text-sm px-2 py-1  rounded hover:bg-red-50"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        )
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Mobile Card View */}
        <div className="md:hidden space-y-4">
          {assignments.length === 0 ? (
            <p className="text-gray-500 text-center py-4">No assignments found</p>
          ) : (
            assignments.map((assignment) => (
              <div key={assignment.id} className=" border-gray-200 rounded-lg p-4">
                <div className="mb-3">
                  <h4 className="font-medium text-gray-900">{assignment.title}</h4>
                  <p className="text-sm text-gray-600">{assignment.employee_name}</p>
                </div>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span className="text-gray-600">Category:</span>
                    <span className="font-medium">{assignment.category}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Weightage:</span>
                    <span className="font-medium">{assignment.weightage_percentage}%</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Frequency:</span>
                    <span className="font-medium">{assignment.frequency}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Cycle:</span>
                    <span className="font-medium">{assignment.cycle_name}</span>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
        </div>
      </div>

      {/* Create Assignment Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg p-4 sm:p-6 w-full max-w-md max-h-[90vh] overflow-y-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
            <h3 className="text-lg font-semibold mb-4">Create Assignment</h3>
            <form onSubmit={handleSubmit} className="space-y-4">
              <input
                type="text"
                placeholder="Assignment Title"
                value={formData.title}
                onChange={(e) => setFormData({...formData, title: e.target.value})}
                className="w-full p-3 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                style={{
                  backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                  border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                }}
                required
              />
              <select
                value={formData.category}
                onChange={(e) => setFormData({...formData, category: e.target.value})}
                className="w-full p-3 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                style={{
                  backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                  border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                }}
              >
                <option value="Operational">Operational</option>
                <option value="Admin">Admin</option>
                <option value="Compliance">Compliance</option>
                <option value="Support">Support</option>
              </select>
              <input
                type="number"
                placeholder="Weightage %"
                value={formData.weightage_percentage}
                onChange={(e) => setFormData({...formData, weightage_percentage: e.target.value})}
                className="w-full p-3 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                style={{
                  backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                  border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                }}
                required
              />
              <select
                value={formData.frequency}
                onChange={(e) => setFormData({...formData, frequency: e.target.value})}
                className="w-full p-3 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                style={{
                  backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                  border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                }}
              >
                <option value="Daily">Daily</option>
                <option value="Weekly">Weekly</option>
                <option value="Monthly">Monthly</option>
                <option value="One-time">One-time</option>
              </select>
              <select
                value={formData.review_cycle_id}
                onChange={(e) => setFormData({...formData, review_cycle_id: e.target.value})}
                className="w-full p-3 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                style={{
                  backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                  border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                }}
                required
              >
                <option value="">Select Review Cycle</option>
                {reviewCycles.map(cycle => (
                  <option key={cycle.id} value={cycle.id}>{cycle.cycle}</option>
                ))}
              </select>
              <select
                value={formData.assigned_employee_id}
                onChange={(e) => setFormData({...formData, assigned_employee_id: e.target.value})}
                className="w-full p-3 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                style={{
                  backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                  border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                }}
                required
              >
                <option value="">Select Employee</option>
                {Array.isArray(employees) && employees.map(emp => (
                  <option key={emp.id} value={emp.id}>
                    {emp.employee_code || `EMP${emp.id}`} - {emp.name}
                  </option>
                ))}
              </select>
              <div className="flex flex-col sm:flex-row gap-3 pt-2">
                <button type="submit" className="flex-1 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 text-sm">
                  Create
                </button>
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="flex-1 bg-gray-300 px-4 py-2 rounded-lg hover:bg-gray-400 text-sm"
                >
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Status Update Modal */}
      {showStatusModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg p-4 sm:p-6 w-full max-w-md max-h-[90vh] overflow-y-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
            <h3 className="text-lg font-semibold mb-4">Update Status</h3>
            <form onSubmit={handleStatusUpdate} className="space-y-4">
              <select
                value={statusData.completion_status}
                onChange={(e) => setStatusData({...statusData, completion_status: e.target.value})}
                className="w-full p-3 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                style={{
                  backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                  border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                }}
              >
                <option value="Not Completed">Not Completed</option>
                <option value="Partially Completed">Partially Completed</option>
                <option value="Completed">Completed</option>
              </select>
              <textarea
                placeholder="Remarks (optional)"
                value={statusData.remarks}
                onChange={(e) => setStatusData({...statusData, remarks: e.target.value})}
                className="w-full p-3 rounded-lg h-20 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
                style={{
                  backgroundColor: `${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}10`,
                  border: `1px solid ${getComputedStyle(document.documentElement).getPropertyValue('--primary-color')}`
                }}
              />
              <div className="flex flex-col sm:flex-row gap-3 pt-2">
                <button type="submit" className="flex-1 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 text-sm">
                  Update
                </button>
                <button
                  type="button"
                  onClick={() => setShowStatusModal(false)}
                  className="flex-1 bg-gray-300 px-4 py-2 rounded-lg hover:bg-gray-400 text-sm"
                >
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
      <Toast toast={toast} hideToast={hideToast} />
    </div>
  );
}
