import { useEffect, useState } from "react";
import { Download, Calendar, Users, TrendingUp, BarChart3, Filter } from "lucide-react";
import api from "../../api";

export default function LeaveReports() {
  const [report, setReport] = useState([]);
  const [dateRange, setDateRange] = useState("thisMonth");
  const [department, setDepartment] = useState("all");
  const [departments, setDepartments] = useState([]);
  const [employees, setEmployees] = useState([]);

  useEffect(() => {
    fetchReport();
    fetchDepartments();
    fetchEmployees();
  }, []);

  useEffect(() => {
    fetchReport();
  }, [dateRange, department]);

  const fetchReport = async () => {
    try {
      const [summaryRes, applicationsRes] = await Promise.all([
        api.get("/api/leave/reports/summary"),
        api.get("/api/leave/applications/")
      ]);
      setReport(summaryRes.data);
      setApplications(applicationsRes.data || []);
    } catch (error) {
      console.error("Error fetching reports:", error);
    }
  };

  const fetchDepartments = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      const response = await fetch(`http://localhost:8000/hospitals/departments/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (response.ok) {
        const data = await response.json();
        setDepartments(data.departments || []);
      }
    } catch (error) {
      console.error("Error fetching departments:", error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        department: emp.department
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: user.id,
          name: user.name,
          employee_code: user.employee_code,
          department: user.department
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
    }
  };

  const [applications, setApplications] = useState([]);

  const getEmployeeInfo = (employeeId) => {
    const employee = employees.find(emp => emp.id === employeeId);
    return employee ? {
      code: employee.employee_code || `EMP${employeeId}`,
      name: employee.name || `Employee ${employeeId}`,
      department: employee.department || 'N/A'
    } : {
      code: `EMP${employeeId}`,
      name: `Employee ${employeeId}`,
      department: 'N/A'
    };
  };

  const getFilteredApplications = () => {
    let filtered = applications;
    
    // Filter by department
    if (department !== "all") {
      filtered = filtered.filter(app => {
        const empInfo = getEmployeeInfo(app.employee_id);
        return empInfo.department.toLowerCase() === department;
      });
    }
    
    // Filter by date range
    const now = new Date();
    filtered = filtered.filter(app => {
      const appDate = new Date(app.applied_at);
      switch (dateRange) {
        case "thisMonth":
          return appDate.getMonth() === now.getMonth() && appDate.getFullYear() === now.getFullYear();
        case "lastMonth":
          const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
          return appDate.getMonth() === lastMonth.getMonth() && appDate.getFullYear() === lastMonth.getFullYear();
        case "thisQuarter":
          const quarterStart = new Date(now.getFullYear(), Math.floor(now.getMonth() / 3) * 3, 1);
          return appDate >= quarterStart;
        case "thisYear":
          return appDate.getFullYear() === now.getFullYear();
        default:
          return true;
      }
    });
    
    return filtered;
  };

  const filteredApplications = getFilteredApplications();

  const stats = {
    totalApplications: filteredApplications.length,
    approvedLeaves: filteredApplications.filter(a => a.status === "Approved").length,
    pendingApprovals: filteredApplications.filter(a => a.status === "Pending").length,
    rejectedLeaves: filteredApplications.filter(a => a.status === "Rejected").length
  };

  const departmentData = filteredApplications.reduce((acc, app) => {
    const existing = acc.find(d => d.employee_id === app.employee_id);
    if (existing) {
      existing[app.status.toLowerCase()]++;
      existing.total++;
    } else {
      acc.push({
        employee_id: app.employee_id,
        total: 1,
        approved: app.status === "Approved" ? 1 : 0,
        pending: app.status === "Pending" ? 1 : 0,
        rejected: app.status === "Rejected" ? 1 : 0
      });
    }
    return acc;
  }, []);

  const exportToCSV = () => {
    const headers = ['Employee Code', 'Employee Name', 'Department', 'Total Applications', 'Approved', 'Pending', 'Rejected', 'Approval Rate'];
    const csvData = departmentData.map(dept => {
      const empInfo = getEmployeeInfo(dept.employee_id);
      const approvalRate = dept.total > 0 ? ((dept.approved / dept.total) * 100).toFixed(1) : 0;
      return [
        empInfo.code,
        empInfo.name,
        empInfo.department,
        dept.total,
        dept.approved,
        dept.pending,
        dept.rejected,
        `${approvalRate}%`
      ];
    });
    
    const csvContent = [headers, ...csvData]
      .map(row => row.map(field => `"${field}"`).join(','))
      .join('\n');
    
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `leave-report-${dateRange}-${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="p-6 space-y-6">
      {/* Header with gradient background matching Organization setup */}
      <div className="p-8 border-b border-gray-100">
        <div className="flex justify-between items-center">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gray-100 rounded-xl flex items-center justify-center">
              <svg className="w-5 h-5 text-gray-600" fill="currentColor" viewBox="0 0 20 20">
                <path d="M2 11a1 1 0 011-1h2a1 1 0 011 1v5a1 1 0 01-1 1H3a1 1 0 01-1-1v-5zM8 7a1 1 0 011-1h2a1 1 0 011 1v9a1 1 0 01-1 1H9a1 1 0 01-1-1V7zM14 4a1 1 0 011-1h2a1 1 0 011 1v12a1 1 0 01-1 1h-2a1 1 0 01-1-1V4z" />
              </svg>
            </div>
            <div>
              <h2 className="text-2xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent mb-2">Leave Reports</h2>
              <p className="text-gray-600 text-base">Comprehensive leave usage analysis and insights</p>
            </div>
          </div>
          <div className="text-right">
            <div className="flex items-center gap-2 text-gray-600 mb-2">
              <span className="text-sm font-medium">Export Available</span>
            </div>
            <button 
              onClick={exportToCSV}
              className="bg-white text-black px-6 py-3 rounded-2xl flex items-center gap-2 transition-all duration-300 shadow-sm hover:shadow-md transform hover:-translate-y-0.5 font-semibold"
            >
              <Download size={18} />
              Export Report
            </button>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="p-4 sm:p-8 border-b border-gray-100">
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="relative flex-1 max-w-full sm:max-w-md">
            <Filter className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400" size={16} />
            <select 
              value={dateRange} 
              onChange={(e) => setDateRange(e.target.value)}
              className="pl-10 sm:pl-12 pr-4 py-2 sm:py-3 border border-black rounded-2xl focus:ring-2 focus:ring-blue-500 focus:border-transparent w-full bg-gray-50 hover:bg-white transition-colors text-sm sm:text-base"
            >
              <option value="thisMonth">This Month</option>
              <option value="lastMonth">Last Month</option>
              <option value="thisQuarter">This Quarter</option>
              <option value="thisYear">This Year</option>
            </select>
          </div>
          <div className="relative">
            <Calendar className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400" size={16} />
            <select 
              value={department} 
              onChange={(e) => setDepartment(e.target.value)}
              className="pl-10 sm:pl-12 pr-8 py-2 sm:py-3 border border-black rounded-2xl focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-gray-50 hover:bg-white transition-colors text-sm sm:text-base w-full sm:w-auto"
            >
              <option value="all">All Departments</option>
              {departments.map(dept => (
                <option key={dept.id} value={dept.name.toLowerCase()}>{dept.name}</option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-6">
        <div className="bg-white p-3 sm:p-6 rounded-2xl border border-black shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-gray-600 text-xs sm:text-sm font-semibold">Total Applications</p>
              <p className="text-xl sm:text-3xl font-bold text-gray-900 mt-1">{stats.totalApplications}</p>
            </div>
            <div className="w-8 h-8 sm:w-12 sm:h-12 bg-gray-100 rounded-2xl flex items-center justify-center">
              <Users className="text-gray-600" size={16} />
            </div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-2xl border border-black shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-gray-600 text-sm font-semibold">Approved</p>
              <p className="text-3xl font-bold text-gray-900 mt-1">{stats.approvedLeaves}</p>
            </div>
            <div className="w-12 h-12 bg-gray-100 rounded-2xl flex items-center justify-center">
              <TrendingUp className="text-gray-600" size={24} />
            </div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-2xl border border-black shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-gray-600 text-sm font-semibold">Pending</p>
              <p className="text-3xl font-bold text-gray-900 mt-1">{stats.pendingApprovals}</p>
            </div>
            <div className="w-12 h-12 bg-gray-100 rounded-2xl flex items-center justify-center">
              <Calendar className="text-gray-600" size={24} />
            </div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-2xl border border-black shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-gray-600 text-sm font-semibold">Rejected</p>
              <p className="text-3xl font-bold text-gray-900 mt-1">{stats.rejectedLeaves}</p>
            </div>
            <div className="w-12 h-12 bg-gray-100 rounded-2xl flex items-center justify-center">
              <BarChart3 className="text-gray-600" size={24} />
            </div>
          </div>
        </div>
      </div>

      {/* Department Breakdown */}
      <div className="bg-white rounded-3xl border border-black shadow-sm overflow-hidden">
        <div className="p-6 border-b border-black bg-gray-50">
          <h3 className="text-xl font-bold text-gray-900">Department-wise Leave Summary</h3>
        </div>
        <div className="p-6">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Employee</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Total Applications</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Approved</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Pending</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Rejected</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Approval Rate</th>
                </tr>
              </thead>
            <tbody className="bg-white divide-y divide-gray-100">
              {departmentData.length === 0 ? (
                <tr>
                  <td colSpan="6" className="px-6 py-12 text-center text-gray-500">
                    <div className="flex flex-col items-center space-y-3">
                      <div className="w-16 h-16 bg-gray-100 rounded-2xl flex items-center justify-center">
                        <BarChart3 className="w-8 h-8 text-gray-400" />
                      </div>
                      <p className="text-lg font-medium text-gray-900">No data available</p>
                      <p className="text-sm text-gray-500">Submit leave applications to see analytics</p>
                    </div>
                  </td>
                </tr>
              ) : (
                departmentData.map((dept, index) => {
                  const approvalRate = dept.total > 0 ? ((dept.approved / dept.total) * 100).toFixed(1) : 0;
                  return (
                    <tr key={index} className={`${index % 2 === 0 ? 'bg-white' : 'bg-gray-50'} hover:bg-blue-50 transition-colors`}>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-semibold text-gray-900">{getEmployeeInfo(dept.employee_id).code}</div>
                        <div className="text-sm text-gray-600">{getEmployeeInfo(dept.employee_id).name}</div>
                        <div className="text-xs text-gray-500">{getEmployeeInfo(dept.employee_id).department}</div>
                      </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {dept.total}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-green-100 text-green-800">
                        {dept.approved}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-yellow-100 text-yellow-800">
                        {dept.pending}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-red-100 text-red-800">
                        {dept.rejected}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      <div className="flex items-center">
                        <div className="w-16 bg-gray-200 rounded-full h-2 mr-2">
                          <div 
                            className="bg-green-600 h-2 rounded-full" 
                            style={{ width: `${approvalRate}%` }}
                          ></div>
                        </div>
                        <span className="text-sm font-semibold">{approvalRate}%</span>
                      </div>
                    </td>
                    </tr>
                  );
                })
              )}
            </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>
  );
}

