import { useEffect, useState } from "react";
import { Download, Calendar, Users, TrendingUp, BarChart3, Filter } from "lucide-react";
import api from "../../api";

export default function LeaveReports() {
  const [report, setReport] = useState([]);
  const [dateRange, setDateRange] = useState("thisMonth");
  const [department, setDepartment] = useState("all");
  const [departments, setDepartments] = useState([]);
  const [employees, setEmployees] = useState([]);

  useEffect(() => {
    fetchReport();
    fetchDepartments();
    fetchEmployees();
  }, []);

  useEffect(() => {
    fetchReport();
  }, [dateRange, department]);

  const fetchReport = async () => {
    try {
      const [summaryRes, applicationsRes] = await Promise.all([
        api.get("/api/leave/reports/summary"),
        api.get("/api/leave/applications/")
      ]);
      setReport(summaryRes.data);
      setApplications(applicationsRes.data || []);
    } catch (error) {
      console.error("Error fetching reports:", error);
    }
  };

  const fetchDepartments = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      const response = await fetch(`http://localhost:8000/hospitals/departments/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (response.ok) {
        const data = await response.json();
        setDepartments(data.departments || []);
      }
    } catch (error) {
      console.error("Error fetching departments:", error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        department: emp.department
      }));
      
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: user.id,
          name: user.name,
          employee_code: user.employee_code,
          department: user.department
        }));
      
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
    }
  };

  const [applications, setApplications] = useState([]);

  const getEmployeeInfo = (employeeId) => {
    const employee = employees.find(emp => emp.id === employeeId);
    return employee ? {
      code: employee.employee_code || `EMP${employeeId}`,
      name: employee.name || `Employee ${employeeId}`,
      department: employee.department || 'N/A'
    } : {
      code: `EMP${employeeId}`,
      name: `Employee ${employeeId}`,
      department: 'N/A'
    };
  };

  const getFilteredApplications = () => {
    let filtered = applications;
    
    // Filter by department
    if (department !== "all") {
      filtered = filtered.filter(app => {
        const empInfo = getEmployeeInfo(app.employee_id);
        return empInfo.department.toLowerCase() === department;
      });
    }
    
    // Filter by date range
    const now = new Date();
    filtered = filtered.filter(app => {
      const appDate = new Date(app.applied_at);
      switch (dateRange) {
        case "thisMonth":
          return appDate.getMonth() === now.getMonth() && appDate.getFullYear() === now.getFullYear();
        case "lastMonth":
          const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
          return appDate.getMonth() === lastMonth.getMonth() && appDate.getFullYear() === lastMonth.getFullYear();
        case "thisQuarter":
          const quarterStart = new Date(now.getFullYear(), Math.floor(now.getMonth() / 3) * 3, 1);
          return appDate >= quarterStart;
        case "thisYear":
          return appDate.getFullYear() === now.getFullYear();
        default:
          return true;
      }
    });
    
    return filtered;
  };

  const filteredApplications = getFilteredApplications();

  const stats = {
    totalApplications: filteredApplications.length,
    approvedLeaves: filteredApplications.filter(a => a.status === "Approved").length,
    pendingApprovals: filteredApplications.filter(a => a.status === "Pending").length,
    rejectedLeaves: filteredApplications.filter(a => a.status === "Rejected").length
  };

  const departmentData = filteredApplications.reduce((acc, app) => {
    const existing = acc.find(d => d.employee_id === app.employee_id);
    if (existing) {
      existing[app.status.toLowerCase()]++;
      existing.total++;
    } else {
      acc.push({
        employee_id: app.employee_id,
        total: 1,
        approved: app.status === "Approved" ? 1 : 0,
        pending: app.status === "Pending" ? 1 : 0,
        rejected: app.status === "Rejected" ? 1 : 0
      });
    }
    return acc;
  }, []);

  const exportToCSV = () => {
    const headers = ['Employee Code', 'Employee Name', 'Department', 'Total Applications', 'Approved', 'Pending', 'Rejected', 'Approval Rate'];
    const csvData = departmentData.map(dept => {
      const empInfo = getEmployeeInfo(dept.employee_id);
      const approvalRate = dept.total > 0 ? ((dept.approved / dept.total) * 100).toFixed(1) : 0;
      return [
        empInfo.code,
        empInfo.name,
        empInfo.department,
        dept.total,
        dept.approved,
        dept.pending,
        dept.rejected,
        `${approvalRate}%`
      ];
    });
    
    const csvContent = [headers, ...csvData]
      .map(row => row.map(field => `"${field}"`).join(','))
      .join('\n');
    
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `leave-report-${dateRange}-${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="rounded-lg shadow-sm" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
      {/* Header */}
      <div className="p-6 border-b ">
        <div className="flex justify-between items-center">
          <div>
            <h2 className="text-xl font-semibold text-primary">Leave Reports & Analytics</h2>
            <p className=" mt-1" style={{color: 'var(--text-secondary, #374151)'}}>Comprehensive leave usage analysis and insights</p>
          </div>
          <div className="flex items-center gap-3">
            <button 
              onClick={exportToCSV}
              className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
            >
              <Download size={16} />
              Export Report
            </button>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="p-6 border-b ">
        <div className="flex gap-4">
          <div className="flex items-center gap-2">
            <Calendar size={16} className="" style={{color: 'var(--text-muted, #6b7280)'}} />
            <select 
              value={dateRange} 
              onChange={(e) => setDateRange(e.target.value)}
              className="border-dark rounded-lg px-3 py-2 text-sm" style={{borderColor: 'var(--border-color, #e2e8f0)'}}
            >
              <option value="thisMonth">This Month</option>
              <option value="lastMonth">Last Month</option>
              <option value="thisQuarter">This Quarter</option>
              <option value="thisYear">This Year</option>
            </select>
          </div>
          <div className="flex items-center gap-2">
            <Filter size={16} className="" style={{color: 'var(--text-muted, #6b7280)'}} />
            <select 
              value={department} 
              onChange={(e) => setDepartment(e.target.value)}
              className="border-dark rounded-lg px-3 py-2 text-sm" style={{borderColor: 'var(--border-color, #e2e8f0)'}}
            >
              <option value="all">All Departments</option>
              {departments.map(dept => (
                <option key={dept.id} value={dept.name.toLowerCase()}>{dept.name}</option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="p-6 border-b ">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <div className="bg-blue-50 p-4 rounded-lg">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-blue-600 text-sm font-medium">Total Applications</p>
                <p className="text-2xl font-bold text-blue-900">{stats.totalApplications}</p>
              </div>
              <Users className="text-blue-600" size={24} />
            </div>
          </div>
          <div className="bg-green-50 p-4 rounded-lg">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-green-600 text-sm font-medium">Approved</p>
                <p className="text-2xl font-bold text-green-900">{stats.approvedLeaves}</p>
              </div>
              <TrendingUp className="text-green-600" size={24} />
            </div>
          </div>
          <div className="bg-yellow-50 p-4 rounded-lg">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-yellow-600 text-sm font-medium">Pending</p>
                <p className="text-2xl font-bold text-yellow-900">{stats.pendingApprovals}</p>
              </div>
              <Calendar className="text-yellow-600" size={24} />
            </div>
          </div>
          <div className="bg-red-50 p-4 rounded-lg">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-red-600 text-sm font-medium">Rejected</p>
                <p className="text-2xl font-bold text-red-900">{stats.rejectedLeaves}</p>
              </div>
              <BarChart3 className="text-red-600" size={24} />
            </div>
          </div>
        </div>
      </div>

      {/* Department Breakdown */}
      <div className="p-6 border-b ">
        <h3 className="text-lg font-semibold text-primary mb-4">Department-wise Leave Summary</h3>
        <div className="overflow-x-auto">
          <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="w-full">
            <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-content">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Employee</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Total Applications</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Approved</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Pending</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Rejected</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Approval Rate</th>
              </tr>
            </thead>
            <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-white divide-y">
              {departmentData.length === 0 ? (
                <tr>
                  <td colSpan="6" className="px-6 py-8 text-center text-muted">
                    No data available
                  </td>
                </tr>
              ) : (
                departmentData.map((dept, index) => {
                  const approvalRate = dept.total > 0 ? ((dept.approved / dept.total) * 100).toFixed(1) : 0;
                  return (
                    <tr key={index} className="hover:bg-content">
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-medium text-primary">{getEmployeeInfo(dept.employee_id).code}</div>
                        <div className="text-sm text-secondary">{getEmployeeInfo(dept.employee_id).name}</div>
                        <div className="text-xs text-muted">{getEmployeeInfo(dept.employee_id).department}</div>
                      </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">
                      {dept.total}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                        {dept.approved}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800">
                        {dept.pending}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800">
                        {dept.rejected}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-primary">
                      <div className="flex items-center">
                        <div className="w-16 bg-gray-200 rounded-full h-2 mr-2">
                          <div 
                            className="bg-green-600 h-2 rounded-full" 
                            style={{ width: `${approvalRate}%` }}
                          ></div>
                        </div>
                        <span className="text-sm font-medium">{approvalRate}%</span>
                      </div>
                    </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}

