import { useEffect, useState } from "react";
import { Plus, Search, Check, X, Eye, Filter, Calendar } from "lucide-react";
import api from "../../api";

export default function LeaveApplications() {
  const [applications, setApplications] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [leaveTypes, setLeaveTypes] = useState([]);
  const [leavePolicies, setLeavePolicies] = useState([]);
  const [leaveBalances, setLeaveBalances] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");
  const [showModal, setShowModal] = useState(false);
  const [showBalanceModal, setShowBalanceModal] = useState(false);
  const [selectedEmployeeId, setSelectedEmployeeId] = useState(null);
  const [showReviewModal, setShowReviewModal] = useState(false);
  const [reviewingApplication, setReviewingApplication] = useState(null);
  const [reviewBalances, setReviewBalances] = useState([]);
  const [formData, setFormData] = useState({
    employee_id: "",
    leave_type_id: "",
    policy_id: "",
    from_date: "",
    to_date: "",
    reason: ""
  });

  useEffect(() => {
    fetchApplications();
    fetchEmployees();
    fetchLeaveTypes();
    fetchLeavePolicies();
  }, []);

  const fetchLeaveBalances = async (employeeId) => {
    try {
      const res = await api.get(`/api/leave/applications/balances/${employeeId}`);
      setLeaveBalances(res.data);
      setSelectedEmployeeId(employeeId);
      setShowBalanceModal(true);
    } catch (error) {
      console.error("Error fetching leave balances:", error);
      alert("Error fetching leave balances");
    }
  };

  const initializeBalances = async (employeeId) => {
    try {
      const res = await api.post(`/api/leave/applications/initialize-balances/${employeeId}`);
      alert(res.data.message);
      fetchLeaveBalances(employeeId);
    } catch (error) {
      console.error("Error initializing balances:", error);
      alert("Error initializing leave balances");
    }
  };

  const fetchApplications = async () => {
    try {
      const res = await api.get("/api/leave/applications/");
      setApplications(res.data);
    } catch (error) {
      console.error("Error fetching applications:", error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      // Fetch from both onboarding and user management like EIS does
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees (filter out auto-generated codes)
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id
      }));
      
      // Process user management employees (users with employee codes)
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: user.id,
          name: user.name,
          employee_code: user.employee_code
        }));
      
      // Combine and remove duplicates (prefer user management data)
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      console.log("Employees from directory:", allEmployees);
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
    }
  };

  const fetchLeaveTypes = async () => {
    try {
      const res = await api.get("/api/leave/types/");
      setLeaveTypes(res.data.filter(type => type.status === "Active"));
    } catch (error) {
      console.error("Error fetching leave types:", error);
    }
  };

  const fetchLeavePolicies = async () => {
    try {
      const res = await api.get("/api/leave/applications/policies");
      setLeavePolicies(res.data);
    } catch (error) {
      console.error("Error fetching leave policies:", error);
    }
  };

  const getEmployeeInfo = (employeeId) => {
    const employee = employees.find(emp => emp.id === employeeId);
    return employee ? {
      code: employee.employee_code || `EMP${employeeId}`,
      name: employee.name || `Employee ${employeeId}`
    } : {
      code: `EMP${employeeId}`,
      name: `Employee ${employeeId}`
    };
  };

  const getLeaveTypeName = (leaveTypeId) => {
    const leaveType = leaveTypes.find(type => type.id === leaveTypeId);
    return leaveType ? leaveType.name : `Leave Type #${leaveTypeId}`;
  };

  const openReviewModal = async (application) => {
    try {
      const res = await api.get(`/api/leave/applications/balances/${application.employee_id}`);
      setReviewBalances(res.data);
      setReviewingApplication(application);
      setShowReviewModal(true);
    } catch (error) {
      console.error("Error fetching balances for review:", error);
    }
  };

  const approve = async (id, comment = "Approved") => {
    try {
      await api.post(`/api/leave/applications/${id}/approve?approver_id=1`, {
        status: "Approved",
        approver_comment: comment
      });
      fetchApplications();
      setShowReviewModal(false);
    } catch (error) {
      console.error("Error approving application:", error);
    }
  };

  const reject = async (id, comment = "Rejected") => {
    try {
      await api.post(`/api/leave/applications/${id}/approve?approver_id=1`, {
        status: "Rejected",
        approver_comment: comment
      });
      fetchApplications();
      setShowReviewModal(false);
    } catch (error) {
      console.error("Error rejecting application:", error);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      // Calculate total days
      const fromDate = new Date(formData.from_date);
      const toDate = new Date(formData.to_date);
      const timeDiff = toDate.getTime() - fromDate.getTime();
      const totalDays = Math.ceil(timeDiff / (1000 * 3600 * 24)) + 1;
      
      const submitData = {
        leave_type_id: parseInt(formData.leave_type_id),
        from_date: formData.from_date,
        to_date: formData.to_date,
        total_days: totalDays,
        reason: formData.reason,
        ...(formData.policy_id && { policy_id: parseInt(formData.policy_id) })
      };
      
      await api.post(`/api/leave/applications/?employee_id=${formData.employee_id}`, submitData);
      fetchApplications();
      handleCloseModal();
      alert("Leave application submitted successfully! Balance updated.");
    } catch (error) {
      console.error("Error creating application:", error);
      let errorMessage = "Failed to submit leave application.";
      
      if (error.response?.data?.detail) {
        const detail = error.response.data.detail;
        if (detail.includes("Insufficient leave balance")) {
          errorMessage = `❌ ${detail}`;
        } else if (detail.includes("Exceeds annual limit")) {
          errorMessage = `❌ ${detail}`;
        } else {
          errorMessage = `❌ ${detail}`;
        }
      }
      
      alert(errorMessage);
    }
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setFormData({
      employee_id: "",
      leave_type_id: "",
      policy_id: "",
      from_date: "",
      to_date: "",
      reason: ""
    });
  };

  const filteredApplications = applications.filter(app => {
    const matchesSearch = app.employee_id?.toString().includes(searchTerm) ||
                         app.reason?.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === "All" || app.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const getStatusColor = (status) => {
    switch (status) {
      case "Approved": return "bg-green-100 text-green-800";
      case "Rejected": return "bg-red-100 text-red-800";
      case "Pending": return "bg-yellow-100 text-yellow-800";
      default: return "bg-gray-100 text-primary";
    }
  };

  return (
    <div className="rounded-lg shadow-sm" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
      {/* Header */}
      <div className="p-6 border-b ">
        <div className="flex justify-between items-center">
          <div>
            <h2 className="text-xl font-semibold text-primary">Leave Applications & Approvals</h2>
            <p className=" mt-1" style={{color: 'var(--text-secondary, #374151)'}}>Review and manage employee leave requests</p>
          </div>
          <div className="flex gap-2">
            <button 
              onClick={() => setShowModal(true)}
              className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
            >
              <Plus size={16} />
              New Application
            </button>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="p-6 border-b ">
        <div className="flex gap-4">
          <div className="relative flex-1 max-w-md">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted" size={16} />
            <input
              type="text"
              placeholder="Search applications..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10 pr-4 py-2 border-dark rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent w-full"
            />
          </div>
          <div className="relative">
            <Filter className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted" size={16} />
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="pl-10 pr-8 py-2 border-dark rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="All">All Status</option>
              <option value="Pending">Pending</option>
              <option value="Approved">Approved</option>
              <option value="Rejected">Rejected</option>
            </select>
          </div>
        </div>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <table style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="w-full">
          <thead style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-content">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Employee</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Leave Details</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Duration</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Reason</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Status</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-muted uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody style={{borderColor: 'var(--border-color, #e2e8f0)'}} className="bg-white divide-y">
            {filteredApplications.length === 0 ? (
              <tr>
                <td colSpan="6" className="px-6 py-8 text-center text-muted">
                  {searchTerm || statusFilter !== "All" ? "No applications found matching your criteria." : "No leave applications yet."}
                </td>
              </tr>
            ) : (
              filteredApplications.map((app) => (
                <tr key={app.id} className="hover:bg-content">
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm font-medium text-primary">{getEmployeeInfo(app.employee_id).code}</div>
                    <div className="text-sm text-secondary">{getEmployeeInfo(app.employee_id).name}</div>
                    <div className="text-sm text-muted">Applied: {new Date(app.applied_at).toLocaleDateString()}</div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm text-primary">{getLeaveTypeName(app.leave_type_id)}</div>
                    <div className="flex items-center text-sm text-muted">
                      <Calendar size={14} className="mr-1" />
                      {app.from_date} to {app.to_date}
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                      {app.total_days} days
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="text-sm text-primary max-w-xs truncate">
                      {app.reason || "No reason provided"}
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(app.status)}`}>
                      {app.status}
                    </span>
                    {app.approver_comment && (
                      <div className="text-xs text-muted mt-1">{app.approver_comment}</div>
                    )}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <div className="flex items-center gap-2">
                      <button 
                        onClick={() => fetchLeaveBalances(app.employee_id)}
                        className="text-blue-600 hover:text-blue-900 p-1 rounded"
                        title="View Leave Balances"
                      >
                        <Eye size={16} />
                      </button>
                      {app.status === "Pending" && (
                        <>
                          <button 
                            onClick={() => openReviewModal(app)}
                            className="text-green-600 hover:text-green-900 p-1 rounded"
                            title="Review & Approve"
                          >
                            <Check size={16} />
                          </button>
                          <button 
                            onClick={() => reject(app.id, "Rejected")}
                            className="text-red-600 hover:text-red-900 p-1 rounded"
                            title="Reject"
                          >
                            <X size={16} />
                          </button>
                        </>
                      )}
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Stats Footer */}
      <div className="px-6 py-4 bg-content border-t ">
        <div className="flex justify-between items-center text-sm text-secondary">
          <span>Total: {applications.length} applications</span>
          <div className="flex gap-4">
            <span>Pending: {applications.filter(a => a.status === "Pending").length}</span>
            <span>Approved: {applications.filter(a => a.status === "Approved").length}</span>
            <span>Rejected: {applications.filter(a => a.status === "Rejected").length}</span>
          </div>
        </div>
      </div>

      {/* New Application Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <h3 className="text-lg font-semibold mb-4">New Leave Application</h3>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-secondary mb-1">Employee</label>
                <select
                  value={formData.employee_id}
                  onChange={(e) => setFormData({...formData, employee_id: e.target.value})}
                  className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                >
                  <option value="">Select Employee ({employees.length} available)</option>
                  {employees.map(emp => (
                    <option key={emp.id} value={emp.id}>
                      {emp.employee_code || `EMP${emp.id}`} - {emp.name}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-secondary mb-1">Leave Policy</label>
                <select
                  value={formData.policy_id}
                  onChange={(e) => setFormData({...formData, policy_id: e.target.value})}
                  className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="">Use Default Policy</option>
                  {leavePolicies.map(policy => (
                    <option key={policy.id} value={policy.id}>
                      {policy.name}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-secondary mb-1">Leave Type</label>
                <select
                  value={formData.leave_type_id}
                  onChange={(e) => setFormData({...formData, leave_type_id: e.target.value})}
                  className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  required
                >
                  <option value="">Select Leave Type</option>
                  {leaveTypes.map(type => (
                    <option key={type.id} value={type.id}>
                      {type.name} ({type.code})
                    </option>
                  ))}
                </select>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-secondary mb-1">From Date</label>
                  <input
                    type="date"
                    value={formData.from_date}
                    onChange={(e) => setFormData({...formData, from_date: e.target.value})}
                    className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary mb-1">To Date</label>
                  <input
                    type="date"
                    value={formData.to_date}
                    onChange={(e) => setFormData({...formData, to_date: e.target.value})}
                    className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    required
                  />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-secondary mb-1">Reason</label>
                <textarea
                  value={formData.reason}
                  onChange={(e) => setFormData({...formData, reason: e.target.value})}
                  className="w-full border-dark rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  rows="3"
                  placeholder="Enter reason for leave..."
                  required
                />
              </div>
              <div className="flex gap-4 pt-4">
                <button
                  type="button"
                  onClick={handleCloseModal}
                  className="flex-1 px-4 py-2 border-dark rounded-lg text-secondary hover:bg-content"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
                >
                  Submit Application
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Leave Balance Modal */}
      {showBalanceModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-lg">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">Leave Balances</h3>
              <button 
                onClick={() => setShowBalanceModal(false)}
                className=" hover:text-secondary" style={{color: 'var(--text-muted, #6b7280)'}}
              >
                <X size={20} />
              </button>
            </div>
            
            {leaveBalances.length === 0 ? (
              <div className="text-center py-8">
                <p className=" mb-4" style={{color: 'var(--text-muted, #6b7280)'}}>No leave balances found for this employee.</p>
                <button 
                  onClick={() => initializeBalances(selectedEmployeeId)}
                  className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg"
                >
                  Initialize Leave Balances
                </button>
              </div>
            ) : (
              <div className="space-y-4">
                {leaveBalances.map((balance) => (
                  <div key={balance.leave_type_id} className="border rounded-lg p-4" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                    <div className="flex justify-between items-center mb-2">
                      <h4 className="font-medium text-primary">
                        {balance.leave_type_name} ({balance.leave_type_code})
                      </h4>
                      <span className={`px-2 py-1 rounded text-sm ${
                        balance.is_overused ? 'bg-red-100 text-red-800' :
                        balance.balance > 5 ? 'bg-green-100 text-green-800' :
                        balance.balance > 0 ? 'bg-yellow-100 text-yellow-800' :
                        'bg-red-100 text-red-800'
                      }`}>
                        {balance.is_overused ? `Overused by ${balance.overused_days} days` : `${balance.balance} days left`}
                      </span>
                    </div>
                    <div className="grid grid-cols-3 gap-4 text-sm">
                      <div>
                        <span className="" style={{color: 'var(--text-muted, #6b7280)'}}>Allocated:</span>
                        <div className="font-medium">{balance.total_allocated} days</div>
                      </div>
                      <div>
                        <span className="" style={{color: 'var(--text-muted, #6b7280)'}}>Used:</span>
                        <div className="font-medium">{balance.used} days</div>
                      </div>
                      <div>
                        <span className="" style={{color: 'var(--text-muted, #6b7280)'}}>Balance:</span>
                        <div className="font-medium">{balance.balance} days</div>
                      </div>
                    </div>
                    <div className="mt-2">
                      <div className="w-full bg-gray-200 rounded-full h-2">
                        <div 
                          className={`h-2 rounded-full ${
                            balance.is_overused ? 'bg-red-500' : 'bg-blue-600'
                          }`}
                          style={{ width: `${Math.min((balance.used / balance.total_allocated) * 100, 100)}%` }}
                        ></div>
                        {balance.is_overused && (
                          <div className="text-xs text-red-600 mt-1">
                            ⚠️ Exceeded limit by {balance.overused_days} days
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
                <div className="mt-4 pt-4 border-t">
                  <button 
                    onClick={() => initializeBalances(selectedEmployeeId)}
                    className="w-full bg-gray-100 hover:bg-gray-200 text-secondary px-4 py-2 rounded-lg text-sm"
                  >
                    Refresh Balances
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Review Modal */}
      {showReviewModal && reviewingApplication && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">Review Leave Application</h3>
              <button 
                onClick={() => setShowReviewModal(false)}
                className=" hover:text-secondary" style={{color: 'var(--text-muted, #6b7280)'}}
              >
                <X size={20} />
              </button>
            </div>
            
            {/* Application Details */}
            <div className="bg-content rounded-lg p-4 mb-4">
              <h4 className="font-medium mb-2">Application Details</h4>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="" style={{color: 'var(--text-muted, #6b7280)'}}>Employee:</span>
                  <div className="font-medium">{getEmployeeInfo(reviewingApplication.employee_id).name}</div>
                  <div className="" style={{color: 'var(--text-secondary, #374151)'}}>{getEmployeeInfo(reviewingApplication.employee_id).code}</div>
                </div>
                <div>
                  <span className="" style={{color: 'var(--text-muted, #6b7280)'}}>Leave Type:</span>
                  <div className="font-medium">{getLeaveTypeName(reviewingApplication.leave_type_id)}</div>
                </div>
                <div>
                  <span className="" style={{color: 'var(--text-muted, #6b7280)'}}>Duration:</span>
                  <div className="font-medium">{reviewingApplication.from_date} to {reviewingApplication.to_date}</div>
                  <div className="text-blue-600">{reviewingApplication.total_days} days</div>
                </div>
                <div>
                  <span className="" style={{color: 'var(--text-muted, #6b7280)'}}>Applied:</span>
                  <div className="font-medium">{new Date(reviewingApplication.applied_at).toLocaleDateString()}</div>
                </div>
              </div>
              {reviewingApplication.reason && (
                <div className="mt-3">
                  <span className="" style={{color: 'var(--text-muted, #6b7280)'}}>Reason:</span>
                  <div className="font-medium">{reviewingApplication.reason}</div>
                </div>
              )}
            </div>

            {/* Leave Balances */}
            <div className="mb-4">
              <h4 className="font-medium mb-2">Current Leave Balances</h4>
              <div className="space-y-3">
                {reviewBalances.map((balance) => (
                  <div key={balance.leave_type_id} className="border rounded-lg p-3" style={{borderColor: 'var(--border-color, #e2e8f0)'}}>
                    <div className="flex justify-between items-center mb-2">
                      <h5 className="font-medium text-primary">
                        {balance.leave_type_name} ({balance.leave_type_code})
                      </h5>
                      <span className={`px-2 py-1 rounded text-sm ${
                        balance.is_overused ? 'bg-red-100 text-red-800' :
                        balance.balance > 5 ? 'bg-green-100 text-green-800' :
                        balance.balance > 0 ? 'bg-yellow-100 text-yellow-800' :
                        'bg-red-100 text-red-800'
                      }`}>
                        {balance.is_overused ? `Overused by ${balance.overused_days} days` : `${balance.balance} days left`}
                      </span>
                    </div>
                    <div className="grid grid-cols-3 gap-4 text-sm">
                      <div>
                        <span className="" style={{color: 'var(--text-muted, #6b7280)'}}>Allocated:</span>
                        <div className="font-medium">{balance.total_allocated} days</div>
                      </div>
                      <div>
                        <span className="" style={{color: 'var(--text-muted, #6b7280)'}}>Used:</span>
                        <div className="font-medium">{balance.used} days</div>
                      </div>
                      <div>
                        <span className="" style={{color: 'var(--text-muted, #6b7280)'}}>Balance:</span>
                        <div className="font-medium">{balance.balance} days</div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-4 pt-4 border-t">
              <button
                onClick={() => setShowReviewModal(false)}
                className="flex-1 px-4 py-2 border-dark rounded-lg text-secondary hover:bg-content"
              >
                Cancel
              </button>
              <button
                onClick={() => reject(reviewingApplication.id, "Rejected after review")}
                className="flex-1 px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 flex items-center justify-center gap-2"
              >
                <X size={16} />
                Reject
              </button>
              <button
                onClick={() => approve(reviewingApplication.id, "Approved after review")}
                className="flex-1 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 flex items-center justify-center gap-2"
              >
                <Check size={16} />
                Approve
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
