import { useState, useEffect } from "react";
import { Calendar, ChevronLeft, ChevronRight, Filter, Users, Clock } from "lucide-react";
import api from "../../api";

export default function LeaveCalendar() {
  const [currentDate, setCurrentDate] = useState(new Date());
  const [viewMode, setViewMode] = useState("month");
  const [selectedFilters, setSelectedFilters] = useState([]);
  const [leaves, setLeaves] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [holidays, setHolidays] = useState([]);
  const [selectedDepartment, setSelectedDepartment] = useState("All Departments");
  const [loading, setLoading] = useState(true);

  const monthNames = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];

  useEffect(() => {
    fetchLeaves();
    fetchEmployees();
    fetchDepartments();
    fetchHolidays();
  }, [currentDate]);

  const fetchLeaves = async () => {
    try {
      setLoading(true);
      const res = await api.get("/api/leave/applications/");
      setLeaves(res.data || []);
    } catch (error) {
      console.error("Error fetching leaves:", error);
      setLeaves([]);
    } finally {
      setLoading(false);
    }
  };

  const fetchEmployees = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      
      // Fetch from both onboarding and user management like EIS does
      const [onboardingRes, usersRes] = await Promise.all([
        api.get('/recruitment/onboarding/list').catch(() => ({ data: [] })),
        fetch(`http://localhost:8000/hospitals/users/${tenant}/list`, {
          headers: { Authorization: `Bearer ${token}` }
        }).then(res => res.ok ? res.json() : { users: [] }).catch(() => ({ users: [] }))
      ]);
      
      const onboardedEmployees = onboardingRes.data || [];
      const userEmployees = usersRes.users || [];
      
      // Process onboarded employees (filter out auto-generated codes)
      const validOnboardedEmployees = onboardedEmployees.filter(emp => {
        if (!emp.employee_id || emp.employee_id.trim() === '') return false;
        const isAutoGenerated = /^[A-Z]{3}\d{6}$/.test(emp.employee_id);
        return !isAutoGenerated;
      });
      
      const onboardedData = validOnboardedEmployees.map(emp => ({
        id: emp.application_id,
        name: emp.candidate_name,
        employee_code: emp.employee_id,
        department: emp.department
      }));
      
      // Process user management employees (users with employee codes)
      const userEmployeeData = userEmployees
        .filter(user => user.employee_code)
        .map(user => ({
          id: user.id,
          name: user.name,
          employee_code: user.employee_code,
          department: user.department
        }));
      
      // Combine and remove duplicates (prefer user management data)
      const allEmployees = [...onboardedData];
      userEmployeeData.forEach(userEmp => {
        const existingIndex = allEmployees.findIndex(emp => emp.employee_code === userEmp.employee_code);
        if (existingIndex === -1) {
          allEmployees.push(userEmp);
        } else {
          allEmployees[existingIndex] = userEmp;
        }
      });
      
      setEmployees(allEmployees);
    } catch (error) {
      console.error("Error fetching employees:", error);
    }
  };

  const fetchDepartments = async () => {
    try {
      const tenant = localStorage.getItem("tenant_db");
      const token = localStorage.getItem("access_token");
      const response = await fetch(`http://localhost:8000/hospitals/departments/${tenant}/list`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (response.ok) {
        const data = await response.json();
        setDepartments(data.departments || []);
      }
    } catch (error) {
      console.error("Error fetching departments:", error);
    }
  };

  const fetchHolidays = async () => {
    try {
      // Try the correct holiday endpoint based on the router
      const res = await api.get("/holidays/list");
      console.log("Holidays response:", res.data);
      setHolidays(res.data || []);
    } catch (error) {
      console.error("Error fetching holidays from /holidays/list:", error);
      setHolidays([]);
    }
  };

  const getEmployeeInfo = (employeeId) => {
    const employee = employees.find(emp => emp.id === employeeId);
    return employee ? {
      code: employee.employee_code || `EMP${employeeId}`,
      name: employee.name || `Employee ${employeeId}`,
      department: employee.department || 'N/A'
    } : {
      code: `EMP${employeeId}`,
      name: `Employee ${employeeId}`,
      department: 'N/A'
    };
  };

  const navigateMonth = (direction) => {
    const newDate = new Date(currentDate);
    newDate.setMonth(currentDate.getMonth() + direction);
    setCurrentDate(newDate);
  };

  const getDaysInMonth = () => {
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const daysInMonth = lastDay.getDate();
    const startingDayOfWeek = firstDay.getDay();

    const days = [];
    
    // Add empty cells for days before the first day of the month
    for (let i = 0; i < startingDayOfWeek; i++) {
      days.push(null);
    }
    
    // Add days of the month
    for (let day = 1; day <= daysInMonth; day++) {
      days.push(day);
    }
    
    return days;
  };

  const getWeekDays = () => {
    const startOfWeek = new Date(currentDate);
    const day = startOfWeek.getDay();
    const diff = startOfWeek.getDate() - day;
    startOfWeek.setDate(diff);
    
    const weekDays = [];
    for (let i = 0; i < 7; i++) {
      const date = new Date(startOfWeek);
      date.setDate(startOfWeek.getDate() + i);
      weekDays.push(date);
    }
    return weekDays;
  };

  const getLeaveForDay = (day) => {
    const currentMonth = currentDate.getMonth() + 1;
    const currentYear = currentDate.getFullYear();
    
    return leaves.filter(leave => {
      const fromDate = new Date(leave.from_date);
      const toDate = new Date(leave.to_date);
      const checkDate = new Date(currentYear, currentMonth - 1, day);
      
      const dateMatch = checkDate >= fromDate && checkDate <= toDate;
      
      // Apply department filter
      if (selectedDepartment !== "All Departments") {
        const empInfo = getEmployeeInfo(leave.employee_id);
        return dateMatch && empInfo.department === selectedDepartment;
      }
      
      return dateMatch;
    });
  };

  const getHolidayForDay = (day) => {
    const currentMonth = currentDate.getMonth() + 1;
    const currentYear = currentDate.getFullYear();
    
    const holiday = holidays.find(holiday => {
      const holidayDate = new Date(holiday.date);
      const matches = holidayDate.getDate() === day && 
             holidayDate.getMonth() === currentMonth - 1 && 
             holidayDate.getFullYear() === currentYear;
      
      if (matches) {
        console.log(`Found holiday for day ${day}:`, holiday);
      }
      
      return matches;
    });
    
    return holiday;
  };

  return (
    <div className="rounded-lg shadow-sm" style={{ backgroundColor: 'var(--card-bg, #ffffff)' }}>
      {/* Header */}
      <div className="p-6 border-b ">
        <div className="flex justify-between items-center">
          <div>
            <h2 className="text-xl font-semibold text-primary">Leave Calendar</h2>
            <p className=" mt-1" style={{color: 'var(--text-secondary, #374151)'}}>View team leaves and plan coverage</p>
          </div>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <Filter size={16} className="" style={{color: 'var(--text-muted, #6b7280)'}} />
              <select 
                value={selectedDepartment}
                onChange={(e) => setSelectedDepartment(e.target.value)}
                className="border-dark rounded-lg px-3 py-2 text-sm" style={{borderColor: 'var(--border-color, #e2e8f0)'}}
              >
                <option value="All Departments">All Departments</option>
                {departments.map(dept => (
                  <option key={dept.id} value={dept.name}>{dept.name}</option>
                ))}
              </select>
            </div>
            <div className="flex rounded-lg border-dark">
              <button 
                onClick={() => setViewMode("month")}
                className={`px-3 py-2 text-sm ${viewMode === "month" ? "bg-blue-100 text-blue-700" : "text-secondary"}`}
              >
                Month
              </button>
              <button 
                onClick={() => setViewMode("week")}
                className={`px-3 py-2 text-sm border-l ${viewMode === "week" ? "bg-blue-100 text-blue-700" : "text-secondary"}`}
              >
                Week
              </button>
              <button 
                onClick={() => setViewMode("list")}
                className={`px-3 py-2 text-sm border-l ${viewMode === "list" ? "bg-blue-100 text-blue-700" : "text-secondary"}`}
              >
                List
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Calendar Navigation */}
      <div className="p-6 border-b ">
        <div className="flex justify-between items-center">
          <div className="flex items-center gap-4">
            <button 
              onClick={() => navigateMonth(-1)}
              className="p-2 hover:bg-gray-100 rounded-lg"
            >
              <ChevronLeft size={20} />
            </button>
            <h3 className="text-lg font-semibold">
              {monthNames[currentDate.getMonth()]} {currentDate.getFullYear()}
            </h3>
            <button 
              onClick={() => navigateMonth(1)}
              className="p-2 hover:bg-gray-100 rounded-lg"
            >
              <ChevronRight size={20} />
            </button>
          </div>
          <button 
            onClick={() => setCurrentDate(new Date())}
            className="px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            Today
          </button>
        </div>
      </div>

      {/* Month View */}
      {viewMode === "month" && (
        <div className="p-6">
          <div className="grid grid-cols-7 gap-1 mb-4">
            {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map(day => (
              <div key={day} className="p-3 text-center text-sm font-medium text-muted">
                {day}
              </div>
            ))}
          </div>
          <div className="grid grid-cols-7 gap-1">
            {getDaysInMonth().map((day, index) => (
              <div key={index} className="min-h-[100px] border p-2">
                {day && (
                  <>
                    <div className="text-sm font-medium text-primary mb-1">{day}</div>
                    {getHolidayForDay(day) && (
                      <div className="text-xs p-1 mb-1 rounded bg-red-100 text-red-800 truncate" title={getHolidayForDay(day).name}>
                        🏖️ {getHolidayForDay(day).name}
                      </div>
                    )}
                    {getLeaveForDay(day).map((leave, idx) => {
                      const empInfo = getEmployeeInfo(leave.employee_id);
                      const statusColors = {
                        'Approved': 'bg-green-100 text-green-800',
                        'Pending': 'bg-yellow-100 text-yellow-800', 
                        'Rejected': 'bg-red-100 text-red-800'
                      };
                      const colorClass = statusColors[leave.status] || 'bg-gray-100 text-primary';
                      return (
                        <div key={idx} className={`text-xs p-1 mb-1 rounded ${colorClass} truncate`} title={`${empInfo.code} - ${empInfo.name} (${empInfo.department}) - ${leave.status}`}>
                          {empInfo.code}
                          <div className={`text-[10px] ${leave.status === 'Approved' ? 'text-green-600' : leave.status === 'Pending' ? 'text-yellow-600' : 'text-red-600'}`}>{empInfo.name}</div>
                          <div className="text-[9px] text-muted">{empInfo.department}</div>
                        </div>
                      );
                    })}
                  </>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Week View */}
      {viewMode === "week" && (
        <div className="p-6">
          <div className="grid grid-cols-7 gap-1 mb-4">
            {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map(day => (
              <div key={day} className="p-3 text-center text-sm font-medium text-muted">
                {day}
              </div>
            ))}
          </div>
          <div className="grid grid-cols-7 gap-1">
            {getWeekDays().map((date, index) => {
              const day = date.getDate();
              const isCurrentMonth = date.getMonth() === currentDate.getMonth();
              return (
                <div key={index} className={`min-h-[120px] border p-2 ${!isCurrentMonth ? 'bg-content' : ''}`}>
                  <div className={`text-sm font-medium mb-1 ${isCurrentMonth ? 'text-primary' : 'text-muted'}`}>
                    {day}
                  </div>
                  {isCurrentMonth && getHolidayForDay(day) && (
                    <div className="text-xs p-1 mb-1 rounded bg-red-100 text-red-800 truncate" title={getHolidayForDay(day).name}>
                      🏖️ {getHolidayForDay(day).name}
                    </div>
                  )}
                  {isCurrentMonth && getLeaveForDay(day).map((leave, idx) => {
                    const empInfo = getEmployeeInfo(leave.employee_id);
                    const statusColors = {
                      'Approved': 'bg-green-100 text-green-800',
                      'Pending': 'bg-yellow-100 text-yellow-800',
                      'Rejected': 'bg-red-100 text-red-800'
                    };
                    const colorClass = statusColors[leave.status] || 'bg-gray-100 text-primary';
                    return (
                      <div key={idx} className={`text-xs p-1 mb-1 rounded ${colorClass} truncate`} title={`${empInfo.code} - ${empInfo.name} (${empInfo.department}) - ${leave.status}`}>
                        {empInfo.code}
                        <div className={`text-[10px] ${leave.status === 'Approved' ? 'text-green-600' : leave.status === 'Pending' ? 'text-yellow-600' : 'text-red-600'}`}>{empInfo.name}</div>
                        <div className="text-[9px] text-muted">{empInfo.department}</div>
                      </div>
                    );
                  })}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* List View */}
      {viewMode === "list" && (
        <div className="p-6">
          {loading ? (
            <div className="text-center py-8 text-muted">Loading leaves...</div>
          ) : (
            <div className="space-y-4">
              {leaves.length === 0 ? (
                <div className="text-center py-8 text-muted">No leaves found for this period.</div>
              ) : (
                leaves.map((leave, index) => (
                  <div key={index} className="flex items-center justify-between p-4 border rounded-lg">
                    <div className="flex items-center gap-4">
                      <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                        <Calendar size={20} className="text-blue-600" />
                      </div>
                      <div>
                        <div className="font-medium text-primary">{getEmployeeInfo(leave.employee_id).code}</div>
                        <div className="text-sm text-muted">{getEmployeeInfo(leave.employee_id).name}</div>
                      </div>
                    </div>
                    <div className="text-right">
                      <div className="text-sm font-medium">{leave.from_date} to {leave.to_date}</div>
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                        leave.status === "Approved" ? "bg-green-100 text-green-800" : 
                        leave.status === "Pending" ? "bg-yellow-100 text-yellow-800" : "bg-red-100 text-red-800"
                      }`}>
                        {leave.status}
                      </span>
                    </div>
                  </div>
                ))
              )}
            </div>
          )}
        </div>
      )}

      {/* Legend */}
      <div className="px-6 py-4 bg-content border-t ">
        <div className="flex items-center gap-6 text-sm">
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 bg-green-500 rounded"></div>
            <span>Approved</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 bg-yellow-500 rounded"></div>
            <span>Pending</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 bg-red-500 rounded"></div>
            <span>Rejected</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 bg-red-500 rounded"></div>
            <span>Holiday</span>
          </div>
        </div>
      </div>
    </div>
  );
}
